### ISSUE TITLE
Cannot read property 'store' of undefined

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10344]
```
2019-07-15T12:51:11.324Z E Unable to load session Cannot read property 'store' of null
TypeError: Cannot read property 'store' of null
    at Object.t.trackStores (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:63:263291)
    at e.<anonymous> (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:9665)
    at E (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:38:13738)
    at Generator._invoke (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:38:13526)
    at Generator.e.(anonymous function) [as next] (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:38:13917)
    at Generator.c (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:84959)
    at f._promiseFulfilled (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:42111)
    at F._settlePromise (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:59201)
    at F._settlePromise0 (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:59799)
    at F._settlePromises (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:61151)
    at p (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:13372)
    at f (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:13311)
    at l._drainQueues (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:14819)
    at drainQueues (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:13053)
From previous event:
    at F.B [as _captureStackTrace] (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:28146)
    at new f (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:40986)
    at vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:44075
    at c (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:63:1089612)
    at Object.<anonymous> (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:63:1094532)
    at Object.<anonymous> (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:63:1094538)
    at o (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:318)
    at Object.<anonymous> (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:63:1030830)
    at o (vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:318)
    at vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:1992
    at vector://vector/webapp/bundles/e9b8313cd5591059cfdc/bundle.js:1:2004
```

`trackStores` reference is https://github.com/matrix-org/matrix-react-sdk/blob/fc636c6cb9ef1d154e9437c06938a03e401f666f/src/utils/StorageManager.js#L158

**Comment by jryans** [comment]
Hmm, not quite sure how to best fix this in a robust way... We can certainly null check `client` in `trackStores`, but then other bits of `MatrixClientPeg.assign` would error instead. Somehow, we need to signal that the client was destroyed and `assign` should abort early.

**Comment by turt2live** [comment]
I highly doubt we'll be able to fix this 2-3 years later. Closing until it happens again.
