### ISSUE TITLE
Riot-im takes the whole screen. 

### ISSUE THREAD

**Issue by shirishag75** [vector-im/element-web#10832]
Riot-web basically takes the whole display. There is no title bar and hence unable to figure out things. Not even able to screenshot. Just have to go to a non-X11 display console and write 

`$killall riot-web`

```
Subject: riot-web occupies the whole screen
Package: riot-web
Version: 1.3.3
Severity: normal



-- System Information:
Debian Release: bullseye/sid
  APT prefers testing
  APT policy: (900, 'testing'), (500, 'testing-debug'), (500, 'stable-debug'), (100, 'unstable-debug'), (100, 'experimental'), (100, 'unstable'), (50, 'experimental-debug')
Architecture: amd64 (x86_64)

Kernel: Linux 5.2.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages riot-web depends on:
ii  gconf-service     3.2.6-5
ii  gconf2            3.2.6-5
ii  libappindicator1  0.4.92-7
ii  libnotify4        0.7.8-1
ii  libnss3           2:3.45-1
ii  libxss1           1:1.2.3-1
ii  libxtst6          2:1.2.3-1

riot-web recommends no packages.

riot-web suggests no packages. 

-- no debconf information
```
You can see from where I'm getting the binary at - 

```
$ apt-cache policy riot-web. Please let me know if any more info. is needed. 
riot-web:
  Installed: 1.3.3
  Candidate: 1.3.3
  Version table:
 *** 1.3.3 990
        990 https://riot.im/packages/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

I am sure the issue might have been reported but still reporting all the same.

**Comment by shirishag75** [comment]
Things have moved to 1.3.6 but still the issue remains. 
```

$ apt-cache policy riot-web
riot-web:
  Installed: 1.3.6
  Candidate: 1.3.6
  Version table:
 *** 1.3.6 990
        990 https://riot.im/packages/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by shirishag75** [comment]
and even with 1.4.0 

While killing it, it showed the following , maybe it gives pointers to someone - 

`[10889:0928/035223.809509:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command`

**Comment by jryans** [comment]
I would guess this something generic that affects app using newer Electron versions on your system? Do you happen to use any other Electron-based apps?

**Comment by shirishag75** [comment]
> I would guess this something generic that affects app using newer Electron versions on your system? Do you happen to use any other Electron-based apps?

I don't have any other electron-based apps. How could I check ?

**Comment by shirishag75** [comment]
It got updated to 1.4.1 but still the same issues are there :(

**Comment by shirishag75** [comment]
even with 1.4.2 the issue remains the same  :(

**Comment by t3chguy** [comment]
Yes. That's why this issue hasn't been closed.

**Comment by shirishag75** [comment]
@t3chguy as shared before, I am open to ideas, I am ok with strace, gdb and any other tools you may recommend which may help out why it is not respecting window borders etc. It's a 16:9 resolution monitor. Does that info. make any difference ?

**Comment by shirishag75** [comment]
Got updated to 1.5.0 but still the same issues are there :( 

Seeing the same bug as before as well as error report - 

```
$ riot-web
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
[13612:1018/231316.208149:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
```

```
Package: riot-web
Version: 1.5.0
Severity: normal

-- System Information:
Debian Release: bullseye/sid
  APT prefers testing
  APT policy: (900, 'testing'), (500, 'testing-debug'), (100, 'unstable-debug'), (100, 'experimental'), (100, 'unstable'), (50, 'experimental-debug')
Architecture: amd64 (x86_64)

Kernel: Linux 5.2.0-3-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages riot-web depends on:
ii  libappindicator3-1  0.4.92-7
ii  libatspi2.0-0       2.34.0-3
ii  libgtk-3-0          3.24.12-1
ii  libnotify4          0.7.8-1
ii  libnss3             2:3.45-1
ii  libsecret-1-0       0.19.1-1
ii  libuuid1            2.34-0.1
ii  libxss1             1:1.2.3-1
ii  libxtst6            2:1.2.3-1
ii  xdg-utils           1.1.3-1

riot-web recommends no packages.

riot-web suggests no packages.

-- no debconf information
```

**Comment by jryans** [comment]
As far as I know, you are only person affected by this issue. There seem to be many other Linux that are not affected, so we need to isolate why it happens for you.

One way to check this would be to run some other Electron thing. Since you said you don't have any at the moment, you could try the https://github.com/electron/electron-quick-start repo by following their instructions and seeing what happens.

**Comment by shirishag75** [comment]
@jryans I would do that although could it to be to do something with nodejs and npm issues - 

```
$ npm start
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! path /home/shirish/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open
npm ERR! enoent ENOENT: no such file or directory, open '/home/shirish/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shirish/.npm/_logs/2019-10-18T18_27_07_794Z-debug.log

~/.npm/_logs$ cat 2019-10-18T18_27_07_794Z-debug.log 
0 info it worked if it ends with ok
1 warn npm npm does not support Node.js v10.15.2
2 warn npm You should probably upgrade to a newer version of node as we
3 warn npm can't make any promises that npm will work with this version.
4 warn npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
5 warn npm You can find the latest version at https://nodejs.org/
6 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
7 info using npm@5.8.0
8 info using node@v10.15.2
9 verbose config Skipping project config: /home/shirish/.npmrc. (matches userconfig)
10 verbose stack Error: ENOENT: no such file or directory, open '/home/shirish/package.json'
11 verbose cwd /home/shirish
12 verbose Linux 5.2.0-3-amd64
13 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
14 verbose node v10.15.2
15 verbose npm  v5.8.0
16 error path /home/shirish/package.json
17 error code ENOENT
18 error errno -2
19 error syscall open
20 error enoent ENOENT: no such file or directory, open '/home/shirish/package.json'
21 error enoent This is related to npm not being able to find a file.
22 verbose exit [ -2, true ]
```

**Comment by shirishag75** [comment]
Anyways, I tried all that they said - 

http://paste.debian.net/1108078/

It took me sometime while using nethogs to figure out what it was doing. I wish there was a way so it tells aloud what packages it is installing, the 146 odd packages it installed :(

This is what it said while trying to start it - 

```
~/games/electron-quick-start$ npm start
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> electron-quick-start@1.0.0 start /home/shirish/games/electron-quick-start
> electron .

[11930:1019/000540.920317:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /home/shirish/games/electron-quick-start/node_modules/electron/dist/chrome-sandbox is owned by root and has mode 4755.


```

**Comment by shirishag75** [comment]
I am at my wits end. I did change the ownership of the binary and file permissions as desired but still get the same error as above - 

```
~/games/electron-quick-start/node_modules/electron/dist$ ls -l chrome-sandbox 
-rwxr-xr-x 1 root root 5099032 Oct 19 00:05 chrome-sandbox
```

**Comment by jryans** [comment]
It looks like you haven't set the mode value. Your `ls` shows 755, but you need 4755 (so that the SUID bit is set).

**Comment by shirishag75** [comment]
I had to do it couple of times before it set the required SUID and was able to start electron. Although I still get the error here as well on the CLI - 

```
$ npm start
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> electron-quick-start@1.0.0 start /home/shirish/games/electron-quick-start
> electron .

[25165:1019/043109.375045:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
```

I also get the hello world image as well as can be seen below - 

![hello-world-electron](https://user-images.githubusercontent.com/727626/67133273-91665980-f1fb-11e9-9449-86b57737068a.png)

**Comment by jryans** [comment]
Does the test app exhibit the problem? I suppose not from the screenshot, but it's better to be explicit.

**Comment by shirishag75** [comment]
Nope. While there were some small issues, but nothing deal-breaking. For me the main reason is that in riot it does not show the minimize, maximize and close icons as can be seen here. I tried the maximize button with the test app. and it got the boundaries from either my window manager or Display manager. I am using lightdm as my display manager and running the default window manager 'marco' . Maybe this helps ?

**Comment by shirishag75** [comment]
I updated to riot-web 1.5.4 and the issue still continues - 

See the errors below - 

```
$ riot-web
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
(node:11975) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:11975) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
[13529:1126/155747.801760:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
(electron) 'setBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.
Killed
```
The problem might be from this statement - 
`
[13529:1126/155747.801760:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command`

Can anyone tell or share something more so I have more insight.

**Comment by shirishag75** [comment]
It got upgraded to 1.5.6 today and still the issue remained, although got some more comments/statements as well - 

```
$ apt-cache policy riot-web
riot-web:
  Installed: 1.5.6
  Candidate: 1.5.6
  Version table:
 *** 1.5.6 990
        990 https://riot.im/packages/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
```

Now for the errors while starting up - 

```
$ riot-web
seshat unavailable Error: Cannot find module 'matrix-seshat'
Require stack:
- /opt/Riot/resources/app.asar/src/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:717:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7609:16)
    at Module._load (internal/modules/cjs/loader.js:622:27)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:775:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (/opt/Riot/resources/app.asar/src/electron-main.js:49:14)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/opt/Riot/resources/app.asar/src/electron-main.js', undefined ]
}
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
(node:13529) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:13529) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(electron) 'setBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.
Killed
```

Killing it I had to go to CTRL+ALT+F1 and figure out via 

`$ ps -aux | grep riot-web` 

and basically do a kill -9 the parent and child processes which were spawned :(

**Comment by jryans** [comment]
```
seshat unavailable Error: Cannot find module 'matrix-seshat'
```

Is a poorly communicated warning about an optional feature and does not indicate a problem. See https://github.com/vector-im/riot-web/issues/11637 to track this.

**Comment by jryans** [comment]
As your full screen issue, so far I am not sure what to suggest... 😖 I am not aware of Riot doing unusual things in this regard, and as far as I know, you are the only one experiencing this issue, which suggests something machine-specific is going on.

**Comment by shirishag75** [comment]
> As your full screen issue, so far I am not sure what to suggest... confounded I am not aware of Riot doing unusual things in this regard, and as far as I know, you are the only one experiencing this issue, which suggests something machine-specific is going on.

I dunno what to say to that :( Maybe the below gives some answers - 

```
$ xrandr --query
Screen 0: minimum 320 x 200, current 1600 x 900, maximum 16384 x 16384
HDMI-1 connected primary 1600x900+0+0 (normal left inverted right x axis y axis) 443mm x 249mm
   1600x900      60.00*+
   1920x1080     60.00    59.94  
   1400x1050     59.95  
   1280x1024     75.02    60.02  
   1440x900      59.90  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32    56.25  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08  
HDMI-2 disconnected (normal left inverted right x axis y axis)
```

Just to be clear it's a VGA monitor connected to a usb port via an adaptor - 
```

$ sudo hwinfo --monitor --short
monitor:                                                        
                       VIEWSONIC VA2038 SERIES
```
does the above help in any way ?

**Comment by jryans** [comment]
Seems normal... The only thing that comes to mind is if you have a separate computer or virtual machine with the same OS, does it happen there? If no, then it's something specific to your original machine. If yes, then we'll need to capture how you set up the machine in hopes that someone else can reproduce it.

**Comment by shirishag75** [comment]
While I do have a VM, riot is running on host. This is a desktop computer. I am using the same machine to reply to you. If you want me to load Debian on the VM and then riot can do that but that will need time, energy, hdd space etc. ,  all of which I'm lacking atm :(

**Comment by shirishag75** [comment]
![neofetch](https://user-images.githubusercontent.com/727626/70534355-c97e7e80-1b52-11ea-9b66-f256d6b0da2c.png)

@jryans there is also this if it helps in anyway ?

**Comment by hg-stolle** [comment]
It is not just Linux. I've encountered the same issue with the current latest release 1.5.6 on Windows 7 SP1, 64 bit.

**Comment by geosword** [comment]
I have the same problem in plasma.
```
$ riot-web
Seshat isn't installed, event indexing is disabled.
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
(node:23766) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:23766) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.

(riot-web:23766): libappindicator-WARNING **: Unable to get the session bus: Unknown or unsupported transport 'disabled' for address 'disabled:'

(riot-web:23766): LIBDBUSMENU-GLIB-WARNING **: Unable to get session bus: Unknown or unsupported transport 'disabled' for address 'disabled:'
```

```
$ dpkg -l riot-web
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                                                  Version                         Architecture                    Description
+++-=====================================================-===============================-===============================-===============================================================================================================
ii  riot-web                                              1.5.8                           amd64                           
```

**Comment by shirishag75** [comment]
@jryans still no luck with 1.5.9 . Btw what is shortcut for toggling to windowed mode in riot-web ?

This is what I got when trying to run it - 

```
$ riot-web
Seshat isn't installed, event indexing is disabled.
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
(node:3592301) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:3592301) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
[3593972:0218/001536.087893:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
(electron) 'setBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.
```

**Comment by shirishag75** [comment]
getting the same error in 1.5.10 as well :(

**Comment by jryans** [comment]
> what is shortcut for toggling to windowed mode in riot-web ?

I am not aware of anything special for Riot... @t3chguy, is there some special full screen shortcut from Electron by chance?

**Comment by t3chguy** [comment]
F11 seems to work on Windows at least,

**Comment by bamonroe** [comment]
I have the same issue. Riot always starts in fullscreen. I have other electron apps that do no have the same problem. I can toggle from fullscreen to windowed after it starts. Also happy to give any debug information.

**Comment by shirishag75** [comment]
Even with 1.5.14 the issue still persists - 

```
$ riot-web
Seshat isn't installed, event indexing is disabled.
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
(node:23888) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
(node:23888) ProtocolDeprecateCallback: The callback argument of protocol module APIs is no longer needed.
[23920:0331/003631.994415:ERROR:buffer_manager.cc(488)] [.DisplayCompositor]GL ERROR :GL_INVALID_OPERATION : glBufferData: <- error from previous GL command
(electron) 'setBadgeCount function' is deprecated and will be removed. Please use 'badgeCount property' instead.
(electron) 'isMenuBarAutoHide function' is deprecated and will be removed. Please use 'autoHideMenuBar property' instead.
Killed
```
as can be seen I had to go CTRL+ALT+F1 grep for all the riot-web processes and kill them.

**Comment by shirishag75** [comment]
Btw there seems to be a collision and now riot-web is riot-desktop. I was unable to download the riot-web and hence had to settle for riot-desktop. Installed riot-desktop 1.6.0-2 and still have the same issues as shared before :(

**Comment by jryans** [comment]
I think someone affected by this issue would either need to debug and isolate it themselves, or construct detailed steps for someone else to reproduce. As far as I can tell, it currently seems to be very specific to just a few people.

There's not really any need to keep reporting it hasn't been fixed each release, that's clear enough by issue being opened. (Perhaps if by some surprise / Electron version upgrade / etc. it's magically fixed, that's of course good to know.)

If there's anything that can be done about this on Riot side, we would need to identify what that is first. At the moment, it's not clear even which layer of the stack is causing this at all, so that needs to be identified first.

Why are only a few people affected here? Are you all using a particular desktop environment or window manager, for example...? These are the kinds of things we need to work out.

**Comment by shirishag75** [comment]
FWIW, tried it again today and got this - 

```
$ element-desktop
/home/shirish/.config/Element exists: no
/home/shirish/.config/Riot exists: yes
Using legacy user data path: /home/shirish/.config/Riot
Starting auto update with base URL: https://packages.riot.im/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Resetting the UI components after locale change
Changing application language to en
Fetching translation json for locale: en
Could not fetch translation json for locale: 'en' Error: Cannot find module './i18n/strings/en.json'
Require stack:
- /opt/Element/resources/app.asar/src/language-helper.js
- /opt/Element/resources/app.asar/src/tray.js
- /opt/Element/resources/app.asar/src/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:261:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AppLocalization.fetchTranslationJson (/opt/Element/resources/app.asar/src/language-helper.js:83:20)
    at /opt/Element/resources/app.asar/src/language-helper.js:102:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element/resources/app.asar/src/language-helper.js:101:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element/resources/app.asar/src/language-helper.js',
    '/opt/Element/resources/app.asar/src/tray.js',
    '/opt/Element/resources/app.asar/src/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
```

had to go on PS1 to kill element-desktop. Wish there was an easier way of killing the processes rather than just using numbers.

**Comment by acxz** [comment]
@shirishag75 

> had to go on PS1 to kill element-desktop. Wish there was an easier way of killing the processes rather than just using numbers.

`ps -Ao pid= -o args= | awk '$4 ~ /element/ { print $1}'  | xargs kill`

**Comment by shirishag75** [comment]
After a long time I tried again but no luck - 

```
$ apt-cache policy element-desktop
element-desktop:
  Installed: 1.10.13
  Candidate: 1.10.13
  Version table:
 *** 1.10.13 500
        500 https://packages.riot.im/debian default/main amd64 Packages
        100 /var/lib/dpkg/status
```

One good thing however, CTRL+C cancels the process, Don't have to go either ps! or elsewhere - 

```
shirish@debian:"05 Jun 2022 17:40:19" ~$ element-desktop
/home/shirish/.config/Element exists: no
/home/shirish/.config/Riot exists: yes
Using legacy user data path: /home/shirish/.config/Riot
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
[2639781:0605/174035.864985:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
esetting the UI components after locale change
Resetting the UI components after locale change
[2639745:0605/174037.251495:ERROR:browser_main_loop.cc(267)] Gdk: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
^C
```

**Comment by uhoreg** [comment]
> Riot-web basically takes the whole display. There is no title bar and hence unable to figure out things.

Could it be that the application somehow got resized to fill the whole screen, with the titlebar off-screen?  Could you try using some keyboard shortcuts to resize/maximize the application?

**Comment by turt2live** [comment]
Closing due to lack of response. If this is still happening, please open a new issue with fresh reproduction steps for our QA team to review.
