### ISSUE TITLE
Cannot minimize (the app?)

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#10949]
```
2019-09-24T15:24:02.899Z W %cUnhandled rejection TypeError: Cannot read property 'offsetTop' of null
    at t._getMessagesHeight (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:84:1228383)
    at t.<anonymous> (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:84:1227301)
    at E (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:24:95936)
    at Generator._invoke (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:24:95724)
    at Generator.forEach.e.(anonymous function) [as next] (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:24:96116)
    at Generator.c (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:1:85788)
    at f._promiseFulfilled (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:1:42659)
    at vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:1:44686
From previous event:
    at D.U [as _captureStackTrace] (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:1:28679)
    at new f (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:1:41534)
    at t.<anonymous> (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:1:44623)
    at t._restoreSavedScrollState (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:84:1226781)
    at t.checkScroll (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:84:1221387)
    at t.componentDidMount (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:84:1220803)
    at t.componentDidMount (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:63:5918)
    at e.notifyAll (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:55:99655)
    at d.close (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:65:60408)
    at d.closeAll (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:40:14015)
    at d.perform (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:40:13510)
    at v.perform (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:40:13427)
    at v.perform (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:17:62597)
    at Object.E [as flushBatchedUpdates] (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:17:62766)
    at u.closeAll (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:40:14015)
    at u.perform (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:40:13510)
    at Object.batchedUpdates (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:55:113960)
    at Object.e [as enqueueUpdate] (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:17:63100)
    at a (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:54:5975)
    at Object.enqueueSetState (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:54:6806)
    at t.s.setState (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:55:96527)
    at t.value (vector://vector/webapp/bundles/5e6b63d216ee957e7492/bundle.js:24:78561) color: red
```

**Comment by turt2live** [comment]
Issue is unlikely to be fixed from such an ancient stacktrace.
