### ISSUE TITLE
Failed to construct 'URL': Invalid URL

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#12345]
```
2020-02-12T10:50:44.859Z E Failed to construct 'URL': Invalid URL
TypeError: Failed to construct 'URL': Invalid URL
    at vector://vector/webapp/bundles/d441f426d823eb4f5dc4/bundle.js:2:108997
    at c (vector://vector/webapp/bundles/d441f426d823eb4f5dc4/bundle.js:2:611746)
    at Generator._invoke (vector://vector/webapp/bundles/d441f426d823eb4f5dc4/bundle.js:2:611499)
    at Generator.forEach.e.<computed> [as next] (vector://vector/webapp/bundles/d441f426d823eb4f5dc4/bundle.js:2:612103)
    at n (vector://vector/webapp/bundles/d441f426d823eb4f5dc4/bundle.js:2:21165)
    at s (vector://vector/webapp/bundles/d441f426d823eb4f5dc4/bundle.js:2:21376)
```

**Comment by t3chguy** [comment]
Too old to action with obfuscated logs
