### ISSUE TITLE
Test failure: cross signing should get cross-signing keys from sync

### ISSUE THREAD

**Issue by foldleft** [vector-im/element-web#12526]
## Overview
This is a bug in `cross-signing.spec.js` that was hidden because some code was executing asynchronously.

I made a change to the file so that the tests do not finish until the promise is resolved.  This surfaced a new bug in which `verifySignature()` in `olmlib.js` is passed a falsy object rather than something with a signature.

## Reproducing the bug

**Apply this patch**

```
diff --git a/spec/unit/crypto/cross-signing.spec.js b/spec/unit/crypto/cross-signing.spec.js
index ccdbef0b..8866722f 100644
--- a/spec/unit/crypto/cross-signing.spec.js
+++ b/spec/unit/crypto/cross-signing.spec.js
@@ -264,6 +264,8 @@ describe("Cross Signing", function() {
         expect(aliceDeviceTrust.isLocallyVerified()).toBeTruthy();
         expect(aliceDeviceTrust.isTofu()).toBeTruthy();
         expect(aliceDeviceTrust.isVerified()).toBeTruthy();
+
+        await alice._crypto._deviceList._savePromise;
     });
 
     it("should use trust chain to determine device verification", async function() {
@@ -580,6 +582,8 @@ describe("Cross Signing", function() {
         const bobDeviceTrust2 = alice.checkDeviceTrust("@bob:example.com", "Dynabook");
         expect(bobDeviceTrust2.isVerified()).toBeFalsy();
         expect(bobDeviceTrust2.isTofu()).toBeFalsy();
+
+        await alice._crypto._deviceList._savePromise;
     });
 
     it("should dis-trust a user when their ssk changes", async function() {
@@ -716,6 +720,8 @@ describe("Cross Signing", function() {
 
         const bobDeviceTrust4 = alice.checkDeviceTrust("@bob:example.com", "Dynabook");
         expect(bobDeviceTrust4.isCrossSigningVerified()).toBeTruthy();
+
+        await alice._crypto._deviceList._savePromise;
     });
 
     it("should offer to upgrade device verifications to cross-signing", async function() {
@@ -793,5 +799,8 @@ describe("Cross Signing", function() {
         const bobTrust3 = alice.checkUserTrust("@bob:example.com");
         expect(bobTrust3.isCrossSigningVerified()).toBeTruthy();
         expect(bobTrust3.isTofu()).toBeTruthy();
+
+        await alice._crypto._deviceList._savePromise;
+        await bob._crypto._deviceList._savePromise;
     });
 });
```

**Run test**
```yarn jest --testEnvironment node spec/unit/crypto/cross-signing.spec.js```

## Output
```
  ● Cross Signing › should get cross-signing keys from sync

    TypeError: Cannot read property 'signatures' of undefined

      318 | ) {
      319 |     const signKeyId = "ed25519:" + signingDeviceId;
    > 320 |     const signatures = obj.signatures || {};
          |                            ^
      321 |     const userSigs = signatures[signingUserId] || {};
      322 |     const signature = userSigs[signKeyId];
      323 |     if (!signature) {

      at Object.verifySignature (src/crypto/olmlib.js:320:28)
      at MatrixClient.<anonymous> (spec/unit/crypto/cross-signing.spec.js:144:30)
      at Crypto.Object.<anonymous>.Crypto._afterCrossSigningLocalKeyChange (src/crypto/index.js:661:26)
      at Crypto.Object.<anonymous>.Crypto.checkOwnCrossSigningTrust (src/crypto/index.js:934:9)
      at MatrixClient.<anonymous> (spec/unit/crypto/cross-signing.spec.js:138:17)
```

## Note
The patch above should be included in the fix for the underlying bug.

**Comment by richvdh** [comment]
Given this doesn't seem to have been reported since 2020... shall we just close it?

**Comment by richvdh** [comment]
silence == agreement
