### ISSUE TITLE
 cannot accept a community invitation.

### ISSUE THREAD

**Issue by bwindels** [vector-im/element-web#12729]
https://github.com/matrix-org/riot-web-rageshakes/issues/2389

**Comment by bwindels** [comment]
```
2020-03-12T22:23:18.632Z E Cannot read property 'userId' of null
TypeError: Cannot read property 'userId' of null
    at t._getMembershipSection (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:3363431)
    at t.render (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:3371378)
    at $a (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2070218)
    at Ya (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2070013)
    at xs (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2105194)
    at gc (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2089537)
    at hc (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2089462)
    at ic (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2086810)
    at vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2045252
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2119846)
2020-03-12T22:23:18.634Z I Ending watcher ID 1584051798423_6_breadcrumbs_null
2020-03-12T22:23:18.634Z I Ending watcher ID 1584051798423_7_TagPanel.disableTagPanel_null
2020-03-12T22:23:18.636Z I Ending watcher ID 1584051798431_8_breadcrumb_rooms_null
2020-03-12T22:23:18.638Z E Cannot read property 'userId' of null
TypeError: Cannot read property 'userId' of null
    at t._getMembershipSection (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:3363431)
    at t.render (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:3371378)
    at $a (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2070218)
    at Ya (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2070013)
    at xs (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2105194)
    at gc (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2089537)
    at hc (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2089462)
    at ic (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2086810)
    at vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2045252
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/5913369ec59578312adc/bundle.js:2:2119846)
2020-03-12T22:23:18.638Z E The above error occured while React was rendering the following components: 
    in GroupView
    in div
    in t
    in div
    in LoggedInView
    in Uc
    in MatrixChat
```

Seems to hint that an entry in the invite section of groups in the sync response didn't contain an `inviter`?

**Comment by foldleft** [comment]
https://github.com/matrix-org/riot-web-rageshakes/issues/2584

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
