### ISSUE TITLE
Cannot read property 'name' of null during 1:1 call

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#13450]
see rageshake

```
2020-04-29T20:00:56.150Z E Cannot read property 'name' of null
TypeError: Cannot read property 'name' of null
    at t.render (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:4573761)
    at Ua (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2272842)
    at La (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2272637)
    at fs (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2308381)
    at lc (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2299630)
    at sc (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2299555)
    at Zs (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2296636)
    at https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2248298
    at t.unstable_runWithPriority (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2323453)
    at Vr (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2248007)
2020-04-29T20:00:56.213Z I Ending watcher ID redacted
2020-04-29T20:00:56.221Z I Ending watcher ID redacted
2020-04-29T20:00:56.241Z I Ending watcher ID redacted
2020-04-29T20:00:56.255Z I Ending watcher ID redacted
2020-04-29T20:00:56.268Z I Ending watcher ID redacted
2020-04-29T20:00:56.269Z I Ending watcher ID redacted
2020-04-29T20:00:56.409Z E Cannot read property 'name' of null
TypeError: Cannot read property 'name' of null
    at t.render (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:4573761)
    at Ua (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2272842)
    at La (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2272637)
    at fs (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2308381)
    at lc (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2299630)
    at sc (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2299555)
    at Zs (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2296636)
    at https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2248298
    at t.unstable_runWithPriority (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2323453)
    at Vr (https://riot.im/app/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2248007)
2020-04-29T20:00:56.420Z E The above error occured while React was rendering the following components: 
    in CallView
    in CallPreview
    in aside
    in div
    in LeftPanel
    in div
    in t
    in div
    in LoggedInView
    in kc
    in MatrixChat
```

**Comment by SimonBrandner** [comment]
@turt2live, is this still relevant?

**Comment by turt2live** [comment]
Let's assume no :D
