### ISSUE TITLE
Searching rooms before sync is completed causes crash?

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#13498]
```
2020-05-03T12:30:11.286Z E Cannot read property 'roomId' of null
TypeError: Cannot read property 'roomId' of null
    at t._getPermalinkCreatorForRoom (vector://vector/webapp/bundles/44ad918b2bd0a9925fd6/bundle.js:2:1737816)
    at t.getSearchResultTiles (vector://vector/webapp/bundles/44ad918b2bd0a9925fd6/bundle.js:2:1753676)
    at t.render (vector://vector/webapp/bundles/44ad918b2bd0a9925fd6/bundle.js:2:1764990)
    at Ua (vector://vector/webapp/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2272842)
    at La (vector://vector/webapp/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2272637)
    at fs (vector://vector/webapp/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2308381)
    at lc (vector://vector/webapp/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2299630)
    at sc (vector://vector/webapp/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2299555)
    at Zs (vector://vector/webapp/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2296636)
    at vector://vector/webapp/bundles/44ad918b2bd0a9925fd6/bundle.js:2:2248298
```

Prior message is CORS failure on `/filter`, indicative of the sync loop trying to establish itself. This was a fresh session and so not an incremental sync failure (though the sync itself looks to be incremental as it loaded from saved state).

**Comment by turt2live** [comment]
I'm just going to close this pending a modern case of it happening. The lack of activity on this issue tells me it's either not common enough to be a workflow issue or that we fixed it and don't know why.

If people are still seeing this, please open a new issue with new information.
