### ISSUE TITLE
Community view can crash when `inviter` is null

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#14133]
```
2020-06-20T17:38:12.597Z I Setting up Mjolnir: after sync
2020-06-20T17:38:12.597Z I Updating Mjolnir ban lists to: 
2020-06-20T17:38:12.647Z E Cannot read property 'userId' of null
TypeError: Cannot read property 'userId' of null
    at t._getMembershipSection (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:3789560)
    at t.render (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:3797529)
    at Us (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1452900)
    at Ls (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1452695)
    at _a (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1488494)
    at lc (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1479741)
    at ac (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1479666)
    at Za (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1476696)
    at https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1428338
    at t.unstable_runWithPriority (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1509772)
2020-06-20T17:38:12.647Z I Ending watcher ID 1592674692548_8_breadcrumbs_null
2020-06-20T17:38:12.647Z I Ending watcher ID 1592674692548_9_TagPanel.disableTagPanel_null
2020-06-20T17:38:12.648Z I Ending watcher ID 1592674692560_10_breadcrumb_rooms_null
2020-06-20T17:38:12.648Z E Cannot read property 'userId' of null
TypeError: Cannot read property 'userId' of null
    at t._getMembershipSection (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:3789560)
    at t.render (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:3797529)
    at Us (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1452900)
    at Ls (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1452695)
    at _a (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1488494)
    at lc (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1479741)
    at ac (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1479666)
    at Za (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1476696)
    at https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1428338
    at t.unstable_runWithPriority (https://riot.im/app/bundles/233b13f20bb4c45d6271/vendors~init.js:2:1509772)
2020-06-20T17:38:12.648Z E The above error occured while React was rendering the following components: 
    in GroupView
    in div
    in t
    in div
    in LoggedInView
    in hu
    in MatrixChat
```

**Comment by t3chguy** [comment]
This is fixed by Spaces landing in Beta in next Release
