### ISSUE TITLE
Element-desktop 1.7.8 builds but doesn't run: JS error

### ISSUE THREAD

**Issue by daduke** [vector-im/element-web#15311]
### Description

I've been building Element-desktop on both Fedora and Ubuntu according to your build instructions since around 1.7.0. With 1.7.8 it builds just fine, but when starting the resulting .rpm or .deb binary, it throws a JS error instead.

### Steps to reproduce

- follow the build instructions: git clone, yarn install, yarn run fetch --noverify --cfgdir '', yarn run build:native, yarn run build
- install .rpm or .deb
- start element-desktop

Result:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'request'
Require stack:
- /opt/Element/resources/app.asar/src/webcontents-handler.js
- /opt/Element/resources/app.asar/src/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:961:15)
    at Function.o._resolveFilename (electron/js2c/browser_init.js:257:919)
    at Module._load (internal/modules/cjs/loader.js:844:27)
    at Function.Module._load (electron/js2c/asar.js:769:28)
    at Module.require (internal/modules/cjs/loader.js:1023:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/opt/Element/resources/app.asar/src/webcontents-handler.js:4:17)
    at Module._compile (internal/modules/cjs/loader.js:1145:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1166:10)
    at Module.load (internal/modules/cjs/loader.js:981:32)
```

Logs being sent: yes/no

### Version information

- element-desktop 1.7.8 on both Fedora and Ubuntu

**Comment by t3chguy** [comment]
`request` is listed in the `yarn.lock` file so something in your environment went squirrelly, we weren't listing it as we should have but will not be rushing a release for it.

**Comment by daduke** [comment]
after you closed the bug I `git pull`ed and got a different yarn.lock than before.. now it's working find on both Fedora and Ubuntu. Thanks for the fast fix!

**Comment by t3chguy** [comment]
Yes, the default branch is not the release branch but rather `develop` so you'll have my fix from above
