### ISSUE TITLE
add console method to login with just hs_url and access token

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#15528]
it can use APIs like /whoami to fill in the gaps

**Comment by genofire** [comment]
Who to use it?

**Comment by celevra** [comment]
it throws following errors:
```
rageshake.ts:69 Warning! Not using an encryption key for rust crypto store.
client.ts:1934 Uncaught (in promise) Error: Cannot enable encryption on MatrixClient with unknown deviceId: ensure deviceId is passed in createClient().
    at Object.initClientCrypto (MatrixClientPeg.ts:335:33)
    at Object.assign (MatrixClientPeg.ts:291:24)
    at async Object.start (MatrixClientPeg.ts:365:15)
    at async er (Lifecycle.ts:985:29)
    at async Go (Lifecycle.ts:798:5)
    at async window.mxLoginWithAccessToken (Lifecycle.ts:1127:50)

```
