### ISSUE TITLE
Guest log out does not make sense

### ISSUE THREAD

**Issue by mehmetalianil** [vector-im/element-web#15700]
![ezgif-3-6cb64a1a4e8d](https://user-images.githubusercontent.com/551129/98795224-43c21d80-240a-11eb-846c-d1ae75541f0a.gif)

![image](https://user-images.githubusercontent.com/551129/98795445-82f06e80-240a-11eb-8d51-c7d958118df4.png)

### Description

Guest login and joining as guest to public rooms work, but when a guest tries to logout, the screen does not get back to the login page. 

### Steps to reproduce

- Open self-hosted element-web with Guest enabled.
- Click Explore rooms
- Join one of the public rooms.
- Wait here (Optionally? My original login was more than 12h ago, timeout issue?)
- After  a while try to log out of the room.
- If I clear local storage from Inspector -> Application than I get back to the login page.

I expected to get back to the login page without manually clearing Local Storage. 

Logs being sent:  Will Try.

### Version information

- **Platform**: web (in-browser)

For the web app:

- **Browser**: 

Brave | 1.16.72 Chromium: 86.0.4240.183 (Official Build) (64-bit)
Revision | 0b568b034b8f7994697cb341eeca5979b84151cc-refs/branch-heads/4240@{#1374}
OS | Windows 10 OS Version 2009 (Build 19042.610)
JavaScript | V8 8.6.395.23
- **URL**: https://chat.grusbv.com/ Riot 1.7.12

**Comment by mehmetalianil** [comment]
Initial login also results in some logs with error, so this might be related to something else.
```
index.js:218 PUT https://matrix.grusbv.com/_matrix/client/r0/user/%404%3Agrusbv.com/account_data/im.vector.setting.breadcrumbs 403 (Forbidden)
(anonymous) @ index.js:218
t @ index.js:179
(anonymous) @ browser-index.js:29
_request @ http-api.js:716
requestOtherUrl @ http-api.js:594
request @ http-api.js:549
authedRequest @ http-api.js:492
(anonymous) @ client.js:2378
y @ http-api.js:968
N.setAccountData @ client.js:2377
setValue @ AccountSettingsHandler.ts:144
setValue @ LocalEchoWrapper.ts:57
setValue @ SettingsStore.ts:424
appendRoom @ BreadcrumbsStore.ts:171
async function (async)
appendRoom @ BreadcrumbsStore.ts:168
(anonymous) @ BreadcrumbsStore.ts:111
a.emit @ events.js:158
(anonymous) @ sync.js:1264
D @ utils.ts:740
async function (async)
D @ utils.ts:739
m._processSyncResponse @ sync.js:1157
m._sync @ sync.js:776
async function (async)
m._sync @ sync.js:743
m._sync @ sync.js:819
async function (async)
m._sync @ sync.js:743
m._sync @ sync.js:819
async function (async)
m._sync @ sync.js:743
m.sync @ sync.js:615
N.startClient @ client.js:5050
start @ MatrixClientPeg.ts:229
async function (async)
start @ MatrixClientPeg.ts:226
(anonymous) @ Lifecycle.ts:674
async function (async)
(anonymous) @ Lifecycle.ts:673
se @ Lifecycle.ts:528
async function (async)
se @ Lifecycle.ts:478
(anonymous) @ Lifecycle.ts:262
Promise.then (async)
(anonymous) @ Lifecycle.ts:260
J @ Lifecycle.ts:128
async function (async)
J @ Lifecycle.ts:120
(anonymous) @ MatrixChat.tsx:403
Promise.then (async)
loadSession @ MatrixChat.tsx:402
(anonymous) @ MatrixChat.tsx:345
Promise.then (async)
MatrixChat @ MatrixChat.tsx:325
bi @ react-dom.production.min.js:134
Ls @ react-dom.production.min.js:176
_a @ react-dom.production.min.js:263
lc @ react-dom.production.min.js:246
ac @ react-dom.production.min.js:246
Za @ react-dom.production.min.js:239
Ya @ react-dom.production.min.js:230
Mc @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
tc @ react-dom.production.min.js:240
qc @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
ne @ init.tsx:149
async function (async)
ne @ init.tsx:145
(anonymous) @ index.ts:200
async function (async)
(anonymous) @ index.ts:103
59 @ index.ts:211
a @ bootstrap:68
(anonymous) @ bootstrap:272
(anonymous) @ bundle.js:2
rageshake.js:65 LL: got 4 members from server for room !pPEIfoJcNqqabbsXoj:grusbv.com
rageshake.js:65 LL: RoomState about to set 4 OOB members ...
rageshake.js:65 LL: RoomState put in OOB_STATUS_FINISHED state ...
rageshake.js:65 LL: telling store to write 0 members for room !pPEIfoJcNqqabbsXoj:grusbv.com
logger.js:47 LL: backend about to store 0 members for !pPEIfoJcNqqabbsXoj:grusbv.com
logger.js:47 LL: backend done storing for !pPEIfoJcNqqabbsXoj:grusbv.com!
rageshake.js:65 Saving device tracking data s128431_8829378_2416_223706_2451_19_786_440156_13
http-api.js:910 Uncaught (in promise) M_GUEST_ACCESS_FORBIDDEN: Guest access not allowed
    at https://chat.grusbv.com/bundles/5266b1fa210ff441aa94/vendors~init.js:2:659362
    at https://chat.grusbv.com/bundles/5266b1fa210ff441aa94/vendors~init.js:2:659519
    at Object.callback (https://chat.grusbv.com/bundles/5266b1fa210ff441aa94/vendors~init.js:2:658673)
    at https://chat.grusbv.com/bundles/5266b1fa210ff441aa94/vendors~init.js:2:29973
    at XMLHttpRequest.r.onreadystatechange (https://chat.grusbv.com/bundles/5266b1fa210ff441aa94/vendors~init.js:2:29997)
b @ http-api.js:910
(anonymous) @ http-api.js:852
(anonymous) @ http-api.js:807
(anonymous) @ http-api.js:742
(anonymous) @ index.js:294
r.onreadystatechange @ index.js:244
async function (async)
(anonymous) @ BreadcrumbsStore.ts:111
a.emit @ events.js:158
(anonymous) @ sync.js:1264
D @ utils.ts:740
async function (async)
D @ utils.ts:739
m._processSyncResponse @ sync.js:1157
m._sync @ sync.js:776
async function (async)
m._sync @ sync.js:743
m._sync @ sync.js:819
async function (async)
m._sync @ sync.js:743
m._sync @ sync.js:819
async function (async)
m._sync @ sync.js:743
m.sync @ sync.js:615
N.startClient @ client.js:5050
start @ MatrixClientPeg.ts:229
async function (async)
start @ MatrixClientPeg.ts:226
(anonymous) @ Lifecycle.ts:674
async function (async)
(anonymous) @ Lifecycle.ts:673
se @ Lifecycle.ts:528
async function (async)
se @ Lifecycle.ts:478
(anonymous) @ Lifecycle.ts:262
Promise.then (async)
(anonymous) @ Lifecycle.ts:260
J @ Lifecycle.ts:128
async function (async)
J @ Lifecycle.ts:120
(anonymous) @ MatrixChat.tsx:403
Promise.then (async)
loadSession @ MatrixChat.tsx:402
(anonymous) @ MatrixChat.tsx:345
Promise.then (async)
MatrixChat @ MatrixChat.tsx:325
bi @ react-dom.production.min.js:134
Ls @ react-dom.production.min.js:176
_a @ react-dom.production.min.js:263
lc @ react-dom.production.min.js:246
ac @ react-dom.production.min.js:246
Za @ react-dom.production.min.js:239
Ya @ react-dom.production.min.js:230
Mc @ react-dom.production.min.js:281
(anonymous) @ react-dom.production.min.js:284
tc @ react-dom.production.min.js:240
qc @ react-dom.production.min.js:284
t.render @ react-dom.production.min.js:290
ne @ init.tsx:149
async function (async)
ne @ init.tsx:145
(anonymous) @ index.ts:200
async function (async)
(anonymous) @ index.ts:103
59 @ index.ts:211
a @ bootstrap:68
(anonymous) @ bootstrap:272
(anonymous) @ bundle.js:2
rageshake.js:65 got device keys for @4:grusbv.com: {guest_device: {…}}
rageshake.js:65 got cross-signing keys for @4:grusbv.com: {master: undefined, self_signing: undefined, user_signing: undefined}
rageshake.js:65 Completed key download for @4:grusbv.com
rageshake.js:65 Device list for @4:grusbv.com now up to date
rageshake.js:65 Saving device tracking data s128431_8829378_2416_223706_2451_19_786_440156_13
```

**Comment by mehmetalianil** [comment]
Unfortunately, Guest accounts don't have account settings.

**Comment by t3chguy** [comment]
You can send logs from Feedback > send debug logs too

**Comment by t3chguy** [comment]
Guest logout makes no sense at all, it should be a Sign in/Create account button instead

**Comment by mehmetalianil** [comment]
> You can send logs from Feedback > send debug logs too

Feedback screen only has this:
![image](https://user-images.githubusercontent.com/551129/98865245-67698000-246b-11eb-9a2a-680bbb4a9fe3.png)

**Comment by t3chguy** [comment]
You are on an out of date version then.

![image](https://user-images.githubusercontent.com/2403652/98877512-9508f600-2478-11eb-926a-70f5176dbd4a.png)
