### ISSUE TITLE
Build failure - neon-sys

### ISSUE THREAD

**Issue by srevinsaju** [vector-im/element-web#15823]
### Description

Build failure on `element-desktop`, `master` branch, possibly something gone awry on `neon-*` again

Build on CentOS 7

I remember having pinned versions on `neon-serde`, but I guess something changed after that. Possibly this issue is to be transfered if all the version corresponding to our dependencies are right.

```
warning: ar: /__w/element-appimage/element-appimage/element-desktop/.hak/matrix-seshat/build/native/target/release/build/neon-sys-22a5e568369ad3fa/out/native/build/Release/obj.target/neon/src/neon.o: No such file or directory

error: failed to run custom build command for `neon-sys v0.4.0`

Caused by:
  process didn't exit successfully: `/__w/element-appimage/element-appimage/element-desktop/.hak/matrix-seshat/build/native/target/release/build/neon-sys-2a7b2ea8a84a18fb/build-script-build` (exit code: 1)
  --- stdout
  added 96 packages from 70 contributors and audited 96 packages in 3.071s
  found 7 vulnerabilities (3 low, 1 moderate, 3 high)
    run `npm audit fix` to fix them, or `npm audit` for details

  > @ build-release /__w/element-appimage/element-appimage/element-desktop/.hak/matrix-seshat/build/native/target/release/build/neon-sys-22a5e568369ad3fa/out/native
  > node-gyp build

  make: Entering directory `/__w/element-appimage/element-appimage/element-desktop/.hak/matrix-seshat/build/native/target/release/build/neon-sys-22a5e568369ad3fa/out/native/build'
    CXX(target) Release/obj.target/neon/src/neon.o
  make: Leaving directory `/__w/element-appimage/element-appimage/element-desktop/.hak/matrix-seshat/build/native/target/release/build/neon-sys-22a5e568369ad3fa/out/native/build'
  TARGET = Some("x86_64-unknown-linux-gnu")
  HOST = Some("x86_64-unknown-linux-gnu")
  AR_x86_64-unknown-linux-gnu = None
  AR_x86_64_unknown_linux_gnu = None
  HOST_AR = None
  AR = None
  running: "ar" "cq" "/__w/element-appimage/element-appimage/element-desktop/.hak/matrix-seshat/build/native/target/release/build/neon-sys-22a5e568369ad3fa/out/libneon.a" "/__w/element-appimage/element-appimage/element-desktop/.hak/matrix-seshat/build/native/target/release/build/neon-sys-22a5e568369ad3fa/out/native/build/Release/obj.target/neon/src/neon.o"
  cargo:warning=ar: /__w/element-appimage/element-appimage/element-desktop/.hak/matrix-seshat/build/native/target/release/build/neon-sys-22a5e568369ad3fa/out/native/build/Release/obj.target/neon/src/neon.o: No such file or directory
  exit code: 1

  --- stderr
  npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1606307317731-0.9247647478828038/node but npm is using /__t/node/12.19.0/x64/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
  In file included from /github/home/.electron-gyp/11.0.1/include/node/v8.h:30:0,
                   from /github/home/.electron-gyp/11.0.1/include/node/node.h:67,
                   from ../node_modules/nan/nan.h:54,
                   from ../src/neon.cc:2:
  /github/home/.electron-gyp/11.0.1/include/node/v8-internal.h: In function 'void v8::internal::PerformCastCheck(T*)':
  /github/home/.electron-gyp/11.0.1/include/node/v8-internal.h:418:33: error: 'remove_cv_t' is not a member of 'std'
               !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                   ^
  /github/home/.electron-gyp/11.0.1/include/node/v8-internal.h:418:33: error: 'remove_cv_t' is not a member of 'std'
  /github/home/.electron-gyp/11.0.1/include/node/v8-internal.h:418:50: error: template argument 2 is invalid
               !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                                    ^
  /github/home/.electron-gyp/11.0.1/include/node/v8-internal.h:418:61: error: '::Perform' has not been declared
               !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
                                                               ^
  In file included from /github/home/.electron-gyp/11.0.1/include/node/node.h:67:0,
                   from ../node_modules/nan/nan.h:54,
                   from ../src/neon.cc:2:
  /github/home/.electron-gyp/11.0.1/include/node/v8.h: At global scope:
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:1658:58: warning: 'deprecated' attribute directive ignored [-Wattributes]
                                   Local<Value> export_value);
                                                            ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:1840:74: warning: 'deprecated' attribute directive ignored [-Wattributes]
       StreamedSource(ExternalSourceStream* source_stream, Encoding encoding);
                                                                            ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:3121:21: warning: 'deprecated' attribute directive ignored [-Wattributes]
     bool IsExternal() const;
                       ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:3437:23: warning: 'deprecated' attribute directive ignored [-Wattributes]
     Local<Value> Name() const { return Description(); }
                         ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:5255:76: warning: 'deprecated' attribute directive ignored [-Wattributes]
         ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                                                              ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:5302:21: warning: 'deprecated' attribute directive ignored [-Wattributes]
     bool IsExternal() const;
                       ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:5329:24: warning: 'deprecated' attribute directive ignored [-Wattributes]
     Contents Externalize();
                          ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:5339:70: warning: 'deprecated' attribute directive ignored [-Wattributes]
     void Externalize(const std::shared_ptr<BackingStore>& backing_store);
                                                                        ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:5350:24: warning: 'deprecated' attribute directive ignored [-Wattributes]
     Contents GetContents();
                          ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:5738:76: warning: 'deprecated' attribute directive ignored [-Wattributes]
         ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                                                              ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:5787:76: warning: 'deprecated' attribute directive ignored [-Wattributes]
         ArrayBufferCreationMode mode = ArrayBufferCreationMode::kExternalized);
                                                                              ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:5796:21: warning: 'deprecated' attribute directive ignored [-Wattributes]
     bool IsExternal() const;
                       ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:5812:24: warning: 'deprecated' attribute directive ignored [-Wattributes]
     Contents Externalize();
                          ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:5822:70: warning: 'deprecated' attribute directive ignored [-Wattributes]
     void Externalize(const std::shared_ptr<BackingStore>& backing_store);
                                                                        ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:5837:24: warning: 'deprecated' attribute directive ignored [-Wattributes]
     Contents GetContents();
                          ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:7182:28: warning: 'deprecated' attribute directive ignored [-Wattributes]
     size_t code_range_size() const { return code_range_size_ / kMB; }
                              ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:7184:46: warning: 'deprecated' attribute directive ignored [-Wattributes]
     void set_code_range_size(size_t limit_in_mb) {
                                                ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:7188:38: warning: 'deprecated' attribute directive ignored [-Wattributes]
     size_t max_semi_space_size_in_kb() const;
                                        ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:7190:56: warning: 'deprecated' attribute directive ignored [-Wattributes]
     void set_max_semi_space_size_in_kb(size_t limit_in_kb);
                                                          ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:7192:31: warning: 'deprecated' attribute directive ignored [-Wattributes]
     size_t max_old_space_size() const { return max_old_generation_size_ / kMB; }
                                 ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:7194:49: warning: 'deprecated' attribute directive ignored [-Wattributes]
     void set_max_old_space_size(size_t limit_in_mb) {
                                                   ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:7198:31: warning: 'deprecated' attribute directive ignored [-Wattributes]
     size_t max_zone_pool_size() const { return max_zone_pool_size_; }
                                 ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:7200:43: warning: 'deprecated' attribute directive ignored [-Wattributes]
     void set_max_zone_pool_size(size_t bytes) { max_zone_pool_size_ = bytes; }
                                             ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:7384:53: warning: 'deprecated' attribute directive ignored [-Wattributes]
   typedef void (*MicrotasksCompletedCallback)(Isolate*);
                                                       ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:8791:59: warning: 'deprecated' attribute directive ignored [-Wattributes]
                                       MeasureMemoryMode mode);
                                                             ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:8854:36: warning: 'deprecated' attribute directive ignored [-Wattributes]
     Local<Context> GetEnteredContext();
                                      ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:9138:22: warning: 'deprecated' attribute directive ignored [-Wattributes]
     void RunMicrotasks() { PerformMicrotaskCheckpoint(); }
                        ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:9182:75: warning: 'deprecated' attribute directive ignored [-Wattributes]
     void AddMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
                                                                             ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:9190:78: warning: 'deprecated' attribute directive ignored [-Wattributes]
     void RemoveMicrotasksCompletedCallback(MicrotasksCompletedCallback callback);
                                                                                ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:9430:54: warning: 'deprecated' attribute directive ignored [-Wattributes]
         AllowCodeGenerationFromStringsCallback callback);
                                                        ^
  /github/home/.electron-gyp/11.0.1/include/node/v8.h:9790:75: warning: 'deprecated' attribute directive ignored [-Wattributes]
     static bool TryHandleSignal(int signal_number, void* info, void* context);
                                                                             ^
  In file included from /github/home/.electron-gyp/11.0.1/include/node/node.h:72:0,
                   from ../node_modules/nan/nan.h:54,
                   from ../src/neon.cc:2:
  /github/home/.electron-gyp/11.0.1/include/node/v8-platform.h:251:38: warning: 'deprecated' attribute directive ignored [-Wattributes]
     virtual size_t GetMaxConcurrency() const { return 0; }
                                        ^
  In file included from ../src/neon.cc:10:0:
  ../src/neon_task.h: In member function 'void neon::Task::complete()':
  ../src/neon_task.h:62:70: warning: 'v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)' is deprecated (declared at /github/home/.electron-gyp/11.0.1/include/node/node.h:182): Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
       node::MakeCallback(isolate_, context->Global(), callback, 2, argv);
                                                                        ^
  ../src/neon.cc: In function 'void Neon_Class_SetClassMap(v8::Isolate*, void*, Neon_DropCallback)':
  ../src/neon.cc:329:41: warning: 'void node::AtExit(void (*)(void*), void*)' is deprecated (declared at /github/home/.electron-gyp/11.0.1/include/node/node.h:705): Use the three-argument variant of AtExit() or AddEnvironmentCleanupHook() [-Wdeprecated-declarations]
     node::AtExit(cleanup_class_map, holder);
                                           ^
  In file included from ../src/neon.cc:8:0:
  ../src/neon_string.h: In member function 'v8::Local<v8::String> neon::Slice::ToJsString(v8::Isolate*, const char*)':
  ../src/neon_string.h:28:27: warning: ignoring return value of 'bool v8::MaybeLocal<T>::ToLocal(v8::Local<S>*) const [with S = v8::String; T = v8::String]', declared with attribute warn_unused_result [-Wunused-result]
       maybe.ToLocal(&result);
                             ^
  make: *** [Release/obj.target/neon/src/neon.o] Error 1
  gyp ERR! build error 
  gyp ERR! stack Error: `make` failed with exit code: 2
  gyp ERR! stack     at ChildProcess.onExit (/__w/element-appimage/element-appimage/element-desktop/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
  gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
  gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
  gyp ERR! System Linux 5.4.0-1031-azure
  gyp ERR! command "/__t/node/12.19.0/x64/bin/node" "/__w/element-appimage/element-appimage/element-desktop/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
  gyp ERR! cwd /__w/element-appimage/element-appimage/element-desktop/.hak/matrix-seshat/build/native/target/release/build/neon-sys-22a5e568369ad3fa/out/native
  gyp ERR! node -v v12.19.0
  gyp ERR! node-gyp -v v5.1.0
  gyp ERR! not ok 
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! @ build-release: `node-gyp build`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the @ build-release script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Complete log attached below;

[log.log](https://github.com/vector-im/element-web/files/5596689/log.log)

**Comment by jryans** [comment]
Hmm, it's true we've had issues with `neon` versions in the past, yes... However, our Element nightly builds seem to run successfully for all platforms even after the Electron 11 upgrade, so I wonder why it's failing here...

We might need to look around the `neon` community to see if anyone else is hitting errors like this.

**Comment by 0xADD1E** [comment]
It may be worth noting that I also am seeing this issue trying to build for win32. I've got it set up in a container, and can share any sort info from there, if that would be helpful

**Comment by srevinsaju** [comment]
@jryans , since https://github.com/vector-im/element-desktop/pull/156 the builds are having another error:
```bash
yarn run v1.22.5
$ yarn run mkdirs && node scripts/fetch-package.js --importkey
$ mkdirp packages deploys
Key imported!
Done in 0.93s.
yarn run v1.22.5
$ yarn run mkdirs && node scripts/fetch-package.js --cfgdir config
$ mkdirp packages deploys
Downloading https://github.com/vector-im/element-web/releases/download/v1.7.14/element-v1.7.14.tar.gz...
Downloading https://github.com/vector-im/element-web/releases/download/v1.7.14/element-v1.7.14.tar.gz.asc...
Signature verification failed! Error: Command failed: gpg --verify packages/element-v1.7.14.tar.gz.asc packages/element-v1.7.14.tar.gz
gpg: can't open `packages/element-v1.7.14.tar.gz.asc': No such file or directory
gpg: verify signatures failed: No such file or directory

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:314:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:314:20)
    at Pipe.<anonymous> (net.js:676:12) {
  killed: false,
  code: 2,
  signal: null,
  cmd: 'gpg --verify packages/element-v1.7.14.tar.gz.asc packages/element-v1.7.14.tar.gz'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by jryans** [comment]
@srevinsaju Well, that PR temporarily reverts to Electron 10.x, so it makes sense that it would make the original issue here go away, but we do intend to eventually use Electron 11, so it's likely to return if we don't figure out the root cause before then.

It looks like you are using `develop` branch of `element-desktop`, but you should use `master` for the most recent stable release. `develop` contains changes to the expected file names (Riot -> Element), but those only working with the upcoming release.

**Comment by srevinsaju** [comment]
The `master` branch builds cleanly. The `develop` branch is the problem as of now. I am not sure if you are aware of https://github.com/vector-im/element-web/issues/4766 which aims to create and distribute an AppImage for element. I had been working on it for the past 3-4 months,

![image](https://user-images.githubusercontent.com/48695438/101280771-06b83380-37dc-11eb-875a-3db6a2fe7a72.png)

13 days ago, all the [continuous  AppImage builds](https://github.com/srevinsaju/element-appimage) were passing, which made me think if element has moved to a new build system and I should consider rewriting my build script. If this error is expected, its fine. Thanks a lot for looking into it, and helping me out.

PS: If you would like me to move the continuous integration for AppImage builds into your repo, cool! I am willing to work on it. Just let me know! We always wanted the Element authors to themselves, officially release the AppImage unlike a third party like me. I am sure I can tweak the script out for you!

**Comment by srevinsaju** [comment]
Fixed,
