### ISSUE TITLE
Can't build on Slackware-current GNU/Linux: seshat doesn't compile/link

### ISSUE THREAD

**Issue by dchmelik** [vector-im/element-web#16176]
### Description

Can't build on Slackware-current GNU/Linux: seshat doesn't compile/link.

### Steps to reproduce

Do everything through 'yarn run build:native'

Logs being sent: yes

### Version information
- **Platform**: desktop

- **OS**: Slackware64-current
- **Version**: element-desktop 1.7.16

**Comment by t3chguy** [comment]
Can you share the error you get?

**Comment by dchmelik** [comment]
```
   Compiling seshat-node v2.2.1 (/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native)
   Compiling neon-serde v0.4.0
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-Wl,--eh-frame-hdr" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.0.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.1.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.10.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.11.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.12.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.13.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.14.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.15.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.2.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.3.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.4.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.5.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.6.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.7.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.8.rcgu.o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.seshat_node.7kci02ru-cgu.9.rcgu.o" "-o" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libseshat_node.so" "-Wl,--version-script=/tmp/rustcrYLjyb/list" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/seshat_node.2uu3kijthp7aoyak.rcgu.o" "-Wl,--gc-sections" "-shared" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps" "-L" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/build/neon-sys-90d5b03a9614c1a5/out" "-L" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libneon_serde-50f31ad8012211fa.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libnum-681b9b2e00ddfff8.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libnum_rational-e441b5aa179d905c.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libnum_iter-2d5fb2fc160737ac.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libnum_complex-d4bd12facc433157.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/liberror_chain-0943fcba6841c784.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libseshat-0027490a246ca847.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libtinysegmenter-892663558789aecd.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libmaplit-314dad89f8eb9c3d.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/liblru_cache-4ae2b677ffc91f30.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/liblinked_hash_map-530fb46a0988bbe1.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libtantivy-af8c10cf896e9ac1.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libhtmlescape-7529517a2edf9e9e.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libsnap-77217fe0f29964d2.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libbase64-b904e08c50341de9.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libregex-6e7a35d47e30acf2.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libthread_local-0bce6f6a05cfeb53.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libregex_syntax-43f98fd16799da22.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libaho_corasick-4bd26eb993570865.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libtantivy_query_grammar-7d0f7f7c4a7681fa.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcombine-8cfde4d6ea9c6fb4.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libbytes-b3832202ada28aaa.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libmurmurhash32-23b98d055e9754d9.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libtantivy_fst-38d2452c61072b02.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/liblevenshtein_automata-8cc0e3ea3c17a937.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfst-b564a273b08c7862.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libutf8_ranges-f41d807a6a413fd2.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libregex_syntax-b7d5b2c61d2a7bad.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libbitpacking-d9717793c049b9a1.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcrunchy-3bf486f798bfdbb9.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libowning_ref-7a856061a8600ca2.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcrc32fast-22175b129a7b7f3c.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libtempfile-93142aef39353f80.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libmemmap-9e8c5b90cbd37eb5.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libatomicwrites-445c60b251604fc8.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libnix-5911a4e2359f489e.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libvoid-8fc0c1048fd4886d.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libtempdir-0ba4f9a5ef2a12e5.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libremove_dir_all-b22515a2684cbc51.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand-e4fbfab87a6ffed7.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libnotify-395f407d3cca2f86.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libwalkdir-2c50bf18376188e9.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libsame_file-be1e035d9dca09f5.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libinotify-929c274378c056be.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libinotify_sys-51a3a7ef7926fcd3.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libmio_extras-92752a008d8280a4.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/liblazycell-db05e2ebef3a3954.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libmio-37c36ff7d1df0ba6.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libiovec-4d8afda402fb9166.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libnet2-90c2849a630b4f6d.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfiletime-778c502a768b1915.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfs2-a6a0e14aa3b27b0a.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libdowncast_rs-957307566a9c5d38.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfnv-523cb4906ba7fe96.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librust_stemmers-1c729c1a1fa01a32.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libitertools-553f5c711a430649.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfutures-4c262c0c33f52e2c.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfutures_executor-427490ea235c2183.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfutures_util-d7d2f8f01d61d0f3.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libmemchr-1cd2bc334aa516fc.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfutures_io-6034008df247a8f2.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libslab-fda80381ad3c34f1.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfutures_channel-8e9df19dc57da047.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libpin_project_lite-7fbfaa48cadf7505.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfutures_sink-de9c67922727a8ea.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfutures_task-856ff7de16e7447a.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libpin_utils-57998bde6df3b9fb.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfutures_core-1c80f18fa20c20e7.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libonce_cell-a73080189fceebb0.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfail-090f731c5c8149f9.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand-b55438185e6af091.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand_xorshift-d0bf0a094088c9a4.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand_pcg-940e99fdbaa17fdf.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand_hc-388541a124718f84.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand_chacha-cabcd142f05178ff.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand_isaac-c95d9afa7af5e58a.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand_core-777ee0aed9fa1d98.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand_os-228942962206f6ed.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand_jitter-a9d93a933cfe9471.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand_core-ac4aaf8523feda1c.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libowned_read-8189da3a4f96041d.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libstable_deref_trait-3cf712456e4e8bee.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcensus-b4258605512f783e.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librayon-621dc6700c22ec38.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librayon_core-7e323b06a2409e2f.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libnum_cpus-ce2844bcaf9b4e20.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcrossbeam_deque-070a9b52dcb32248.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcrossbeam_epoch-56eb1fabb90d64cc.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libmemoffset-4589db0cd1229a0e.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcrossbeam_channel-944c6b5a9ac9cc7e.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcrossbeam_utils-8303e63c067bbcc2.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libeither-60371cca1568c997.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcrossbeam-3a458f9a60fd61c7.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcrossbeam_queue-91aa44545799513a.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcrossbeam_channel-846c478ae4bb41d4.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcrossbeam_deque-3e2c6ea1bff30a11.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcrossbeam_epoch-53b2a3d2ca3b4f45.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libmemoffset-9d94f648ba21a6d9.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcrossbeam_utils-4e2141e3a055bb7b.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/liblazy_static-b54ea61e9aa6debf.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libmaybe_uninit-1c79b49338fb9f98.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libchrono-545d3e754553af32.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libnum_integer-70c126a7fdb61390.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libnum_traits-b214cd11fd7a512f.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libtime-95c32146b0a76b01.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfailure-9c1960af5deb6228.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libbacktrace-15a8c351f62e4dd2.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libminiz_oxide-2fd1916b1d74ee84.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libadler-1dd15fdba01606f2.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libobject-e149547f3de5fd3c.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libaddr2line-69022f0a0f0b0e76.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libgimli-46b85a419e38b4c9.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librustc_demangle-4bc343e4f7107278.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libpbkdf2-d0da11b73a0fff79.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libbase64-d485f451b0711361.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libsha2-6e8bdf72f91005ba.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcpuid_bool-a511188b3e8fb9e7.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libblock_buffer-b4121c52d2581dfe.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand_core-abc908bc92a539cb.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libgetrandom-9c3507ca1e54bbf0.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libhkdf-d8a376ce0c8959d5.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libhmac-b0e0a8a23eba1a03.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcrypto_mac-b243a629a922b87a.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libsubtle-fe4b2b64b0825baa.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libdigest-bbccbcc8164fc7b8.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libaes_ctr-70847406d4b5e0ae.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libctr-9ccca5a797dd103b.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libaes_soft-152d8f65d5f321b0.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libopaque_debug-ff52af415c56e1a8.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcipher-9f7d6444ced4c786.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libgeneric_array-ea0bb9d560cf9cde.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libtypenum-2d706fa23af31e2b.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libbyteorder-78f845dcd1a7523b.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand-4b2e48ed64e4e205.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand_chacha-49f995876d1a27ff.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libppv_lite86-09e91ff2e1ad1a59.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librand_core-c2b85c66b2b7cf64.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libthiserror-cdc405071f871cb0.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libserde_json-2bb9bb8be6ba5f16.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libryu-1946cf97168e20e7.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libitoa-4d06b90586fc5f4e.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libr2d2_sqlite-6498aaf7b017ad05.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/librusqlite-1bf3cd49c942d261.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libbitflags-f38a3fb45b06ceaa.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfallible_streaming_iterator-76a3aa192369efab.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfallible_iterator-0481f00e7adc68ce.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libhashlink-530b6a7b708e09ae.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libhashbrown-34bfeed0750d8496.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libahash-d8ff61051ab20e6a.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/liblibsqlite3_sys-1ff7f12210602aad.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libr2d2-1d22ada7bcfce05c.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libscheduled_thread_pool-5feb751a9b253e90.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libparking_lot-554126d88af0a8dc.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libparking_lot_core-376f52695f75f129.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libsmallvec-5198deb4931efd8c.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/liblock_api-4dd410a08cf3775f.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libscopeguard-a2978916e207ad74.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libinstant-8982471d2f1646fd.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/liblog-a3d7dc54f5d2e2ae.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libzeroize-5e310883383773fd.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libuuid-28cca91a9948645e.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libgetrandom-38cd62e3ec0db6a7.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/liblibc-b502e9fd79183211.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcfg_if-11669ae4b1851f60.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libserde-49175def493ca3bf.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libneon-d25d2ed67dfac01f.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libsemver-4088b5d007ff9a9a.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libsemver_parser-0196d03212d62d55.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcslice-2e18f29c5bd9ea10.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libneon_runtime-8ec9bf2545529865.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libneon_sys-2d77b9de096a4969.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libcfg_if-36ae210379aafc9a.rlib" "/root/element-desktop-1.7.16/.hak/matrix-seshat/build/native/target/release/deps/libfs_extra-d6dcc16d31dec310.rlib" "-Wl,--start-group" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libstd-2f929b84647103fb.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-f035732310d86ca0.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libminiz_oxide-af1afb1bbad105a3.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libadler-bf7fba92d640d8e4.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libobject-8ebd6d54aab74d92.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libaddr2line-58f8e315fe137f96.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libgimli-75ffbc4bee06f1a6.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-d0ffa1717a570b8b.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-5da6a9dcb9e60c71.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-f303bff8a0161af0.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-38f1c02b796a36d5.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-f7b404a253f95dc5.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-dc51fb3839964985.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-f0fef7c12e927486.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-c2c0c8738063bfc6.rlib" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libcore-41ef839b5748798c.rlib" "-Wl,--end-group" "/usr/lib64/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-b6558af35e97a0e5.rlib" "-Wl,-Bdynamic" "-lsqlcipher" "-lstdc++" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
  = note: /usr/bin/ld: cannot find -lsqlcipher
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: could not compile `seshat-node`

To learn more, run the command again with --verbose.
neon ERR! cargo build failed

Error: cargo build failed
    at Target.<anonymous> (/root/element-desktop-1.7.16/.hak/matrix-seshat/build/node_modules/neon-cli/lib/target.js:121:35)
    at step (/root/element-desktop-1.7.16/.hak/matrix-seshat/build/node_modules/neon-cli/lib/target.js:32:23)
    at Object.next (/root/element-desktop-1.7.16/.hak/matrix-seshat/build/node_modules/neon-cli/lib/target.js:13:53)
    at fulfilled (/root/element-desktop-1.7.16/.hak/matrix-seshat/build/node_modules/neon-cli/lib/target.js:4:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
error Command failed with exit code 1.
```

**Comment by t3chguy** [comment]
Looks like you are missing the sqlcipher dependency

**Comment by dchmelik** [comment]
Please add a dependencies section to the README,

**Comment by t3chguy** [comment]
The recommended way to build is in docker https://github.com/vector-im/element-desktop/blob/develop/dockerbuild/Dockerfile

**Comment by dchmelik** [comment]
Installing the dependency solves the problem, but not the problem of lack of such various documentation.

**Comment by jryans** [comment]
I'd be happy to take PRs to update these docs however would be helpful... We don't have many people building desktop outside of the official builds, so I think it just hasn't come up.
