### ISSUE TITLE
End-to-end tests failing on pip install step

### ISSUE THREAD

**Issue by jryans** [vector-im/element-web#16272]
```
Traceback (most recent call last):
  File "get-pip.py", line 24226, in <module>
    main()
  File "get-pip.py", line 199, in main
    bootstrap(tmpdir=tmpdir)
  File "get-pip.py", line 82, in bootstrap
    from pip._internal.cli.main import main as pip_entry_point
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 954, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 896, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1147, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1123, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1104, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 444, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 541, in spec_from_file_location
  File "/tmp/tmpl3gzq7zy/pip.zip/pip/_internal/cli/main.py", line 60
    sys.stderr.write(f"ERROR: {exc}")
                                   ^
SyntaxError: invalid syntax
handle_error
```

Seems related to https://github.com/pypa/get-pip/issues/83. Most likely we can pin to an install for a specific Python version once we know what we're running...

**Comment by jryans** [comment]
This should be resolved now for new PRs, and I retriggered all the existing ones that were failing, so they should turn green soon. In the end, the right fix was moving CI to a newer base image with modern Python.
