### ISSUE TITLE
"Encryption can not be verified" icon should not look like "This conversation is encrypted" icon

### ISSUE THREAD

**Issue by theCalcaholic** [vector-im/element-web#16520]
![element-desktop-bug-report](https://user-images.githubusercontent.com/6317548/108863150-30ba0e80-75f1-11eb-9bbf-082bd45604ad.png)

### Description

Currently, the icon that marks a conversation/room as encrypted is exactly the same (maybe slightly scaled down) as the icon that shows for a single message that "the authenticity of this encrypted message can't be guaranteed on this device".

Ideally, these icons should look differently, the latter maybe showing a yellow color or a question mark symbol or similar to denote, that there's an issue rather than trust/security (as a shield icon suggests).

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Ubuntu 20.04
- **Version**: 1.7.21

**Comment by waclaw66** [comment]
This is annoying longstanding bug. I see it almoast next to every message.
Maybe some debug log would help to solve it. Following is shown when I click to a room...
```
Looking at $_1ljnRnB6YAYb5UEcDEQtimq8l_L5ahc4IQQ84oVyQw rageshake.js:52:4
Switching to room id !TOZTddobMdopmqVIdZ:server.net at event undefined rageshake.js:52:4
RVS update: !TOZTddobMdopmqVIdZ:server.net undefined loading? false joining? false initial? true shouldPeek? true rageshake.js:52:4
Returning cached capabilities
```
There is a lot of `undefined`.
I suspect database inconsistency, it would be helpful to have a tool which checks, fixes and cleans it.
