### ISSUE TITLE
element-desktop: native dependencies don't build correctly if your electron versions are mismatched

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#16773]
I may be wrong here, but when following the [element-desktop Starting section](https://github.com/vector-im/element-desktop#starting) of the README, it asks me to install the latest `electron`. At the time of writing this is `12.0.2`.

However, the `build.electronVersion` in `package.json` is currently `11.2.3`.

I wanted to test out some native modules with my development setup, so I ran `yarn run build:native`, and then did `yarn start`. I ended up with the following logs:

```
> yarn start
yarn run v1.22.10
$ electron .
Keytar unexpected error: Error: Module did not self-register: '/home/user/code/element-desktop/.hak/hakModules/keytar/build/Release/keytar.node'.
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/user/code/element-desktop/.hak/hakModules/keytar/lib/keytar.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
Seshat unexpected error: Error: The module '/home/user/code/element-desktop/.hak/hakModules/matrix-seshat/native/index.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 85. This version of Node.js requires
NODE_MODULE_VERSION 87. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/user/code/element-desktop/.hak/hakModules/matrix-seshat/lib/index.js:15:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
/home/user/.config/Element exists: yes
/home/user/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Done in 6.41s.
>
```

Oh noes!

Now, changing `electronVersion` in `package.json` to `12.0.2` which matches the electron version that was installed, and re-running `yarn run build:native` caused the modules to be built with the same electron/node version as what I was running Element-Desktop with. No more printout, and native modules work when I run `yarn start` again.

Ideally we would install the same electron version specified in `package.json`, rather than just `yarn add electron`, right? Or am I abusing the instructions in some way?

**Comment by jryans** [comment]
> Ideally we would install the same electron version specified in `package.json`, rather than just `yarn add electron`, right? Or am I abusing the instructions in some way?

Right, we have historically avoided actually recorded `electron` as a dependency, but perhaps that makes sense to do now the desktop is in a separate repo from web...?

**Comment by PF4Public** [comment]
Would it be possible to add a logic to detect electron version at build time?

**Comment by anoadragon453** [comment]
@jryans Who is this question directed to?

**Comment by t3chguy** [comment]
We now specify it as a dependency so running `yarn` should do the right thing and install the correct version.
