### ISSUE TITLE
Soft crash when trying to view a group

### ISSUE THREAD

**Issue by zaibon** [vector-im/element-web#16886]
### Description

App suddenly crash, I don't really have any special flow that lead to the crash though

### Steps to reproduce

It just crash after a couple of seconds I start the app.

Describe how what happens differs from what you expected.

Log: sent    

### Version information

- **Platform**: web (in-browser) 

For the web app:

- **Browser**: Chrome Version 89.0.4389.114 (Official Build) (64-bit)
- **OS**: Arch Linux
- **URL**: app.element.io

**Comment by jryans** [comment]
Are you by chance viewing a group / community page?

The logs shows the following:

```
2021-04-08T07:01:49.881Z E Invalid file provided: cannot determine MXC URI. Has it been redacted?
Error: Invalid file provided: cannot determine MXC URI. Has it been redacted?
    at https://app.element.io/bundles/6421c751c3aa2dc359ed/vendors~init.js:2:196400
    at s (https://app.element.io/bundles/6421c751c3aa2dc359ed/vendors~init.js:2:196484)
    at c (https://app.element.io/bundles/6421c751c3aa2dc359ed/vendors~init.js:2:196514)
    at Rl._getMembershipSection (https://app.element.io/bundles/6421c751c3aa2dc359ed/vendors~init.js:2:5049134)
    at Rl.render (https://app.element.io/bundles/6421c751c3aa2dc359ed/vendors~init.js:2:5057214)
    at ja (https://app.element.io/bundles/6421c751c3aa2dc359ed/vendors~init.js:2:2066005)
    at La (https://app.element.io/bundles/6421c751c3aa2dc359ed/vendors~init.js:2:2065800)
    at fs (https://app.element.io/bundles/6421c751c3aa2dc359ed/vendors~init.js:2:2101599)
    at lc (https://app.element.io/bundles/6421c751c3aa2dc359ed/vendors~init.js:2:2092846)
    at sc (https://app.element.io/bundles/6421c751c3aa2dc359ed/vendors~init.js:2:2092771)
```

...just after trying to show a group page.

**Comment by zaibon** [comment]
I narrowed down the issue. It seems the problem happened when I tried to access a room that is created by the mx-puppet-discord bridge. 
I since then remove this discord guild from my bridge, but I still have an invite to one of the room showing up. And when I try to click on the invite, I get the crash again.

**Comment by turt2live** [comment]
@zaibon are you still seeing this? If so, is there an avatar visible on the invite in the room list or is it blank? Also, would you be expecting an avatar there?

**Comment by zaibon** [comment]
I'm not seeing it anymore no.

**Comment by zaibon** [comment]
I just reproduce the same bug again. 
Joined a new guild using the mx-puppet-discord bridge. I have an invitation to a room and when I click on it, I get the crash.

Here is how it looks:
![2021-05-17_420x103_scrot](https://user-images.githubusercontent.com/303164/118504139-8eab4d80-b72b-11eb-9a0d-9875e92f0f48.png)

So the avatar is there. I can provide logs again if you need some, just let me know.

**Comment by SimonBrandner** [comment]
Spaces are now in beta
