### ISSUE TITLE
3pid invite failed somehow

### ISSUE THREAD

**Issue by dbkr** [vector-im/element-web#1711]
Invited using vector-web bulk invite.

```
2016-07-01 09:53:12,689 - synapse.handlers.federation - 1745 - INFO - POST-16763975 - Could not find invite event for third_party_invite - discarding: {'origin': 'matrix.org', 'or
igin_server_ts': 1467363192685, 'sender': '@Amandine:matrix.org', 'event_id': '$14673631922320300zyurE:matrix.org', 'prev_events': [(u'$14673610382317024cCxOn:matrix.org', {u'sha2
56': u'fkBOLfCFyk1dmn/J3dfI3ybKae+uYrAkAovXNarB9qE'})], 'state_key': u'@20710:matrix.org', 'content': {'third_party_invite': {'signed': {'token': 'jJPnpicMgRonXyohbksUIyNxmdSqOcdJ
rEpfEUITPoyPtPapLgFFiwJrFxqjzWEAUZnWEgDWzRLJTSXeQNIpdTAetEnGgdfxEraOYxuaVDeQmPTqyoFSmVVrkzCGFCZR', 'signatures': {'vector.im': {'ed25519:0': '3/OIYPN9e4cSqbWXzzD20oKHhF67Pww1wBTQs
mjRzpboOgwbP0lRgAvbV8vcCbCFzClmJlfuFAqcQarcWAmhBg'}}, 'mxid': '@20710:matrix.org', 'sender': '@Amandine:matrix.org'}}, 'membership': u'invite'}, 'depth': 30L, 'prev_state': [], 'r
oom_id': u'!LQhJBTLcfkzoyQyOxc:matrix.org', 'auth_events': [('$14673597602315426QKRrG:matrix.org', {u'sha256': u'ZSIBmnpCYzhJ6KRuR8Prwo32UdoYPMw0dmVYLiDKJ7w'}), ('$146736064423164
74GEiOG:matrix.org', {u'sha256': u'S3ZAawUi/HloS3lt2FhMKekZ2DuIqiJyS+wt1Za9wL0'}), ('$14673597602315427nEHqF:matrix.org', {u'sha256': u'LxZJQ3NLF65GMAKmwr7yVSCeT5VcBe84w4ULxsCJOA4
'}), ('$14673597602315428dqxUI:matrix.org', {u'sha256': u'NYsCSxX9FUqiFkk9liHvYjmUVISXIUsyGY18JiOOlMc'})], 'hashes': {'sha256': u'wDELvTRi1jrTaqmXi3oDcKU6wwZ64UWkgNmJ5O9qbro'}, 't
ype': 'm.room.member'}
2016-07-01 09:53:12,689 - synapse.http.server - 135 - ERROR - POST-16763975 - Failed handle request synapse.http.server._async_render on <synapse.rest.ClientRestResource object at
 0x5e29410>: <XForwardedForRequest at 0x7f9968f0dfc8 method=POST uri=/_matrix/client/r0/join/!LQhJBTLcfkzoyQyOxc:matrix.org?access_token=<redacted> clientproto=HTTP/1.1 site=8080>
Traceback (most recent call last):
  File "synapse/http/server.py", line 114, in wrapped_request_handler
    yield request_handler(self, request)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/http/server.py", line 260, in _async_render
    callback_return = yield callback(request, **kwargs)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/rest/client/v1/room.py", line 254, in on_POST
    third_party_signed=content.get("third_party_signed", None),
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/handlers/room_member.py", line 157, in update_membership
    ratelimit=ratelimit,
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/handlers/room_member.py", line 184, in _update_membership
    third_party_signed,
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "synapse/federation/federation_server.py", line 600, in exchange_third_party_invite
    signed,
  File "/mnt/disk/home/matrix/venv-synapse/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1128, in _inlineCallbacks
    result = g.send(result)
  File "synapse/handlers/federation.py", line 1688, in exchange_third_party_invite
    event_dict, event, context
TypeError: 'NoneType' object is not iterable
```

**Comment by thekyriarchy** [comment]
I had issues with bulk inviting using MXID, but no error whatsoever. just silent failure. is this connected to #1713

**Comment by kittykat** [comment]
I'm going to close this issue for now as we haven't had any recent reports about bulk 3pid invites failing and the mechanisms around that have changed since 2016
