### ISSUE TITLE
text in mobile client shown but not in desktop element

### ISSUE THREAD

**Issue by damnms** [vector-im/element-web#17281]
![image](https://user-images.githubusercontent.com/40913090/118103287-08fd6a00-b3da-11eb-86a2-56ed15a83d28.png)

this text is correctly shown in the mobile client

### Description

text that should be shown is not shown in the desktop element. when i use my mobile client it is shown.
### Steps to reproduce

- send this message to any matrix user: sprintf(curlget,"https://tiles.wo-cloud.com/composite/landingpage_web/%d/%02d/%02d/%02d/%02d/m3/0405.jpeg",systime.wYear,systime.wMonth,day,hour,min);
- the text is not shown in element desktop

Log: sent/not sent?  sent  

### Version information

- **Platform**: web (in-browser) or desktop? desktop

For the desktop app:

- **OS**: Windows, macOS, Ubuntu, Arch Linux, etc? Fedora 34
- **Version**: 1.x.y 
Version von Element: 1.7.27
Version von olm: 3.2.1

**Comment by t3chguy** [comment]
```
2021-05-13T09:00:38.893Z E URI malformed
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at S (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:297532)
    at E (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:297440)
    at formatHref (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:1115211)
    at i.get (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:2333519)
    at i.resolve (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:2333139)
    at l (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:2351134)
    at d (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:2351959)
    at u (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:2352353)
    at Object.Q (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:359085)
2021-05-13T09:00:38.893Z E URI malformed
URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at S (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:297532)
    at E (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:297440)
    at formatHref (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:1115211)
    at i.get (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:2333519)
    at i.resolve (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:2333139)
    at l (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:2351134)
    at d (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:2351959)
    at u (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:2352353)
    at Object.Q (vector://vector/webapp/bundles/19666200d0894fe308d2/vendors~init.js:2:359085)
```

**Comment by damnms** [comment]
so element desktop tries to do some uri validation even if this is a code snippet? 
imo this is a bug then, because a code snippt contain anything that does not fit any norm

**Comment by t3chguy** [comment]
Sure, its part of the pill finding code, its just missing a try-catch

**Comment by t3chguy** [comment]
and linkifying ftr, they both explode in the same manner; couple of try-catches later:

![image](https://user-images.githubusercontent.com/2403652/118105417-44953580-b3d4-11eb-80e0-10ce81f02aab.png)

**Comment by damnms** [comment]
awesome, thanks for that super fast support and fix :)
