### ISSUE TITLE
"Some of your messages have not been sent" message appears every time I open element

### ISSUE THREAD

**Issue by Zachinquarantine** [vector-im/element-web#17589]
### Description

Whenever element restarts or I open the client, the "Some of your message have not been sent" issue shows up. (as pictured below)
![slika](https://user-images.githubusercontent.com/69423184/121067569-35b65e80-c799-11eb-904c-e1327f315d5a.png)
When I hit "Delete", my latest  message gets cropped lengthwise:
![slika](https://user-images.githubusercontent.com/69423184/121067688-5bdbfe80-c799-11eb-8d31-6ea17ff8c53a.png)
When I hit "Retry", or go to another room and then back to that chat, it disappears, but the ! logo remains.
![slika](https://user-images.githubusercontent.com/69423184/121067787-7b732700-c799-11eb-95f2-8519568bc956.png)

### Steps to reproduce

- open element desktop
- look at the bottom of the chatroom you closed it in
- you will see that message there
Describe how what happens differs from what you expected.
There should be no "your messages didn't send" message because I never sent any messages in the first place.

Logs being sent: yes

### Version information

- **Platform**: desktop

For the desktop app:

- **OS**: Windows
- **Version**: 1.7.30

**Comment by Zachinquarantine** [comment]
sent logs

**Comment by turt2live** [comment]
```
2021-06-07T18:05:02.711Z E Cannot set read marker to a pending event ($redacted-0)
Error: Cannot set read marker to a pending event ($redacted-0)
    at F.setRoomReadMarkers (vector://vector/webapp/bundles/6f5c25b49711cab9c570/vendors~init.js:2:544428)
    at e.sendReadReceipt (vector://vector/webapp/bundles/6f5c25b49711cab9c570/vendors~init.js:2:1859667)
    at e.updateReadReceiptOnUserActivity (vector://vector/webapp/bundles/6f5c25b49711cab9c570/vendors~init.js:2:1866006)
  ```
    
  this is the theme

**Comment by novocaine** [comment]
Possible duplicate of https://github.com/vector-im/element-web/issues/17078

**Comment by Glandos** [comment]
I got the same after a messy call (no Element call), and the "Delete all" button generate this:
```
Uncaught TypeError: e is undefined
    decryptEventIfNeeded client.ts:7772
    getEvents TimelinePanel.tsx:1731
    reloadEvents TimelinePanel.tsx:1684
    Kd TimelinePanel.tsx:925
    emit events.js:158
    emit typed-event-emitter.ts:89
    t ReEmitter.ts:55
    emit events.js:158
    emit typed-event-emitter.ts:89
    updatePendingEvent room.ts:2829
    updatePendingEventStatus client.ts:4854
    cancelPendingEvent client.ts:4419
    removeFromQueue Resend.ts:64
    cancelUnsentEvents Resend.ts:42
    cancelUnsentEvents Resend.ts:41
    _ RoomStatusBar.tsx:145
    React 11
    unstable_runWithPriority scheduler.production.min.js:18
    React
```

How can I generate more useful logs?
