### ISSUE TITLE
Element no longer provides a helpful error when event is too large

### ISSUE THREAD

**Issue by aaronraimist** [vector-im/element-web#17663]
### Description

Previous versions provided an error message "Event too large" when you send an event over 65536 bytes. Here's version 1.0.0 for example:

<img width="886" src="https://user-images.githubusercontent.com/5855073/122160788-289f0c80-ce36-11eb-9a8f-a39b2a121fe2.png">

It wasn't a great error but at least gave you some information as to why the event failed to send. I'm not sure when it regressed but Element 1.7.30 just shows a generic event failed to send error. It would be nice if this gave you some more information as to why it failed to send and also remove/disable the resend button since that isn't going to help.

<img width="870" src="https://user-images.githubusercontent.com/5855073/122160729-0f965b80-ce36-11eb-9e18-a1e15af3b550.png">

https://matrix.to/#/!OGEhHVWSdvArJzumhm:matrix.org/$OWZOZClgbWcSDHCYRVygH7e70JyNSr5fqFCvJlpELvs?via=matrix.org&via=privacytools.io&via=tchncs.de

**Comment by aaronraimist** [comment]
Looks like regressed in https://github.com/matrix-org/matrix-react-sdk/pull/5897

**Comment by t3chguy** [comment]
It also doesn't tell you anything useful if the server rejected the message due to unknown room version

**Comment by anoadragon453** [comment]
Here's a [pre-prepared example](https://gist.githubusercontent.com/anoadragon453/a7f1029b8f526391cb71f0a02ec216bf/raw/a7ab486f620f4332e57c1d4a98e422441654e1ce/lots-of-words.txt) you can copy and paste into a message to reproduce with.

Note that sending a message will also fail if the event is over 49152 bytes in an encrypted room. Attempting to send a long message in an encrypted room results in the following in the JS console:

```
Error sending event Error: Message too long (104200 bytes). The maximum for an encrypted message is 49152 bytes.
    at checkPayloadLength (vector://vector/webapp/bundles/7eb9a34c4713eb085ec4/init.js:109058:17)
    at OlmDevice.encryptGroupMessage (vector://vector/webapp/bundles/7eb9a34c4713eb085ec4/init.js:109801:5)
    at MegolmEncryption.encryptMessage (vector://vector/webapp/bundles/7eb9a34c4713eb085ec4/init.js:111025:39)
    at async Crypto.encryptEvent (vector://vector/webapp/bundles/7eb9a34c4713eb085ec4/init.js:29509:30)
    at async Promise.all (index 0)
```

#### Edits being too large

This behaviour also subtlety emerges when editing a long message. If you have a message that's slightly below the character limit ([example](https://gist.github.com/anoadragon453/7d0d741f0d0ee560ecdaf17600ea98dd)), and then edit it. The extra metadata that goes into the edit event will go over the message limit. Thus you are able send a message, but not edit it. In this case, even a "your message is too long" error is confusing, because _even if I delete a couple characters in my edit, the message is for some reason too long when it wasn't a second ago??_

It would be nice to handle this in an elegant manner, though I have to defer to design on how to communicate "edited messages require more characters that a non-edited message" to users.
