### ISSUE TITLE
Messages no longer syncing properly

### ISSUE THREAD

**Issue by yousefamar** [vector-im/element-web#17981]
#### Description

Messages will sporadically not sync, until I close element-desktop entirely and restart it. At the beginning, messages are consistent (including with my other Android session) and then they diverge for Desktop, with approx 50% of messages not appearing, across any chat. Probably related to #17966 since I get that too, and sync being dodgy in general. The error that keeps repeating is this (sending rageshake too):

```
2021-07-13T08:52:44.317Z E Caught /sync error TypeError: Cannot read property 'roomId' of null
    at Object._evaluateEvent (vector://vector/webapp/bundles/5b667ec9b5ae6c11f354/vendors~init.js:2:798461)
    at Object.onEvent (vector://vector/webapp/bundles/5b667ec9b5ae6c11f354/vendors~init.js:2:797853)
    at z.s.emit (vector://vector/webapp/bundles/5b667ec9b5ae6c11f354/vendors~init.js:2:19261)
    at vector://vector/webapp/bundles/5b667ec9b5ae6c11f354/vendors~init.js:2:3531171
    at Array.forEach (<anonymous>)
    at p._processSyncResponse (vector://vector/webapp/bundles/5b667ec9b5ae6c11f354/vendors~init.js:2:3531021)
    at p._sync (vector://vector/webapp/bundles/5b667ec9b5ae6c11f354/vendors~init.js:2:3529101)
```

Any advice much appreciated!

#### Steps to reproduce

- Be me
- Use element

#### Version information

- **Platform**: Desktop

For the desktop app:

- **OS**: Ubuntu 20.04.2
- **Version**: 1.7.32

**Comment by ShadowJonathan** [comment]
Which homeserver do you use?

**Comment by yousefamar** [comment]
My own one at matrix.amar.io (https://federationtester.matrix.org/#amar.io), which is Synapse at v1.31.0

**Comment by yousefamar** [comment]
(the reason I don't think it's the homeserver though is because everything works just fine as usual for Element Android for me)
