### ISSUE TITLE
Downloading logs crashes swaywm

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18509]
### Steps to reproduce

1. feedback
2. submit logs
3. download logs

### What happened?

crash to login manager

### What did you expect?

download logs

### Operating system

arch

### Application version

Element Nightly version: 2021081201 Olm version: 3.2.3

### How did you install the app?

aur nightly-bin

**Comment by Palid** [comment]
@HarHarLinks pinging, as you may have not noticed the above comment. 😄

**Comment by HarHarLinks** [comment]
was just busy, here is some log obtained by running `sway -d > logfile 2>&1` minus lots of `sworkstyle` and similar lines. is there somewhere to submit log non-public?

This is now Element Nightly version: 2021090301 Olm version: 3.2.3 from aur/element-desktop-nightly-bin, sway 1:1.6.1-1, wlroots 0.14.1-1, a bunch of gnome apps installed and nemo 5.0.3-1 file manager, arch linux

```
[...]
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /opt/Element-Nightly/resources/app.asar/lib/language-helper.js
- /opt/Element-Nightly/resources/app.asar/lib/tray.js
- /opt/Element-Nightly/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AppLocalization.fetchTranslationJson (/opt/Element-Nightly/resources/app.asar/lib/language-helper.js:76:20)
    at /opt/Element-Nightly/resources/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element-Nightly/resources/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element-Nightly/resources/app.asar/lib/language-helper.js',
    '/opt/Element-Nightly/resources/app.asar/lib/tray.js',
    '/opt/Element-Nightly/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
Resetting the UI components after locale change
[...]
00:00:13.586 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 36 (WM_CLIENT_MACHINE) for window 8388631
00:00:13.586 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 427 (_GTK_THEME_VARIANT) for window 8388631
00:00:13.586 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 431 (_NET_WM_BYPASS_COMPOSITOR) for window 8388631
00:00:13.586 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 294 (XdndAware) for window 8388631
00:00:13.586 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 329 (_NET_WM_USER_TIME) for window 8388631
00:00:13.586 [DEBUG] [wlr] [types/wlr_surface.c:743] New wlr_surface 0x562fb27e1880 (res 0x562fb189da80)
00:00:13.586 [DEBUG] [wlr] [xwayland/xwm.c:1566] New xwayland surface: 0x562fb27e1880
00:00:14.451 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 329 (_NET_WM_USER_TIME) for window 8388609
00:00:14.452 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 274 (WM_STATE) for window 8388631
00:00:14.452 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 274 (WM_STATE) for window 8388631
00:00:15.162 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 329 (_NET_WM_USER_TIME) for window 8388609
00:00:16.394 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 329 (_NET_WM_USER_TIME) for window 8388609
00:00:17.498 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 329 (_NET_WM_USER_TIME) for window 8388609
00:00:17.506 [DEBUG] [sway/desktop/xwayland.c:761] New xwayland unmanaged surface
00:00:17.506 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 402 (CHROMIUM_TIMESTAMP) for window 8388615
00:00:17.506 [DEBUG] [wlr] [xwayland/selection/incoming.c:486] XCB_XFIXES_SELECTION_NOTIFY (selection=1, owner=8388632)
00:00:17.506 [DEBUG] [wlr] [xwayland/selection/incoming.c:451] XCB_SELECTION_NOTIFY (selection=1, property=276, target=277)
00:00:19.850 [DEBUG] [sway/desktop/xwayland.c:761] New xwayland unmanaged surface
00:00:19.913 [DEBUG] [sway/desktop/xwayland.c:683] New xwayland surface title='(null)' class='(null)'
00:00:19.973 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 349 (_NET_WM_ICON_NAME) for window 10485771
00:00:20.025 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 37 (WM_ICON_NAME) for window 10485771
00:00:20.026 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 36 (WM_CLIENT_MACHINE) for window 10485771
00:00:20.026 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 346 (WM_LOCALE_NAME) for window 10485771
00:00:20.026 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 345 (WM_CLIENT_LEADER) for window 10485771
00:00:20.026 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 362 (_NET_WM_USER_TIME_WINDOW) for window 10485771
00:00:20.026 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 354 (_NET_WM_SYNC_REQUEST_COUNTER) for window 10485771
00:00:20.034 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 466 (_NET_WM_OPAQUE_REGION) for window 10485771
00:00:20.034 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 294 (XdndAware) for window 10485771
00:00:20.040 [DEBUG] [sway/desktop/xwayland.c:761] New xwayland unmanaged surface
00:00:20.040 [DEBUG] [wlr] [xwayland/selection/incoming.c:486] XCB_XFIXES_SELECTION_NOTIFY (selection=1, owner=10486021)
00:00:20.043 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 427 (_GTK_THEME_VARIANT) for window 10485771
00:00:20.043 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 402 (CHROMIUM_TIMESTAMP) for window 8388615
00:00:20.087 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 274 (WM_STATE) for window 10485771
00:00:20.087 [DEBUG] [wlr] [xwayland/xwm.c:796] unhandled X11 property 274 (WM_STATE) for window 10485771
00:00:20.087 [DEBUG] [wlr] [types/wlr_surface.c:743] New wlr_surface 0x562fb26876e0 (res 0x562fb274edf0)
00:00:20.087 [DEBUG] [wlr] [xwayland/xwm.c:1566] New xwayland surface: 0x562fb26876e0
00:00:20.112 [DEBUG] [wlr] [xwayland/selection/incoming.c:451] XCB_SELECTION_NOTIFY (selection=1, property=276, target=277)
00:00:20.150 [DEBUG] [sway/ipc-server.c:332] Sending window::new event
00:00:20.150 [DEBUG] [sway/ipc-server.c:958] Added IPC reply of type 0x80000003 to client 98 queue: { "change": "new", "container": { "id": 15, "type": "con", "orientation": "none", "percent": 0.0, "urgent": false, "marks": [ ], "focused": false, "layout": "none", "border": "none", "current_border_width": 0, "rect": { "x": 0, "y": 25, "width": 0, "height": -25 }, "deco_rect": { "x": 960, "y": -390, "width": 960, "height": 25 }, "window_rect": { "x": 0, "y": 0, "width": 0, "height": 0 }, "geometry": { "x": 0, "y": 0, "width": 922, "height": 571 }, "name": null, "window": 10485771, "nodes": [ ], "floating_nodes": [ ], "focus": [ ], "fullscreen_mode": 0, "sticky": false, "pid": 77953, "app_id": null, "visible": false, "max_render_time": 0, "shell": "xwayland", "inhibit_idle": false, "idle_inhibitors": { "user": "none", "application": "none" }, "window_properties": { "class": "Element-desktop-nightly", "instance": "element-desktop-nightly", "transient_for": 8388609, "window_role": "GtkFileChooserDialog", "window_type": "dialog" } } }
00:00:20.151 [DEBUG] [sway/ipc-server.c:958] Added IPC reply of type 0x80000003 to client 110 queue: { "change": "new", "container": { "id": 15, "type": "con", "orientation": "none", "percent": 0.0, "urgent": false, "marks": [ ], "focused": false, "layout": "none", "border": "none", "current_border_width": 0, "rect": { "x": 0, "y": 25, "width": 0, "height": -25 }, "deco_rect": { "x": 960, "y": -390, "width": 960, "height": 25 }, "window_rect": { "x": 0, "y": 0, "width": 0, "height": 0 }, "geometry": { "x": 0, "y": 0, "width": 922, "height": 571 }, "name": null, "window": 10485771, "nodes": [ ], "floating_nodes": [ ], "focus": [ ], "fullscreen_mode": 0, "sticky": false, "pid": 77953, "app_id": null, "visible": false, "max_render_time": 0, "shell": "xwayland", "inhibit_idle": false, "idle_inhibitors": { "user": "none", "application": "none" }, "window_properties": { "class": "Element-desktop-nightly", "instance": "element-desktop-nightly", "transient_for": 8388609, "window_role": "GtkFileChooserDialog", "window_type": "dialog" } } }
00:00:20.151 [DEBUG] [sway/ipc-server.c:958] Added IPC reply of type 0x80000003 to client 122 queue: { "change": "new", "container": { "id": 15, "type": "con", "orientation": "none", "percent": 0.0, "urgent": false, "marks": [ ], "focused": false, "layout": "none", "border": "none", "current_border_width": 0, "rect": { "x": 0, "y": 25, "width": 0, "height": -25 }, "deco_rect": { "x": 960, "y": -390, "width": 960, "height": 25 }, "window_rect": { "x": 0, "y": 0, "width": 0, "height": 0 }, "geometry": { "x": 0, "y": 0, "width": 922, "height": 571 }, "name": null, "window": 10485771, "nodes": [ ], "floating_nodes": [ ], "focus": [ ], "fullscreen_mode": 0, "sticky": false, "pid": 77953, "app_id": null, "visible": false, "max_render_time": 0, "shell": "xwayland", "inhibit_idle": false, "idle_inhibitors": { "user": "none", "application": "none" }, "window_properties": { "class": "Element-desktop-nightly", "instance": "element-desktop-nightly", "transient_for": 8388609, "window_role": "GtkFileChooserDialog", "window_type": "dialog" } } }
00:00:20.151 [DEBUG] [sway/ipc-server.c:332] Sending window::floating event
00:00:20.151 [DEBUG] [sway/ipc-server.c:958] Added IPC reply of type 0x80000003 to client 98 queue: { "change": "floating", "container": { "id": 15, "type": "floating_con", "orientation": "none", "percent": 0.27467658730158734, "urgent": false, "marks": [ ], "focused": false, "layout": "none", "border": "none", "current_border_width": 0, "rect": { "x": 497, "y": 604, "width": 926, "height": 598 }, "deco_rect": { "x": 0, "y": 0, "width": 0, "height": 0 }, "window_rect": { "x": 2, "y": 0, "width": 922, "height": 571 }, "geometry": { "x": 0, "y": 0, "width": 922, "height": 571 }, "name": null, "window": 10485771, "nodes": [ ], "floating_nodes": [ ], "focus": [ ], "fullscreen_mode": 0, "sticky": false, "pid": 77953, "app_id": null, "visible": true, "max_render_time": 0, "shell": "xwayland", "inhibit_idle": false, "idle_inhibitors": { "user": "none", "application": "none" }, "window_properties": { "class": "Element-desktop-nightly", "instance": "element-desktop-nightly", "transient_for": 8388609, "window_role": "GtkFileChooserDialog", "window_type": "dialog" } } }
00:00:20.151 [DEBUG] [sway/ipc-server.c:958] Added IPC reply of type 0x80000003 to client 110 queue: { "change": "floating", "container": { "id": 15, "type": "floating_con", "orientation": "none", "percent": 0.27467658730158734, "urgent": false, "marks": [ ], "focused": false, "layout": "none", "border": "none", "current_border_width": 0, "rect": { "x": 497, "y": 604, "width": 926, "height": 598 }, "deco_rect": { "x": 0, "y": 0, "width": 0, "height": 0 }, "window_rect": { "x": 2, "y": 0, "width": 922, "height": 571 }, "geometry": { "x": 0, "y": 0, "width": 922, "height": 571 }, "name": null, "window": 10485771, "nodes": [ ], "floating_nodes": [ ], "focus": [ ], "fullscreen_mode": 0, "sticky": false, "pid": 77953, "app_id": null, "visible": true, "max_render_time": 0, "shell": "xwayland", "inhibit_idle": false, "idle_inhibitors": { "user": "none", "application": "none" }, "window_properties": { "class": "Element-desktop-nightly", "instance": "element-desktop-nightly", "transient_for": 8388609, "window_role": "GtkFileChooserDialog", "window_type": "dialog" } } }
00:00:20.151 [DEBUG] [sway/ipc-server.c:958] Added IPC reply of type 0x80000003 to client 122 queue: { "change": "floating", "container": { "id": 15, "type": "floating_con", "orientation": "none", "percent": 0.27467658730158734, "urgent": false, "marks": [ ], "focused": false, "layout": "none", "border": "none", "current_border_width": 0, "rect": { "x": 497, "y": 604, "width": 926, "height": 598 }, "deco_rect": { "x": 0, "y": 0, "width": 0, "height": 0 }, "window_rect": { "x": 2, "y": 0, "width": 922, "height": 571 }, "geometry": { "x": 0, "y": 0, "width": 922, "height": 571 }, "name": null, "window": 10485771, "nodes": [ ], "floating_nodes": [ ], "focus": [ ], "fullscreen_mode": 0, "sticky": false, "pid": 77953, "app_id": null, "visible": true, "max_render_time": 0, "shell": "xwayland", "inhibit_idle": false, "idle_inhibitors": { "user": "none", "application": "none" }, "window_properties": { "class": "Element-desktop-nightly", "instance": "element-desktop-nightly", "transient_for": 8388609, "window_role": "GtkFileChooserDialog", "window_type": "dialog" } } }
00:00:20.158 [DEBUG] [sway/ipc-server.c:332] Sending window::title event
00:00:20.162 [DEBUG] [sway/ipc-server.c:958] Added IPC reply of type 0x80000003 to client 98 queue: { "change": "title", "container": { "id": 15, "type": "floating_con", "orientation": "none", "percent": 0.27467658730158734, "urgent": false, "marks": [ ], "focused": false, "layout": "none", "border": "none", "current_border_width": 0, "rect": { "x": 497, "y": 604, "width": 926, "height": 598 }, "deco_rect": { "x": 0, "y": 0, "width": 0, "height": 0 }, "window_rect": { "x": 2, "y": 0, "width": 922, "height": 571 }, "geometry": { "x": 0, "y": 0, "width": 922, "height": 571 }, "name": "data:application\/octet-stream;base64,[some base64]", "window": 10485771, "nodes": [ ], "floating_nodes": [ ], "focus": [ ], "fullscreen_mode": 0, "sticky": false, "pid": 77953, "app_id": null, "visible": true, "max_render_time": 0, "shell": "xwayland", "inhibit_idle": false, "idle_inhibitors": { "user": "none", "application": "none" }, "window_properties": { "class": "Element-desktop-nightly", "instance": "element-desktop-nightly", "title": "data:application\/octet-stream;base64,[some base64]", "transient_for": 8388609, "window_role": "GtkFileChooserDialog", "window_type": "dialog" } } }
00:00:20.162 [DEBUG] [sway/ipc-server.c:958] Added IPC reply of type 0x80000003 to client 110 queue: { "change": "title", "container": { "id": 15, "type": "floating_con", "orientation": "none", "percent": 0.27467658730158734, "urgent": false, "marks": [ ], "focused": false, "layout": "none", "border": "none", "current_border_width": 0, "rect": { "x": 497, "y": 604, "width": 926, "height": 598 }, "deco_rect": { "x": 0, "y": 0, "width": 0, "height": 0 }, "window_rect": { "x": 2, "y": 0, "width": 922, "height": 571 }, "geometry": { "x": 0, "y": 0, "width": 922, "height": 571 }, "name": "data:application\/octet-stream;base64,[some base64]", "window": 10485771, "nodes": [ ], "floating_nodes": [ ], "focus": [ ], "fullscreen_mode": 0, "sticky": false, "pid": 77953, "app_id": null, "visible": true, "max_render_time": 0, "shell": "xwayland", "inhibit_idle": false, "idle_inhibitors": { "user": "none", "application": "none" }, "window_properties": { "class": "Element-desktop-nightly", "instance": "element-desktop-nightly", "title": "data:application\/octet-stream;base64,[some base64]", "transient_for": 8388609, "window_role": "GtkFileChooserDialog", "window_type": "dialog" } } }
00:00:20.162 [DEBUG] [sway/ipc-server.c:958] Added IPC reply of type 0x80000003 to client 122 queue: { "change": "title", "container": { "id": 15, "type": "floating_con", "orientation": "none", "percent": 0.27467658730158734, "urgent": false, "marks": [ ], "focused": false, "layout": "none", "border": "none", "current_border_width": 0, "rect": { "x": 497, "y": 604, "width": 926, "height": 598 }, "deco_rect": { "x": 0, "y": 0, "width": 0, "height": 0 }, "window_rect": { "x": 2, "y": 0, "width": 922, "height": 571 }, "geometry": { "x": 0, "y": 0, "width": 922, "height": 571 }, "name": "data:application\/octet-stream;base64,[some base64]", "window": 10485771, "nodes": [ ], "floating_nodes": [ ], "focus": [ ], "fullscreen_mode": 0, "sticky": false, "pid": 77953, "app_id": null, "visible": true, "max_render_time": 0, "shell": "xwayland", "inhibit_idle": false, "idle_inhibitors": { "user": "none", "application": "none" }, "window_properties": { "class": "Element-desktop-nightly", "instance": "element-desktop-nightly", "title": "data:application\/octet-stream;base64,[some base64]", "transient_for": 8388609, "window_role": "GtkFileChooserDialog", "window_type": "dialog" } } }
00:00:20.166 [DEBUG] [sway/tree/view.c:495] Checking criteria [class="^Element"]
00:00:20.166 [DEBUG] [sway/tree/view.c:500] for_window '[class="^Element"]' matches view 0x562fb27c5990, cmd: 'layout tabbed'
00:00:20.166 [INFO] [sway/commands.c:257] Handling command 'layout tabbed'
00:00:20.166 [DEBUG] [sway/ipc-server.c:332] Sending window::focus event
00:00:20.166 [DEBUG] [sway/ipc-server.c:958] Added IPC reply of type 0x80000003 to client 98 queue: { "change": "focus", "container": { "id": 15, "type": "floating_con", "orientation": "none", "percent": 0.27467658730158734, "urgent": false, "marks": [ ], "focused": true, "layout": "none", "border": "none", "current_border_width": 0, "rect": { "x": 497, "y": 604, "width": 926, "height": 598 }, "deco_rect": { "x": 0, "y": 0, "width": 0, "height": 0 }, "window_rect": { "x": 2, "y": 0, "width": 922, "height": 571 }, "geometry": { "x": 0, "y": 0, "width": 922, "height": 571 }, "name": "data:application\/octet-stream;base64,[some base64]", "window": 10485771, "nodes": [ ], "floating_nodes": [ ], "focus": [ ], "fullscreen_mode": 0, "sticky": false, "pid": 77953, "app_id": null, "visible": true, "max_render_time": 0, "shell": "xwayland", "inhibit_idle": false, "idle_inhibitors": { "user": "none", "application": "none" }, "window_properties": { "class": "Element-desktop-nightly", "instance": "element-desktop-nightly", "title": "data:application\/octet-stream;base64,[some base64]", "transient_for": 8388609, "window_role": "GtkFileChooserDialog", "window_type": "dialog" } } }
00:00:20.166 [DEBUG] [sway/ipc-server.c:958] Added IPC reply of type 0x80000003 to client 110 queue: { "change": "focus", "container": { "id": 15, "type": "floating_con", "orientation": "none", "percent": 0.27467658730158734, "urgent": false, "marks": [ ], "focused": true, "layout": "none", "border": "none", "current_border_width": 0, "rect": { "x": 497, "y": 604, "width": 926, "height": 598 }, "deco_rect": { "x": 0, "y": 0, "width": 0, "height": 0 }, "window_rect": { "x": 2, "y": 0, "width": 922, "height": 571 }, "geometry": { "x": 0, "y": 0, "width": 922, "height": 571 }, "name": "data:application\/octet-stream;base64,[some base64]", "window": 10485771, "nodes": [ ], "floating_nodes": [ ], "focus": [ ], "fullscreen_mode": 0, "sticky": false, "pid": 77953, "app_id": null, "visible": true, "max_render_time": 0, "shell": "xwayland", "inhibit_idle": false, "idle_inhibitors": { "user": "none", "application": "none" }, "window_properties": { "class": "Element-desktop-nightly", "instance": "element-desktop-nightly", "title": "data:application\/octet-stream;base64,[some base64]", "transient_for": 8388609, "window_role": "GtkFileChooserDialog", "window_type": "dialog" } } }
00:00:20.166 [DEBUG] [sway/ipc-server.c:958] Added IPC reply of type 0x80000003 to client 122 queue: { "change": "focus", "container": { "id": 15, "type": "floating_con", "orientation": "none", "percent": 0.27467658730158734, "urgent": false, "marks": [ ], "focused": true, "layout": "none", "border": "none", "current_border_width": 0, "rect": { "x": 497, "y": 604, "width": 926, "height": 598 }, "deco_rect": { "x": 0, "y": 0, "width": 0, "height": 0 }, "window_rect": { "x": 2, "y": 0, "width": 922, "height": 571 }, "geometry": { "x": 0, "y": 0, "width": 922, "height": 571 }, "name": "data:application\/octet-stream;base64,[some base64]", "window": 10485771, "nodes": [ ], "floating_nodes": [ ], "focus": [ ], "fullscreen_mode": 0, "sticky": false, "pid": 77953, "app_id": null, "visible": true, "max_render_time": 0, "shell": "xwayland", "inhibit_idle": false, "idle_inhibitors": { "user": "none", "application": "none" }, "window_properties": { "class": "Element-desktop-nightly", "instance": "element-desktop-nightly", "title": "data:application\/octet-stream;base64,[some base64]", "transient_for": 8388609, "window_role": "GtkFileChooserDialog", "window_type": "dialog" } } }
00:00:20.166 [DEBUG] [sway/tree/arrange.c:263] Usable area for ws: 1920x1050@0,30
00:00:20.166 [DEBUG] [sway/tree/arrange.c:293] Arranging workspace '4' at 0.000000, 390.000000
00:00:20.166 [DEBUG] [sway/tree/arrange.c:77] Arranging 0x7ffe864894b0 horizontally
00:00:20.166 [DEBUG] [sway/desktop/transaction.c:398] Transaction 0x562fb28626e0 committing with 5 instructions
00:00:20.166 [DEBUG] [sway/desktop/transaction.c:494] Transaction 0x562fb28626e0 is ready
00:00:20.166 [DEBUG] [sway/desktop/transaction.c:294] Applying transaction 0x562fb28626e0
00:00:20.166 [DEBUG] [sway/tree/container.c:1255] Container 0x562fb26707f0 entered output 0x562fb24cf470
sway: render/wlr_texture.c:29: wlr_texture_from_pixels: Assertion `data' failed.
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
Gdk-Message: 13:04:31.890: Error reading events from display: Broken pipe
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
Gdk-Message: 13:04:31.890: Error reading events from display: Broken pipe
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
[2021-09-03 13:04:31.890] [error] Window: Unable to receive IPC header
Gdk-Message: 13:04:31.890: Error reading events from display: Broken pipe
Gdk-Message: 13:04:31.890: Error reading events from display: Broken pipe
Gdk-Message: 13:04:31.890: Error reading events from display: Broken pipe
(EE) failed to read Wayland events: Connection reset by peer
Gdk-Message: 13:04:31.891: Error reading events from display: Broken pipe
mono: Fatal IO error 11 (Resource temporarily unavailable) on X server :0.
```

That `[some base64]` is a partial log archive:

```
2021-09-03T11:04:16.301Z I Initialised rageshake.
2021-09-03T11:04:16.302Z I To fix line numbers in Chrome: Meatball menu � Settings � Ignore list � Add /rageshake\.js$
2021-09-03T11:04:16.303Z I Using Electron platform
2021-09-03T11:04:16.305Z I Configuring rageshake persistence...
2021-09-03T11:04:16.308Z I returning explicit theme: dark
2021-09-03T11:04:16.309Z I returning explicit theme: dark
2021-09-03T11:04:16.313Z I Loading skin...
2021-09-03T11:04:16.315Z I Using WebAssembly Olm
2021-09-03T11:04:16.655Z I Skin loaded!
2021-09-03T11:04:16.662Z I set language to en-us
2021-09-03T11:04:16.674Z I Application is running in production mode
2021-09-03T11:04:16.675Z I Vector starting at vector://vector/webapp/
2021-09-03T11:04:16.675Z I Verifying homeserver configuration
2021-09-03T11:04:16.675Z I Config uses a default_server_name - doing .well-known lookup
2021-09-03T11:04:16.675Z W DEPRECATED CONFIG OPTION: In the future, default_server_name will not be accepted. Please use default_server_config instead.
2021-09-03T11:04:16.960Z I Using homeserver config: {"hsUrl":"https://matrix-client.matrix.org","hsName":"matrix.org","hsNameIsDifferent":true,"isUrl":"https://vector.im","isDefault":true,"isNameResolvable":true,"warning":null}
2021-09-03T11:04:16.960Z I Updating SdkConfig with validated discovery information
2021-09-03T11:04:16.963Z I returning explicit theme: dark
2021-09-03T11:04:16.980Z I No pickle key available
2021-09-03T11:04:17.004Z I Restoring session for @hhl:matrix.server
2021-09-03T11:04:17.004Z I setLoggedIn: mxid: @hhl:matrix.server deviceId: SOMEID guest: false hs: https://matrix.server:8448/ softLogout: false  freshLogin: false
2021-09-03T11:04:17.006Z I StorageManager: Checking storage consistency
2021-09-03T11:04:17.006Z I StorageManager: Local storage supported? true
2021-09-03T11:04:17.006Z I StorageManager: IndexedDB supported? true
2021-09-03T11:04:17.006Z I StorageManager: Local storage contains data
```

Looks to me like it isn't able to either generate the rageshake in this case (it works when "submitting" instead of "downloading"), or communicate the finished rageshake archive to sway/GtkFileChooserDialog.

**Comment by novocaine** [comment]
It looks like something bad happens within sway at `sway: render/wlr_texture.c:29: wlr_texture_from_pixels: Assertion `data' failed.`

If the sway process is terminating, you can generate a core dump from and submit it to the swaywm project for them to inspect. Unfortunately, I don't think element web maintainers are going to be able to help - the element process can't crash your wm unless there's bugs in the wm..

**Comment by HarHarLinks** [comment]
Thanks, makes sense, I'll follow up with them.

What's with the i18n error at the start of the log?

**Comment by HarHarLinks** [comment]
I am noticing that stable element seems to run in native wayland (`element-desktop --enable-features=UseOzonePlatform --ozone-platform=wayland`) whereas nightly does run, but will show no window, only the indicator icon (`element-desktop-nightly --enable-features=UseOzonePlatform --ozone-platform=wayland`).

**Comment by novocaine** [comment]
> Thanks, makes sense, I'll follow up with them.
> 
> What's with the i18n error at the start of the log?

discussed here https://github.com/vector-im/element-web/issues/18189#issuecomment-885251137

note that while failing to fetch translations seems like a problem and might cause JS errors, it can't crash the process or your wm or cause assertions to fail
