### ISSUE TITLE
Can't send file attachment from ~/.../

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#18510]
### Steps to reproduce

Try to upload `~/.../somefile`

### What happened?

The file 'somefile' failed to upload.

I'd submit logs, but #18509

### What did you expect?

upload

### Operating system

arch

### Application version

Element Nightly version: 2021081201 Olm version: 3.2.3

### How did you install the app?

aur nightly-bin

**Comment by SimonBrandner** [comment]
Yeah, I can repro. It seems to not like the file extensions/no file extension.

**Comment by HarHarLinks** [comment]
it does not depend on the filename itself for me, but `~/.../` as parent or nested (grand)*parent directory

**Comment by HarHarLinks** [comment]
When launching element from a shell? I don't think there are any relevant ones:

```
(element-desktop-nightly:16014): Gtk-WARNING **: 13:51:35.849: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
Starting auto update with base URL: https://packages.element.io/nightly/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /opt/Element-Nightly/resources/app.asar/lib/language-helper.js
- /opt/Element-Nightly/resources/app.asar/lib/tray.js
- /opt/Element-Nightly/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AppLocalization.fetchTranslationJson (/opt/Element-Nightly/resources/app.asar/lib/language-helper.js:76:20)
    at /opt/Element-Nightly/resources/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element-Nightly/resources/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element-Nightly/resources/app.asar/lib/language-helper.js',
    '/opt/Element-Nightly/resources/app.asar/lib/tray.js',
    '/opt/Element-Nightly/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
Resetting the UI components after locale change
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /opt/Element-Nightly/resources/app.asar/lib/language-helper.js
- /opt/Element-Nightly/resources/app.asar/lib/tray.js
- /opt/Element-Nightly/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AppLocalization.fetchTranslationJson (/opt/Element-Nightly/resources/app.asar/lib/language-helper.js:76:20)
    at /opt/Element-Nightly/resources/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element-Nightly/resources/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element-Nightly/resources/app.asar/lib/language-helper.js',
    '/opt/Element-Nightly/resources/app.asar/lib/tray.js',
    '/opt/Element-Nightly/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
```

**Comment by HarHarLinks** [comment]
> it does not depend on the filename itself for me, but `~/.../` as parent or nested (grand)*parent directory

other dot dirs (e.g. `.config`) work

**Comment by SimonBrandner** [comment]
> When launching element from a shell?

No, I meant the in-app console, sorry - `Ctrl+Shift+I`. Do you see any there?

**Comment by HarHarLinks** [comment]
I don't think so, this is what happens:

```
rageshake.js?432e:65 [Media Config] Fetching
rageshake.js?432e:65 Starting load of AsyncWrapper for modal
rageshake.js?432e:65 [Media Config] Fetched config: {m.upload.size: 52428800}m.upload.size: 52428800__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
rageshake.js?432e:65 Starting load of AsyncWrapper for modal
rageshake.js?432e:65 Starting load of AsyncWrapper for modal
```

**Comment by novocaine** [comment]
Moving to O-low as I think this likely affects Linux users only; if we can repro on other platforms, happy to elevate
