### ISSUE TITLE
Error: Cannot find module './i18n/strings/en-us.json', app cannot start

### ISSUE THREAD

**Issue by haasn** [vector-im/element-web#19153]
### Steps to reproduce

1. Execute `element`

### What did you expect?

* Element shows up as usual.

### What happened?

```
λ element
/home/nand/.config/Element exists: yes
/home/nand/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /usr/share/io.element.element/resources/app.asar/lib/language-helper.js
- /usr/share/io.element.element/resources/app.asar/lib/tray.js
- /usr/share/io.element.element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Function.n._resolveFilename (electron/js2c/browser_init.js:257:1128)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at AppLocalization.fetchTranslationJson (/usr/share/io.element.element/resources/app.asar/lib/language-helper.js:76:20)
    at /usr/share/io.element.element/resources/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/usr/share/io.element.element/resources/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/share/io.element.element/resources/app.asar/lib/language-helper.js',
    '/usr/share/io.element.element/resources/app.asar/lib/tray.js',
    '/usr/share/io.element.element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
Resetting the UI components after locale change
```

No further progress is reported, the app gets stuck in this state - no window is ever shown.

### Additional notes

I also tried the 1.8.4 element package from the tumbleweed system repos, with the exact same result. The last known working version was 1.8.2.

### Operating system

openSuSE Tumbleweed

### Application version

1.8.5-1.suse.tw.taw

### How did you install the app?

https://github.com/taw00/element-rpm

### Homeserver

matrix.org

### Have you submitted a rageshake?

No

**Comment by novocaine** [comment]
I think the errors in the log might be a red-herring as I've seen that error reported in other issues from Linux users e.g. here where the app must have launched in order for the user to reach the point they did https://github.com/vector-im/element-web/issues/18510

**Comment by novocaine** [comment]
Possibly related to https://github.com/vector-im/element-web/issues/19169

**Comment by haasn** [comment]
> Possibly related to #19169

Good chance of that. If I start element a second time (while the first instance is already "stuck"), I also get a white window, so that might be what the Ubuntu users are reporting.

**Comment by novocaine** [comment]
Note that https://github.com/vector-im/element-web/issues/19169 is an issue with glibc in Ubuntu (https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468) - possibly SuSE is also affected, but hard to tell unless you can capture a core dump as the reporter of that issue did

**Comment by haasn** [comment]
I don't get a core dump, as the process, in my case, does not crash. (I think I was misled by the second comment in that issue, which sounds more like my issue and less like the OP's)

I'd love to provide more info using gdb, but I can't find a package for element's debug symbols in either the official repos or the repo I got element from.

**Comment by novocaine** [comment]
If there's no crash, gdb won't help :/

Nightly builds have been updated to Electron 13.5 - updating to that is definitely worth a try, but I don't think https://github.com/taw00/element-rpm builds nightlies so you would either have to build `develop` yourself or wait for the next release.

Not sure if related, but one of the comments in the glibc thread says a blank window is a symptom  https://bugs.launchpad.net/ubuntu/+source/glibc/+bug/1944468/comments/27

**Comment by sci-42ver** [comment]
If someone still has this problem, it seems to be because they need the proxy (e.g. they can't access the matrix homeserver). Then they may still use en-us instead of using en.

By [`element-desktop --enable-logging`](https://www.adamsdesk.com/posts/element-desktop-error-cannot-find-module/) we can find where we are stuck. Then if we are stuck at something like `FetchHttpApi`, then we can use [`element-desktop --proxy-server=socks5://127.0.0.1:port`](https://github.com/element-hq/element-desktop/issues/772#issuecomment-1513258947) to solve the problem.
