### ISSUE TITLE
Power level changes get lost/reset on first attempt

### ISSUE THREAD

**Issue by rda0** [vector-im/element-web#19285]
### Description

I am not sure if this is a Synapse or Element bug. I can see the PUT requests on `/_matrix/client/r0/rooms/<roomid>/state/m.room.power_levels/` in my homeserver's synapse logs with status 200.

I will list the steps to reproduce this most of the time.

I can reproduce this with https://app.element.io/ on `matrix.org`.

### Steps to reproduce

1) create 2 private unencrypted rooms
2) click on the room (or space) in room list (or space panel)
3) in settings change `m.room.topic` from `50` to `100` -> resets to `50`
4) change (3) again -> sets it to `100`
5) change any other power level in the same room without problems
6) repeat (2) - (5) for the other room -> resets once on step (3)

On step (3) I can always see something happening with keys in Synapse logs and Element console.

Here is a video that shows what I mean:

https://user-images.githubusercontent.com/6731714/136517468-bf398a95-854d-4996-a9cc-b3fdfc927ebe.mp4

As you can see in the video, I would like to change a setting from `Admin` to `Moderator` power level.
The first time it is immediately reset to `Admin`. The second time the setting stays on `Moderator`.

#### What did you expect?

Settings (power levels) should not revert back to the previous state after some time.

#### What happened instead?

The first time trying to change a setting immediately reverts back to the previous state.
The second time it does not.

#### Synapse logs

```
2021-10-05 13:01:17,623 - synapse.access.http.8008 - 410 - INFO - POST-26836246 - 198.51.100.123 - 8008 - {@rda:example.com} Processed request: 0.003sec/-0.000sec (0.002sec, 0.000sec) (0.000sec/0.000sec/0) 2B 200 "POST /_matrix/client/r0/rooms/!obdDZhOzmxmliogITi%3Aexample.com/read_markers HTTP/1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.9.0 Chrome/91.0.4472.164 Electron/13.4.0 Safari/537.36" [0 dbevts]
2021-10-05 13:01:17,633 - synapse.access.http.8008 - 410 - INFO - PUT-26836247 - 198.51.100.123 - 8008 - {@rda:example.com} Processed request: 0.008sec/-0.000sec (0.003sec, 0.000sec) (0.001sec/0.003sec/3) 2B 200 "PUT /_matrix/client/r0/user/%40rda%3Aexample.com/account_data/im.vector.setting.breadcrumbs HTTP/1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.9.0 Chrome/91.0.4472.164 Electron/13.4.0 Safari/537.36" [0 dbevts]
2021-10-05 13:01:19,869 - synapse.access.http.8008 - 410 - INFO - GET-26836689 - 198.51.100.123 - 8008 - {@rda:example.com} Processed request: 0.003sec/-0.000sec (0.001sec, 0.000sec) (0.000sec/0.001sec/1) 14B 200 "GET /_matrix/client/unstable/org.matrix.msc2432/rooms/!obdDZhOzmxmliogITi%3Aexample.com/aliases HTTP/1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.9.0 Chrome/91.0.4472.164 Electron/13.4.0 Safari/537.36" [0 dbevts]
2021-10-05 13:01:22,829 - synapse.access.http.9093 - 410 - INFO - POST-26836729 - 127.0.0.1 - 9093 - {@rda:example.com} Processed request: 0.037sec/-0.000sec (0.004sec, 0.000sec) (0.000sec/0.000sec/0) 79B 200 "POST /_synapse/replication/send_event/%24-3Cb89K-LBwLc2lTkMqlWGC04SD1Nq34SvqVKmmwkQI/ZtQHvByngH HTTP/1.1" "Synapse/1.43.0" [0 dbevts]
2021-10-05 13:01:23,021 - synapse.access.http.8008 - 410 - INFO - POST-26836734 - 198.51.100.123 - 8008 - {@rda:example.com} Processed request: 0.011sec/-0.000sec (0.004sec, 0.000sec) (0.001sec/0.003sec/4) 2B 200 "POST /_matrix/client/r0/rooms/!obdDZhOzmxmliogITi%3Aexample.com/read_markers HTTP/1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.9.0 Chrome/91.0.4472.164 Electron/13.4.0 Safari/537.36" [0 dbevts]
2021-10-05 13:01:23,093 - synapse.access.http.8008 - 410 - INFO - GET-26836739 - 198.51.100.123 - 8008 - {@rda:example.com} Processed request: 0.014sec/-0.000sec (0.002sec, 0.000sec) (0.001sec/0.012sec/2) 898B 200 "GET /_matrix/client/unstable/room_keys/version HTTP/1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.9.0 Chrome/91.0.4472.164 Electron/13.4.0 Safari/537.36" [0 dbevts]
2021-10-05 13:01:22,983 - synapse.access.http.8231 - 410 - INFO - POST-401375 - 127.0.0.1 - 8231 - {@rda:example.com} Processed request: 0.010sec/-0.000sec (0.003sec, 0.000sec) (0.001sec/0.003sec/3) 12431B 200 "POST /_matrix/client/r0/keys/query HTTP/1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.9.0 Chrome/91.0.4472.164 Electron/13.4.0 Safari/537.36" [0 dbevts]
2021-10-05 13:01:22,832 - synapse.access.http.8241 - 410 - INFO - PUT-91581 - 127.0.0.1 - 8241 - {@rda:example.com} Processed request: 0.081sec/-0.000sec (0.010sec, 0.003sec) (0.005sec/0.013sec/8) 59B 200 "PUT /_matrix/client/r0/rooms/!obdDZhOzmxmliogITi%3Aexample.com/state/m.room.power_levels/ HTTP/1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.9.0 Chrome/91.0.4472.164 Electron/13.4.0 Safari/537.36" [3 dbevts]
2021-10-05 13:01:32,981 - synapse.access.http.8008 - 410 - INFO - GET-26838165 - 198.51.100.123 - 8008 - {@rda:example.com} Processed request: 0.003sec/-0.000sec (0.003sec, 0.000sec) (0.000sec/0.001sec/1) 14B 200 "GET /_matrix/client/unstable/org.matrix.msc2432/rooms/!obdDZhOzmxmliogITi%3Aexample.com/aliases HTTP/1.0" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Element/1.9.0 Chrome/91.0.4472.164 Electron/13.4.0 Safari/537.36" [0 dbevts]
```

#### Element console log

```
Saving device tracking data xxxxxxxxx rageshake.js:52:4
Backup public key xxxxxxxxx is trusted locally rageshake.js:52:4
Backup version 1 still current rageshake.js:52:4
Looking at $9Y4n8VWPrT4MB-yLUXFt7RmrKfEuB9vXiMc4Soidyao rageshake.js:52:4
Switching to room id !vNmPakErObYnNImhTY:matrix.org at event undefined rageshake.js:52:4
RVS update: !vNmPakErObYnNImhTY:matrix.org undefined loading? false joining? false initial? true shouldPeek? true rageshake.js:52:4
Returning cached capabilities rageshake.js:52:4
newscreen room/!vNmPakErObYnNImhTY:matrix.org rageshake.js:52:4
[!vNmPakErObYnNImhTY:matrix.org] Current version: 6 rageshake.js:52:4
[!vNmPakErObYnNImhTY:matrix.org] Version capability:
Object { default: "6", available: {…}, "org.matrix.msc3244.room_capabilities": {…} }
rageshake.js:52:4
Persisting sync data up to xxxxxxxxx .worker.js:1:62323
Starting load of AsyncWrapper for modal rageshake.js:52:4
Marking device list outdated for @rda0:matrix.org rageshake.js:52:4
Starting key download for
Array [ "@rda0:matrix.org" ]
rageshake.js:52:4
got device keys for @rda0:matrix.org:
Object { NURLQEOSIR: {…}, ZWMLNDOSHM: {…} }
rageshake.js:52:4
got cross-signing keys for @rda0:matrix.org:
Object { master: {…}, self_signing: {…}, user_signing: {…} }
rageshake.js:52:4
downloadKeys: already have a download in progress for @rda0:matrix.org: awaiting its result rageshake.js:52:4
Completed key download for @rda0:matrix.org rageshake.js:52:4
Device list for @rda0:matrix.org now up to date rageshake.js:52:4
Old unverified sessions: rageshake.js:52:4
New unverified sessions: rageshake.js:52:4
Checking key backup status... rageshake.js:52:4
Old unverified sessions: rageshake.js:52:4
New unverified sessions: rageshake.js:52:4
Backup public key xxxxxxxxx is trusted locally rageshake.js:52:4
Backup version 1 still current rageshake.js:52:4
Saving device tracking data xxxxxxxxx 09355 rageshake.js:52:4
Looking at $S9xkhx4uahCIzMsS3CNgCYgnCo2T-kFl6LwR5ZzzAkc rageshake.js:52:4
Switching to room id !DVvZZfOguSoqmouiHk:matrix.org at event undefined rageshake.js:52:4
RVS update: !DVvZZfOguSoqmouiHk:matrix.org undefined loading? false joining? false initial? true shouldPeek? true rageshake.js:52:4
Returning cached capabilities rageshake.js:52:4
newscreen room/!DVvZZfOguSoqmouiHk:matrix.org rageshake.js:52:4
[!DVvZZfOguSoqmouiHk:matrix.org] Current version: 6 rageshake.js:52:4
[!DVvZZfOguSoqmouiHk:matrix.org] Version capability:
Object { default: "6", available: {…}, "org.matrix.msc3244.room_capabilities": {…} }
rageshake.js:52:4
Starting load of AsyncWrapper for modal rageshake.js:52:4
Marking device list outdated for @rda0:matrix.org rageshake.js:52:4
Starting key download for
Array [ "@rda0:matrix.org" ]
rageshake.js:52:4
got device keys for @rda0:matrix.org:
Object { NURLQEOSIR: {…}, ZWMLNDOSHM: {…} }
rageshake.js:52:4
got cross-signing keys for @rda0:matrix.org:
Object { master: {…}, self_signing: {…}, user_signing: {…} }
rageshake.js:52:4
downloadKeys: already have a download in progress for @rda0:matrix.org: awaiting its result rageshake.js:52:4
Completed key download for @rda0:matrix.org rageshake.js:52:4
Device list for @rda0:matrix.org now up to date rageshake.js:52:4
Saving device tracking data xxxxxxxxx rageshake.js:52:4
Old unverified sessions: rageshake.js:52:4
New unverified sessions: rageshake.js:52:4
Checking key backup status... rageshake.js:52:4
Old unverified sessions: rageshake.js:52:4
New unverified sessions: rageshake.js:52:4
Backup public key xxxxxxxxx is trusted locally rageshake.js:52:4
Backup version 1 still current
```

### Operating system

Windows

### Application version

Element version: 1.9.0 Olm version: 3.2.3

### How did you install the app?

https://element.io/get-started

### Homeserver

phys.ethz.ch

### Have you submitted a rageshake?

Yes

**Comment by rda0** [comment]
I can no longer reproduce this (v1.11.40). Looks good.
