### ISSUE TITLE
Leave Room Button Fails to Leave Room

### ISSUE THREAD

**Issue by qpix44** [vector-im/element-web#19667]
### Steps to reproduce

For a contact I click "room options" then the "leave room" button. The room remains there forever. I've tried this dozens of times over months now. And I've also tried the "room options"... "settings"... "leave room" button and that also does absolutely nothing for me.

#### What did you expect?
Room Goes Away
#### What happened instead?
Room Stays

### Operating system

Linux Mint

### Application version

1.7.25

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by qpix44** [comment]
PS- Internal Room ID: !XINpbTRxcfDSYMhXBm:matrix.org

**Comment by SimonBrandner** [comment]
Leaving works fine for me, could you please send logs they might be essential for figuring out what is happening?

**Comment by qpix44** [comment]
Thanks for the reply. The log entries pertaining to the roomID are:
issue.txt
mx_local_settings = {"analyticsOptIn":false,"showCookieBar":false,"language":"en-us","blacklistUnverifiedDevicesPerRoom":{"!XINpbTRxcfDSYMhXBm:matrix.org":false}}

log-0
2021-11-09T14:46:05.887Z I Switching to room id !XINpbTRxcfDSYMhXBm:matrix.org at event undefined
2021-11-09T14:46:05.912Z I RVS update: !XINpbTRxcfDSYMhXBm:matrix.org  loading? false joining? false initial? true shouldPeek? true
2021-11-09T14:46:05.912Z I Returning cached capabilities
2021-11-09T14:46:05.913Z I newscreen room/!XINpbTRxcfDSYMhXBm:matrix.org
2021-11-09T14:46:05.926Z I updateTint from RoomView.gatherTimelinePanelRef
2021-11-09T14:46:05.926Z I Tinter.tint from updateTint
2021-11-09T14:46:05.938Z I [!XINpbTRxcfDSYMhXBm:matrix.org] Current version: 6
2021-11-09T14:46:05.938Z I [!XINpbTRxcfDSYMhXBm:matrix.org] Version capability:  {"default":"6","available":{"1":"stable","2":"stable","3":"stable","4":"stable","5":"stable","6":"stable","7":"stable","8":"stable","9":"stable","org.matrix.msc2176":"unstable","org.matrix.msc2716v3":"unstable"},"org.matrix.msc3244.room_capabilities":{"knock":{"preferred":"7","support":["7","8","9","org.matrix.msc2716v3"]},"restricted":{"preferred":"9","support":["8","9"]}}}
2021-11-09T14:46:06.383Z I Event $k4yzQpeV_sxNoK3x4Y6_at4lXo3RwHMwnRx-tLvxAvk already in timeline !XINpbTRxcfDSYMhXBm:matrix.org:2021-11-09T13:03:11.808Z
2021-11-09T14:46:06.383Z I Event $qaxheh3243Ib8P8sSs0hYtxERj9uR97wKi8xfH17DkU already in timeline !XINpbTRxcfDSYMhXBm:matrix.org:2021-11-09T13:03:11.808Z
2021-11-09T14:46:06.383Z I Event $6rco2en_oc5Ktj8qxdC9LXdR6uDCAOMNwS6M8sfOQz8 already in timeline !XINpbTRxcfDSYMhXBm:matrix.org:2021-11-09T13:03:11.808Z
2021-11-09T14:46:06.383Z I Event $gHVvGnxBjcfLPe_UScexKvFlZG9p8U2Mw-XB4vEK0-o already in timeline !XINpbTRxcfDSYMhXBm:matrix.org:2021-11-09T13:03:11.808Z
2021-11-09T14:46:06.383Z I Event $jrrphfhOjvp8x90qXi_JytaBIHVICsesADFDVwYUDc8 already in timeline !XINpbTRxcfDSYMhXBm:matrix.org:2021-11-09T13:03:11.808Z
2021-11-09T14:46:06.383Z I Event $ubyG6ER2DZ16v8MLwc2hZ7M4e4v4RbRplQXTsf16P74 already in timeline !XINpbTRxcfDSYMhXBm:matrix.org:2021-11-09T13:03:11.808Z
2021-11-09T14:46:06.383Z I Event $n-P0YUU0kWEuzk-cbhy_p5_7KMVmVSuX8A6IBJlCpb0 already in timeline !XINpbTRxcfDSYMhXBm:matrix.org:2021-11-09T13:03:11.808Z
2021-11-09T14:46:06.383Z I Event $SpUdZRCJX3qifVvXSy28XJaiYLsph_Z9yGPHbSAr6M4 already in timeline !XINpbTRxcfDSYMhXBm:matrix.org:2021-11-09T13:03:11.808Z
2021-11-09T14:46:06.383Z I Event $FCF8fdlJxtVrhDPTlEf9LUylhxHQbslPZySkDlSG6vg already in timeline !XINpbTRxcfDSYMhXBm:matrix.org:2021-11-09T13:03:11.808Z
2021-11-09T14:46:06.397Z W Error decrypting event (id=$k4yzQpeV_sxNoK3x4Y6_at4lXo3RwHMwnRx-tLvxAvk): DecryptionError[msg: The sender's device has not sent us the keys for this message.,

log-1
2021-11-09T04:11:59.346Z I Notified 0 devices we failed to create Olm sessions in !XINpbTRxcfDSYMhXBm:matrix.org
2021-11-09T04:11:59.346Z I setting pendingEvent status to sending in !XINpbTRxcfDSYMhXBm:matrix.org event ID ~!XINpbTRxcfDSYMhXBm:matrix.org:m1636431119310.0 -> undefined
2021-11-09T04:11:59.604Z E Error sending event M_FORBIDDEN: User @username:matrix.org not in room !XINpbTRxcfDSYMhXBm:matrix.org (<FrozenEventV3 event_id=$Tt074zqI3a5gX0M7LWPp1dN66R5oR6nXwU-S_oL7fBs, type=m.room.member, state_key=@username:matrix.org, outlier=False>)
    at vector://vector/webapp/bundles/365a72cf9c29f7e25e25/vendors~init.js:2:783491
    at vector://vector/webapp/bundles/365a72cf9c29f7e25e25/vendors~init.js:2:783648
    at Object.callback (vector://vector/webapp/bundles/365a72cf9c29f7e25e25/vendors~init.js:2:782802)
    at vector://vector/webapp/bundles/365a72cf9c29f7e25e25/vendors~init.js:2:35818
    at XMLHttpRequest.r.onreadystatechange (vector://vector/webapp/bundles/365a72cf9c29f7e25e25/vendors~init.js:2:35842)
2021-11-09T04:11:59.604Z I setting pendingEvent status to not_sent in !XINpbTRxcfDSYMhXBm:matrix.org event ID ~!XINpbTRxcfDSYMhXBm:matrix.org:m1636431119310.0 -> undefined
2021-11-09T04:11:59.616Z I Starting load of AsyncWrapper for modal

log-1 has many other references to the room ID but I'm hoping this will be enough because it has a lot of contact references I'd have to edit out.

log-2
2021-11-09T03:56:26.812Z I Switching to room id !XINpbTRxcfDSYMhXBm:matrix.org at event undefined
2021-11-09T03:56:26.820Z I RVS update: !XINpbTRxcfDSYMhXBm:matrix.org  loading? false joining? false initial? true shouldPeek? true
2021-11-09T03:56:26.821Z I Returning cached capabilities
2021-11-09T03:56:26.821Z I newscreen room/!XINpbTRxcfDSYMhXBm:matrix.org
2021-11-09T03:56:26.827Z I updateTint from RoomView.gatherTimelinePanelRef
2021-11-09T03:56:26.827Z I Tinter.tint from updateTint
2021-11-09T03:56:26.838Z I [!XINpbTRxcfDSYMhXBm:matrix.org] Current version: 6
2021-11-09T03:56:26.838Z I [!XINpbTRxcfDSYMhXBm:matrix.org] Version capability: 

After this I don't see any substantial entries for the room ID. I wish the log file system would have option to scrub most personally identifying data for privacy, but it does not seem to.

**Comment by qpix44** [comment]
I have debugging information above, hopefully this will be of help.

**Comment by t3chguy** [comment]
204 is not a valid response for `/leave`

https://spec.matrix.org/v1.2/client-server-api/#post_matrixclientv3roomsroomidleave

says it must be 200 if the room was left.

**Comment by t3chguy** [comment]
@okias if you're seeing the `/leave` request and the room isn't coming down `/sync` in the `leave` section then its a server issue. @qpix44 are you still seeing this? If so we could do with some new logs which have better details.

**Comment by t3chguy** [comment]
Closing as a server issue
