### ISSUE TITLE
DM room is encrypted on one side but not the other

### ISSUE THREAD

**Issue by kegsay** [vector-im/element-web#19705]
### Steps to reproduce

- Sign up for a brand new matrix.org account
- Start a DM with me. (v6)
- The DM is not encrypted for you but it is for me.

I dug into this and the reason why is because the initiator does not have the entire room state: it lacks the `m.room.encryption` event, whereas I have:
<img width="724" alt="Screenshot 2021-11-11 at 16 09 03" src="https://user-images.githubusercontent.com/7190048/141331708-eac94c56-7775-469e-ac7a-ae124735ee68.png">

On the other side, they ONLY had `m.room.create` and `m.room.member`. Looking at the logs for this, it looks like the code which processes `/sync` fell over which has resulted in partial state:
```
2021-11-11T15:59:02.408Z I No usable key backup: not enabling key backup
2021-11-11T15:59:02.424Z I LL: got 1 members from server for room !GtAZwcgIRgGMvUCNyF:matrix.org
2021-11-11T15:59:02.425Z I LL: RoomState about to set 1 OOB members ...
2021-11-11T15:59:02.425Z I LL: RoomState put in finished state ...
2021-11-11T15:59:02.425Z I LL: telling store to write 0 members for room !GtAZwcgIRgGMvUCNyF:matrix.org
2021-11-11T15:59:02.438Z I Event $f1lzUDKNqNHHBNWeGZCYmupQzXc4ppsycYSNkrKUNU0 already in timeline !GtAZwcgIRgGMvUCNyF:matrix.org:2021-11-11T15:59:02.128Z
2021-11-11T15:59:02.759Z I Saving device tracking data m2462457537~2.2462457541~3.2462457541_757284961_7414302_1102398485_1047423627_2750527_358471574_2268960259_210115
2021-11-11T15:59:05.426Z E Caught /sync error TypeError: Cannot read property 'getContent' of undefined
    at Y.<anonymous> (vector://vector/webapp/bundles/d443354bdb439e133de8/vendors~init.js:2:157412)
    at Y.s.emit (vector://vector/webapp/bundles/d443354bdb439e133de8/vendors~init.js:2:11111)
    at vector://vector/webapp/bundles/d443354bdb439e133de8/vendors~init.js:2:3166333
    at Array.forEach (<anonymous>)
    at y.processSyncResponse (vector://vector/webapp/bundles/d443354bdb439e133de8/vendors~init.js:2:3166188)
    at y.doSync (vector://vector/webapp/bundles/d443354bdb439e133de8/vendors~init.js:2:3163984)
```

Leaving the DM room and making a new DM room fixed this.

The initiator has:
```
Element 1.9.4
Olm 3.2.3
OS: Windows
```

### Outcome

This should work fine and be encrypted.

### Operating system

Windows

### Application version

Element 1.9.4 Olm 3.2.3

### How did you install the app?

From element.io

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by dbkr** [comment]
Decoder ring says the top stack frame is `{"source":"webpack:///node_modules/matrix-react-sdk/src/stores/SpaceStore.ts","line":709,"column":42,"name":"getContent"}`

**Comment by t3chguy** [comment]
That looks to be assuming that accountData changes always have a lastEvent, will fix
