### ISSUE TITLE
Tests sometimes fail with cryptic jsdom errors

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#19858]
```
TypeError: Cannot read property '_origin' of null
    at Window.get localStorage [as localStorage] (/workdir/node_modules/jsdom/lib/jsdom/browser/Window.js:420:50)
    at createClient (/workdir/matrix-js-sdk/src/matrix.ts:472:26)
    at Registration.replaceClient (/workdir/src/components/structures/auth/Registration.tsx:273:42)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Re-running the test appears to fix it.

**Comment by t3chguy** [comment]
Puppeteer tests are on their way out, long live cypress
