### ISSUE TITLE
TypeError: Cannot read property 'offsetParent' of null 

### ISSUE THREAD

**Issue by DoM1niC** [vector-im/element-web#19948]
### Steps to reproduce

Hey Devs,
I got since the recent Commits from 29.11.2021 everytime a crash by searching  / clicking on the sidebar Events could this affected by https://github.com/matrix-org/matrix-react-sdk/commit/9727a82a12f255500febc2890c870e0d7ad3d320 ?

### Outcome

**LOG**
```
rageshake.ts:65 TypeError: Cannot read property 'offsetParent' of null
    at _ (RovingTabIndex.tsx:174)
    at S (RovingTabIndex.tsx:130)
    at Object.aa [as useReducer] (react-dom.production.min.js:159)
    at t.useReducer (react.production.min.js:23)
    at w (RovingTabIndex.tsx:188)
    at na (react-dom.production.min.js:157)
    at Ua (react-dom.production.min.js:180)
    at qs (react-dom.production.min.js:269)
    at Sc (react-dom.production.min.js:250)
    at yc (react-dom.production.min.js:250)
e.<computed> @ rageshake.ts:65
rageshake.ts:65 Ending non-existent watcher ID undefined
e.<computed> @ rageshake.ts:65
rageshake.ts:65 TypeError: Cannot read property 'offsetParent' of null
    at _ (RovingTabIndex.tsx:174)
    at S (RovingTabIndex.tsx:130)
    at Object.aa [as useReducer] (react-dom.production.min.js:159)
    at t.useReducer (react.production.min.js:23)
    at w (RovingTabIndex.tsx:188)
    at na (react-dom.production.min.js:157)
    at Ua (react-dom.production.min.js:180)
    at qs (react-dom.production.min.js:269)
    at Sc (react-dom.production.min.js:250)
    at yc (react-dom.production.min.js:250)
e.<computed> @ rageshake.ts:65
rageshake.ts:65 The above error occured while React was rendering the following components: 
    at w (vector://vector/webapp/bundles/a97b46f3f4cc909721ef/init.js:1:218144)
    at i (vector://vector/webapp/bundles/a97b46f3f4cc909721ef/init.js:1:1211579)
    at div
    at div
    at aside
    at div
    at e (vector://vector/webapp/bundles/a97b46f3f4cc909721ef/init.js:1:1758467)
    at div
    at div
    at div
    at div
    at T (vector://vector/webapp/bundles/a97b46f3f4cc909721ef/init.js:1:2415223)
    at n (vector://vector/webapp/bundles/a97b46f3f4cc909721ef/init.js:1:706254)
    at We (vector://vector/webapp/bundles/a97b46f3f4cc909721ef/init.js:1:2358631)
e.<computed> @ rageshake.ts:65
```

### Operating system

Windows

### Browser information

Electron App

### URL for webapp

messenger.3dns.eu

### Application version

Develop

### Homeserver

messenger.3dns.eu

### Will you send logs?

Yes

**Comment by novocaine** [comment]
Also experiencing this

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/pull/7228
