### ISSUE TITLE
`node-gyp` related build issue for Node 17

### ISSUE THREAD

**Issue by ghost** [vector-im/element-web#20075]
I resolved part of the problem of #19486 by myself, however I run into another build issue preventing Element desktop from being build
Error logs (verbose):
```
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@17.2.0 | darwin | arm64
gyp info find Python using Python version 3.10.0 found at "/opt/homebrew/opt/python@3.10/bin/python3.10"
(node:29530) [DEP0150] DeprecationWarning: Setting process.config is deprecated. In the future the property will be read-only.
(Use `node --trace-deprecation ...` to show where the warning was created)
gyp info spawn /opt/homebrew/opt/python@3.10/bin/python3.10
gyp info spawn args [
gyp info spawn args   '/Users/david/code/element-desktop/.hak/keytar/aarch64-apple-darwin/build/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/david/code/element-desktop/.hak/keytar/aarch64-apple-darwin/build/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/david/code/element-desktop/.hak/keytar/aarch64-apple-darwin/build/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/david/.electron-gyp/13.5.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/david/.electron-gyp/13.5.1',
gyp info spawn args   '-Dnode_gyp_dir=/Users/david/code/element-desktop/.hak/keytar/aarch64-apple-darwin/build/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/david/.electron-gyp/13.5.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/david/code/element-desktop/.hak/keytar/aarch64-apple-darwin/build',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
gyp: name 'openssl_fips' is not defined while evaluating condition 'openssl_fips != ""' in binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/david/code/element-desktop/.hak/keytar/aarch64-apple-darwin/build/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Darwin 21.1.0
gyp ERR! command "/opt/homebrew/Cellar/node/17.2.0/bin/node" "/Users/david/code/element-desktop/.hak/keytar/aarch64-apple-darwin/build/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/david/code/element-desktop/.hak/keytar/aarch64-apple-darwin/build
gyp ERR! node -v v17.2.0
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
verbose 6.547370917 Error: Command failed with exit code 1.
    at ProcessTermError.ExtendableBuiltin (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:721:66)
    at ProcessTermError.MessageError (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:750:123)
    at new ProcessTermError (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:790:113)
    at /opt/homebrew/lib/node_modules/yarn/lib/cli.js:34672:30
    at Generator.throw (<anonymous>)
    at step (/opt/homebrew/lib/node_modules/yarn/lib/cli.js:310:30)
    at /opt/homebrew/lib/node_modules/yarn/lib/cli.js:323:13
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

_Originally posted by @D4v1dH03 in https://github.com/vector-im/element-web/issues/19486#issuecomment-987110730_

**Comment by dbkr** [comment]
Looks like this will be fixed when we can upgrade Electron. Until then, a workaround will be to use a different node version to build.

**Comment by gsouquet** [comment]
The build steps outlined on the README.md say 

> Install or update node.js so that your node is at least v14.x.

A good first step before upgrading the Electron version would be to recommend using Node.js LTS (v14 or v16).
Marking as good first issue as we'll accept a PR to change the build steps and this issue will go away when upgrading Electron

**Comment by gsouquet** [comment]
Closing to make https://github.com/vector-im/element-web/issues/21043 the canonical issue about node 17
