### ISSUE TITLE
Desktop app crashes on logout

### ISSUE THREAD

**Issue by LeFunFun** [vector-im/element-web#20122]
### Steps to reproduce

1. Where are you starting? What can you see?
2. What do you click?
3. More steps…

### Outcome

What happened?
I was logging out when a issue screen appeared.

### Operating system

Windows

### Application version

Element version 1.9.6

### How did you install the app?

From the official page of Element

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by ShadowJonathan** [comment]
What was the issue? what did it say?

**Comment by LeFunFun** [comment]
![Captura de pantalla (12)](https://user-images.githubusercontent.com/95881330/145466449-4e5c4b00-d97e-4053-b8d5-f1f1f7a7c7d8.png)

**Comment by LeFunFun** [comment]
> What was the issue? what did it say?
![Captura de pantalla (12)](https://user-images.githubusercontent.com/95881330/145466836-da1f043b-c5e4-4cec-93ff-e2ccf92313c0.png)

**Comment by ShadowJonathan** [comment]
Did you click the "submit debug logs" button?

**Comment by LeFunFun** [comment]
> ¿Hiciste clic en el botón "enviar registros de depuración"?

Yes

**Comment by ShadowJonathan** [comment]
Okay, then i think you have done all you can, thanks

**Comment by gsouquet** [comment]
Looks like widgets are unhappy. Haven't investigated further

```
2021-12-08T21:08:14.541Z W Ending non-existent watcher ID undefined
2021-12-08T21:08:14.592Z E Cannot read property 'roomId' of null
TypeError: Cannot read property 'roomId' of null
    at Function.emissionForRoom (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:398828)
    at r.componentWillUnmount (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:2300800)
    at ms (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3145815)
    at bs (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3147608)
    at xc (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3159658)
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3186360)
    at Gi (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3102951)
    at Tc (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3157619)
    at hc (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3153730)
    at vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3103174
2021-12-08T21:08:14.595Z E Cannot read property 'roomId' of null
TypeError: Cannot read property 'roomId' of null
    at Function.emissionForRoom (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:398828)
    at r.componentWillUnmount (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:2300800)
    at ms (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3145815)
    at bs (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3147608)
    at xc (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3159658)
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3186360)
    at Gi (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3102951)
    at Tc (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3157619)
    at hc (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3153730)
    at vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:3103174
2021-12-08T21:08:14.595Z E The above error occured while React was rendering the following components: 
    at r (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:2298924)
    at div
    at r (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:2298071)
    at R (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:2897868)
    at r (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:883133)
    at qe (vector://vector/webapp/bundles/a34eec43b65847244a8c/vendors~init.js:2:2842554)
```

**Comment by t3chguy** [comment]
Already fixed on develop, this was a CallHandler listener which only got partially removed from LIV
