### ISSUE TITLE
element-desktop build fails with gyp http 403 error

### ISSUE THREAD

**Issue by rda0** [vector-im/element-web#20167]
Building element-desktop v1.9.7 on Ubuntu 20.04 fails with:

```
gyp info it worked if it ends with ok
gyp info using node-gyp@6.1.0
gyp info using node@16.13.1 | linux | x64
gyp info find Python using Python version 3.8.10 found at "/usr/bin/python3"
gyp http GET https://atom.io/download/electron/v16.13.1/node-v16.13.1-headers.tar.gz
gyp http 403 https://atom.io/download/electron/v16.13.1/node-v16.13.1-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: 403 response downloading https://atom.io/download/electron/v16.13.1/node-v16.13.1-headers.tar.gz
gyp ERR! stack     at Request.<anonymous> (/home/gitlab-runner/builds/VNqxRNev/0/core/element-desktop/.hak/keytar/x86_64-unknown-linux-gnu/build/node_modules/node-gyp/lib/install.js:188:14)
gyp ERR! stack     at Request.emit (node:events:402:35)
gyp ERR! stack     at Request.onRequestResponse (/home/gitlab-runner/builds/VNqxRNev/0/core/element-desktop/.hak/keytar/x86_64-unknown-linux-gnu/build/node_modules/request/request.js:1059:10)
gyp ERR! stack     at ClientRequest.emit (node:events:390:28)
gyp ERR! stack     at HTTPParser.parserOnIncomingClient (node:_http_client:623:27)
gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
gyp ERR! stack     at TLSSocket.socketOnData (node:_http_client:487:22)
gyp ERR! stack     at TLSSocket.emit (node:events:390:28)
gyp ERR! stack     at addChunk (node:internal/streams/readable:315:12)
gyp ERR! stack     at readableAddChunk (node:internal/streams/readable:289:9)
gyp ERR! System Linux 5.4.0-74-generic
gyp ERR! command "/usr/bin/node" "/home/gitlab-runner/builds/VNqxRNev/0/core/element-desktop/.hak/keytar/x86_64-unknown-linux-gnu/build/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /home/gitlab-runner/builds/VNqxRNev/0/core/element-desktop/.hak/keytar/x86_64-unknown-linux-gnu/build
gyp ERR! node -v v16.13.1
gyp ERR! node-gyp -v v6.1.0
gyp ERR! not ok 
1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Looks like something is wrong with the electron version in the URL (`https://atom.io/download/electron/v16.13.1/node-v16.13.1-headers.tar.gz`), which looks like the node version.

Using `electronVersion` in `package.json` as in previous versions works:

```
  "build": {
    "appId": "im.riot.app",
    "electronVersion": "13.5.2",
  ...
```

Versions:

- nodejs: v16.13.1
- yarn: 1.22.17
- npm: 8.1.2

**Comment by dbkr** [comment]
You should find there's another commit that adds the electronVersion back - I had to add it back & re-do the release, so try again

**Comment by rda0** [comment]
Thank you, works. Sorry my bad, I rebased onto the master branch and did not get that commit.
