### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getVisibleRooms')

### ISSUE THREAD

**Issue by ohporter** [vector-im/element-web#20278]
### Steps to reproduce

1. Where are you starting? What can you see?

Updated to our Element Web to 1.9.8, running Element Web in a browser

2. What do you click?

Clicked browser refresh button

3. More steps…

Running Synapse 1.49 unfederated with no publicly visible rooms, only single private space with only private space member visible rooms

#### What did you expect?

No browser console errors.

#### What happened instead?

I see this error in the console when element loads (which seems benign):
```
vendors~init.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getVisibleRooms')
    at j.getSpaceFilteredRoomIds (vendors~init.js:2)
    at j.onAction (vendors~init.js:2)
    at j.onDispatch (vendors~init.js:2)
    at o.e._invokeCallback (vendors~init.js:2)
    at o.e.dispatch (vendors~init.js:2)
```

### Operating system

Debian 11

### Browser information

Version 96.0.4664.45 (Official Build) (64-bit)

### URL for webapp

Element Web v1.9.8 docker image

### Application version

Element version: 1.9.8 Olm version: 3.2.8

### Homeserver

private homeserver

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
The logs you sent don't seem to have this error recently.
The error I see in the logs is

```
2021-12-20T16:08:16.571Z E /sync error %s Server returned 502 error
Error: Server returned 502 error
    at https://element.konsulko.com/bundles/8e5737671ae49a63c3b5/vendors~init.js:2:956886
    at https://element.konsulko.com/bundles/8e5737671ae49a63c3b5/vendors~init.js:2:956951
    at Object.callback (https://element.konsulko.com/bundles/8e5737671ae49a63c3b5/vendors~init.js:2:956083)
    at https://element.konsulko.com/bundles/8e5737671ae49a63c3b5/vendors~init.js:2:28999
    at XMLHttpRequest.i.onreadystatechange (https://element.konsulko.com/bundles/8e5737671ae49a63c3b5/vendors~init.js:2:29023)
    at XMLHttpRequest.<anonymous> (https://element.konsulko.com/bundles/8e5737671ae49a63c3b5/vendors~init.js:2:6189671)
```

and

```
2021-12-20T15:33:54.184Z E /sync error %s request failed: CORS request rejected: https://matrix.konsulko.com/_matrix/client/r0/sync?filter=0&timeout=30000&since=s290_22641_4_94_264_15_1_21_1
ConnectionError: request failed: CORS request rejected: https://matrix.konsulko.com/_matrix/client/r0/sync?filter=0&timeout=30000&since=s290_22641_4_94_264_15_1_21_1
    at https://element.konsulko.com/bundles/b087b7dfe002d02dbf07/vendors~init.js:2:937212
    at Object.callback (https://element.konsulko.com/bundles/b087b7dfe002d02dbf07/vendors~init.js:2:936949)
    at u (https://element.konsulko.com/bundles/b087b7dfe002d02dbf07/vendors~init.js:2:29383)
    at XMLHttpRequest.i.onreadystatechange (https://element.konsulko.com/bundles/b087b7dfe002d02dbf07/vendors~init.js:2:28813)
    at XMLHttpRequest.<anonymous> (https://element.konsulko.com/bundles/b087b7dfe002d02dbf07/vendors~init.js:2:5571441)
2021-12-20T15:33:54.186Z E request failed: CORS request rejected: https://matrix.konsulko.com/_matrix/client/r0/sync?filter=0&timeout=30000&since=s290_22641_4_94_264_15_1_21_1
ConnectionError: request failed: CORS request rejected: https://matrix.konsulko.com/_matrix/client/r0/sync?filter=0&timeout=30000&since=s290_22641_4_94_264_15_1_21_1
    at https://element.konsulko.com/bundles/b087b7dfe002d02dbf07/vendors~init.js:2:937212
    at Object.callback (https://element.konsulko.com/bundles/b087b7dfe002d02dbf07/vendors~init.js:2:936949)
    at u (https://element.konsulko.com/bundles/b087b7dfe002d02dbf07/vendors~init.js:2:29383)
    at XMLHttpRequest.i.onreadystatechange (https://element.konsulko.com/bundles/b087b7dfe002d02dbf07/vendors~init.js:2:28813)
    at XMLHttpRequest.<anonymous> (https://element.konsulko.com/bundles/b087b7dfe002d02dbf07/vendors~init.js:2:5571441)

**Comment by t3chguy** [comment]
This is fixed on develop
