### ISSUE TITLE
Infinite spinner + exceptions when trying to join a space

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#20457]
### Steps to reproduce

* Typed `/join #bsky:matrix.org`
* Clicked the join button

#### What did you expect?

Join the space

#### What happened instead?

Infinite spinner, with exceptions on console looking like:

```
rageshake.ts:65 Degrading performance to find missing room in "m.favourite": !LiSLXinTDCsepePiYW:matrix.org
consoleObj.<computed> @ rageshake.ts:65
(anonymous) @ instrument.js:111
(anonymous) @ logger.ts:50
getRoomIndex @ OrderingAlgorithm.ts:76
handleRoomUpdate @ ImportanceAlgorithm.ts:163
handleRoomUpdate @ Algorithm.ts:780
handleRoomUpdate @ RoomListStore.ts:366
tryUpdate @ RoomListStore.ts:257
onDispatchAsync @ RoomListStore.ts:269
(anonymous) @ RoomListStore.ts:199
run @ setImmediate.js:40
runIfPresent @ setImmediate.js:69
onGlobalMessage @ setImmediate.js:109
postMessage (async)
registerImmediate @ setImmediate.js:120
setImmediate @ setImmediate.js:27
onAction @ RoomListStore.ts:199
onDispatch @ AsyncStoreWithClient.ts:62
_invokeCallback @ Dispatcher.js:198
dispatch @ Dispatcher.js:174
dispatch @ dispatcher.ts:45
listener @ MatrixActionCreators.ts:279
emit @ events.js:158
forSource @ ReEmitter.ts:45
emit @ events.js:158
forSource @ ReEmitter.ts:45
emit @ events.js:153
addEventToTimeline @ event-timeline-set.ts:601
addLiveEvent @ event-timeline-set.ts:567
addLiveEvent @ room.ts:1425
addLiveEvents @ room.ts:1795
processRoomEvents @ sync.ts:1716
(anonymous) @ sync.ts:1308
promiseMapSeries @ utils.ts:469
async function (async)
promiseMapSeries @ utils.ts:469
processSyncResponse @ sync.ts:1212
doSync @ sync.ts:835
async function (async)
doSync @ sync.ts:802
doSync @ sync.ts:878
async function (async)
doSync @ sync.ts:802
doSync @ sync.ts:878
async function (async)
doSync @ sync.ts:802
doSync @ sync.ts:878
async function (async)
doSync @ sync.ts:802
doSync @ sync.ts:878
async function (async)
doSync @ sync.ts:802
doSync @ sync.ts:878
async function (async)
doSync @ sync.ts:802
doSync @ sync.ts:878
async function (async)
doSync @ sync.ts:802
doSync @ sync.ts:878
async function (async)
doSync @ sync.ts:802
doSync @ sync.ts:878
async function (async)
doSync @ sync.ts:820
11:18:02.386 ImportanceAlgorithm.ts:165 Uncaught (in promise) Error: Room !LiSLXinTDCsepePiYW:matrix.org has no index in m.favourite
    at ImportanceAlgorithm_ImportanceAlgorithm.handleRoomUpdate (ImportanceAlgorithm.ts:165)
    at Algorithm_Algorithm.handleRoomUpdate (Algorithm.ts:780)
    at RoomListStoreClass.handleRoomUpdate (RoomListStore.ts:366)
    at tryUpdate (RoomListStore.ts:257)
    at RoomListStoreClass.onDispatchAsync (RoomListStore.ts:269)
    at RoomListStore.ts:199
    at run (setImmediate.js:40)
    at runIfPresent (setImmediate.js:69)
    at onGlobalMessage (setImmediate.js:109)
```

### Operating system

macOS 12.1 on M1

### Application version

Nightly

### Will you send logs?

Yes

**Comment by gsouquet** [comment]
This also failed for me and the console log were looking like

```
rageshake.ts:65 Caught /sync error TypeError: Cannot read property 'has' of undefined
    at SpaceStore_SpaceStoreClass.onMemberUpdate (vector://vector/webapp/bundles/ec4837687cd664130848/init.js:8246:52)
    at MatrixClient.<anonymous> (vector://vector/webapp/bundles/ec4837687cd664130848/init.js:8566:14)
    at MatrixClient.emit (vector://vector/webapp/bundles/ec4837687cd664130848/vendors~init.js:168:7)
    at RoomState.forSource (vector://vector/webapp/bundles/ec4837687cd664130848/init.js:69333:22)
    at RoomState.emit (vector://vector/webapp/bundles/ec4837687cd664130848/vendors~init.js:168:7)
    at vector://vector/webapp/bundles/ec4837687cd664130848/init.js:98025:14
    at Array.forEach (<anonymous>)
    at RoomState.setStateEvents (vector://vector/webapp/bundles/ec4837687cd664130848/init.js:98003:17)
    at SyncApi.processRoomEvents (vector://vector/webapp/bundles/ec4837687cd664130848/init.js:69092:25)
    at vector://vector/webapp/bundles/ec4837687cd664130848/init.js:68687:12
```

**Comment by ara4n** [comment]
seems every space join is failing for me (can't accept an invite from philip to one either)

**Comment by t3chguy** [comment]
Fixed by https://github.com/matrix-org/matrix-react-sdk/commit/08a0c6f86c614d264599926d38c78eca0c6a33d8
