### ISSUE TITLE
install + start + error message - `Invalid homeserver discovery response`

### ISSUE THREAD

**Issue by soloturn** [vector-im/element-web#20952]
### Steps to reproduce

1. Where are you starting? What can you see?
arch linux install ```paru -S element-desktop``` which installs it from the AUR: https://archlinux.org/packages/community/x86_64/element-desktop/.

2.  start
```element-desktop```

3. error message. first impression :(

> Failed to start
>
> Your Element is misconfigured
>
> Invalid homeserver discovery response

![](https://user-images.githubusercontent.com/825568/152717487-4480a113-d096-49b6-882e-65b362e39b95.png)

#### What did you expect?
working login screen, maybe searchable dropdown for home server.

#### What happened instead?
error.

### Operating system

arch linux

### Application version

no idea, it is not displayed. should be 1.10 ...

### Homeserver

irrelevant.

**Comment by SimonBrandner** [comment]
If you're willing to lose your config, you can try `rm -rf .config/Element`, does that help? Also, Arch is not officially supported

**Comment by soloturn** [comment]
tried ```rm -rf ~/.config/Element```, the error stays the same. it looks for en.json in a non-standard location.

```
> element-desktop
/home/st/.config/Element exists: no
/home/st/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Resetting the UI components after locale change
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[602055:0207/065304.426359:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
Changing application language to en-us,en
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en-us.json'
Require stack:
- /usr/lib/element/app.asar/lib/language-helper.js
- /usr/lib/element/app.asar/lib/tray.js
- /usr/lib/element/app.asar/lib/electron-main.js
- /usr/lib/electron15/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:934:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Module._load (node:internal/modules/cjs/loader:779:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at AppLocalization.fetchTranslationJson (/usr/lib/element/app.asar/lib/language-helper.js:76:20)
    at /usr/lib/element/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/usr/lib/element/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/element/app.asar/lib/language-helper.js',
    '/usr/lib/element/app.asar/lib/tray.js',
    '/usr/lib/element/app.asar/lib/electron-main.js',
    '/usr/lib/electron15/resources/default_app.asar/main.js',
    undefined
  ]
}
Fetching translation json for locale: en
Could not fetch translation json for locale: 'en' Error: Cannot find module './i18n/strings/en.json'
Require stack:
- /usr/lib/element/app.asar/lib/language-helper.js
- /usr/lib/element/app.asar/lib/tray.js
- /usr/lib/element/app.asar/lib/electron-main.js
- /usr/lib/electron15/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:934:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Module._load (node:internal/modules/cjs/loader:779:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at AppLocalization.fetchTranslationJson (/usr/lib/element/app.asar/lib/language-helper.js:76:20)
    at /usr/lib/element/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/usr/lib/element/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/lib/element/app.asar/lib/language-helper.js',
    '/usr/lib/element/app.asar/lib/tray.js',
    '/usr/lib/element/app.asar/lib/electron-main.js',
    '/usr/lib/electron15/resources/default_app.asar/main.js',
    undefined
  ]
}
Resetting the UI components after locale change

```

**Comment by soloturn** [comment]
thanks! now it works. but the behavior is not so beginner friendly. the following i did on the command line:

* opening the app console resulted in showing the login screen. maybe the page was cached. 
* i did not log in. hitting the x button then closed the window, but not the application. i did ctrl-c on the command line.
* ```ps``` revealed 3 element processes running. i stopped them with ```kill -QUIT```
* restarting then resulted that element displayed "logging out", and then displaying the login screen.
```
[669415:0208/131824.861413:ERROR:indexed_db_factory_impl.cc(847)] IndexedDB recovering from a corrupted (and deleted) database.
Resetting the UI components after locale change
[669456:0208/131840.965232:ERROR:broker_posix.cc(40)] Recvmsg error: Connection reset by peer (104)
fish: Job 1, 'element-desktop' terminated by signal SIGTRAP (Trace or breakpoint trap)
```
* starting again displays that i need to sign out. still - i never signed in yet.

![image](https://user-images.githubusercontent.com/825568/152987416-d38384bc-7210-4f62-92eb-2ccb44245410.png)

**Comment by turt2live** [comment]
I don't believe there's anything actionable on here. The remainder appears to be yet another case of https://github.com/vector-im/element-web/issues/22563.
