### ISSUE TITLE
Following most "Setting up a Dev Environment" instructions followed by `yarn build` in README resulted in error

### ISSUE THREAD

**Issue by anoadragon453** [vector-im/element-web#21109]
Following the instructions in https://github.com/vector-im/element-web/#setting-up-a-dev-environment resulted in the following error when running `yarn build`:

<details>

<summary>error traceback</summary>

```
[user@izzy element-web]$ yarn reskindex
yarn run v1.22.17
$ reskindex -h src/header
Reskindex completed
Done in 0.13s.
[user@izzy element-web]$ yarn build
yarn run v1.22.17
$ yarn clean && yarn build:genfiles && yarn build:bundle
$ rimraf lib webapp
$ yarn reskindex && yarn build:res && yarn build:jitsi
$ reskindex -h src/header
Reskindex completed
$ node scripts/copy-res.js
$ node scripts/build-jitsi.js
Making webapp directory
Downloading Jitsi script
Done with Jitsi download
$ webpack --progress --bail --mode production
Unset VERSION variable - this may affect build output
31% building 144/163 modules 19 active ...react-sdk/src/utils/StorageManager.tsModuleNotFoundError: Module not found: Error: Can't resolve './component-index' in '/home/user/code/element-web/matrix-react-sdk/src'
    at /home/user/code/element-web/node_modules/webpack/lib/Compilation.js:925:10
    at /home/user/code/element-web/node_modules/webpack/lib/NormalModuleFactory.js:401:22
    at /home/user/code/element-web/node_modules/webpack/lib/NormalModuleFactory.js:130:21
    at /home/user/code/element-web/node_modules/webpack/lib/NormalModuleFactory.js:224:22
    at /home/user/code/element-web/node_modules/neo-async/async.js:2830:7
    at /home/user/code/element-web/node_modules/neo-async/async.js:6877:13
    at /home/user/code/element-web/node_modules/webpack/lib/NormalModuleFactory.js:214:25
    at /home/user/code/element-web/node_modules/enhanced-resolve/lib/Resolver.js:213:14
    at /home/user/code/element-web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/user/code/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/user/code/element-web/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
    at /home/user/code/element-web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/user/code/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/user/code/element-web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/user/code/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/user/code/element-web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/user/code/element-web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/user/code/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/user/code/element-web/node_modules/enhanced-resolve/lib/RootPlugin.js:37:38
    at _next44 (eval at create (/home/user/code/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:8:1)
    at eval (eval at create (/home/user/code/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:31:1)
    at /home/user/code/element-web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/user/code/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /home/user/code/element-web/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
    at /home/user/code/element-web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/user/code/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /home/user/code/element-web/node_modules/enhanced-resolve/lib/Resolver.js:285:5
    at eval (eval at create (/home/user/code/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /home/user/code/element-web/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15
    at /home/user/code/element-web/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15
resolve './component-index' in '/home/user/code/element-web/matrix-react-sdk/src'
  using description file: /home/user/code/element-web/matrix-react-sdk/package.json (relative path: ./src)
    Field 'matrix_src_browser' doesn't contain a valid alias configuration
    Field 'browser' doesn't contain a valid alias configuration
    using description file: /home/user/code/element-web/matrix-react-sdk/package.json (relative path: ./src/component-index)
      no extension
        Field 'matrix_src_browser' doesn't contain a valid alias configuration
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/code/element-web/matrix-react-sdk/src/component-index doesn't exist
      .js
        Field 'matrix_src_browser' doesn't contain a valid alias configuration
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/code/element-web/matrix-react-sdk/src/component-index.js doesn't exist
      .json
        Field 'matrix_src_browser' doesn't contain a valid alias configuration
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/code/element-web/matrix-react-sdk/src/component-index.json doesn't exist
      .ts
        Field 'matrix_src_browser' doesn't contain a valid alias configuration
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/code/element-web/matrix-react-sdk/src/component-index.ts doesn't exist
      .tsx
        Field 'matrix_src_browser' doesn't contain a valid alias configuration
        Field 'browser' doesn't contain a valid alias configuration
        /home/user/code/element-web/matrix-react-sdk/src/component-index.tsx doesn't exist
      as directory
        /home/user/code/element-web/matrix-react-sdk/src/component-index doesn't exist
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[user@izzy element-web]$
```

</details>

It appears that running `yarn skindex` in `element-web` did not create a `component-index.js` in `element-web/matrix-react-sdk`. Doing the following allowed a `yarn build` in `element-web` to work:

```
cd matrix-react-sdk
yarn reskindex
```

To be clear, the exact commands run were:

```
git clone git@github.com:vector-im/element-web
cd element-web/
git clone git@github.com:matrix-org/matrix-react-sdk
git clone git@github.com:matrix-org/matrix-js-sdk
cd matrix-js-sdk/
yarn link
pamac search yarn
yarn install yarn
pamac install yarn
yarn link
yarn
cd ..
cd matrix-react-sdk/
yarn link
yarn
cd ..
yarn link matrix-js-sdk
yarn link matrix-react-sdk
yarn
yarn reskindex
yarn build  // fails!
cd matrix-react-sdk/
yarn reskindex
cd ..
yarn build  // succeeds
```

Is this expected?

**Comment by t3chguy** [comment]
Pretty much, dev environment is intended to use `yarn start`

**Comment by anoadragon453** [comment]
Ah, ok then!
