### ISSUE TITLE
Sending `[click here](https://matrix.to)` causes a tile crash

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#21216]
It's trying to parse the permalink and the parser isn't able to determine an entity for it, so it throws. The exception is caught by the tile error boundary.

This can have a wider effect on search results because the nearest error boundary is the middle panel itself.

Likely regressed from various bits of work around permalinks and pills, possibly the linkify stuff.

**Comment by gsouquet** [comment]
@turt2live I don't see a tile crash anymore, but can still see a lot of exception thrown in the console.
Not sure whether that's something we want to fix

```
rageshake.ts:72 Failed to parse permalink Error: Unknown entity type in permalink
    at MatrixToPermalinkConstructor.parsePermalink (://vector/webapp/bundles/4cea899c692cfa54629e/init.js:138822:13)
    at parsePermalink (://vector/webapp/bundles/4cea899c692cfa54629e/init.js:26164:68)
    at tryTransformPermalinkToLocalHref (://vector/webapp/bundles/4cea899c692cfa54629e/init.js:26101:28)
    at Object.a (://vector/webapp/bundles/4cea899c692cfa54629e/init.js:30802:137)
    at Object.onopentag (://vector/webapp/bundles/4cea899c692cfa54629e/vendors~init.js:30051:48)
    at Parser.push.Parser.onopentagend (://vector/webapp/bundles/4cea899c692cfa54629e/vendors~init.js:44975:86)
    at Tokenizer.push.Tokenizer.stateBeforeAttributeName (://vector/webapp/bundles/4cea899c692cfa54629e/vendors~init.js:45455:22)
```

**Comment by turt2live** [comment]
It's logged, not thrown?
