### ISSUE TITLE
CMD+[number] does not switch to space anymore

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21290]
### Steps to reproduce

1. Use `CtrlOrCommand+[number]`

#### What did you expect?

To switch to space

#### What happened instead?

Does not switch to space, and there's the following exception thrown

```
invariant.js:35 Uncaught (in promise) Error: Minified exception occurred; use the non-minified dev environment for the full error message and additional helpful warnings.
    at invariant (invariant.js:35:1)
    at MatrixDispatcher.dispatch (Dispatcher.js:167:157)
    at MatrixDispatcher.dispatch (dispatcher.ts:45:19)
    at SpaceStore_SpaceStoreClass.setActiveSpace (SpaceStore.ts:249:35)
    at SpaceStore_SpaceStoreClass.onAction (SpaceStore.ts:1166:26)
    at SpaceStore_SpaceStoreClass.onDispatch (AsyncStoreWithClient.ts:62:20)
    at MatrixDispatcher._invokeCallback (Dispatcher.js:198:1)
    at MatrixDispatcher.dispatch (Dispatcher.js:174:1)
    at sentryWrapped (helpers.js:76:1)
```

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is part of a larger class of bugs caused by https://github.com/matrix-org/matrix-react-sdk/pull/7910
