### ISSUE TITLE
logging me automatically out

### ISSUE THREAD

**Issue by gerhardbeck** [vector-im/element-web#21332]
### Steps to reproduce

Element logs me automatically out

### Operating system

Ubuntu 21.04 LTS

### Application version

Element

### How did you install the app?

Flatpack

### Homeserver

synod.im

### Will you send logs?

Yes

**Comment by gerhardbeck** [comment]
Wanted to send logs, but: **unable to connect to database**

**Comment by gsouquet** [comment]
This looks like a duplicate of https://github.com/vector-im/element-web/issues/21098 but would need some more information to say for sure.

**Comment by t3chguy** [comment]
@gsouquet doubt that IDB would be missing in the Element Flatpak

**Comment by gerhardbeck** [comment]
@gsouquet  Which information do you need? Just doublechecked: It's a flatpak installation, Version 1.10.4
@t3chguy What information of the console are you going to need?

**Comment by t3chguy** [comment]
Anything in the console that may be relevant to why you're being logged out, the logs you're unable to send (unable to connect to database) would have contained the console for your last few sessions.

**Comment by gerhardbeck** [comment]
OK, I try to send the information it it crashes again

08.03.2022 16:34:58 Michael Telatynski ***@***.***>:

**Comment by gerhardbeck** [comment]
ok, got the problem now, that Element is busy and crashes.
Console says:
![image](https://user-images.githubusercontent.com/41069802/158021940-43ead382-b985-47c4-abc3-7cf1c13fb3d6.png)

![image](https://user-images.githubusercontent.com/41069802/158021993-3c6f1316-74e7-49e7-ac3f-ac282aab6f9f.png)

and one issue:

![image](https://user-images.githubusercontent.com/41069802/158022018-c38ed18e-5eda-4f0b-abbf-0b8c598bca1d.png)

Anything helpfull?

**Comment by gerhardbeck** [comment]
and after a closing and a start: 
![image](https://user-images.githubusercontent.com/41069802/158022080-b1846204-b8d5-47c9-bf98-1a584f67609d.png)

console errors:
![image](https://user-images.githubusercontent.com/41069802/158022112-297a881b-5baa-471c-8bb2-9a1064f6dfe0.png)

and concerning the logs:
![image](https://user-images.githubusercontent.com/41069802/158022144-ed5833aa-2195-4505-ba36-dba804448f44.png)

**Comment by gsouquet** [comment]
For searchability, this seems to be another case of IndexedDB failing with the error messag, no connected database

**Comment by erikjohnston** [comment]
```
rageshake.ts:72 Failed to prepare to encrypt events for !SGNQGPGUwtcPBUotTL:matrix.org DOMException: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Backend.filterOutNotifiedErrorDevices (https://develop.element.io/bundles/c9eb09f5297decfb9c0f/init.js:202997:25)
    at IndexedDBCryptoStore.filterOutNotifiedErrorDevices (https://develop.element.io/bundles/c9eb09f5297decfb9c0f/init.js:45414:25)
    at OlmDevice.filterOutNotifiedErrorDevices (https://develop.element.io/bundles/c9eb09f5297decfb9c0f/init.js:130972:35)
    at MegolmEncryption.notifyFailedOlmDevices (https://develop.element.io/bundles/c9eb09f5297decfb9c0f/init.js:132239:58)
    at https://develop.element.io/bundles/c9eb09f5297decfb9c0f/init.js:131810:22
    at async Promise.all (index 1)
    at async prepareSession (https://develop.element.io/bundles/c9eb09f5297decfb9c0f/init.js:131749:7)
consoleObj.<computed> @ rageshake.ts:72
rageshake.ts:81
```

This just happened to me on develop.element.io. My account stopped updating and had that in the logs (I couldn't rageshake due to it either). When I refreshed it logged me in as a guest, which was confusing.

**Comment by klardotsh** [comment]
This (or some flavor of this) has been happening to me for at least a month across both app.element.io in Firefox and the standalone Electron app. I can usually stay logged in for 4-6 hours at a time and then will inevitably miss notifications because I'm automatically logged out for reasons unknown, but only insofar as needing a password to log back in (don't have to reselect homeserv/user). To say this is irritating would be the understatement of the month; I'd love to provide whatever logs I can to help next time I see this (sadly I just logged myself back in on app.element.io so don't have said logs handy right now, I don't think?)

**Comment by erikjohnston** [comment]
Just happened again with me. This is particularly annoying as it forgets **all** your preferences.

**Comment by k79e** [comment]
Happened to me just now.

**Comment by t3chguy** [comment]
![image](https://user-images.githubusercontent.com/2403652/202209601-3fbc7fb5-ac7e-4f0c-a4a5-b91818accc52.png)

Soft logout looks like this

**Comment by richvdh** [comment]
Sadness:

![image](https://github.com/vector-im/element-web/assets/1389908/5f4b4a2e-1528-42f9-b462-1352fcb0c773)
