### ISSUE TITLE
Jitsi widget doesn't close after leaving a meeting

### ISSUE THREAD

**Issue by Sleuth56** [vector-im/element-web#21648]
### Steps to reproduce

1. Open the april 1st nightly build of element desktop
2. Join a jitsi conference through element
3. Leave the meeting
4. Change rooms
The widget will follow you around forever

#### What did you expect?
The widget to close after exiting the meeting

#### What happened instead?
The widget follows you around until you close element or force reload it.

### Operating system

Arch Linux

### Application version

Element Nightly version: 2022040101 Olm version: 3.2.8

### How did you install the app?

AUR

### Homeserver

NA

### Will you send logs?

Let me know if this can't be reproduced of if I can help in any other ways.

**Comment by Sleuth56** [comment]
```
Failed to parse URL parameter value: meet.element.io SyntaxError: Unexpected token m in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.t.parse (jitsi_external_api.min.js:2:21554)
    at jitsi_external_api.min.js:2:8223
    at Array.forEach (<anonymous>)
    at jitsi_external_api.min.js:2:8030
    at Object.754 (jitsi_external_api.min.js:2:8324)
    at n (jitsi_external_api.min.js:2:32954)
    at Object.872 (jitsi_external_api.min.js:2:21029)
    at n (jitsi_external_api.min.js:2:32954)
    at jitsi_external_api.min.js:2:33214
c @ jitsi_external_api.min.js:2
jitsi_external_api.min.js:2 Failed to parse URL parameter value: NfCMBjikwOKUtmmwShrexroboticsorgxdojuj2ygg SyntaxError: Unexpected token N in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.t.parse (jitsi_external_api.min.js:2:21554)
    at jitsi_external_api.min.js:2:8223
    at Array.forEach (<anonymous>)
    at jitsi_external_api.min.js:2:8030
    at Object.754 (jitsi_external_api.min.js:2:8324)
    at n (jitsi_external_api.min.js:2:32954)
    at Object.872 (jitsi_external_api.min.js:2:21029)
    at n (jitsi_external_api.min.js:2:32954)
    at jitsi_external_api.min.js:2:33214
c @ jitsi_external_api.min.js:2
jitsi_external_api.min.js:2 Failed to parse URL parameter value: $isAudioOnly SyntaxError: Unexpected token $ in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.t.parse (jitsi_external_api.min.js:2:21554)
    at jitsi_external_api.min.js:2:8223
    at Array.forEach (<anonymous>)
    at jitsi_external_api.min.js:2:8030
    at Object.754 (jitsi_external_api.min.js:2:8324)
    at n (jitsi_external_api.min.js:2:32954)
    at Object.872 (jitsi_external_api.min.js:2:21029)
    at n (jitsi_external_api.min.js:2:32954)
    at jitsi_external_api.min.js:2:33214
c @ jitsi_external_api.min.js:2
jitsi_external_api.min.js:2 Failed to parse URL parameter value: Sleuth SyntaxError: Unexpected token S in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.t.parse (jitsi_external_api.min.js:2:21554)
    at jitsi_external_api.min.js:2:8223
    at Array.forEach (<anonymous>)
    at jitsi_external_api.min.js:2:8030
    at Object.754 (jitsi_external_api.min.js:2:8324)
    at n (jitsi_external_api.min.js:2:32954)
    at Object.872 (jitsi_external_api.min.js:2:21029)
    at n (jitsi_external_api.min.js:2:32954)
    at jitsi_external_api.min.js:2:33214
c @ jitsi_external_api.min.js:2
jitsi_external_api.min.js:2 Failed to parse URL parameter value: https%3A%2F%2Fmatrix.rexrobotics.org%2F_matrix%2Fmedia%2Fr0%2Fdownload%2Frexrobotics.org%2FaMRiSWtrcxRFEgqhOQKFJZDx SyntaxError: Unexpected token h in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.t.parse (jitsi_external_api.min.js:2:21554)
    at jitsi_external_api.min.js:2:8223
    at Array.forEach (<anonymous>)
    at jitsi_external_api.min.js:2:8030
    at Object.754 (jitsi_external_api.min.js:2:8324)
    at n (jitsi_external_api.min.js:2:32954)
    at Object.872 (jitsi_external_api.min.js:2:21029)
    at n (jitsi_external_api.min.js:2:32954)
    at jitsi_external_api.min.js:2:33214
c @ jitsi_external_api.min.js:2
jitsi_external_api.min.js:2 Failed to parse URL parameter value: %40sleuth%3Arexrobotics.org SyntaxError: Unexpected token @ in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.t.parse (jitsi_external_api.min.js:2:21554)
    at jitsi_external_api.min.js:2:8223
    at Array.forEach (<anonymous>)
    at jitsi_external_api.min.js:2:8030
    at Object.754 (jitsi_external_api.min.js:2:8324)
    at n (jitsi_external_api.min.js:2:32954)
    at Object.872 (jitsi_external_api.min.js:2:21029)
    at n (jitsi_external_api.min.js:2:32954)
    at jitsi_external_api.min.js:2:33214
c @ jitsi_external_api.min.js:2
jitsi_external_api.min.js:2 Failed to parse URL parameter value: !NfCMBjikwOKUtmmwSh%3Arexrobotics.org SyntaxError: Unexpected token ! in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.t.parse (jitsi_external_api.min.js:2:21554)
    at jitsi_external_api.min.js:2:8223
    at Array.forEach (<anonymous>)
    at jitsi_external_api.min.js:2:8030
    at Object.754 (jitsi_external_api.min.js:2:8324)
    at n (jitsi_external_api.min.js:2:32954)
    at Object.872 (jitsi_external_api.min.js:2:21029)
    at n (jitsi_external_api.min.js:2:32954)
    at jitsi_external_api.min.js:2:33214
c @ jitsi_external_api.min.js:2
jitsi_external_api.min.js:2 Failed to parse URL parameter value: dark SyntaxError: Unexpected token d in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.t.parse (jitsi_external_api.min.js:2:21554)
    at jitsi_external_api.min.js:2:8223
    at Array.forEach (<anonymous>)
    at jitsi_external_api.min.js:2:8030
    at Object.754 (jitsi_external_api.min.js:2:8324)
    at n (jitsi_external_api.min.js:2:32954)
    at Object.872 (jitsi_external_api.min.js:2:21029)
    at n (jitsi_external_api.min.js:2:32954)
    at jitsi_external_api.min.js:2:33214
c @ jitsi_external_api.min.js:2
jitsi_external_api.min.js:2 Failed to parse URL parameter value: $roomName SyntaxError: Unexpected token $ in JSON at position 0
    at JSON.parse (<anonymous>)
    at Object.t.parse (jitsi_external_api.min.js:2:21554)
    at jitsi_external_api.min.js:2:8223
    at Array.forEach (<anonymous>)
    at jitsi_external_api.min.js:2:8030
    at Object.754 (jitsi_external_api.min.js:2:8324)
    at n (jitsi_external_api.min.js:2:32954)
    at Object.872 (jitsi_external_api.min.js:2:21029)
    at n (jitsi_external_api.min.js:2:32954)
    at jitsi_external_api.min.js:2:33214
c @ jitsi_external_api.min.js:2
PostmessageTransport.js:93 [PostmessageTransport] Sending object to vector://vector:  Object
://vector/config.vector.json?cachebuster=1648867834557:1          Failed to load resource: net::ERR_FILE_NOT_FOUND
://vector/config.json?cachebuster=1648867834558:1          Failed to load resource: net::ERR_FILE_NOT_FOUN
```
