### ISSUE TITLE
Can't add notification keyword with a leading dot

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21679]
### Steps to reproduce

1. Go to settings > notifications
2. Add `...push complete` as a notification keyword
3. Hit save

#### What did you expect?

For the keyword to be added

#### What happened instead?

A dialog said "An error occurred whilst saving your notification preferences."

This is due to synapse failing on that API call

```
rageshake.ts:72 Error updating keyword push rules: M_UNKNOWN: cannot add new rule_ids that start with '.'
    at parseErrorResponse (vector://vector/webapp/bundles/ea4a579e03f118a31be5/init.js:56168:13)
    at vector://vector/webapp/bundles/ea4a579e03f118a31be5/init.js:56118:17
    at Object.callback (vector://vector/webapp/bundles/ea4a579e03f118a31be5/init.js:56042:9)
    at on_end (vector://vector/webapp/bundles/ea4a579e03f118a31be5/vendors~init.js:209405:13)
    at XMLHttpRequest.on_state_change (vector://vector/webapp/bundles/ea4a579e03f118a31be5/vendors~init.js:209355:7)
    at XMLHttpRequest.<anonymous> (vector://vector/webapp/bundles/ea4a579e03f118a31be5/vendors~init.js:129739:41)
```

#### What to do?

If we can't technically allow a rule that starts with a dot, we should do client side validation to ensure that we prevent people from adding those keywords

If we end up going the client side validation rule, I believe we should inspect the implementation on synapse's side to cater for all failing use cases, and not only the leading dot

### Will you send logs?

No

**Comment by dbkr** [comment]
This probably just needs us to sanitise the pattern (ie. remove the leading '.'s) before passing it as the rule ID

**Comment by gsouquet** [comment]
I personally would like to have a notification that starts with a dot, in a room i'm a member of I'd like to be notified when the automatic event says `...Push complete!`

**Comment by bolu-tife** [comment]
I have worked on this issue and the keyword tags allow dots.
