### ISSUE TITLE
Notification panel not loading

### ISSUE THREAD

**Issue by gsouquet** [vector-im/element-web#21704]
### Steps to reproduce

1. Open notification panel

#### What did you expect?

To see my notifications

#### What happened instead?

Infinite spinner

```
TypeError: Cannot read properties of null (reading 'eventShouldLiveIn')
    at ://vector/webapp/bundles/c479161cb1670673e417/init.js:21132:18
    at Array.reduce (<anonymous>)
    at MatrixClient.partitionThreadedEvents (://vector/webapp/bundles/c479161cb1670673e417/init.js:21127:21)
    at ://vector/webapp/bundles/c479161cb1670673e417/init.js:17786:55
    at async Promise.all (://vector/webapp/index 0)
    at async ScrollPanel.checkFillState
```

### Will you send logs?

No

**Comment by bbhtt** [comment]
Saw it today on develop.element.io (Element version: cec31d0e714e-react-233278546bda-js-dde4285cdf5f
Olm version: 3.2.8) but a different debug logs. Maybe same issue?

```
E can't access property "partitionThreadedEvents", timelineSet.room is null
paginateEventTimeline/promise<@https://develop.element.io/bundles/e37fe6d2bc28222c285c/init.js:17906:50
promise callback*paginateEventTimeline@https://develop.element.io/bundles/e37fe6d2bc28222c285c/init.js:17892:106
paginate@https://develop.element.io/bundles/e37fe6d2bc28222c285c/init.js:88791:30
TimelinePanel_TimelinePanel/<@https://develop.element.io/bundles/e37fe6d2bc28222c285c/element-web-app.js:23253:31
TimelinePanel_TimelinePanel/<@https://develop.element.io/bundles/e37fe6d2bc28222c285c/element-web-app.js:23285:19
maybeFill/<@https://develop.element.io/bundles/e37fe6d2bc28222c285c/init.js:82720:25
promise callback*maybeFill@https://develop.element.io/bundles/e37fe6d2bc28222c285c/init.js:82719:59
ScrollPanel/<@https://develop.element.io/bundles/e37fe6d2bc28222c285c/init.js:82358:33
ScrollPanel/<@https://develop.element.io/bundles/e37fe6d2bc28222c285c/init.js:82387:15
async*ScrollPanel/<@https://develop.element.io/bundles/e37fe6d2bc28222c285c/init.js:82275:13
componentDidMount@https://develop.element.io/bundles/e37fe6d2bc28222c285c/init.js:82578:10
Yi@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59354:411
dk@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59394:160
exports.unstable_runWithPriority@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59499:343
gg@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59257:325
Uj@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59387:281
Lj@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59378:373
jg/<@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59258:115
exports.unstable_runWithPriority@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59499:343
gg@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59257:325
jg@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59258:63
ig@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59257:428
Jg@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59372:203
enqueueSetState@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59268:213
C.prototype.setState@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59451:369
onLoaded@https://develop.element.io/bundles/e37fe6d2bc28222c285c/element-web-app.js:24134:12
promise callback*loadTimeline@https://develop.element.io/bundles/e37fe6d2bc28222c285c/element-web-app.js:24240:12
initTimeline@https://develop.element.io/bundles/e37fe6d2bc28222c285c/element-web-app.js:24098:17
UNSAFE_componentWillMount@https://develop.element.io/bundles/e37fe6d2bc28222c285c/element-web-app.js:23937:10
Og@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59273:128
pi@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59316:156
ck@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59404:427
bk@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59385:349
ak@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59385:280
Tj@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59385:138
Lj@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59378:163
jg/<@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59258:115
exports.unstable_runWithPriority@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59499:343
gg@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59257:325
jg@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59258:63
ig@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59257:428
Hb@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59427:101
gd@https://develop.element.io/bundles/e37fe6d2bc28222c285c/vendors~init.js:59208:354
```
