### ISSUE TITLE
Element randomly closes shows trap int3 in journal log

### ISSUE THREAD

**Issue by konomikitten** [vector-im/element-web#21974]
### Steps to reproduce

When using Element the will randomly close checking the systemd journal log shows the following errors:

```
Apr 28 14:41:19 debian kernel: traps: element-desktop[5332] trap int3 ip:5613988af889 sp:7ffd392945c0 error:0 in element-desktop (deleted)[56139845d000+6af0000]
Apr 28 14:48:01 debian kernel: traps: element-desktop[2978235] trap int3 ip:558a70042173 sp:7ffd64c15a80 error:0 in element-desktop[558a6d011000+6af0000]
Apr 28 16:49:30 debian kernel: traps: element-desktop[2979339] trap int3 ip:558bc35d2173 sp:7ffdf03792b0 error:0 in element-desktop[558bc05a1000+6af0000]
```

#### What did you expect?
Client to not random crash.

#### What happened instead?
Client randomly crashes.

### Operating system

Debian Unstable

### Application version

Element version: 1.10.11 Olm version: 3.2.8

### How did you install the app?

https://element.io/get-started#linux-details

### Will you send logs?

No

**Comment by andybalaam** [comment]
@konomikitten If it happens again, please can you send logs afterwards? That will help us find out why it happened.

**Comment by konomikitten** [comment]
@andybalaam I generated a rage shake and looked through the logs and the logs around the time of the crash abruptly end with `2022-04-28T06:49:08.472Z I Currently showing toasts for: `

log-3.log
```
2022-04-28T06:49:08.451Z I Old unverified sessions: 
2022-04-28T06:49:08.451Z I New unverified sessions: 
2022-04-28T06:49:08.451Z I Currently showing toasts for: 
2022-04-28T06:49:08.461Z I Checking key backup status...
2022-04-28T06:49:08.472Z I Old unverified sessions: 
2022-04-28T06:49:08.472Z I New unverified sessions: 
2022-04-28T06:49:08.472Z I Currently showing toasts for: 
```

I'm sending in a rage shake with this issue as a link but I don't think it will be helpful.

**Comment by konomikitten** [comment]
Crashed again sending another rage shake.

dmesg UTC
```
[Fri Apr 29 04:07:28 2022] traps: element-desktop[3088545] trap int3 ip:55af97646173 sp:7ffd37dbcfb0 error:0 in element-desktop[55af94615000+6af0000]
```

**Comment by konomikitten** [comment]
Its happening when I click the activate button on a notification same as what another person reported in #20926... Quoting them:

> I am able to repro the libnotify crash by simply clicking a notification which is supposed to open the room with that new message.

I originally posted in that thread when I found one of the posts talking about int3 but was instead told to create this issue instead.

**Comment by t3chguy** [comment]
Related https://github.com/vector-im/element-web/issues/19240 https://github.com/vector-im/element-web/issues/8279 https://github.com/vector-im/element-web/issues/5315

@konomikitten can you try reproduce whilst running element desktop from a terminal to get the STDOUT?

Thanks

**Comment by konomikitten** [comment]
@t3chguy is there something I need to run for the logs to be useful they don't seem very useful?

```text
$ element-desktop 
/home/debian/.config/Element exists: yes
/home/debian/.config/Riot exists: no
xdg-settings: default-url-scheme-handler not implemented for xfce
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
Could not fetch translation json for locale: 'en' Error: Cannot find module './i18n/strings/en.json'
Require stack:
- /opt/Element/resources/app.asar/lib/language-helper.js
- /opt/Element/resources/app.asar/lib/tray.js
- /opt/Element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at AppLocalization.fetchTranslationJson (/opt/Element/resources/app.asar/lib/language-helper.js:76:20)
    at /opt/Element/resources/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element/resources/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element/resources/app.asar/lib/language-helper.js',
    '/opt/Element/resources/app.asar/lib/tray.js',
    '/opt/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
Resetting the UI components after locale change
[3516327:0429/193631.040473:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Changing application language to en
Fetching translation json for locale: en
Could not fetch translation json for locale: 'en' Error: Cannot find module './i18n/strings/en.json'
Require stack:
- /opt/Element/resources/app.asar/lib/language-helper.js
- /opt/Element/resources/app.asar/lib/tray.js
- /opt/Element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at AppLocalization.fetchTranslationJson (/opt/Element/resources/app.asar/lib/language-helper.js:76:20)
    at /opt/Element/resources/app.asar/lib/language-helper.js:89:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element/resources/app.asar/lib/language-helper.js:88:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element/resources/app.asar/lib/language-helper.js',
    '/opt/Element/resources/app.asar/lib/tray.js',
    '/opt/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
Trace/breakpoint trap
bash ~
$
```

**Comment by konomikitten** [comment]
I'm closing this in favour of issue #21996 which describes the bug better than my report does.

**Comment by cedricbonhomme** [comment]
I have the same issue with element-desktop. Just installed it today on Ubuntu.
Element closes randomly, not with libnotify notifications.

I will now provide logs just for your information.

Below is the final output of strace:

```bash
sendto(77, "p\0\0\0\20\0\1\0\0\0\0\0\0\0\0\0\5\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 112, MSG_NOSIGNAL, NULL, 0) = 112
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=43, events=POLLIN}, {fd=44, events=POLLIN}, {fd=82, events=POLLIN}], 5, 0) = 0 (Timeout)
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=43, events=POLLIN}, {fd=44, events=POLLIN}, {fd=82, events=POLLIN}], 5, 785) = 1 ([{fd=12, revents=POLLIN}])
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
read(12, "!", 2)                        = 1
sendto(77, "p\0\0\0\20\0\1\0\0\0\0\0\0\0\0\0\5\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 112, MSG_NOSIGNAL, NULL, 0) = 112
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=43, events=POLLIN}, {fd=44, events=POLLIN}, {fd=82, events=POLLIN}], 5, 0) = 0 (Timeout)
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=43, events=POLLIN}, {fd=44, events=POLLIN}, {fd=82, events=POLLIN}], 5, 533) = 1 ([{fd=12, revents=POLLIN}])
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
read(12, "!", 2)                        = 1
sendto(77, "p\0\0\0\20\0\1\0\0\0\0\0\0\0\0\0\5\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 112, MSG_NOSIGNAL, NULL, 0) = 112
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=43, events=POLLIN}, {fd=44, events=POLLIN}, {fd=82, events=POLLIN}], 5, 0) = 0 (Timeout)
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=43, events=POLLIN}, {fd=44, events=POLLIN}, {fd=82, events=POLLIN}], 5, 281) = 1 ([{fd=12, revents=POLLIN}])
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
read(12, "!", 2)                        = 1
sendto(77, "p\0\0\0\20\0\1\0\0\0\0\0\0\0\0\0\5\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 112, MSG_NOSIGNAL, NULL, 0) = 112
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=43, events=POLLIN}, {fd=44, events=POLLIN}, {fd=82, events=POLLIN}], 5, 0) = 0 (Timeout)
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
recvmsg(44, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=43, events=POLLIN}, {fd=44, events=POLLIN}, {fd=82, events=POLLIN}], 5, 30) = 0 (Timeout)
recvmsg(43, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
madvise(0x2cc0466c000, 16384, MADV_DONTNEED) = 0
madvise(0x2cc01cd8000, 16384, MADV_DONTNEED) = 0
madvise(0x2cc04688000, 28672, MADV_DONTNEED) = 0
madvise(0x2cc04680000, 16384, MADV_DONTNEED) = 0
madvise(0x2cc05674000, 49152, MADV_DONTNEED) = 0
madvise(0x2cc050e4000, 16384, MADV_DONTNEED) = 0
madvise(0x2cc04670000, 16384, MADV_DONTNEED) = 0
madvise(0x2cc036d4000, 81920, MADV_DONTNEED) = 0
madvise(0x2cc05154000, 16384, MADV_DONTNEED) = 0
madvise(0x2cc02b14000, 16384, MADV_DONTNEED) = 0
madvise(0x2cc0074c000, 32768, MADV_DONTNEED) = 0
madvise(0x2cc010cc000, 524288, MADV_DONTNEED) = 0
madvise(0x2cc05e68000, 262144, MADV_DONTNEED) = 0
madvise(0x2cc01c0c000, 131072, MADV_DONTNEED) = 0
madvise(0x2cc05e48000, 131072, MADV_DONTNEED) = 0
madvise(0x2cc05f68000, 262144, MADV_DONTNEED) = 0
madvise(0x2cc05f28000, 131072, MADV_DONTNEED) = 0
madvise(0x2cc056f0000, 65536, MADV_DONTNEED) = 0
madvise(0x2cc05700000, 65536, MADV_DONTNEED) = 0
madvise(0x2cc05148000, 16384, MADV_DONTNEED) = 0
madvise(0x2cc0479c000, 61440, MADV_DONTNEED) = -1 EINVAL (Invalid argument)
--- SIGTRAP {si_signo=SIGTRAP, si_code=SI_KERNEL} ---
+++ killed by SIGTRAP (core dumped) +++
```

From the console where I executed Element:

```bash
cedric@kubuntu:~$ element-desktop 
/home/cedric/.config/Element exists: yes
/home/cedric/.config/Riot exists: no
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Resetting the UI components after locale change
[31054:0525/142754.232579:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
Changing application language to en-us
Fetching translation json for locale: en-us
Resetting the UI components after locale change
Trace/breakpoint trap (core dumped)
```

In syslog:

```bash
May 25 14:25:35 kubuntu kernel: [25012.707075] traps: element-desktop[30356] trap int3 ip:55d89b2739e2 sp:7ffcd479ad80 error:0 in element-desktop[55d898243000+6aee000]

```

**Comment by siddhpant** [comment]
I just encountered this.

```
[21600.265543] traps: element-desktop[9743] trap int3 ip:55bc7dae105f sp:7ffe7a613570 error:0 in element-desktop[55bc7a2f0000+75ea000]
```

Version info:

- Element version: 1.11.17
- Olm version: 3.2.12
- 6.0.0-6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1 (2022-12-09) x86_64 GNU/Linux
