### ISSUE TITLE
Sending of Messages not possible - but Mobil Client Android / iOS works fine 

### ISSUE THREAD

**Issue by DerHaber** [vector-im/element-web#22012]
### Steps to reproduce

After typing an message and try to send, some secounds later it is shown, that this message could not be sended.

![image](https://user-images.githubusercontent.com/104765537/166223346-5cf7437c-0056-487d-bcbc-8b4f596dc691.png)

Using my Mobil Android App, sending and reciving works fine.

### Operating system

Windows

### Application version

1.10.11

### Homeserver

Synapse

### Will you send logs?

Yes

**Comment by DerHaber** [comment]
A log from the CLient. Servername replaced with 'xxx'

2022-05-02T10:35:59.785Z I PUT /sendToDevice/m.room.encrypted/m1651487759785.14 {"@b-lem:matrix.xxx.de":["VXELLMCOFE","XHGGTSGDTO","AMARLLIMJE"],"@m-hab:matrix.xxx.de":["VPCYPLROTM","SSRSUEFCTI","SWGPYFHJTY","NEWPVSJZSW","FFBDVDVBJY","LREEMGHEWO","ESHKFXBYZT","OWABHSUIAN","GFSKDDIPKJ"]}
2022-05-02T10:35:59.792Z E Failed to share megolm keys for 8s6uztic0ACn3D4YXFt5AYECM7zL7JvTq4miMiu6Ol4 in !sEiTdaMeEbvyJswSpu:matrix.xxx.de (slice 1/1)
2022-05-02T10:35:59.793Z E Failed to ensure outbound session in !sEiTdaMeEbvyJswSpu:matrix.xxx.de request failed: CORS request rejected: https://matrix.xxx.de/_matrix/client/r0/sendToDevice/m.room.encrypted/m1651487759785.14
ConnectionError: request failed: CORS request rejected: https://matrix.xxx.de/_matrix/client/r0/sendToDevice/m.room.encrypted/m1651487759785.14
    at vector://vector/webapp/bundles/21ed71297f175e2d4e03/vendors~init.js:2:793665
    at Object.callback (vector://vector/webapp/bundles/21ed71297f175e2d4e03/vendors~init.js:2:793285)
    at u (vector://vector/webapp/bundles/21ed71297f175e2d4e03/vendors~init.js:2:12111)
    at XMLHttpRequest.i.onreadystatechange (vector://vector/webapp/bundles/21ed71297f175e2d4e03/vendors~init.js:2:11541)
2022-05-02T10:35:59.793Z E Failed to prepare to encrypt events for !sEiTdaMeEbvyJswSpu:matrix.xxx.de request failed: CORS request rejected: https://matrix.xxx.de/_matrix/client/r0/sendToDevice/m.room.encrypted/m1651487759785.14
ConnectionError: request failed: CORS request rejected: https://matrix.xxx.de/_matrix/client/r0/sendToDevice/m.room.encrypted/m1651487759785.14
    at vector://vector/webapp/bundles/21ed71297f175e2d4e03/vendors~init.js:2:793665
    at Object.callback (vector://vector/webapp/bundles/21ed71297f175e2d4e03/vendors~init.js:2:793285)
    at u (vector://vector/webapp/bundles/21ed71297f175e2d4e03/vendors~init.js:2:12111)
    at XMLHttpRequest.i.onreadystatechange (vector://vector/webapp/bundles/21ed71297f175e2d4e03/vendors~init.js:2:11541)
2022-05-02T10:36:00.850Z I sendEvent of type m.room.message in !sEiTdaMeEbvyJswSpu:matrix.xxx.de with txnId m1651487760849.15
2022-05-02T10:36:00.850Z W Setting event as NOT_SENT due to messages in the same state
2022-05-02T10:36:08.673Z I Starting load of AsyncWrapper for modal
2022-05-02T10:36:12.330Z I Starting load of AsyncWrapper for modal
2022-05-02T10:36:46.676Z I Sending bug report.

**Comment by duxovni** [comment]
matrix-org/element-web-rageshakes#12612

**Comment by DerHaber** [comment]
I don't understand, what to do. On Friday everything wiorks fine. On Monday nothing.

**Comment by duxovni** [comment]
My first guess is some sort of communication issue between your browser and the homeserver. It looks like your browser is sending CORS requests to the server, and not getting responses. Your homeserver seems to be responding to CORS requests right now with no issues; is this still happening, even after a refresh?

**Comment by DerHaber** [comment]
We are using the Element Desktop App, this happens from every Windows PC from Today :(
