### ISSUE TITLE
Reports of soft-crash around reading `parent` of undefined

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#22175]
```
2022-05-12T05:27:22.207Z E Cannot read properties of undefined (reading 'parent')
TypeError: Cannot read properties of undefined (reading 'parent')
    at He.readReceiptPosition (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~element-web-app.js:2:1042078)
    at He.animateMarker (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~element-web-app.js:2:1042303)
    at He.componentDidMount (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~element-web-app.js:2:1041307)
    at hs (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:3063847)
    at Cl (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:3080905)
    at t.unstable_runWithPriority (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:3106190)
    at zi (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:3022782)
    at Fl (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:3077450)
    at hl (vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:3073561)
    at vector://vector/webapp/bundles/0dfc1e1dd51d68d7008e/vendors~init.js:2:3023005
```

**Comment by t3chguy** [comment]
Lots of 

```
2022-05-12T21:33:15.758Z W ReadReceiptMarker for @<redacted> has no valid horizontalContainer
2022-05-12T21:33:15.763Z W ReadReceiptMarker for @<redacted> has no valid horizontalContainer
2022-05-12T21:33:15.772Z W ReadReceiptMarker for @<redacted> has no valid horizontalContainer
2022-05-12T21:33:15.774Z W ReadReceiptMarker for @<redacted> has no valid horizontalContainer
```
