### ISSUE TITLE
Edited message in thread with reaction throws error: `Can't load this message (m.room.message)` - `Cannot read properties of null (reading 'getMyMembership')`

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#22195]
### Steps to reproduce

 1. Start a thread
 1. Add some thread replies
 1. React to one of the replies
 1. Edit the reply you reacted to
 1. Clear cache and refresh
 1. Notice the thread now has a `Can't load this message (m.room.message)`, `Submit logs` (tile error boundary) for the message in question
 
 ```
react_devtools_backend.js:3973 TypeError: Cannot read properties of null (reading 'getMyMembership')
    at ReactionsRow_ReactionsRow.render (ReactionsRow.tsx:170:32)
    at qi (react-dom.production.min.js:187:125)
    at pi (react-dom.production.min.js:186:166)
    at ck (react-dom.production.min.js:269:357)
    at bk (react-dom.production.min.js:250:341)
    at ak (react-dom.production.min.js:250:277)
    at Tj (react-dom.production.min.js:250:138)
    at Lj (react-dom.production.min.js:243:146)
    at react-dom.production.min.js:123:110
    at push.exports.unstable_runWithPriority (scheduler.production.min.js:18:336)
    at gg (react-dom.production.min.js:122:318)
    at jg (react-dom.production.min.js:123:61)
    at ig (react-dom.production.min.js:122:428)
    at Jg (react-dom.production.min.js:237:147)
    at Object.enqueueSetState (react-dom.production.min.js:133:211)
    at TimelinePanel_TimelinePanel.push.C.setState (react.production.min.js:12:356)
    at onLoaded (TimelinePanel.tsx:1279:18)
```

(*spawned from https://github.com/vector-im/element-web/issues/22157#issuecomment-1124338375*)

#### What did you expect?

Message with reaction would load

#### What happened instead?

The tile error boundary was shown in place of the message: `Can't load this message (m.room.message)`, `Submit logs`

### Operating system

Windows 10

### Browser information

Chrome Version 101.0.4951.64

### URL for webapp

https://develop.element.io/

### Application version

Element version: 479d4bf-react-5348572439be-js-4d4d6e1411b6 Olm version: 3.2.8

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
Nothing in that stack says anything relating to threads, what makes you so sure for A-Threads?

**Comment by MadLittleMods** [comment]
@t3chguy That's where it was reproduced. I don't know if the root cause is related to threads.

**Comment by t3chguy** [comment]
Same cause as https://github.com/vector-im/element-web/issues/22141 - missing `room` object in store
