### ISSUE TITLE
Stuck on semi unread (muted/events)

### ISSUE THREAD

**Issue by chagai95** [vector-im/element-web#22296]
### Steps to reproduce

1. Not sure, might be related to virtual rooms.
2. Click on the semi unread icon:

![image](https://user-images.githubusercontent.com/31655082/169551933-48b010c1-65ad-4474-99c0-2a911e69ab0c.png)
Here is a video showing the problem:
https://aarenet-my.sharepoint.com/:v:/p/chagai_friedlander/EczaQkfh0PRFp6QYrHQX-OQBLrX0Td2UU7MQEQ5budxUHQ

#### What did you expect?
To go to the semi unread room
#### What happened instead?
I get this error in the console:
```
MatrixChat.tsx:900 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '0')
    at MatrixChat.viewRoom (MatrixChat.tsx:900:40)
    at Object.ID_36 (MatrixChat.tsx:659:38)
    at MatrixDispatcher._invokeCallback (Dispatcher.js:198:1)
    at MatrixDispatcher.dispatch (Dispatcher.js:174:1)
```

seems like there is no room id in the room info [here](https://github.com/matrix-org/matrix-react-sdk/blob/025fb631b7ffd7a870f2e2aaebeb5a46edfef375/src/components/structures/MatrixChat.tsx#L876) which is why it then throws the error [here](https://github.com/matrix-org/matrix-react-sdk/blob/025fb631b7ffd7a870f2e2aaebeb5a46edfef375/src/components/structures/MatrixChat.tsx#L900)

### Operating system

Windows

### Browser information

Version 100.0.4896.127 (Official Build) (64-bit)

### URL for webapp

https://develop.element.io

### Application version

Develop branch

### Homeserver

private server

### Will you send logs?

No

**Comment by SimonBrandner** [comment]
Something weird is happening either in https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/stores/spaces/SpaceStore.ts#L177 or in https://github.com/matrix-org/matrix-react-sdk/blob/develop/src/components/views/spaces/SpaceTreeLevel.tsx#L87
