### ISSUE TITLE
Problem Connecting to matrix.org 

### ISSUE THREAD

**Issue by Johnnyreyman** [vector-im/element-web#22493]
### Steps to reproduce

I open the app and try to sign in. It will not let me sign in with matrix.org as the homeserver. This is both on the community port and the Flatpak.

### What should have happened?
I should be able to sign into element-desktop

#### What happened instead?
I get an error when trying to connect with matrix.org.
Error:
`There was a problem communicating with the homeserver, please try again later.`

### Operating system

Arch Linux

### Application version

Element version 1.10.14

### How did you install the app?

Flathub

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by weeman1337** [comment]
Hi @Johnnyreyman thank you for opening this issue.

Can you have a look at the console if there are any errors and post them here?  
You can open the console by pressing `Ctrl + Shift + i`.

Double-check that you don't send sensitive information!

**Comment by Johnnyreyman** [comment]
Console output: (Error that keeps repeating)
```
index.js:218          GET https://matrix-client.matrix.org/_matrix/client/versions net::ERR_NETWORK_CHANGED
(anonymous) @ index.js:218
t @ index.js:179
(anonymous) @ browser-index.js:34
doRequest @ http-api.ts:849
requestOtherUrl @ http-api.ts:724
request @ http-api.ts:676
pokeKeepAlive @ sync.ts:1430
setTimeout (async)
startKeepAlives @ sync.ts:1402
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
doSync @ sync.ts:866
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
rageshake.ts:73 MatrixClient sync state => CATCHUP
rageshake.ts:73 /sync error ConnectionError: request failed: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/r0/sync?filter=%7B%7D&timeout=0&since=s3011043940_757284974_8577320_1401197515_1421837692_3317160_506862112_4020072514_0
    at vector://vector/webapp/bundles/d9fcc3c3b96b27cefb1d/vendors~init.js:2:874245
    at Object.callback (vector://vector/webapp/bundles/d9fcc3c3b96b27cefb1d/vendors~init.js:2:873865)
    at u (vector://vector/webapp/bundles/d9fcc3c3b96b27cefb1d/vendors~init.js:2:12195)
    at XMLHttpRequest.i.onreadystatechange (vector://vector/webapp/bundles/d9fcc3c3b96b27cefb1d/vendors~init.js:2:11625)
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:50
onSyncError @ sync.ts:941
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
doSync @ sync.ts:866
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
rageshake.ts:73 ConnectionError: request failed: CORS request rejected: https://matrix-client.matrix.org/_matrix/client/r0/sync?filter=%7B%7D&timeout=0&since=s3011043940_757284974_8577320_1401197515_1421837692_3317160_506862112_4020072514_0
    at http-api.ts:946:23
    at Object.callback (http-api.ts:872:21)
    at u (index.js:266:22)
    at XMLHttpRequest.i.onreadystatechange (index.js:242:7)
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:50
onSyncError @ sync.ts:942
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
doSync @ sync.ts:866
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
Promise.then (async)
onSyncError @ sync.ts:959
doSync @ sync.ts:792
await in doSync (async)
(anonymous) @ sync.ts:971
rageshake.ts:73 Number of consecutive failed sync requests: 10
rageshake.ts:73 Starting keep-alive
rageshake.ts:73 MatrixClient sync state => ERROR

```

**Comment by turt2live** [comment]
Looks like your network adapter changed. 

Unfortunately this is not an issue we can fix.

**Comment by Johnnyreyman** [comment]
How do I bypass the error then? I have tried reinstalling the app from the flatpak, arch repos and AUR. I cannot find a way to fix this. Also got a new error:
![image](https://user-images.githubusercontent.com/31798114/173496796-29a60e3b-0129-4527-b444-41a3e75a179a.png)

**Comment by Johnnyreyman** [comment]
That is from the AUR version.

**Comment by turt2live** [comment]
The error looks like it's related to your network configuration in some way - this is not something we can bypass or provide support for, sorry.

**Comment by Johnnyreyman** [comment]
Any links or suggestions for errors with this on arch? I have basically exhausted every avenue except a full reinstall.

**Comment by Johnnyreyman** [comment]
I have no issues with any other devices in my network.

**Comment by turt2live** [comment]
[#element-web:matrix.org](https://matrix.to/#/#element-web:matrix.org) on Matrix might be able to help. We cannot provide operating system level support ourselves, however.
