### ISSUE TITLE
Import Cycle: Lifecycle through to ReadyWatchingStore

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22594]
```
      at new ReadyWatchingStore (src/stores/ReadyWatchingStore.ts:36:29)
      at new <anonymous> (src/stores/AsyncStoreWithClient.ts:32:32)
      at new AsyncStoreWithClient (src/stores/AsyncStoreWithClient.ts:32:27)
      at new MessagePreviewStore (src/stores/room-list/MessagePreviewStore.ts:96:9)
      at Object.<anonymous> (src/stores/room-list/MessagePreviewStore.ts:90:39)
      at Object.<anonymous> (src/components/views/rooms/RoomTile.tsx:31:1)
      at Object.<anonymous> (src/components/views/messages/DateSeparator.tsx:31:1)
      at Object.<anonymous> (src/components/views/dialogs/MessageEditHistoryDialog.tsx:32:1)
      at Object.<anonymous> (src/components/views/messages/TextualBody.tsx:42:1)
      at Object.<anonymous> (src/components/views/messages/MessageEvent.tsx:34:1)
      at Object.<anonymous> (src/events/EventTileFactory.tsx:28:1)
      at Object.<anonymous> (src/Unread.ts:23:1)
      at Object.<anonymous> (src/stores/room-list/algorithms/tag-sorting/RecentAlgorithm.ts:24:1)
      at Object.<anonymous> (src/stores/room-list/algorithms/tag-sorting/index.ts:23:1)
      at Object.<anonymous> (src/stores/room-list/algorithms/list-ordering/ImportanceAlgorithm.ts:23:1)
      at Object.<anonymous> (src/stores/room-list/algorithms/list-ordering/index.ts:17:1)
      at Object.<anonymous> (src/stores/room-list/algorithms/Algorithm.ts:36:1)
      at Object.<anonymous> (src/stores/room-list/RoomListStore.ts:31:1)
      at Object.<anonymous> (src/components/views/dialogs/InviteDialog.tsx:42:1)
      at Object.<anonymous> (src/RoomInvite.tsx:28:1)
      at Object.<anonymous> (src/TextForEvent.tsx:35:1)
      at Object.<anonymous> (src/Notifier.ts:30:1)
      at Object.<anonymous> (src/Lifecycle.ts:31:1)
      at Object.<anonymous> (src/modules/ProxiedModuleApi.ts:31:1)
```

We should break the loop at `Notifier` or earlier if we can.

Affects modules work.

**Comment by turt2live** [comment]
this is a complex cycle - have worked around it in other ways (see https://github.com/matrix-org/matrix-react-sdk/pull/8246/commits/d314ad028a0c4abc21edbf5656bb774d1ccae190 )
