### ISSUE TITLE
Soft crash on space panel view (unknown exact cause) - "Something went wrong!" error

### ISSUE THREAD

**Issue by turt2live** [vector-im/element-web#22752]
### Steps to reproduce

Unsure if this actually reproduces it:

1. Browse a space (mentioned in rageshake)
2. Join some subspaces and rooms
3. Crash

It's possible this is also related to a paginated request completing at the same time as the join.

#### What did you expect?

Not to crash

#### What happened instead?

```
2022-07-06T16:21:34.440Z E Caught /sync error Cannot read properties of null (reading 'getJoinedMemberCount')
TypeError: Cannot read properties of null (reading 'getJoinedMemberCount')
    at MatrixClient.updateMetrics (vector://vector/webapp/bundles/d54181b85f77a9f74413/init.js:24889:37)
    at MatrixClient.emit (vector://vector/webapp/bundles/d54181b85f77a9f74413/vendors~init.js:665:7)
    at MatrixClient.emit (vector://vector/webapp/bundles/d54181b85f77a9f74413/init.js:30916:18)
    at vector://vector/webapp/bundles/d54181b85f77a9f74413/init.js:58936:16
    at async Object.promiseMapSeries (vector://vector/webapp/bundles/d54181b85f77a9f74413/bundle.js:1329:5)
    at async SyncApi.processSyncResponse (vector://vector/webapp/bundles/d54181b85f77a9f74413/init.js:58848:5)
    at async SyncApi.doSync (vector://vector/webapp/bundles/d54181b85f77a9f74413/init.js:58510:7)
```
```
2022-07-06T16:21:42.955Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (NotFoundError | 8)
2022-07-06T16:21:42.960Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (NotFoundError | 8)
2022-07-06T16:21:42.960Z E The above error occurred while React was rendering the following components: 
    at div
    at div
    at div
    at AccessibleButton (vector://vector/webapp/bundles/d54181b85f77a9f74413/init.js:3368:5)
    at li
    at Tile (vector://vector/webapp/bundles/d54181b85f77a9f74413/element-web-app.js:35014:5)
    at HierarchyLevel (vector://vector/webapp/bundles/d54181b85f77a9f74413/element-web-app.js:35343:5)
    at ul
    at RovingTabIndexProvider (vector://vector/webapp/bundles/d54181b85f77a9f74413/init.js:26428:5)
    at SpaceHierarchy (vector://vector/webapp/bundles/d54181b85f77a9f74413/element-web-app.js:35565:5)
    at div
    at SpaceLanding (vector://vector/webapp/bundles/d54181b85f77a9f74413/element-web-app.js:35875:5)
    at div
    at MainSplit_MainSplit (vector://vector/webapp/bundles/d54181b85f77a9f74413/element-web-app.js:18948:5)
    at ErrorBoundary (vector://vector/webapp/bundles/d54181b85f77a9f74413/element-web-app.js:63350:5)
    at main
    at SpaceRoomView_SpaceRoomView (vector://vector/webapp/bundles/d54181b85f77a9f74413/element-web-app.js:36266:5)
    at RoomView_RoomView (vector://vector/webapp/bundles/d54181b85f77a9f74413/element-web-app.js:36751:5)
    at vector://vector/webapp/bundles/d54181b85f77a9f74413/init.js:6205:76
    at div
    at div
    at div
    at LoggedInView_LoggedInView (vector://vector/webapp/bundles/d54181b85f77a9f74413/element-web-app.js:39354:5)
    at ErrorBoundary (vector://vector/webapp/bundles/d54181b85f77a9f74413/element-web-app.js:63350:5)
    at MatrixChat (vector://vector/webapp/bundles/d54181b85f77a9f74413/element-web-app.js:849:5)
```
```
{"source":"webpack:///matrix-react-sdk/src/stores/RoomViewStore.tsx","line":216,"column":44,"name":"getJoinedMemberCount"}
```

### Operating system

Windows 10

### Application version

Nightly

### How did you install the app?

The Internet

### Homeserver

t2l.io

### Will you send logs?

Yes

**Comment by Mikaela** [comment]
Coming from #22924, it happened again and as it was closed in favour of this one, I sent logs. I think it may be related to mass clicking join at many rooms in a Space?

**Comment by Zocker1999NET** [comment]
Happens to me as well each time I try to join a room from a space's view, but not when joining sub-spaces. I don't think it comes from mass-joining as I tried to join each room at once without success. Happens to me especially when joining rooms from [#community:matrix.org](https://matrix.to/#/#community:matrix.org) or its sub-spaces.

**Comment by elsandosgrande** [comment]
A few months later, this issue is present on both stable and develop. It's intermittent, meaning that it doesn't happen every time one joins a room, and seems to only be present when joining rooms that are part of a given space, not independent rooms.

I'm not sure if this was mentioned before in the many duplicate tickets, but Element actually successfully joins the room in spite of the soft crash, on both stable and develop, at least on my laptop. In other words, if I click on “Clear cache and reload”, after reloading, the room will be present in the list of rooms in the given space and I can start messaging right away.

Here's my log from a few dozen minutes ago, converted to ZIP for uploading in this comment: [rageshake.zip](https://github.com/vector-im/element-web/files/9683894/rageshake.zip)

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/0d100cbbce0d3ea4b3c8e9503befd1a5837503c2
