### ISSUE TITLE
"Can't load this message" when enabling previews on imgur urls

### ISSUE THREAD

**Issue by HarHarLinks** [vector-im/element-web#22766]
### Steps to reproduce

Send an imgur deeplink such as https://i.imgur.com/PDmdr8v.jpeg with URL previews enabled
![imgur](https://user-images.githubusercontent.com/2803622/177748217-2f4a3583-1d6c-4f12-827a-88fb40d7391f.gif)

#### What did you expect?
show the message content + URL preview
#### What happened instead?
message shows for a split second, but errors once URL preview is requested

### Operating system

arch

### Application version

Element Nightly version: 2022070701 Olm version: 3.2.8

### How did you install the app?

aur

### Will you send logs?

No

**Comment by t3chguy** [comment]
@HarHarLinks please send logs.

**Comment by HarHarLinks** [comment]
done

**Comment by t3chguy** [comment]
```
2022-07-07T10:22:11.126Z E Cannot read properties of undefined (reading 'trim')
TypeError: Cannot read properties of undefined (reading 'trim')
    at LinkPreviewWidget_LinkPreviewWidget.render (vector://vector/webapp/bundles/d58c54b589752dac9a3c/init.js:144964:210)
    at qi (vector://vector/webapp/bundles/d58c54b589752dac9a3c/vendors~init.js:60218:188)
    at pi (vector://vector/webapp/bundles/d58c54b589752dac9a3c/vendors~init.js:60217:173)
    at ck (vector://vector/webapp/bundles/d58c54b589752dac9a3c/vendors~init.js:60300:427)
    at bk (vector://vector/webapp/bundles/d58c54b589752dac9a3c/vendors~init.js:60281:347)
    at ak (vector://vector/webapp/bundles/d58c54b589752dac9a3c/vendors~init.js:60281:278)
    at Tj (vector://vector/webapp/bundles/d58c54b589752dac9a3c/vendors~init.js:60281:138)
    at Lj (vector://vector/webapp/bundles/d58c54b589752dac9a3c/vendors~init.js:60274:163)
    at vector://vector/webapp/bundles/d58c54b589752dac9a3c/vendors~init.js:60154:115
    at push.exports.unstable_runWithPriority (vector://vector/webapp/bundles/d58c54b589752dac9a3c/vendors~init.js:60395:343)

**Comment by t3chguy** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/commit/6f21a155a4009b5aa8ddfe1cc7b397561ae756de
