### ISSUE TITLE
Settings dialog closes when going to "Help & About"

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#22892]
### Steps to reproduce

1. Your avatar -> All settings
2. In the settings dialog, "Help & About"

#### What did you expect?
See "help & about"

#### What happened instead?
Settings dialog closes

### How did you install the app?

Flatpak

### Will you send logs?

No

**Comment by MadLittleMods** [comment]
There is a lot of these errors in your logs:
```
2022-07-19T13:37:10.841Z E Failed to set presence: Invalid Authorization header.
M_MISSING_TOKEN: Invalid Authorization header.
    at w (vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:875615)
    at vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:875018
    at Object.callback (vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:874581)
    at vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:11897
    at i.onreadystatechange (vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:11921)
```

Which looks like it all started at the beginning of your session today. The following is literally the beginning of the logs today and it's already spitting out the error. The other log files are from `2022-02-26` and `2022-01-13` so I assume you don't use this session a lot? Maybe you signed out this device previously which is why the token is invalid? It sounds like Element needs to handle an invalid token better and explain to the user what happened.
```
2022-07-19T13:29:26.875Z I Initialised rageshake.
2022-07-19T13:29:26.875Z I To fix line numbers in Chrome: Meatball menu → Settings → Ignore list → Add /rageshake\.js$
2022-07-19T13:29:26.880Z I Using Electron platform
2022-07-19T13:29:26.889Z I Configuring rageshake persistence...
2022-07-19T13:29:26.905Z I Using WebAssembly Olm
2022-07-19T13:29:26.944Z I set language to en
2022-07-19T13:29:27.309Z I Application is running in production mode
2022-07-19T13:29:27.311Z I Vector starting at vector://vector/webapp/
2022-07-19T13:29:27.311Z I Verifying homeserver configuration
2022-07-19T13:29:27.311Z I Config uses a default_server_name - doing .well-known lookup
2022-07-19T13:29:27.311Z W DEPRECATED CONFIG OPTION: In the future, default_server_name will not be accepted. Please use default_server_config instead.
2022-07-19T13:29:27.627Z I Using homeserver config: {"hsUrl":"https://matrix-client.matrix.org","hsName":"matrix.org","hsNameIsDifferent":true,"isUrl":"https://vector.im","isDefault":true,"isNameResolvable":true,"warning":null}
2022-07-19T13:29:27.628Z I Updating SdkConfig with validated discovery information
2022-07-19T13:29:27.762Z I No pickle key available
2022-07-19T13:29:27.762Z I Restoring session for @kittykat:matrix.org
2022-07-19T13:29:27.762Z I setLoggedIn: mxid: @kittykat:matrix.org deviceId: XXXXXXXXXX guest: false hs: https://matrix-client.matrix.org/ softLogout: false  freshLogin: false
2022-07-19T13:29:27.764Z I StorageManager: Checking storage consistency
2022-07-19T13:29:27.764Z I StorageManager: Local storage supported? true
2022-07-19T13:29:27.764Z I StorageManager: IndexedDB supported? true
2022-07-19T13:29:27.764Z I StorageManager: Local storage contains data? true
2022-07-19T13:29:27.764Z I StorageManager: Crypto initialised? true
2022-07-19T13:29:27.766Z I StorageManager: Sync store using IndexedDB contains data? true
2022-07-19T13:29:27.768Z I StorageManager: Crypto store using IndexedDB contains data? true
2022-07-19T13:29:27.768Z I StorageManager: Storage consistency checks passed
2022-07-19T13:29:27.783Z E Expected a pickle key, but none provided.  Encryption may not work.
2022-07-19T13:29:27.783Z I Session persisted for @kittykat:matrix.org
2022-07-19T13:29:27.783Z I Lifecycle: Starting MatrixClient
2022-07-19T13:29:27.796Z I Switching to room id !scWLPzRfexAhRDBBbc:matrix.org at event undefined
2022-07-19T13:29:27.797Z I StorageManager: Persistent? true
2022-07-19T13:29:27.869Z I Failed to check for protocol support: will retry Invalid Authorization header.
M_MISSING_TOKEN: Invalid Authorization header.
    at w (vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:875615)
    at vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:875018
    at Object.callback (vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:874581)
    at vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:11897
    at i.onreadystatechange (vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:11921)
2022-07-19T13:29:28.086Z I EventIndex: Error initializing the event index {"message":"Error opening the database: DatabaseUnlockError(\"Invalid passphrase\")"}
2022-07-19T13:29:28.087Z I IndexedDBStore.startup: connecting to backend
2022-07-19T13:29:28.087Z I MatrixClientPeg: waiting for MatrixClient store to initialise
2022-07-19T13:29:28.117Z I IndexedDB worker is ready
2022-07-19T13:29:29.757Z I IndexedDBStore.startup: loading presence events
2022-07-19T13:29:29.762Z I IndexedDBStore.startup: processing presence events
2022-07-19T13:29:29.762Z I Crypto: Starting up crypto store...
2022-07-19T13:29:29.763Z I connecting to indexeddb matrix-js-sdk:crypto
2022-07-19T13:29:29.764Z I connected to indexeddb matrix-js-sdk:crypto
2022-07-19T13:29:29.767Z I Crypto: initialising roomlist...
2022-07-19T13:29:29.779Z I Crypto: initialising crypto object...
2022-07-19T13:29:29.780Z I Crypto: initialising Olm...
2022-07-19T13:29:29.780Z I Crypto: initialising Olm device...
2022-07-19T13:29:29.787Z W Unable to initialise e2e OLM.BAD_ACCOUNT_KEY
Error: OLM.BAD_ACCOUNT_KEY
    at vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:2975810
    at Fe.<anonymous> (vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:2978689)
    at Fe.unpickle (vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:2975516)
    at vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:2466528
    at n.onsuccess (vector://vector/webapp/bundles/3021093bbd74213f659a/vendors~init.js:2:3137810)
```

**Comment by kittykat** [comment]
Michael said that there was a problem with accessing my keyring. The fix for this issue would be to handle the errors better.

@MadLittleMods the session was cross-signed but very old, as you noticed. I haven't looked at it in a month or two at this point.

Can I help with any other details?
