### ISSUE TITLE
Timeline won't load more messages - `TypeError: Cannot read properties of null (reading 'getEvents')`

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#22899]
### Steps to reproduce

1. Switch to a room
1. Scroll up and start paginating
1. Get stuck with a loading indicator
   - It was stuck the whole day. Every time I came back it wouldn't get further
1. Eventually pressed the up arrow to view messages and now it has a loading indicator on the bottom
1. Everything is broken now and I see errors in the console

```
TypeError: Cannot read properties of null (reading 'getEvents')
    at TimelineWindow.getEvents (timeline-window.ts:378:37)
    at TimelinePanel_TimelinePanel.getEvents (TimelinePanel.tsx:1412:59)
    at TimelinePanel.tsx:534:73
```

#### What did you expect?

Timeline is able to scrollback and is able to recover.

#### What happened instead?

Timeline broken on both ends.

### Operating system

Windows 10

### Browser information

Chrome Version 103.0.5060.114

### URL for webapp

develop.element.io

### Application version

1519d5672e4c-react-0053f21286e8-js-32bb4b1fc464

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by MadLittleMods** [comment]
Related to https://github.com/vector-im/element-web/issues/18325
