### ISSUE TITLE
Soft crash: Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by t3chguy** [vector-im/element-web#23080]
### Steps to reproduce

Unknown

### Outcome

```
2022-08-15T14:38:29.048Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (NotFoundError | 8)
2022-08-15T14:38:29.050Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (NotFoundError | 8)
2022-08-15T14:38:29.050Z E The above error occurred while React was rendering the following components: 
    at h3
    at div
    at div
    at vc (https://app.element.io/bundles/4758a480cb8185932b7e/vendors~element-web-app.js:2:625545)
    at g (https://app.element.io/bundles/4758a480cb8185932b7e/vendors~element-web-app.js:2:1128711)
    at div
    at dm (https://app.element.io/bundles/4758a480cb8185932b7e/vendors~element-web-app.js:2:718221)
    at https://app.element.io/bundles/4758a480cb8185932b7e/vendors~init.js:2:134590
    at div
    at div
    at div
    at ym (https://app.element.io/bundles/4758a480cb8185932b7e/vendors~element-web-app.js:2:762308)
    at g (https://app.element.io/bundles/4758a480cb8185932b7e/vendors~element-web-app.js:2:1128711)
    at Be (https://app.element.io/bundles/4758a480cb8185932b7e/vendors~element-web-app.js:2:30151)
```

**Comment by t3chguy** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/22752
