### ISSUE TITLE
 Crashes when opening from tray on Wayland #345 

### ISSUE THREAD

**Issue by julianfairfax** [vector-im/element-web#23202]
### Steps to reproduce

1. Run the app on Wayland with `flatpak run im.riot.Riot --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland`
2. Close it to the tray
3. Reopen it

#### What did you expect?
The app to show up

#### What happened instead?
It crashed

Log:
/home/julian/.var/app/im.riot.Riot/config/Element exists: yes
/home/julian/.var/app/im.riot.Riot/config/Riot exists: no
LaunchProcess: failed to execvp:
xdg-settings
[3:0904/015329.899533:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0904/015329.899645:ERROR:bus.cc(398)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en
Fetching translation json for locale: en
[51:0904/015329.960830:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is egl, ANGLE is 
Resetting the UI components after locale change
Resetting the UI components after locale change
[3:0904/015330.078693:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[3:0904/015330.078791:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
[3:0904/015341.056804:ERROR:wayland_event_watcher.cc(36)] libwayland: wl_surface@32: error 0: gtk_shell::get_gtk_surface already requested

/app/bin/element: line 10:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

The opening attempt and crash is:
```
[3:0904/015341.056804:ERROR:wayland_event_watcher.cc(36)] libwayland: wl_surface@32: error 0: gtk_shell::get_gtk_surface already requested

/app/bin/element: line 10:     3 Trace/breakpoint trap   (core dumped) env TMPDIR="$XDG_RUNTIME_DIR/app/${FLATPAK_ID:-im.riot.Riot}" zypak-wrapper /app/Element/element-desktop $FLAGS "$@"
```

### Operating system

Arch Linux, fully up-to-date

### Application version

Element version: 1.11.4 Olm version: 3.2.12

### How did you install the app?

Flatpak

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by julianfairfax** [comment]
https://github.com/flathub/org.signal.Signal/issues/345 might be related. Could this be an Electron issue?

**Comment by SimonBrandner** [comment]
This actually sounds like a potential Flatpak issue - do you have any other Electron Flatpak apps to test with?

**Comment by julianfairfax** [comment]
This is a log from Standard Notes running on Wayland with `flatpak override --user --env=USE_WAYLAND=1 org.standardnotes.standardnotes --socket=wayland`:
```
LaunchProcess: failed to execvp:
xdg-settings
[3:0904/092909.662711:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[3:0904/092909.662765:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
09:29:09.696 › APPIMAGE env is not defined, current application is not an AppImage
extServer: Server started at http://127.0.0.1:45653
[53:0904/092909.750476:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is egl, ANGLE is 
[53:0904/092909.753280:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
[3:0904/092909.827312:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
[3:0904/092909.827375:ERROR:browser_main_loop.cc(267)] Gtk: gtk_widget_get_scale_factor: assertion 'GTK_IS_WIDGET (widget)' failed
09:29:10.149 › APPIMAGE env is not defined, current application is not an AppImage
09:29:10.485 › PackageManager[Info]: received sync event for: Rich Markdown Editor (0.19.0) (deleted: false), TokenVault (2.0.10) (deleted: false), Dracula (2.0.1) (deleted: false)
09:29:10.497 › PackageManager[Info]: Checking for update for Rich Markdown Editor
Latest: 0.19.0 | Installed: 0.19.0
09:29:10.499 › PackageManager[Info]: Checking for update for TokenVault
Latest: 2.0.10 | Installed: 2.0.10
09:29:10.500 › PackageManager[Info]: Checking for update for Dracula
Latest: 2.0.1 | Installed: 2.0.1
[63:0904/092910.622106:ERROR:node_controller.cc(585)] Trying to re-add dropped peer 41D9751174603560.8104F5BC695C77EF
09:29:17.440 › APPIMAGE env is not defined, current application is not an AppImage
[3:0904/092917.448543:ERROR:wayland_event_watcher.cc(292)] Fatal Wayland protocol error 0 on interface wl_surface (object 31). Shutting down..
/app/bin/start-standardnotes: line 17:     3 Trace/breakpoint trap   (core dumped) zypak-wrapper /app/standardnotes/standard-notes --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland $@
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 09:29:18.863: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:29:18.863: Failed to load module "canberra-gtk-module"
[225:0904/092918.880855:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[225:0904/092918.880917:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
09:29:18.924 › APPIMAGE env is not defined, current application is not an AppImage
extServer: Server started at http://127.0.0.1:45653
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[269:0904/092918.983111:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
09:29:19.370 › APPIMAGE env is not defined, current application is not an AppImage
09:29:19.754 › PackageManager[Info]: received sync event for: Rich Markdown Editor (0.19.0) (deleted: false), TokenVault (2.0.10) (deleted: false), Dracula (2.0.1) (deleted: false)
09:29:19.764 › PackageManager[Info]: Checking for update for Rich Markdown Editor
Latest: 0.19.0 | Installed: 0.19.0
09:29:19.767 › PackageManager[Info]: Checking for update for TokenVault
Latest: 2.0.10 | Installed: 2.0.10
09:29:19.768 › PackageManager[Info]: Checking for update for Dracula
Latest: 2.0.1 | Installed: 2.0.1
[269:0904/092921.413025:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
BackupsManager: Data backup successfully saved: 2022-09-04T07-29-21.449Z.txt
```

The reopening takes place here, and is successful:
```
[3:0904/092917.448543:ERROR:wayland_event_watcher.cc(292)] Fatal Wayland protocol error 0 on interface wl_surface (object 31). Shutting down..
/app/bin/start-standardnotes: line 17:     3 Trace/breakpoint trap   (core dumped) zypak-wrapper /app/standardnotes/standard-notes --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland $@
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 09:29:18.863: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:29:18.863: Failed to load module "canberra-gtk-module"
[225:0904/092918.880855:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[225:0904/092918.880917:ERROR:bus.cc(397)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
09:29:18.924 › APPIMAGE env is not defined, current application is not an AppImage
extServer: Server started at http://127.0.0.1:45653
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[269:0904/092918.983111:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.
09:29:19.370 › APPIMAGE env is not defined, current application is not an AppImage
09:29:19.754 › PackageManager[Info]: received sync event for: Rich Markdown Editor (0.19.0) (deleted: false), TokenVault (2.0.10) (deleted: false), Dracula (2.0.1) (deleted: false)
09:29:19.764 › PackageManager[Info]: Checking for update for Rich Markdown Editor
Latest: 0.19.0 | Installed: 0.19.0
09:29:19.767 › PackageManager[Info]: Checking for update for TokenVault
Latest: 2.0.10 | Installed: 2.0.10
09:29:19.768 › PackageManager[Info]: Checking for update for Dracula
Latest: 2.0.1 | Installed: 2.0.1
[269:0904/092921.413025:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
BackupsManager: Data backup successfully saved: 2022-09-04T07-29-21.449Z.txt
```

**Comment by t3chguy** [comment]
> Could this be an Electron issue?

It is either an Electron or a Flatpak issue, given Electron handles all of the tray integration handling.

**Comment by julianfairfax** [comment]
> > Could this be an Electron issue?
> 
> It is either an Electron or a Flatpak issue, given Electron handles all of the tray integration handling.

Well the Standard Notes Flatpak is also Electron and works fine. How can I figure out which is causing issues with Element?

**Comment by t3chguy** [comment]
Try using the official deb release, on a deb env running wayland with no flatpak involved at all

**Comment by julianfairfax** [comment]
> Try using the official deb release, on a deb env running wayland with no flatpak involved at all

Here's the error log from that:
```
element-desktop --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland
/home/martin/.config/Element exists: yes
/home/martin/.config/Riot exists: no
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
[4642:0911/185759.632748:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is egl, ANGLE is 
Fetching translation json for locale: en_EN
Changing application language to en-gb,en
Fetching translation json for locale: en-gb
Could not fetch translation json for locale: 'en-gb' Error: Cannot find module './i18n/strings/en_GB.json'
Require stack:
- /opt/Element/resources/app.asar/lib/language-helper.js
- /opt/Element/resources/app.asar/lib/tray.js
- /opt/Element/resources/app.asar/lib/settings.js
- /opt/Element/resources/app.asar/lib/ipc.js
- /opt/Element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at AppLocalization.fetchTranslationJson (/opt/Element/resources/app.asar/lib/language-helper.js:87:20)
    at /opt/Element/resources/app.asar/lib/language-helper.js:100:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element/resources/app.asar/lib/language-helper.js:99:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element/resources/app.asar/lib/language-helper.js',
    '/opt/Element/resources/app.asar/lib/tray.js',
    '/opt/Element/resources/app.asar/lib/settings.js',
    '/opt/Element/resources/app.asar/lib/ipc.js',
    '/opt/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en-gb,en
Fetching translation json for locale: en-gb
Could not fetch translation json for locale: 'en-gb' Error: Cannot find module './i18n/strings/en_GB.json'
Require stack:
- /opt/Element/resources/app.asar/lib/language-helper.js
- /opt/Element/resources/app.asar/lib/tray.js
- /opt/Element/resources/app.asar/lib/settings.js
- /opt/Element/resources/app.asar/lib/ipc.js
- /opt/Element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at AppLocalization.fetchTranslationJson (/opt/Element/resources/app.asar/lib/language-helper.js:87:20)
    at /opt/Element/resources/app.asar/lib/language-helper.js:100:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element/resources/app.asar/lib/language-helper.js:99:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element/resources/app.asar/lib/language-helper.js',
    '/opt/Element/resources/app.asar/lib/tray.js',
    '/opt/Element/resources/app.asar/lib/settings.js',
    '/opt/Element/resources/app.asar/lib/ipc.js',
    '/opt/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Fetching translation json for locale: en
Resetting the UI components after locale change
[4599:0911/185832.873105:ERROR:wayland_event_watcher.cc(36)] libwayland: wl_surface@32: error 0: gtk_shell::get_gtk_surface already requested

[1]    4599 trace trap  element-desktop --enable-features=UseOzonePlatform,WaylandWindowDecorationselement-desktop --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland
/home/martin/.config/Element exists: yes
/home/martin/.config/Riot exists: no
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
[4642:0911/185759.632748:ERROR:gpu_init.cc(486)] Passthrough is not supported, GL is egl, ANGLE is 
Fetching translation json for locale: en_EN
Changing application language to en-gb,en
Fetching translation json for locale: en-gb
Could not fetch translation json for locale: 'en-gb' Error: Cannot find module './i18n/strings/en_GB.json'
Require stack:
- /opt/Element/resources/app.asar/lib/language-helper.js
- /opt/Element/resources/app.asar/lib/tray.js
- /opt/Element/resources/app.asar/lib/settings.js
- /opt/Element/resources/app.asar/lib/ipc.js
- /opt/Element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at AppLocalization.fetchTranslationJson (/opt/Element/resources/app.asar/lib/language-helper.js:87:20)
    at /opt/Element/resources/app.asar/lib/language-helper.js:100:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element/resources/app.asar/lib/language-helper.js:99:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element/resources/app.asar/lib/language-helper.js',
    '/opt/Element/resources/app.asar/lib/tray.js',
    '/opt/Element/resources/app.asar/lib/settings.js',
    '/opt/Element/resources/app.asar/lib/ipc.js',
    '/opt/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en-gb,en
Fetching translation json for locale: en-gb
Could not fetch translation json for locale: 'en-gb' Error: Cannot find module './i18n/strings/en_GB.json'
Require stack:
- /opt/Element/resources/app.asar/lib/language-helper.js
- /opt/Element/resources/app.asar/lib/tray.js
- /opt/Element/resources/app.asar/lib/settings.js
- /opt/Element/resources/app.asar/lib/ipc.js
- /opt/Element/resources/app.asar/lib/electron-main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at AppLocalization.fetchTranslationJson (/opt/Element/resources/app.asar/lib/language-helper.js:87:20)
    at /opt/Element/resources/app.asar/lib/language-helper.js:100:39
    at Array.forEach (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element/resources/app.asar/lib/language-helper.js:99:17) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element/resources/app.asar/lib/language-helper.js',
    '/opt/Element/resources/app.asar/lib/tray.js',
    '/opt/Element/resources/app.asar/lib/settings.js',
    '/opt/Element/resources/app.asar/lib/ipc.js',
    '/opt/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Fetching translation json for locale: en
Resetting the UI components after locale change
[4599:0911/185832.873105:ERROR:wayland_event_watcher.cc(36)] libwayland: wl_surface@32: error 0: gtk_shell::get_gtk_surface already requested

[1]    4599 trace trap  element-desktop --enable-features=UseOzonePlatform,WaylandWindowDecorations
```

The error is the same

**Comment by emiltoacs** [comment]
I'm running element-desktop on Arch installed from the package 1.11.20-1 and I use to run element with the parameters

> element-desktop --enable-features=UseOzonePlatform,WaylandWindowDecorations --ozone-platform=wayland

 that leads to the same error as above 

> ERROR:wayland_event_watcher.cc(36)] libwayland: wl_surface@33: error 0: gtk_shell::get_gtk_surface already requested

but I managed to solve the issue thanks to different parameters: 

> element-desktop --enable-features=UseOzonePlatform,WaylandWindowDecorations,WebRTCPipeWireCapturer --ozone-hint=auto

So now I can close and reopen element from the system-tray without error.
