### ISSUE TITLE
Invite with email is failing

### ISSUE THREAD

**Issue by kittykat** [vector-im/element-web#23505]
### Steps to reproduce

1. Go to room list in the right panel
2. "Invite to this room"
3. Paste or type in email and press return

#### What did you expect?
User is invited

#### What happened instead?
Get this error:
![Screenshot from 2022-10-17 10-23-08](https://user-images.githubusercontent.com/51663/196141423-bbf1aa88-9728-4d41-943f-857907df7e25.png)

Issue is happening at least since last Thursday

### Browser information

Chromium 106.0.5249.119 (Official Build) Arch Linux (64-bit)

### URL for webapp

develop.element.io

### Application version

Element version: 322745464c0e-react-1d1860842ef5-js-6245661cd7ae Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
This might be a release blocker, needs investigation

```
2022-10-17T09:20:26.381Z E Error searching identity server:
2022-10-17T09:20:26.381Z E fetch failed: Failed to fetch
ConnectionError: fetch failed: Failed to fetch
    at MatrixHttpApi.requestOtherUrl (https://develop.element.io/bundles/d1b253ee39346ad2b631/init.js:140945:13)
    at async IdentityAuthClient.registerForToken (https://develop.element.io/bundles/d1b253ee39346ad2b631/init.js:65811:9)
    at async IdentityAuthClient.getAccessToken (https://develop.element.io/bundles/d1b253ee39346ad2b631/init.js:65732:15)
    at async InviteDialog_InviteDialog.updateSuggestions (https://develop.element.io/bundles/d1b253ee39346ad2b631/init.js:137005:25)
2022-10-17T09:20:26.848Z E Error searching identity server:
2022-10-17T09:20:26.848Z E fetch failed: Failed to fetch
ConnectionError: fetch failed: Failed to fetch
    at MatrixHttpApi.requestOtherUrl (https://develop.element.io/bundles/d1b253ee39346ad2b631/init.js:140945:13)
    at async IdentityAuthClient.registerForToken (https://develop.element.io/bundles/d1b253ee39346ad2b631/init.js:65811:9)
    at async IdentityAuthClient.getAccessToken (https://develop.element.io/bundles/d1b253ee39346ad2b631/init.js:65732:15)
    at async InviteDialog_InviteDialog.updateSuggestions (https://develop.element.io/bundles/d1b253ee39346ad2b631/init.js:137005:25)
2022-10-17T09:20:40.139Z I Update available to 322745464c0e-react-1d1860842ef5-js-be11fa6b5a82 but won't be shown
2022-10-17T09:20:40.383Z I Inviting lukelemoignan@gmail.com
2022-10-17T09:20:40.576Z E fetch failed: Failed to fetch
ConnectionError: fetch failed: Failed to fetch
    at MatrixHttpApi.requestOtherUrl (https://develop.element.io/bundles/d1b253ee39346ad2b631/init.js:140945:13)
    at async IdentityAuthClient.registerForToken (https://develop.element.io/bundles/d1b253ee39346ad2b631/init.js:65811:9)
    at async IdentityAuthClient.getAccessToken (https://develop.element.io/bundles/d1b253ee39346ad2b631/init.js:65732:15)
    at async MatrixClient.inviteByThreePid (https://develop.element.io/bundles/d1b253ee39346ad2b631/init.js:17800:35)
