### ISSUE TITLE
Room list won't populate - `TypeError: Cannot read properties of undefined (reading 'getTs')`

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#23635]
### Steps to reproduce

1. Page-load Element
2. Room list won't load/populate

![](https://user-images.githubusercontent.com/558581/198378965-96074645-3736-47bb-841b-4dd9c2668014.png)

#### What did you expect?

Room list loads in

#### What happened instead?

Room list does not load and I noticed this error in the console

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'getTs')
    at RecentAlgorithm.ts:114:23
    at Array.map (<anonymous>)
    at getLastTs (RecentAlgorithm.ts:112:54)
    at RecentAlgorithm.ts:65:50
    at Array.sort (<anonymous>)
    at sortRooms (RecentAlgorithm.ts:64:18)
    at RecentAlgorithm.sortRooms (RecentAlgorithm.ts:126:16)
    at sortRoomsWithAlgorithm (index.ts:53:51)
    at ImportanceAlgorithm_ImportanceAlgorithm.setRooms (ImportanceAlgorithm.ts:110:41)
    at Algorithm_Algorithm.generateFreshTags (Algorithm.ts:590:23)
    at Algorithm_Algorithm.setKnownRooms (Algorithm.ts:508:14)
    at RoomListStoreClass.regenerateAllLists (RoomListStore.ts:535:24)
    at RoomListStoreClass.makeReady (RoomListStore.ts:116:14)
    at RoomListStoreClass.onReady (RoomListStore.ts:148:20)
    at ReadyWatchingStore.onReady (AsyncStoreWithClient.ts:38:35)
    at Object.ID_22 (ReadyWatchingStore.ts:86:28)
    at MatrixDispatcher._invokeCallback (Dispatcher.js:198:1)
    at MatrixDispatcher.dispatch (Dispatcher.js:174:1)
    at sentryWrapped (helpers.js:77:1)
```

### Operating system

Windows 10

### Browser information

Chrome Version 107.0.5304.63

### URL for webapp

https://develop.element.io/

### Application version

Element version: 2a46122f2864-react-c497046e39f6-js-b44787192db1 Olm version: 3.2.12

### Homeserver

matrix.org

### Will you send logs?

Yes, see https://github.com/matrix-org/element-web-rageshakes/issues/16511

**Comment by turt2live** [comment]
This is a threads regression.

**Comment by turt2live** [comment]
Regressed by https://github.com/matrix-org/matrix-react-sdk/pull/9510
