### ISSUE TITLE
Failures when sharing outbound session keys are swallowed

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#23792]
Sometimes there is an error queuing the to-device messages to share a megolm session; for example:

```
2022-11-15T09:10:40.454Z I Created batch of to-device messages with txn id m1668503440454.99 for @Manu:matrix.org:LKJZLJSTCC,@Manu:matrix.org:PSMTLDOWQW,@Manu:matrix.org:QHXUARLSTR,@Manu:matrix.org:HCYZTMSXSO
2022-11-15T09:10:40.454Z E sendToDevice failed Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Worker.<anonymous> (https://develop.element.io/bundles/a20ea4fbdbb209900525/init.js:88547:25)
2022-11-15T09:10:40.454Z E encryptAndSendToDevices promises failed Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Worker.<anonymous> (https://develop.element.io/bundles/a20ea4fbdbb209900525/init.js:88547:25)
2022-11-15T09:10:40.454Z E failed to encryptAndSendToDevices Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Worker.<anonymous> (https://develop.element.io/bundles/a20ea4fbdbb209900525/init.js:88547:25)
2022-11-15T09:10:40.454Z E Failed to share megolm keys for WpOHNMd4I3K9glwFfyxo2nsfr9T1ZUDvsP79v4okTsM in !xlFGXqMroSeHUQLGdq:matrix.org (slice 1/6)
2022-11-15T09:10:40.454Z E Failed to ensure outbound session in !xlFGXqMroSeHUQLGdq:matrix.org Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Worker.<anonymous> (https://develop.element.io/bundles/a20ea4fbdbb209900525/init.js:88547:25)
```

However, these errors are just logged, rather than being fed back to the user. 

Exactly why the IDBDatabase is complaining like this is something of a mystery to me (see also https://github.com/vector-im/element-web/issues/14174), but I would argue it is better to show the user even a cryptic error than to let them send a message that nobody will be able to decrypt.

**Comment by richvdh** [comment]
One thing that might cause the IndexedDB database to fail this way is running Element in two tabs at once.

**Comment by poljar** [comment]
One thing that the logs from the original message don't indicate is that we say that we're ready to encrypt for the room, while this is obviously false:

```
2022-11-23T08:54:47.951Z E Failed to ensure outbound session in !xlFGXqMroSeHUQLGdq:matrix.org Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
InvalidStateError: Failed to execute 'transaction' on 'IDBDatabase': The database connection is closing.
    at Worker.<anonymous> (https://develop.element.io/bundles/b2ddf1ed560f96309016/init.js:89141:25)
2022-11-23T08:54:47.951Z I Ready to encrypt events for !xlFGXqMroSeHUQLGdq:matrix.org
```

Propagating the error and not marking things as ready to encrypt seems like the wise choice here, unless we can figure out why the connection is closing and reopen it automagically.

If things don't get marked as ready to encrypt and we let users know that a failure happened, the user might will have the ability to retry the send which might then succeed. This would upgrade the silent UTD to a visible retry.

**Comment by poljar** [comment]
I think this is the place where the error gets swallowed even though callers of the method catch and log errors as well:

https://github.com/matrix-org/matrix-js-sdk/blob/b318a77ecef179a6fd288cdf32d3ff9c5e8ea989/src/crypto/algorithms/megolm.ts#L288-L292

**Comment by richvdh** [comment]
> I think this is the place where the error gets swallowed even though callers of the method catch and log errors as well:
> 
> https://github.com/matrix-org/matrix-js-sdk/blob/b318a77ecef179a6fd288cdf32d3ff9c5e8ea989/src/crypto/algorithms/megolm.ts#L288-L292

Yes, inded.
