### ISSUE TITLE
Element is offline after the first log on

### ISSUE THREAD

**Issue by Ithvr** [vector-im/element-web#24047]
### Steps to reproduce

1. Log on the client for the first time
2. Verify the client
3. Restart the client

#### What did you expect?
I expect that when I start Element that I get log on as normal 
#### What happened instead?
Everything works fine when I log on Element Desktop the first time, but after I restart the client is stuck being offline telling that "Connectivity to the server has been lost."
I know the server is working well since it works on other clients, and the browser version of element

### Operating system

OpenSUSE Tumbleweed

### Application version

Element-Desktop 1.11.15

### How did you install the app?

OpenSUSE repository 

### Homeserver

element.ithvr.no

### Will you send logs?

Yes

**Comment by N0Manches** [comment]
I have the same error on opensuse tumbleweed for weeks.
Tried to delete all configs, reinstall... nothing works.

Clicking on "Help & About" just closes the window.
```
Information for package element-desktop:
----------------------------------------
Repository     : openSUSE-Tumbleweed-Oss
Name           : element-desktop
Version        : 1.11.17-1.1
Arch           : noarch
Vendor         : openSUSE
Installed Size : 4.0 MiB
Installed      : Yes
Status         : up-to-date
Source package : element-desktop-1.11.17-1.1.src
Upstream URL   : https://github.com/vector-im/element-desktop
Summary        : A glossy Matrix collaboration client - desktop
Description    : 
    A glossy Matrix collaboration client - desktop
```
```
openSUSE Tumbleweed 20230110
```

When I try to use flatpak or the PWA with ungoogled-chromium I am logged out as soon the process is terminated.
So it also does not work on Fedora.

Really annoying... atm I can only use the web version in the browser on all my operating system I use.

**Comment by t3chguy** [comment]
I suggest reporting this upstream to the OpenSUSE package (community) maintainer. It isn't one we package & support

**Comment by N0Manches** [comment]
found the others
https://github.com/vector-im/element-web/issues/23956
https://github.com/vector-im/element-web/issues/18584


But of course I verified it with my Android phone then everything works fine until I restart the application, everytime. No idea what I could do differently.
But what is a bit strange to me that I need to verify it twice first it asked for the keys `desktop -> android`. Afterwards my phone says there is a new device `android -> desktop`. Is that normal? The verification process with the qr code are both the same.

**Comment by AUSBird** [comment]
I'm also having the same issue. I login and it works until the application restarts when the whole app just wont connect.

My console output after restarting gives me this
```
Keytar isn't installed; secure key storage is disabled.
Seshat isn't installed, event indexing is disabled.
/home/ausbird/.config/Element exists: yes
/home/ausbird/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to en-us,en,en,en
Fetching translation json for locale: en-us
Fetching translation json for locale: en
Fetching translation json for locale: en
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[19320:0116/080329.443447:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[19383:0116/080329.500425:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
Changing application language to en-us,en,en,en
Fetching translation json for locale: en-us
Fetching translation json for locale: en
Fetching translation json for locale: en
Fetching translation json for locale: en
Resetting the UI components after locale change
```

I noticed it mentions `Keytar isn't installed; secure key storage is disabled.`, is this potentially part of a cause for the issue?

**Comment by subscribernamegoeshere** [comment]
where would i find this keytar message? my ctrl shift i    from inside element-desktop client on this opensuse 15.4 machine doesnt show keytar error. those look like very early-on messages from a log, but i can only just as fast press ctrl+shift+i  and eventually only kind of see later bootstrapping messages of this element-desktop client?

I see stuff like the following:

....
rageshake.ts:73 Restoring session for @subscribernamegoeshereyougettheidea:matrix.org
rageshake.ts:73 setLoggedIn: mxid: @subscribernamegoeshereyougettheidea:matrix.org deviceId: DEVICEIDHERE000000 guest: false hs: https://matrix-client.matrix.org/ softLogout: false  freshLogin: false
....
rageshake.ts:73 StorageManager: Checking storage consistency
rageshake.ts:73 StorageManager: Local storage supported? true
rageshake.ts:73 StorageManager: IndexedDB supported? true
rageshake.ts:73 StorageManager: Local storage contains data? true
rageshake.ts:73 StorageManager: Crypto initialised? true
rageshake.ts:73 StorageManager: Sync store using IndexedDB contains data? true
rageshake.ts:73 StorageManager: Crypto store using IndexedDB contains data? true
rageshake.ts:73 StorageManager: Storage consistency checks passed
rageshake.ts:73 Expected a pickle key, but none provided.  Encryption may not work.
.....
rageshake.ts:73 Session persisted for @subscribernamegoeshereyougettheidea:matrix.org
rageshake.ts:73 Lifecycle: Starting MatrixClient
rageshake.ts:73 EventIndex: Event indexing isn't installed for the platform, not initializing.
rageshake.ts:73 IndexedDBStore.startup: connecting to backend
rageshake.ts:73 MatrixClientPeg: waiting for MatrixClient store to initialise
rageshake.ts:73 StorageManager: Persistent? true
rageshake.ts:73 Switching to room id ROOMID1GOESHERE:matrix.org at event undefined
rageshake.ts:73 IndexedDB worker is ready
logger.ts:46 LocalIndexedDBStoreBackend.connect: connecting...
logger.ts:46 LocalIndexedDBStoreBackend.connect: awaiting connection...
logger.ts:46 LocalIndexedDBStoreBackend.connect: connected
logger.ts:46 LocalIndexedDBStoreBackend: loading account data...
logger.ts:46 LocalIndexedDBStoreBackend: loading sync data...
logger.ts:46 LocalIndexedDBStoreBackend: loaded sync data
logger.ts:46 LocalIndexedDBStoreBackend: loaded account data
logger.ts:46 LocalIndexedDBStoreBackend: loaded initial data
rageshake.ts:73 IndexedDBStore.startup: loading presence events
rageshake.ts:73 IndexedDBStore.startup: processing presence events
rageshake.ts:73 Crypto: Starting up crypto store...
rageshake.ts:73 connecting to indexeddb matrix-js-sdk:crypto
rageshake.ts:73 connected to indexeddb matrix-js-sdk:crypto
rageshake.ts:73 Crypto: initialising roomlist...
rageshake.ts:73 Crypto: initialising crypto object...
rageshake.ts:73 Crypto: initialising Olm...
rageshake.ts:73 Crypto: initialising Olm device...
rageshake.ts:73 Unable to initialise e2e Error: OLM.BAD_ACCOUNT_KEY
.......

**Comment by AUSBird** [comment]
I ran the element app from a terminal and it gave me that output

**Comment by subscribernamegoeshere** [comment]
> I ran the element app from a terminal and it gave me that output

thanks for this information. by the way did you already file a bugreport with opensuse folks for this situation or anyone in here to really get this stuff solved on the opensuse platforms? thanks.

**Comment by asdil12** [comment]
The keytar and Seshat messages are unrelated. They are, because on openSUSE element-desktop is build without native bindings that would allow searching for messages. This is because of the abysmal node/cargo build process not being easy to run in the secure build environment that doesn't have internet access.

I have to say that I don't run into this issues on tumbleweed.
This is my startup log:

```
Keytar isn't installed; secure key storage is disabled.
Seshat isn't installed, event indexing is disabled.
/home/MYUSER/.config/Element exists: yes
/home/MYUSER/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Changing application language to de
Fetching translation json for locale: de
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to de
Fetching translation json for locale: de
Resetting the UI components after locale change
```

**Comment by subscribernamegoeshere** [comment]
i am far from being technically knowledgeable about all of this, i dont build my software on my own. coming back to this logged out state after every restart of the element application, what is the actual root cause that opensuse vendor and their compilation does have this bug? is this already known? will opensuse ever again have a working and lasting element application? what was different in december or november of last year that their compiled and built application worked normally and now does not any more? any real answers to this?

**Comment by asdil12** [comment]
The problem is that I cannot reproduce this issue on my tumbleweed installation.

You could try to delete your `.config/Element` directory and start with a fresh config. (Make sure you have a different client still logged in to keep your encrypted chats).
Also you could create a test account on a different server and see if the issue only appears on that particular server.

**Comment by subscribernamegoeshere** [comment]
doesnt help at all removing the .config/Element/ folder. the client re-logs in and re-verfiies with other existing devices.

upon first shutdown of the new opensuse logged-in instance newly creasted device id and all, it is immediately offline for good upon the next re-start of this client. once again. all the same.

how are we gonna figure out whats happening? please solve this. :(

**Comment by asdil12** [comment]
I'm sorry but I only package that software for openSUSE and have no idea about the inner workings of element. This sounds like a bug in element that only appears under very specific circumstances that I can't even reproduce.

I can only recommend you to try a different matrix client. Nheko is in the openSUSE repos and works pretty well.

**Comment by subscribernamegoeshere** [comment]
can you please create yourself a test account on matrix.org to use the same server and backend situation? and on leap 15.4 .  i have added this signle repository
> https://download.opensuse.org/repositories/devel:/languages:/nodejs/15.4/ 

and I guess these three packages are being used from that rpm-md repo

> element-desktop-1.11.20-lp154.1.1.noarch
> element-web-1.11.20-lp154.2.1.noarch
> nodejs-electron-22.1.0-lp154.1.1.x86_64

thanks for looking into this matter. it was working happily for a long time on 15.4 but now it does not :(

**Comment by subscribernamegoeshere** [comment]
one other thing that strikes me odd is that a simple not logged in element desktop client only showing the basic matrix.org landscape scene fotography with the login signup etc buttons would not load of this element desktop application is pinned to the taskmanager area and thus being automatic started when the kde desktop of the opensuse 15.4 starts for the normal user session. when there having a basic simple wifi connection that is slow to establish or taking a while to acquire ip addresses and all this element desktop application shows in its fullscreen window that something is wrong and it could not resolve element.io and it should be restarted and what not. so even the basic starting up of an non logged in element desktop application (client) is not robust enough to handle non networking and non online states of the machine when the networking connection the internet connection is not yet established, cut, broken or dns servers are not responding yet etc.

is it maybe possible as my opensuse 15.4 element-desktop was always in the automagic startup when it tries to reestablish the user account it maybe first quickly fails to get hold of ip addresses dns results and what not then somehow yanks all this information or parts of the authentication headers cookies or session states or whichever exact technical details and then lands in this failed state of profile or user account and user session of the matrix.org account, and when shortly thereafter the networking layers of the machine are there and fully established the session is already hosed and borked and of no use any more?

just an idea. please look into this bug. why would opensuse 15.4 users be left out in the dark and have no real working element-desktop client any more? this cant be state of the art for the opensuse 15.4 platform and this cant be a serious thing going on that a user needs to endure these days. can it? thanks

btw, a native firefox (rpm) on opensuse 15.4 can happily run a matrix-web (surfing element.io) way to connect to the matrix.org backend and this session happily works, survives firefox shutdowns, machine shutdowns, machine reboots and all that. as it ought to be.

what now? thanks.

**Comment by subscribernamegoeshere** [comment]
still all the same tried over again everything with currently:

element-desktop-1.11.22-lp154.1.1.noarch
element-web-1.11.22-lp154.1.1.noarch
nodejs-common-5.0-150400.1.4.x86_64
nodejs16-16.18.1-150400.3.12.1.x86_64
nodejs-electron-22.2.1-lp154.3.1.x86_64

opensuse 15.4 is only able to have a matrix element client running from within a webbrowser. so sad :(

**Comment by subscribernamegoeshere** [comment]
still defunct after todays rpm

element-web-1.11.23-lp154.1.1.noarch
element-desktop-1.11.23-lp154.1.1.noarch
nodejs-common-5.0-150400.1.4.x86_64
nodejs16-16.18.1-150400.3.12.1.x86_64
nodejs-electron-22.2.1-lp154.3.1.x86_64

**Comment by barathrm** [comment]
Same issue, also opensuse tumbleweed, KDE. kwallet is open. Same logs as others:

Related?
- https://github.com/vector-im/element-web/issues/18584#issuecomment-1046303527
- https://github.com/vector-im/element-web/issues/24220#issuecomment-1381455059

```
fetch.ts:62          GET https://matrix-client.matrix.org/_matrix/client/r0/rooms/!OYSLYJkMrXEGbkKkEy%3Amatrix.org/messages?limit=20&dir=b&from=<snip>&filter=%7B%22lazy_load_members%22%3Atrue%7D 401
fetch @ fetch.ts:62
requestOtherUrl @ fetch.ts:264
request @ fetch.ts:205
authedRequest @ fetch.ts:156
createMessagesRequest @ client.ts:5843
paginateEventTimeline @ client.ts:6089
paginate @ timeline-window.ts:291
(anonymous) @ TimelinePanel.tsx:546
(anonymous) @ TimelinePanel.tsx:577
(anonymous) @ ScrollPanel.tsx:492
Promise.then (async)
maybeFill @ ScrollPanel.tsx:491
(anonymous) @ ScrollPanel.tsx:392
(anonymous) @ ScrollPanel.tsx:261
componentDidUpdate @ ScrollPanel.tsx:216
_s @ react-dom.production.min.js:219
Rl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
$i @ react-dom.production.min.js:122
Il @ react-dom.production.min.js:252
vl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$i @ react-dom.production.min.js:122
Yi @ react-dom.production.min.js:123
Wi @ react-dom.production.min.js:122
ml @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
f.setState @ react.production.min.js:12
(anonymous) @ TimelinePanel.tsx:927
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
updateSyncState @ sync.ts:1815
recoverFromSyncStartupError @ sync.ts:583
await in recoverFromSyncStartupError (async)
(anonymous) @ sync.ts:630
await in (anonymous) (async)
(anonymous) @ sync.ts:631
await in (anonymous) (async)
(anonymous) @ sync.ts:631
await in (anonymous) (async)
(anonymous) @ sync.ts:631
rageshake.ts:73 M_MISSING_TOKEN: MatrixError: [401] Invalid Authorization header. (https://matrix-client.matrix.org/_matrix/client/r0/rooms<snip>matrix.org/messages?limit=20&dir=b&from=<snip>&filter=%7B%22lazy_load_members%22%3Atrue%7D)
    at c (vector://vector/webapp/bundles/46c15e92c07efd41fd08/vendors~init.js:2:1430935)
    at p.requestOtherUrl (vector://vector/webapp/bundles/46c15e92c07efd41fd08/vendors~init.js:2:3548381)
e.<computed> @ rageshake.ts:73
(anonymous) @ logger.ts:44
(anonymous) @ ScrollPanel.tsx:405
await in (anonymous) (async)
(anonymous) @ ScrollPanel.tsx:261
componentDidUpdate @ ScrollPanel.tsx:216
_s @ react-dom.production.min.js:219
Rl @ react-dom.production.min.js:259
t.unstable_runWithPriority @ scheduler.production.min.js:18
$i @ react-dom.production.min.js:122
Il @ react-dom.production.min.js:252
vl @ react-dom.production.min.js:243
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:18
$i @ react-dom.production.min.js:122
Yi @ react-dom.production.min.js:123
Wi @ react-dom.production.min.js:122
ml @ react-dom.production.min.js:237
enqueueSetState @ react-dom.production.min.js:133
f.setState @ react.production.min.js:12
(anonymous) @ TimelinePanel.tsx:927
s.emit @ events.js:158
emit @ typed-event-emitter.ts:59
updateSyncState @ sync.ts:1815
recoverFromSyncStartupError @ sync.ts:583
await in recoverFromSyncStartupError (async)
(anonymous) @ sync.ts:630
await in (anonymous) (async)
(anonymous) @ sync.ts:631
await in (anonymous) (async)
(anonymous) @ sync.ts:631
await in (anonymous) (async)
(anonymous) @ sync.ts:631
```

**Comment by subscribernamegoeshere** [comment]
thanks for further participants in this bug. is it maybe possible that a security store (kde wallet?) is involved in this issue? although my kde wallet (same here) does not show any access or prompt when element desktop on opensuse leap 15.4 is running or starting. my kde wallet is also not automatically unlocked and needs a password.

at present this kde wallet only seems to store wifi credentials.
thanks.

**Comment by subscribernamegoeshere** [comment]
okay this is still the same, with:

element-desktop-1.11.26-lp154.1.1.noarch
element-web-1.11.26-lp154.2.1.noarch

nodejs16-16.19.1-150400.3.15.1.x86_64
nodejs-common-5.0-150400.1.4.x86_64
nodejs-electron-22.3.4-lp154.1.1.x86_64

-------

invalid authorization header after returing to this client / instance. no connection possible.
okay seriously, will this ever be investigated any further? what can we as users do more?

it seems as if opensuse platform is kind of becoming abandonware and steering itself in very differnt directions from where it has once been, what I read at various places but thats another story I guess.

**Comment by t3chguy** [comment]
@subscribernamegoeshere have you reported it to the community maintainer of your package?

**Comment by asdil12** [comment]
> is this maybe a hint as well to shortcoming of this opensuse element-desktop built binaries and package and so? maybe this situation gives additional hints into some causes why authentication headers or basic connection does not succeed or why some stages of the handshake with the element/matrix backend servers are failing or missing or something in this regard?

This is something I can actually help with:

You could use this script to wait for internet access and only afterwards start element-desktop:

```bash
for i in {1..300} ; do ping -c1 opensuse.org && element-desktop && break ; sleep 1 ; done
```
