### ISSUE TITLE
element suddenly not connecting any more (matrix.org account) immediately offline, finding no way to make it work

### ISSUE THREAD

**Issue by subscribernamegoeshere** [vector-im/element-web#24220]
### Steps to reproduce

1. Where are you starting? What can you see?

some opensuse project provided element desktop (and element web package in cooperation/dependency) but installed on december 2022 already, no newer element packages provided yet

Name        : element-desktop
Version     : 1.11.17
Release     : lp154.1.1
Architecture: noarch
Install Date: Fri 23 Dec 2022 04:15:43 PM CET
Group       : Unspecified
Size        : 4206972
License     : Apache-2.0
Signature   : RSA/SHA256, Fri 23 Dec 2022 11:38:28 AM CET, Key ID 3c66cd9ba89c3a8a
Source RPM  : element-desktop-1.11.17-lp154.1.1.src.rpm
Build Date  : Fri 23 Dec 2022 11:37:58 AM CET
Build Host  : lamb58
Relocations : (not relocatable)
Packager    : https://www.suse.com/
Vendor      : obs://build.opensuse.org/devel:languages:nodejs
URL         : https://github.com/vector-im/element-desktop
Summary     : A glossy Matrix collaboration client - desktop

Name        : element-web
Version     : 1.11.17
Release     : lp154.2.1
Architecture: noarch
Install Date: Fri 23 Dec 2022 04:15:42 PM CET
Group       : Unspecified
Size        : 46654322
License     : Apache-2.0
Signature   : RSA/SHA256, Fri 23 Dec 2022 11:32:40 AM CET, Key ID 3c66cd9ba89c3a8a
Source RPM  : element-web-1.11.17-lp154.2.1.src.rpm
Build Date  : Fri 23 Dec 2022 11:32:06 AM CET
Build Host  : lamb65
Relocations : (not relocatable)
Packager    : https://www.suse.com/
Vendor      : obs://build.opensuse.org/devel:languages:nodejs
URL         : https://github.com/vector-im/element-web
Summary     : A glossy Matrix collaboration client - web files

3. What do you click?
i always shut down this laptop linux machine completely. it has full disk encryption. it is kind of new few months old, nvme all fine working normally i say. next time i restart linux element gui appears after i login to kde desktop and it writes out error that it has trouble finding some of its profile meta files or similar I dont recally maybe files became corrupted (no disk errors, no filesystem errors though, never seen this error before) and it needs me to login again and re-verify myself with another client of mine. luckily i have some mobile phone with my same matrix.org account, i reverified both (only these two devices) machines/sessions. now they both wrote that i would have two linux element and one android element. the one being logged in last time two or three days ago. the newer element linux alive now.

then i shut down this element linux machine again properly normally. fire it up back today and now element is always constantly offline and red error line in my very few chatrooms, single one-on-one chat only to a friend etc.) it will not connect or not settle down.

this machine has different wifi access providers all work fine, i can browse the web, ping, everything. i couldnt make element work / connect again so far. on this linux machine. my element on mobile phone works fine. i also never sign out of my accounts.

5. More steps…
so before signing out deliberately (or trying at least? is it really a networking issue?) on this linux machine again and addong another new and to-be-verified session yet again, I was wondering what is going on here, or if these incidents and issues have got to do anything with each other, if all my trouble began two days ago when those files were invalid, corrupted or whatever happened back then.

i am kind of worried for my element data, my chats (few only) my account state it is in etc. also I dont know if element has some kind of offline feature maybe I accidentally acitvated? but i hope i am not totally an idiot :(

this linux x64 notebook works fine and normal though, no crashes no funny stuff. anyone able to help? how do I diagnose whats wrong here or look into some metadata or cache or profile files or whatever is going on? thanks.

### Operating system

opensuse 15.4

### Application version

1.11.17

### How did you install the app?

build service opensuse

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by subscribernamegoeshere** [comment]
even tried real LAN networking cable based connection. no success. also different internet providers. all have real dualstack ipv4 and ipv6 here. no connection. on this linux machine :(

**Comment by subscribernamegoeshere** [comment]
ss -np   shows a single established ipv6 target from electron process name

tcp   ESTAB  0      0                 [2xxx:XXXXX]:56774 [2606:4700:10::6814:c825]:443   users:(("electron",pid=4898,fd=26)) 

not going anywhere in the element gui though. it displays some of the very recent content from earlier today cached but is shown as offline

**Comment by subscribernamegoeshere** [comment]
I actually have two ipv6 and one ipv4 https/443 established lines on a new quit/restart of element desktop application

tcp   ESTAB  0      0                                            10.xx.xx.xx:59582                18.158.54.30:443   users:(("electron",pid=7065,fd=27))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
tcp   ESTAB  0      0                 [2xxxx:xxxxxxx]:39280 [2606:4700:3031::6815:1c34]:443   users:(("electron",pid=7065,fd=28))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
tcp   ESTAB  0      0                 [2xxxxx:xxxxxx:xxx]:33874   [2606:4700:10::6814:c825]:443   users:(("electron",pid=7065,fd=26))

**Comment by turt2live** [comment]
Logs were reported sent for this issue, but they do not appear to exist - are you able to send those over please? If there's no Submit Debug Logs button visible, please open the Electron devtools with <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>, go to the Console tab, and type `mxSendRageshake("https://github.com/vector-im/element-web/issues/24220");`, and hit <kbd>Enter</kbd>. This will send logs and associate them with this issue for investigation.

**Comment by subscribernamegoeshere** [comment]
I think having briefly gone through your recently updated bugs, I found this
https://github.com/vector-im/element-web/issues/21332

corrupting session data or profile files or what that stuff is called due to indexddb stuff, that bug and the descriptions in there sounds exactly what some days ago my linux element client suddenly complained about that I needed to log-out or re-login on this linux machine.

can I safely send logfiles without compromising personal data to help with this bug? thanks.

**Comment by subscribernamegoeshere** [comment]
in its current state of the elements gui being in one of my chatrooms I see the following in the console:

rageshake.ts:73 M_MISSING_TOKEN: MatrixError: [401] Invalid Authorization header. (https://matrix-client.matrix.org/_matrix/client/r0/rooms/XXXXXXXXXXmatrix.org/messages?limit=20&dir=b&from=t112246-3609438903_757284974_7716894_1838590967_1866451789_3910671_729960391_6340442728_0&filter=%7B%22lazy_load_members%22%3Atrue%7D)
at c (vector://vector/webapp/bundles/234a62761793011e9c1f/vendorsinit.js:2:1381963)
at p.requestOtherUrl (vector://vector/webapp/bundles/234a62761793011e9c1f/vendorsinit.js:2:3582770)

constantly coming up again and again.

**Comment by subscribernamegoeshere** [comment]
any more stuff I could do to help? this client doesnt update its content any more, in my own three chats, one to myself and two to two different fellow matrix participants, it only shows:

-----
Connectivity to the server has been lost.
Sent messages will be stored until your connection has returned.

-----

would it help to log off and log back on, or do I endanger some kind of content of my local metadata and session files etc? although the re-login on this linux machine generated a new linux session being shown on my single additional client on my android device. so every log-in and log-out generates more sessions. any means to really come back to a session with the help of some backups or so or would this be pointless and no use of any kind? is my situation linked to that indexeddb bug I linked to? although i logged off and back on after that on this linux machine, and it did work then for a couple of more hours after that.

thanks for hints and advice how to handle this from here.

**Comment by subscribernamegoeshere** [comment]
okay I give up with this bugreport as there are no questions being answered and I see no progress here. Today opensuse build system provided new:

-----------
Name        : element-desktop
Version     : 1.11.20
Release     : lp154.1.1
Architecture: noarch
Group       : Unspecified
Size        : 4208461
License     : Apache-2.0
Signature   : RSA/SHA256, Fri 20 Jan 2023 03:44:11 PM CET, Key ID 3c66cd9ba89c3a8a
Source RPM  : element-desktop-1.11.20-lp154.1.1.src.rpm
Build Date  : Fri 20 Jan 2023 03:43:53 PM CET


and

Name        : element-web
Version     : 1.11.20
Release     : lp154.2.1
Architecture: noarch
Group       : Unspecified
Size        : 51462546
License     : Apache-2.0
Signature   : RSA/SHA256, Fri 20 Jan 2023 02:25:08 PM CET, Key ID 3c66cd9ba89c3a8a
Source RPM  : element-web-1.11.20-lp154.2.1.src.rpm
Build Date  : Fri 20 Jan 2023 02:24:33 PM CET

----
which I both installed and applied. the linux element-desktop client still shows me being offline and some partly content of my very few chat windows. 

so then i finally decided to logout on this malfunctioning linux client and relogin on this newly updates element-desktop 1.11.20.....

it only created a new session/device yet again. then a whole lot of different mess megan on verifiying my other android and the whole workflow on the guis, of both android element and linux element-desktop actually created additional mess suddenly both of my devices/sessions seemed to be unverified me needing to abandon the automatically appearing verification workflow and manually in the security area starting to make sense and progress of how to verify just the linux session. i was kinda slightly panicking that everything was breaking down, is there actually no real way (maybe it doesnt make sense cryptographically, i am not much of an expert in these details) to properly and fully return to a previously having existed session and fully be that session once again? sessions seem to always like newly be generated and I simply lack the understanding if or how to recreate or reestablish and rebuild that session if possible at all.

will see how long this session on the linux machine will survive. there seems quite a lot of mess still going on with all this encryption and entities/sessions stuff going on in the workflow, the codebase or something. some mess seriously needs to be sorted out and be straightnered out :)

thanks anyhow.

**Comment by subscribernamegoeshere** [comment]
okay after working for a while with this newer build 1.11.20 by opensuse build platform, and after shutting down the linux machine and coming back to it after a while, this newly logged in and newly created session by the linux machine is seemingly offline once again all the same and doesnt reconnect back or revalidate or whatever means.

meanwhile I think i found another bugreport about this kind of behavior of suse/opensuse? built element packages and stuff about keytar missing or something developery wizardry ;)

https://github.com/vector-im/element-web/issues/24047

thanks for helping.
