### ISSUE TITLE
Flaky test crypto/decryption-failure.spec.ts "Decryption Failure Bar"

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#24351]
This failed once, and passed when I re-ran it:

https://github.com/matrix-org/matrix-react-sdk/actions/runs/4025147397/jobs/6918012660

https://github.com/matrix-org/matrix-react-sdk/actions/runs/4025147397

```
Decryption Failure Bar
Copy /home/runner/work/matrix-react-sdk/matrix-react-sdk/cypress/plugins/synapsedocker/templates/default -> /home/runner/work/_temp/react-sdk-synapsedocker-IQIDNz
Gen /home/runner/work/matrix-react-sdk/matrix-react-sdk/cypress/plugins/synapsedocker/templates/default/homeserver.yaml
Gen /home/runner/work/matrix-react-sdk/matrix-react-sdk/cypress/plugins/synapsedocker/templates/default/localhost.signing.key
Starting synapse with config dir /home/runner/work/_temp/react-sdk-synapsedocker-IQIDNz...
Started synapse with id 9f7fdc1ae6f54669d96dd2d3e7c794542f45029ff9a8d7eb4c0dcf181475bea9 on port 35039.
 HTTP  1/27/2023 2:06:06 PM 127.0.0.1 GET /
 HTTP  1/27/2023 2:06:06 PM 127.0.0.1 Returned 200 in 1 ms
 HTTP  1/27/2023 2:06:06 PM 127.0.0.1 GET /bundles/8daecd524ef4ddb8f921/bundle.css
 HTTP  1/27/2023 2:06:06 PM 127.0.0.1 Returned 200 in 2 ms
...
 HTTP  1/27/2023 2:10:31 PM 127.0.0.1 GET /img/element-icons/home.71443c4.svg
 HTTP  1/27/2023 2:10:31 PM 127.0.0.1 Returned 304 in 2 ms
    1) "before each" hook for "should prompt the user to verify, if this device isn't verified and there are other verified devices or backups"
Stopped synapse id ee9f2384b4caeaf196c75b7374460992f366d400584664391cced31e79684547.
 HTTP  1/27/2023 2:10:46 PM 127.0.0.1 GET /sw.js
 HTTP  1/27/2023 2:10:46 PM 127.0.0.1 Returned 304 in 2 ms


  0 passing (5m)
  1 failing

  1) Decryption Failure Bar
       "before each" hook for "should prompt the user to verify, if this device isn't verified and there are other verified devices or backups":
     CypressError: `cy.wrap()` timed out waiting `10000ms` to complete.

You called `cy.wrap()` with a promise that never resolved.

To increase the timeout, use `{ timeout: number }`

https://on.cypress.io/wrap

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Decryption Failure Bar`
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:137139:78)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:8914:23)
      at <unknown> (http://localhost:8080/__cypress/runner/cypress_runner.js:4036:41)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:8914:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:6849:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:6906:18)
      at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:6951:10)
      at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:7027:18)
      at _drainQueueStep (http://localhost:8080/__cypress/runner/cypress_runner.js:3621:12)
      at _drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:3614:9)
      at ../../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:3630:5)
      at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:3500:14)
  From Your Spec Code:
      at Context.eval (webpack:///./cypress/support/bot.ts:144:18)
```

**Comment by andybalaam** [comment]
Another failure today https://cloud.cypress.io/projects/ppvnzg/runs/8764/test-results?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%7B%22value%22%3A%22FAILED%22%2C%22label%22%3A%22FAILED%22%7D%5D&testingTypesEnum=%5B%5D

**Comment by gsouquet** [comment]
Another failure here https://cloud.cypress.io/projects/ppvnzg/runs/8855/test-results
