### ISSUE TITLE
Crash on Chromebook with `Cannot read properties of null (reading 'initCrypto')`

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#24449]
See this [rageshake](https://github.com/matrix-org/element-web-rageshakes/issues/19956)

Interesting-looking messages from the log:

```
2023-02-06T14:32:05.465Z I Failed to check for protocol support: will retry MatrixError: [401] Invalid access token passed. (https://matrix-client.matrix.org/_matrix/client/r0/thirdparty/protocols)
M_UNKNOWN_TOKEN: MatrixError: [401] Invalid access token passed. (https://matrix-client.matrix.org/_matrix/client/r0/thirdparty/protocols)
    at c (https://app.element.io/bundles/9cc74975dc7c11f9b492/vendors~init.js:2:1397071)
    at p.requestOtherUrl (https://app.element.io/bundles/9cc74975dc7c11f9b492/vendors~init.js:2:3541113)
...
2023-02-06T14:32:06.592Z W Unable to initialise e2e Cannot read properties of null (reading 'initCrypto')
TypeError: Cannot read properties of null (reading 'initCrypto')
    at Object.initClientCrypto (https://app.element.io/bundles/9cc74975dc7c11f9b492/vendors~init.js:2:122685)
    at async Object.assign (https://app.element.io/bundles/9cc74975dc7c11f9b492/vendors~init.js:2:121877)
    at async Object.start (https://app.element.io/bundles/9cc74975dc7c11f9b492/vendors~init.js:2:123028)
    at async ue (https://app.element.io/bundles/9cc74975dc7c11f9b492/vendors~element-web-app.js:2:1174001)
    at async ie (https://app.element.io/bundles/9cc74975dc7c11f9b492/vendors~element-web-app.js:2:1171704)
    at async ee (https://app.element.io/bundles/9cc74975dc7c11f9b492/vendors~element-web-app.js:2:1169845)
    at async Object.K (https://app.element.io/bundles/9cc74975dc7c11f9b492/vendors~element-web-app.js:2:1165503)
    at async https://app.element.io/bundles/9cc74975dc7c11f9b492/vendors~element-web-app.js:2:18799
```

**Comment by t3chguy** [comment]
Not a supported Desktop OS
https://github.com/vector-im/element-web#supported-environments
