### ISSUE TITLE
`Error: Room !xxx has no index in im.vector.fake.invite`

### ISSUE THREAD

**Issue by MadLittleMods** [vector-im/element-web#24545]
### Steps to reproduce

1. I don't know how I got this error but I just saw it in the devtools console

```
ImportanceAlgorithm.ts:165 Uncaught (in promise) Error: Room !xxx has no index in im.vector.fake.invite
    at S.handleRoomUpdate (ImportanceAlgorithm.ts:165:19)
    at k.handleRoomUpdate (Algorithm.ts:738:23)
    at R.handleRoomUpdate (RoomListStore.ts:362:45)
    at R.onDispatchAsync (RoomListStore.ts:209:28)
    at RoomListStore.ts:187:33
    at setImmediate.js:40:13
    at y (setImmediate.js:69:21)
    at a (setImmediate.js:109:17)
```

Relevant code: [`ImportanceAlgorithm.ts#L153-L193`](https://github.com/matrix-org/matrix-react-sdk/blob/477de46814ef6501d600541eb24533159b976255/src/stores/room-list/algorithms/list-ordering/ImportanceAlgorithm.ts#L153-L193)

#### What did you expect?

No error

#### What happened instead?

Error

### Operating system

Windows 10

### Browser information

Chrome Version 110.0.5481.78 

### URL for webapp

app.gitter.im

### Application version

Element version 1.11.23-rc.1

### Homeserver

gitter.im

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
Fixed by new room list
