### ISSUE TITLE
Loading the session fails with "Unable to load session Error decrypting secret access_token: bad MAC"

### ISSUE THREAD

**Issue by justjanne** [vector-im/element-web#24560]
None of the previous reporters included any reproduction steps. They all reported element refusing to launch with the aforementioned error.

Element fails with the following stacktrace:

```
2023-02-16T19:42:57.280Z I Got pickle key
2023-02-16T19:42:57.281Z E Unable to load session Error decrypting secret access_token: bad MAC
Error: Error decrypting secret access_token: bad MAC
    at  s (webpack:///node_modules/matrix-js-sdk/src/crypto/aes.ts:95:14)
    at async te (webpack:///node_modules/matrix-react-sdk/src/Lifecycle.ts:455:16)
    at async Object.q (webpack:///node_modules/matrix-react-sdk/src/Lifecycle.ts:149:8)
    at async webpack:///node_modules/matrix-react-sdk/src/components/structures/MatrixChat.tsx:343:16
```

**Comment by t3chguy** [comment]
Vast majority of reports are from Linux, 3 from Windows. Theory: race condition between app launch and keyring unlocking

**Comment by Johennes** [comment]
Removing from our board as this is not a fire based on our definition of it and, thus, won't be picked up by our processes.

CC @daniellekirkwood / @andybalaam
