### ISSUE TITLE
Occasional crashes with SIGTRAP

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#24600]
### Steps to reproduce

 ¯\\_(ツ)_/¯

It just happens randomly

#### What did you expect?

The app to keep working

#### What happened instead?

The app exits with a SIGTRAP. The following is shown on the console:

```
Trace/breakpoint trap (core dumped)
```

### Operating system

Ubuntu 22.04

### Application version

Element Nightly version: 2023022001 Olm version: 3.2.12

### How did you install the app?

nightly debian

### Will you send logs?

No

**Comment by richvdh** [comment]
Not really sure how to diagnose this; the core dumps are totally useless.

**Comment by t3chguy** [comment]
@Igetin the flatpak is community maintained and known to have issues, I suggest you respond to one of the open issues on https://github.com/flathub/im.riot.Riot/

**Comment by t3chguy** [comment]
Currently we only maintain debs

**Comment by JokerGermany** [comment]
https://github.com/Ubuntu-Installation/Installations-Script/blob/main/22-04.sh#L198
sudo wget -O /usr/share/keyrings/element-io-archive-keyring.gpg https://packages.element.io/debian/element-io-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main" | sudo tee /etc/apt/sources.list.d/element-io.list

**Comment by dkasak** [comment]
Duplicate of https://github.com/vector-im/element-web/issues/20926?

**Comment by t3chguy** [comment]
@dkasak without a trace from @richvdh we can't assert that its within `DecommitSystemPages`

**Comment by richvdh** [comment]
> @dkasak without a trace from @richvdh we can't assert that its within `DecommitSystemPages`

Indeed. How can I get such a trace? Are unstripped binaries, or debug symbols, available?

**Comment by t3chguy** [comment]
You'd likely need to build it yourself unfortunately - https://github.com/vector-im/element-web/wiki/Getting-a-crash-log-out-of-Element-Desktop#linux

**Comment by jplatte** [comment]
I don't think that's right. Electron provides official debug builds that you should be able to use to run Element. Trying to find the instructions...

**Comment by jplatte** [comment]
Found it! https://github.com/vector-im/element-web/issues/18943#issuecomment-1021473090

**Comment by dkasak** [comment]
Additionally, if you're on Arch, it has [Debuginfod](https://wiki.archlinux.org/title/Debuginfod) set up so you can retrieve debug symbols after the fact.

**Comment by jplatte** [comment]
I think Electron / Chromium is a bit.. special when it comes to debugging. That said, it's been a while since I've tried debugging it, maybe things have improved.

**Comment by richvdh** [comment]
Right, thanks. I hadn't realised that the binary in Element's distribution is actually just electron, nor that electron publish debug builds.

I downloaded https://github.com/electron/electron/releases/download/v23.1.0/electron-v23.1.0-linux-x64-debug.zip, and copied the `electron.debug` therein into `/opt/Element-Nightly/`. The original binary (`element-desktop-nightly`) has a build link (`readelf --string-dump=.gnu_debuglink`) to `electron.debug`, which gdb uses to find the debug symbols.

**Comment by richvdh** [comment]
The stacktrace at the crash is:


```
#0  0x0000564dbb6e3d3f in partition_alloc::internal::DiscardSystemPagesInternal (address=<optimised out>, length=<optimised out>) at ../../base/allocator/partition_allocator/page_allocator_internals_posix.h:388
#1  partition_alloc::DiscardSystemPages (address=<optimised out>, length=<optimised out>) at ../../base/allocator/partition_allocator/page_allocator.cc:342
#2  0x0000564dbb6eb84b in partition_alloc::internal::PartitionPurgeSlotSpan<true> (slot_span=0x32b0018015e0, discard=true) at ../../base/allocator/partition_allocator/partition_root.cc:457
#3  partition_alloc::internal::PartitionPurgeBucket<true> (bucket=0x564dbfcea730 <(anonymous namespace)::g_root+1456>) at ../../base/allocator/partition_allocator/partition_root.cc:536
#4  partition_alloc::PartitionRoot<true>::PurgeMemory (this=<optimised out>, flags=<optimised out>) at ../../base/allocator/partition_allocator/partition_root.cc:1291
#5  0x0000564dbb6e3ac8 in partition_alloc::MemoryReclaimer::Reclaim (this=0x564dbfcf3008 <partition_alloc::MemoryReclaimer::Instance()::instance>, flags=3) at ../../base/allocator/partition_allocator/memory_reclaimer.cc:92
#6  0x0000564dbb5fe9a9 in base::allocator::(anonymous namespace)::RunMemoryReclaimer (task_runner=...) at ../../base/allocator/partition_alloc_support.cc:195
#7  0x0000564dbb589f36 in base::OnceCallback<void ()>::Run() && (this=0x32b0012c2000) at ../../base/functional/callback.h:152
#8  base::TaskAnnotator::RunTaskImpl (this=<optimised out>, pending_task=...) at ../../base/task/common/task_annotator.cc:157
#9  0x0000564dbb5aa3c9 in base::TaskAnnotator::RunTask<base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_0>(perfetto::StaticString, base::PendingTask&, base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*)::$_0&&) (
    this=0x32b0002c01d0, pending_task=..., event_name=..., args=...) at ../../base/task/common/task_annotator.h:85
#10 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl (this=0x32b0002c0000, continuation_lazy_now=0x7ffe4a579220) at ../../base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:484
#11 0x0000564dbb5aad1c in non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() () at ../../base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:335
#12 0x0000564dbb5453af in base::MessagePumpGlib::HandleDispatch (this=0x32b00023af40) at ../../base/message_loop/message_pump_glib.cc:374
#13 base::(anonymous namespace)::WorkSourceDispatch (source=<optimised out>, unused_func=<optimised out>, unused_data=<optimised out>) at ../../base/message_loop/message_pump_glib.cc:127
#14 0x00007f2d5f4bbd3b in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007f2d5f5106c8 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007f2d5f4b93e3 in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#17 0x0000564dbb5450a7 in base::MessagePumpGlib::Run (this=0x32b00023af40, delegate=<optimised out>) at ../../base/message_loop/message_pump_glib.cc:400
#18 0x0000564dbb5ab5a6 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run (this=0x32b0002c0000, application_tasks_allowed=true, timeout=...) at ../../base/task/sequence_manager/thread_controller_with_message_pump_impl.cc:644
#19 0x0000564dbb56a337 in base::RunLoop::Run (this=0x32b001234fc0, location=...) at ../../base/run_loop.cc:140
#20 0x0000564dba68a18f in content::BrowserMainLoop::RunMainMessageLoop (this=<optimised out>) at ../../content/browser/browser_main_loop.cc:1054
#21 0x0000564dba68c112 in content::BrowserMainRunnerImpl::Run (this=0x32b0002f0de0) at ../../content/browser/browser_main_runner_impl.cc:162
#22 0x0000564dba687549 in content::BrowserMain (parameters=...) at ../../content/browser/browser_main.cc:32
#23 0x0000564db84c4cf4 in content::RunBrowserProcessMain (main_function_params=..., delegate=0x7ffe4a579bf0) at ../../content/app/content_main_runner_impl.cc:708
#24 0x0000564db84c6139 in content::ContentMainRunnerImpl::RunBrowser (this=0x32b000248200, main_params=..., start_minimal_browser=<optimised out>) at ../../content/app/content_main_runner_impl.cc:1246
#25 0x0000564db84c5ec9 in content::ContentMainRunnerImpl::Run (this=0x32b000248200) at ../../content/app/content_main_runner_impl.cc:1102
#26 0x0000564db84c2ee3 in content::RunContentProcess (params=..., content_main_runner=0x32b000248200) at ../../content/app/content_main.cc:348
#27 0x0000564db84c3605 in content::ContentMain (params=...) at ../../content/app/content_main.cc:376
#28 0x0000564db81e6d1d in main (argc=<optimised out>, argv=0x7ffe4a579de8) at ../../electron/shell/app/electron_main_linux.cc:40
```

... which does seem to be the same as #20926.

**Comment by richvdh** [comment]
Duplicate of #20926
