### ISSUE TITLE
MaxListenersExceededWarning: Possible EventEmitter memory leak detected...

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24628]
### Steps to reproduce

I discovered console and found this warning:
`MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Thread.update listeners added. Use emitter.setMaxListeners() to increase limit`

#### What happened instead?
I just clicked to view other room in space and have got a big amount of that warning: 27.

```
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Thread.update listeners added. Use emitter.setMaxListeners() to increase limit
    at d (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:10568)
    at s.addListener (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:13152)
    at E.on (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:454526)
    at a.reEmit (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:1072049)
    at a.reEmit (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:1072273)
    at f.setThread (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:241355)
    at i (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:3608693)
    at Array.map (<anonymous>)
    at vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:302359
    at async E.updateThreadMetadata (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:480166)
    
 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Thread.update listeners added. Use emitter.setMaxListeners() to increase limit
    at d (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:10568)
    at s.addListener (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:13152)
    at E.on (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:454526)
    at a.reEmit (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:1072049)
    at a.reEmit (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:1072273)
    at f.setThread (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:241355)
    at i (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:3608693)
    at Array.map (<anonymous>)
    at vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:302359
    at async E.updateThreadMetadata (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:480166)

MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Thread.update listeners added. Use emitter.setMaxListeners() to increase limit
    at d (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:10568)
    at s.addListener (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:13152)
    at E.on (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:454526)
    at a.reEmit (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:1072049)
    at a.reEmit (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:1072273)
    at f.setThread (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:241355)
    at i (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:3608693)
    at Array.map (<anonymous>)
    at vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:302359
    at async E.updateThreadMetadata (vector://vector/webapp/bundles/27555574f7ee6ca05898/vendors~init.js:2:480166)
```

### Operating system

Windows

### Application version

1.11.23

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
This is not an issue. There are simply many things listening to the event emitter. If it was in the hundreds it'd be a leak.
