### ISSUE TITLE
Get Failed to load timeline position when click on The conversation continues here

### ISSUE THREAD

**Issue by JeanPaulLucien** [vector-im/element-web#24665]
### Steps to reproduce

I was in room for a long time.

> Room title is ruhaskell/meetup
> Room address is #gitter_ruhaskell=2Fmeetup:matrix.org

Room has got the status "The room has been replaced...".
I found the link `#ruhaskell_meetup:gitter.im` in the messages of the room. I clicked to it and have joined to room successfully. 
Then I clicked on "... continues here" (link: https://matrix.to/#/#ruHaskell_meetup:gitter.im)

#### What did you expect?
Not that.
#### What happened instead?
Popup:
> #### Failed to load timeline position
> Tried to load a specific point in this room's timeline, but you do not have permission to view the message in question.

Console:
```
GET https://matrix-client.matrix.org/_matrix/client/r0/rooms/!jjkaaCVlXjzyslmmSJ%3Agitter.im/context/%24n1FjwdNlY2rGeHU0LK41G6CPRwOyjGbhRov7Wx0c25o?filter=%7B%22lazy_load_members%22%3Atrue%7D 403
fetch @ fetch.ts:62
Error loading timeline panel at !jjkaaCVlXjzyslmmSJ:gitter.im/$n1FjwdNlY2rGeHU0LK41G6CPRwOyjGbhRov7Wx0c25o M_FORBIDDEN: MatrixError: [403] You don't have permission to access that event. (https://matrix-client.matrix.org/_matrix/client/r0/rooms/!jjkaaCVlXjzyslmmSJ%3Agitter.im/context/%24n1FjwdNlY2rGeHU0LK41G6CPRwOyjGbhRov7Wx0c25o?filter=%7B%22lazy_load_members%22%3Atrue%7D)
    at c (vector://vector/webapp/bundles/.../vendors~init.js:2:1430935)
    at p.requestOtherUrl (vector://vector/webapp/bundles/.../vendors~init.js:2:3548382)
```

### Operating system

Windows

### Application version

1.11.23

### How did you install the app?

In-app update

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
> You don't have permission to access that event.

The issue is one of history permissions

@MadLittleMods could this possibly be the migration thing not setting the appropriate history visibility for the target of the tombstone?

**Comment by MadLittleMods** [comment]
I'm not sure what room that the `#gitter_ruhaskell=2Fmeetup:matrix.org` alias points to as it doesn't work now.

---

Joining [`#ruHaskell_meetup:gitter.im`](https://matrix.to/#/#ruHaskell_meetup:gitter.im) works as expected for me and lands me at `!jjkaaCVlXjzyslmmSJ:gitter.im`

History visibility (`m.room.history_visibility`) is set to `world_readable` for all public Gitter rooms.

The event in the 403 `/context` error, `$n1FjwdNlY2rGeHU0LK41G6CPRwOyjGbhRov7Wx0c25o`, is the `m.room.create` event in the room, so it definitely should be available/visible no matter what.

Doing `/join https://matrix.to/#/!jjkaaCVlXjzyslmmSJ:gitter.im/$n1FjwdNlY2rGeHU0LK41G6CPRwOyjGbhRov7Wx0c25o?via=matrix.org` reproduces the problem though. Seems like a Synapse issue? And I'm guessing Element picks the `m.room.create` event to continue reading from.

**Comment by MadLittleMods** [comment]
It looks like this is a duplicate of https://github.com/vector-im/element-web/issues/1230

---

> Doing `/join https://matrix.to/#/!jjkaaCVlXjzyslmmSJ:gitter.im/$n1FjwdNlY2rGeHU0LK41G6CPRwOyjGbhRov7Wx0c25o?via=matrix.org` (or using `gitter.im` via server) to mimic the request reproduces the problem (404/403 on `/context`). Seems like a Synapse issue? And I'm guessing Element picks the `m.room.create` event to continue reading from since it's the earliest event in the room.


In Synapse, given that we're in the `gitter.im` room, the `matrix.org` server knows about the `m.room.create` event for the state/auth chain. But it's probably just listed as an ["outlier"](https://github.com/matrix-org/synapse/blob/develop/docs/development/room-dag-concepts.md#outliers) which won't be returned for `/event` or `/context`.

It looks like this is just a case where `matrix.org` doesn't have the `m.room.create` event and the client `/event` and `/context` endpoints don't ask over federation to backfill it. Here are the issues tracking that problem:

 - https://github.com/matrix-org/synapse/issues/3848
 - https://github.com/matrix-org/synapse/issues/15263
 - The other thing that could help here is forwards fill on `/messages` since we could call `/messages?dir=f` and it would just work to pull the earliest messages in the room. (needs an MSC, related https://github.com/matrix-org/matrix-public-archive/issues/72)
 
This issue is probably better closed in favor of those issues but it does not to discount the fact that this is a really awful user experience.
