### ISSUE TITLE
The build fails due to "TypeError: Cannot read properties of undefined (reading 'date')"

### ISSUE THREAD

**Issue by luixxiul** [vector-im/element-web#24699]
### Steps to reproduce

1. Fresh install or create a PR on matrix-react-sdk to check build status

#### What did you expect?

The build should be successful.

#### What happened instead?

The build fails due to `TypeError: Cannot read properties of undefined (reading 'date')`.

````
2023-03-01 05:22:04.479 [element-js] ERROR in ../matrix-react-sdk/src/utils/exportUtils/exportCustomCSS.css (../matrix-react-sdk/node_modules/raw-loader/dist/cjs.js!../matrix-react-sdk/src/utils/exportUtils/exportCustomCSS.css)
2023-03-01 05:22:04.479 [element-js] Module build failed (from ../matrix-react-sdk/node_modules/raw-loader/dist/cjs.js):
2023-03-01 05:22:04.479 [element-js] TypeError: Cannot read properties of undefined (reading 'date')
2023-03-01 05:22:04.479 [element-js]     at extendFormats (/home/user/matrix-react-sdk/node_modules/ajv-keywords/keywords/_formatLimit.js:63:25)
2023-03-01 05:22:04.479 [element-js]     at defFunc (/home/user/matrix-react-sdk/node_modules/ajv-keywords/keywords/_formatLimit.js:54:5)
2023-03-01 05:22:04.479 [element-js]     at defineKeywords (/home/user/matrix-react-sdk/node_modules/ajv-keywords/index.js:17:22)
2023-03-01 05:22:04.479 [element-js]     at Object.<anonymous> (/home/user/matrix-react-sdk/node_modules/schema-utils/dist/validate.js:65:1)
2023-03-01 05:22:04.479 [element-js]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-03-01 05:22:04.479 [element-js]     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-03-01 05:22:04.479 [element-js]     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-03-01 05:22:04.479 [element-js]     at Module._load (node:internal/modules/cjs/loader:958:12)
2023-03-01 05:22:04.479 [element-js]     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-03-01 05:22:04.479 [element-js]     at require (node:internal/modules/cjs/helpers:110:18)
2023-03-01 05:22:04.479 [element-js]     at Object.<anonymous> (/home/user/matrix-react-sdk/node_modules/schema-utils/dist/index.js:6:5)
2023-03-01 05:22:04.479 [element-js]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-03-01 05:22:04.479 [element-js]     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-03-01 05:22:04.479 [element-js]     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-03-01 05:22:04.479 [element-js]     at Module._load (node:internal/modules/cjs/loader:958:12)
2023-03-01 05:22:04.479 [element-js]     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-03-01 05:22:04.479 [element-js]     at require (node:internal/modules/cjs/helpers:110:18)
2023-03-01 05:22:04.479 [element-js]     at Object.<anonymous> (/home/user/matrix-react-sdk/node_modules/raw-loader/dist/index.js:10:20)
2023-03-01 05:22:04.479 [element-js]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-03-01 05:22:04.479 [element-js]     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-03-01 05:22:04.479 [element-js]     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-03-01 05:22:04.479 [element-js]     at Module._load (node:internal/modules/cjs/loader:958:12)
2023-03-01 05:22:04.479 [element-js]     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-03-01 05:22:04.479 [element-js]     at require (node:internal/modules/cjs/helpers:110:18)
2023-03-01 05:22:04.479 [element-js]     at Object.<anonymous> (/home/user/matrix-react-sdk/node_modules/raw-loader/dist/cjs.js:3:16)
2023-03-01 05:22:04.479 [element-js]     at Module._compile (node:internal/modules/cjs/loader:1254:14)
2023-03-01 05:22:04.479 [element-js]     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
2023-03-01 05:22:04.479 [element-js]     at Module.load (node:internal/modules/cjs/loader:1117:32)
2023-03-01 05:22:04.479 [element-js]     at Module._load (node:internal/modules/cjs/loader:958:12)
2023-03-01 05:22:04.479 [element-js]     at Module.require (node:internal/modules/cjs/loader:1141:19)
2023-03-01 05:22:04.479 [element-js]     at require (node:internal/modules/cjs/helpers:110:18)
2023-03-01 05:22:04.479 [element-js]     at loadLoader (/home/user/element-web/node_modules/loader-runner/lib/loadLoader.js:18:17)
2023-03-01 05:22:04.479 [element-js]     at iteratePitchingLoaders (/home/user/element-web/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
2023-03-01 05:22:04.479 [element-js]     at runLoaders (/home/user/element-web/node_modules/loader-runner/lib/LoaderRunner.js:365:2)
2023-03-01 05:22:04.479 [element-js]     at NormalModule.doBuild (/home/user/element-web/node_modules/webpack/lib/NormalModule.js:295:3)
2023-03-01 05:22:04.479 [element-js]     at NormalModule.build (/home/user/element-web/node_modules/webpack/lib/NormalModule.js:446:15)
2023-03-01 05:22:04.479 [element-js]     at Compilation.buildModule (/home/user/element-web/node_modules/webpack/lib/Compilation.js:739:10)
2023-03-01 05:22:04.479 [element-js]     at /home/user/element-web/node_modules/webpack/lib/Compilation.js:981:14
2023-03-01 05:22:04.479 [element-js]     at /home/user/element-web/node_modules/webpack/lib/NormalModuleFactory.js:409:6
2023-03-01 05:22:04.479 [element-js]     at /home/user/element-web/node_modules/webpack/lib/NormalModuleFactory.js:155:13
2023-03-01 05:22:04.479 [element-js]     at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/user/element-web/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:42:1)
2023-03-01 05:22:04.479 [element-js]     at /home/user/element-web/node_modules/webpack/lib/NormalModuleFactory.js:138:29
2023-03-01 05:22:04.479 [element-js]     at /home/user/element-web/node_modules/webpack/lib/NormalModuleFactory.js:346:9
2023-03-01 05:22:04.479 [element-js]     at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
2023-03-01 05:22:04.480 [element-js] ℹ ｢wdm｣: Failed to compile.
````

### Will you send logs?

No

**Comment by luixxiul** [comment]
This seems to have broken the build: https://github.com/matrix-org/matrix-react-sdk/commit/5a3d9d682f58056c2cb88f74c4286be2bd13cdf7

**Comment by andybalaam** [comment]
Fixed in https://github.com/matrix-org/matrix-react-sdk/pull/10262 thanks @t3chguy !
