### ISSUE TITLE
Thread not marked as thread in the timeline

### ISSUE THREAD

**Issue by weeman1337** [vector-im/element-web#24750]
### Steps to reproduce

1. User A sends a message
2. User A replies to this message
3. User B reacts to the reply
4. User C starts a thread based on the reply

#### What did you expect?

Thread marked in timeline

#### What happened instead?

No thread in timeline

![image](https://user-images.githubusercontent.com/6216686/223102910-a01f1d77-9296-4203-91ad-8ba571f7a238.png)

### Operating system

Ubuntu 22.04.2 LTS

### Application version

Element Nightly version: 2023030501 Olm version: 3.2.12

### How did you install the app?

https://packages.element.io/debian/

### Homeserver

element.ems.host

### Will you send logs?

Yes

**Comment by weeman1337** [comment]
Found this error in console:

```
Uncaught (in promise) M_INVALID_PARAM: MatrixError: [400] event_id $98Mv3vKyK5ySYdhmQuwP05mlZaZ2AxMuwZE2aJ_CA34 is not related to thread $QpcFC52ASS7_iiX6TdM4JFvGu6cDf0vH78t5F7TxNqY (https://element.ems.host/_matrix/client/r0/rooms/!GUMgJVREVreXOrrahw%3Amatrix.org/receipt/m.read/%2498Mv3vKyK5ySYdhmQuwP05mlZaZ2AxMuwZE2aJ_CA34)
    at parseErrorResponse (vector://vector/webapp/bundles/478cfa754bb90b57ce0a/init.js:86258:12)
    at MatrixHttpApi.requestOtherUrl (vector://vector/webapp/bundles/478cfa754bb90b57ce0a/init.js:138516:86)
```
