### ISSUE TITLE
Flaky test loading-test.tsx

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#24769]
### Steps to reproduce

Sometimes we are getting test failures like this:

```
Error: Unable to fire a "change" event - please provide a DOM element.

    at createEvent (node_modules/@testing-library/dom/dist/events.js:27:11)
    at Function.createEvent.<computed> [as change] (node_modules/@testing-library/dom/dist/events.js:106:38)
    at Function.fireEvent.<computed> [as change] (node_modules/@testing-library/dom/dist/events.js:110:68)
    at Function.fireEvent.<computed> [as change] (node_modules/@testing-library/react/dist/fire-event.js:18:52)
    at change (test/app-tests/loading-test.tsx:634:19)
```

Example: https://github.com/vector-im/element-web/actions/runs/4363221945
(This passed on a re-run.)

**Comment by richvdh** [comment]
I think this file predates cypress (as in, the project itself, not just our use of it), and would be distinctly improved by a rewrite as a set of cypress tests.

**Comment by andybalaam** [comment]
[This failure](https://github.com/vector-im/element-web/actions/runs/4892632760) proves that I did not fix it :-(
