### ISSUE TITLE
"Error downloading audio" when recording a voice mesage

### ISSUE THREAD

**Issue by RayBB** [vector-im/element-web#24904]
### Steps to reproduce

1. I was in a 1:1 non encrypted chat
2. I clicked the button to record a voice messsage and talked for about a minute.
3. When I clicked stop recording it said: "Error downloading audio"

<img width="832" alt="image" src="https://user-images.githubusercontent.com/921217/227147839-7b2c66c7-f750-4b9a-b7dc-8826bf04b9e8.png">

#### What did you expect?
To be able to listen to and send my audio

#### What happened instead?
Can't listen to my audio or send it

### Operating system

macOS

### Application version

1.11.25

### How did you install the app?

https://packages.riot.im/desktop/install/macos/Element.dmg

### Homeserver

matrix.org

### Will you send logs?

Yes

**Comment by madduck** [comment]
I have the same problem on 1.11.65 on Linux, using Firefox:

![image](https://github.com/element-hq/element-web/assets/195073/aadcc737-c6dc-4a86-a366-63b257153e49)

It's notworthy that I can download the file and it'll play just fine in VLC, so not sure what the error actually is.

**Comment by t3chguy** [comment]
> so not sure what the error actually is.

Without sharing the logs, neither do we.

**Comment by t3chguy** [comment]
The original logs for this issue have expired

**Comment by madduck** [comment]
Let me know what you need. There is nothing in the browser console, and `/rageshake` doesn't work:

![image](https://github.com/element-hq/element-web/assets/195073/3b122de8-b3c8-4aec-9e1f-1cbbdb27ecbb)

PS: I accidentally filed this under "not in a browser" but I am actually just using Firefox, with my own 1.11.65.

**Comment by t3chguy** [comment]
@madduck you didn't file this issue, it was filed in 2023 by @RayBB.

If you want to contribute logs to this such that it isn't closed you'd need to reproduce on a client with rageshake configured, e.g. app.element.io or better yet develop.element.io

**Comment by madduck** [comment]
Done, submitted via develop

**Comment by t3chguy** [comment]
```
2024-04-26T11:08:37.408Z E Error decoding recording:  The buffer passed to decodeAudioData contains an unknown content type. (EncodingError | 0)
2024-04-26T11:08:37.408Z W Trying to re-encode to WAV instead...
2024-04-26T11:08:37.408Z D Decoder WASM path: https://develop.element.io/bundles/d45bd6959fe3a2a3b9d2/../../decoderWorker.min.wasm
2024-04-26T11:08:37.408Z E Caught decoding error: attempting to access detached ArrayBuffer
./matrix-react-sdk/src/audio/compat.ts/decodeOgg/<@https://develop.element.io/bundles/d45bd6959fe3a2a3b9d2/bundle.js:206308:24
decodeOgg@https://develop.element.io/bundles/d45bd6959fe3a2a3b9d2/bundle.js:206305:10
./matrix-react-sdk/src/audio/Playback.ts/prepare/this.audioBuf</<@https://develop.element.io/bundles/d45bd6959fe3a2a3b9d2/bundle.js:205555:58

2024-04-26T11:08:37.408Z E Error processing audio file: attempting to access detached ArrayBuffer
./matrix-react-sdk/src/audio/compat.ts/decodeOgg/<@https://develop.element.io/bundles/d45bd6959fe3a2a3b9d2/bundle.js:206308:24
decodeOgg@https://develop.element.io/bundles/d45bd6959fe3a2a3b9d2/bundle.js:206305:10
./matrix-react-sdk/src/audio/Playback.ts/prepare/this.audioBuf</<@https://develop.element.io/bundles/d45bd6959fe3a2a3b9d2/bundle.js:205555:58

2024-04-26T11:08:37.425Z error Unhandled promise rejection: EncodingError: The buffer passed to decodeAudioData contains an unknown content type.
```

@madduck can you share the `View Source` for the impacted event?

**Comment by madduck** [comment]
@t3chguy here you go:

```
{
  "type": "m.room.message",
  "content": {
    "body": "Voice message",
    "msgtype": "m.audio",
    "file": {
      "v": "v2",
      "key": {
        "alg": "A256CTR",
        "ext": true,
        "k": "tWZbUUgu7YqooPNuRAKb0E7sAjnjCLgUa8oqW5DN-Wk",
        "key_ops": [
          "encrypt",
          "decrypt"
        ],
        "kty": "oct"
      },
      "iv": "OSgZsfltb3AAAAAAAAAAAA",
      "hashes": {
        "sha256": "oRhIs49cQkE1BA+wx3IxVTYuaW1/HvHibKNtBNxCcWQ"
      },
      "url": "mxc://madduck.net/ZiNdsIhUUhucVCdjMepQPzrF"
    },
    "info": {
      "duration": 2817,
      "mimetype": "audio/ogg",
      "size": 3385
    },
    "org.matrix.msc1767.text": "Voice message",
    "org.matrix.msc1767.file": {
      "file": {
        "v": "v2",
        "key": {
          "alg": "A256CTR",
          "ext": true,
          "k": "tWZbUUgu7YqooPNuRAKb0E7sAjnjCLgUa8oqW5DN-Wk",
          "key_ops": [
            "encrypt",
            "decrypt"
          ],
          "kty": "oct"
        },
        "iv": "OSgZsfltb3AAAAAAAAAAAA",
        "hashes": {
          "sha256": "oRhIs49cQkE1BA+wx3IxVTYuaW1/HvHibKNtBNxCcWQ"
        },
        "url": "mxc://madduck.net/ZiNdsIhUUhucVCdjMepQPzrF"
      },
      "name": "Voice message.ogg",
      "mimetype": "audio/ogg",
      "size": 3385
    },
    "org.matrix.msc1767.audio": {
      "duration": 2817,
      "waveform": [
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0,
        0
      ]
    },
    "org.matrix.msc3245.voice": {},
    "m.mentions": {}
  }
}
```

**Comment by RinCat** [comment]
I encountered a similar issue. A user was sending multiple voice and it shows `Error downloading audio` after a few working ones. 

The ogg file can be downloaded.  The format looks ogg:
```
file Voice message.ogg 

Voice message.ogg: Ogg data, Opus audio, version 0.1, mono, 48000 Hz (Input Sample Rate)
```
But data invalid:
```
ffprobe Voice message.ogg          
                                                                                                                                                                                                                                        
ffprobe version 6.1.1 Copyright (c) 2007-2023 the FFmpeg developers
[ogg @ 0x5603710fa240] Cannot identify new stream
[ogg @ 0x5603710fa240] failed to create or replace stream
Voice message.ogg: Invalid data found when processing input
```

So it seems either ogg encoding issue or file decrypt issue.

**Comment by z411** [comment]
Hello, I'm having the same issue on Firefox Linux (139.0.1) and Element Linux. It happens with M4A/AAC files (OGG work). This is the JS trackback:

```
Error processing audio file: TypeError: attempting to access detached ArrayBuffer
    c compat.ts:36
    c compat.ts:33
    audioBuf Playback.ts:179
    audioBuf Playback.ts:169
    prepare Playback.ts:168
    componentDidMount AudioPlayerBase.tsx:52
    React 94
    C scheduler.production.js:144
    js scheduler.production.js:192
    Webpack 16
[rageshake.ts:69:16](webpack://element-web/src/rageshake/rageshake.ts)
    t rageshake.ts:69
    <anonymous> logger.ts:109
    componentDidMount AudioPlayerBase.tsx:53
    (Async: promise callback)
    componentDidMount AudioPlayerBase.tsx:52
    React 94
    C scheduler.production.js:144
    (Async: EventHandlerNonNull)
    js scheduler.production.js:192
    Webpack 16
```

The weird thing is that on Firefox Windows it works.

**Comment by alexander-potemkin** [comment]
Same issue. It started to appear all of the sudden last week.

But in my case it also affect 'usual' files to download - including images, I have to use mobile client to see them.

Any chance to get this fixed?

**Comment by OdinVex** [comment]
I just started getting this very recently too, maybe about a week. Only audio messages seem to be affected. They're my own messages from another client and they still play, the error message simply shows. I can download affected clips, too. They **are** decrypted (OggS header, etc).

Edit: I believe it's related to:
```
rageshake.ts:69 Error processing audio file: TypeError: Cannot perform Construct on a detached ArrayBuffer
    at new Uint8Array (<anonymous>)
    at compat.ts:35:28
    at new Promise (<anonymous>)
    at c (compat.ts:32:12)
    at r.prepare (Playback.ts:174:39)
```

Notice error origin, `src/audio/Playback.ts`.
