### ISSUE TITLE
Element Desktop crashes after a couple of time.

### ISSUE THREAD

**Issue by JokerGermany** [vector-im/element-web#25010]
### Steps to reproduce

Sadly - There is no way to reproduce

There is no pattern recognized.
It can crash when you do a voice call, it can crash when it's just in the Background.

It happens really frequent since a week or two

```
/opt/Element/element-desktop %U
/home/jokergermany/.config/Element exists: yes
/home/jokergermany/.config/Riot exists: no
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to de
Fetching translation json for locale: de
Resetting the UI components after locale change
Resetting the UI components after locale change
skipping config: /opt/Element/MangoHud.conf [ not found ]
skipping config: /home/jokergermany/.config/MangoHud/element-desktop.conf [ not found ]
parsing config: /home/jokergermany/.config/MangoHud/MangoHud.conf [ ok ]
MANGOHUD: Connected to D-Bus as ":1.164".
Changing application language to de
Fetching translation json for locale: de
Resetting the UI components after locale change
[11020:0401/131359.127838:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

I suppose this message to syslog has something to do with it:
`Apr  1 13:39:04 huppyryzen kernel: [ 2396.670871] traps: ThreadPoolForeg[11029] trap int3 ip:55c0dee68224 sp:7f02a11909d0 error:0 in element-desktop[55c0db5e2000+785e000]`

I found some messages like this before, but i am not sure if it has something to do with the crash
https://www.file-upload.net/download-15122443/_opt_Element_element-desktop.1000.crash.html

#### What did you expect?
Not to crash
#### What happened instead?
crashed anyway

### Operating system

Ubuntu Mate 22.04

### Application version
Version von Element: 1.11.26
Version von Olm: 3.2.12

_No response_

### Will you send logs?

Yes

**Comment by JokerGermany** [comment]
At the momentan i "try" to reproduce the bug with 1.11.28.
The Message when i start it is:
```
/opt/Element/element-desktop %U
Seshat unexpected error: Error: libcrypto.so.1.1: Kann die Shared-Object-Datei nicht Ã¶ffnen: Datei oder Verzeichnis nicht gefunden
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/opt/Element/resources/app.asar/node_modules/matrix-seshat/lib/index.js:16:22)
    at Module._compile (node:internal/modules/cjs/loader:1174:14) {
  code: 'ERR_DLOPEN_FAILED'
}
/home/jokergermany/.config/Element exists: yes
/home/jokergermany/.config/Riot exists: no
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to de
Fetching translation json for locale: de
skipping config: /opt/Element/MangoHud.conf [ not found ]
skipping config: /home/jokergermany/.config/MangoHud/element-desktop.conf [ not found ]
parsing config: /home/jokergermany/.config/MangoHud/MangoHud.conf [ ok ]
Resetting the UI components after locale change
MANGOHUD: Connected to D-Bus as ":1.240".
Resetting the UI components after locale change
Changing application language to de
Fetching translation json for locale: de
Resetting the UI components after locale change
[21792:0401/140359.134888:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018

```

**Comment by andybalaam** [comment]
Looks like this could be the same thing as https://github.com/vector-im/element-web/issues/24600

**Comment by t3chguy** [comment]
> How did you install the app?
No response

Needs info.

**Comment by JokerGermany** [comment]
https://github.com/Ubuntu-Installation/Installations-Script/blob/main/22-04.sh#L198
sudo wget -O /usr/share/keyrings/element-io-archive-keyring.gpg https://packages.element.io/debian/element-io-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https://packages.element.io/debian/ default main" | sudo tee /etc/apt/sources.list.d/element-io.list

**Comment by JokerGermany** [comment]
But looks like it's fixed with 28.
Don't crashed again since the update.

But the error at start ist new
Seshat unexpected error: Error: libcrypto.so.1.1: Kann die Shared-Object-Datei nicht Ã¶ffnen: Datei oder Verzeichnis nicht gefunden
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:2:1822)
    at Module._extensions..node (node:internal/modules/cjs/loader:1259:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:2:2049)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at Module.require (node:internal/modules/cjs/loader:1068:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (/opt/Element/resources/app.asar/node_modules/matrix-seshat/lib/index.js:16:22)
    at Module._compile (node:internal/modules/cjs/loader:1174:14) {
  code: 'ERR_DLOPEN_FAILED'
}

**Comment by t3chguy** [comment]
Fixed by https://github.com/vector-im/element-desktop/pull/606 - will be in next release

**Comment by t3chguy** [comment]
> Perhaps it has something to do with the libcrypto?

1.11.29 shouldn't depend on libcrypto, only on your system libsqlcipher0

**Comment by JokerGermany** [comment]
I can't reproduce it at the moment when i am starting it in the terminal therefore here is only the crash file
https://www.file-upload.net/download-15128403/_opt_Element_element-desktop.1000.crash.html

**Comment by JokerGermany** [comment]
https://www.file-upload.net/download-15129060/_opt_Element_element-desktop.1000.crash.html

```
Apr 14 09:12:06 huppyryzen dbus-daemon[1979]: [session uid=1000 pid=1979] Activating service name='org.freedesktop.Notifications' requested by ':1.72' (uid=1000 pid=2517 comm="/opt/Element/element-desktop --hidden " label="unconfined")
Apr 14 09:12:06 huppyryzen dbus-daemon[1979]: [session uid=1000 pid=1979] Successfully activated service 'org.freedesktop.Notifications'
Apr 14 09:12:24 huppyryzen kernel: [  828.027496] traps: ThreadPoolForeg[2748] trap int3 ip:55e4947aa8e4 sp:7fe19dd6e4f0 error:0 in element-desktop[55e490f23000+7859000]
Apr 14 09:12:24 huppyryzen systemd[1]: Starting Process error reports when automatic reporting is enabled...
Apr 14 09:12:24 huppyryzen systemd[1]: Started crash report submission.
Apr 14 09:12:24 huppyryzen whoopsie[8584]: [09:12:24] Using lock path: /var/lock/whoopsie/lock
Apr 14 09:12:24 huppyryzen systemd[1]: whoopsie.service: Deactivated successfully.
Apr 14 09:12:24 huppyryzen whoopsie-upload-all[8583]: INFO:root:/var/crash/_usr_bin_obs.1000.crash already marked for upload, skipping
Apr 14 09:12:24 huppyryzen whoopsie-upload-all[8583]: INFO:root:/var/crash/_usr_bin_marco.1000.crash already marked for upload, skipping
Apr 14 09:12:24 huppyryzen whoopsie-upload-all[8583]: INFO:root:/var/crash/_usr_bin_mate-session.1000.crash already marked for upload, skipping
Apr 14 09:12:24 huppyryzen whoopsie-upload-all[8583]: INFO:root:/var/crash/_usr_bin_mate-settings-daemon.1000.crash already marked for upload, skipping
Apr 14 09:12:24 huppyryzen systemd[1]: Started crash report submission.
Apr 14 09:12:24 huppyryzen whoopsie-upload-all[8583]: INFO:root:Collecting info for /var/crash/_opt_Element_element-desktop.1000.crash...
Apr 14 09:12:24 huppyryzen whoopsie[8588]: [09:12:24] Using lock path: /var/lock/whoopsie/lock
Apr 14 09:12:24 huppyryzen systemd[1]: whoopsie.service: Deactivated successfully.
Apr 14 09:12:28 huppyryzen whoopsie-upload-all[8583]: INFO:root:Marking /var/crash/_opt_Element_element-desktop.1000.crash for whoopsie upload
Apr 14 09:12:28 huppyryzen whoopsie-upload-all[8583]: INFO:root:Waiting for whoopsie to upload reports (timeout: 20 s)
Apr 14 09:12:28 huppyryzen whoopsie-upload-all[8583]: INFO:root:  missing (remaining: 20 s): /var/crash/_opt_Element_element-desktop.1000.uploaded
Apr 14 09:12:28 huppyryzen systemd[1]: Started crash report submission.
Apr 14 09:12:28 huppyryzen whoopsie[9312]: [09:12:28] Using lock path: /var/lock/whoopsie/lock
Apr 14 09:12:28 huppyryzen whoopsie[9312]: [09:12:28] Parsing /var/crash/_opt_Element_element-desktop.1000.crash.
Apr 14 09:12:28 huppyryzen whoopsie[9312]: [09:12:28] Uploading /var/crash/_opt_Element_element-desktop.1000.crash.
```

**Comment by JokerGermany** [comment]
```
/opt/Element/element-desktop %U
/home/jokergermany/.config/Element exists: yes
/home/jokergermany/.config/Riot exists: no
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to de
Fetching translation json for locale: de
Resetting the UI components after locale change
Resetting the UI components after locale change
skipping config: /opt/Element/MangoHud.conf [ not found ]
skipping config: /home/jokergermany/.config/MangoHud/element-desktop.conf [ not found ]
parsing config: /home/jokergermany/.config/MangoHud/MangoHud.conf [ ok ]
MANGOHUD: Connected to D-Bus as ":1.251".
Changing application language to de
Fetching translation json for locale: de
Resetting the UI components after locale change
[26788:0414/225749.976832:ERROR:nss_util.cc(357)] After loading Root Certs, loaded==false: NSS error code: -8018
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

syslog
`Apr 14 23:12:18 huppyryzen kernel: [ 7898.273916] traps: ThreadPoolForeg[26799] trap int3 ip:5631d44848e4 sp:7fb08a79cf50 error:0 in element-desktop[5631d0bfd000+7859000]`

**Comment by JokerGermany** [comment]
Okay this time it crashed so hard, that it lost is session =(
Send protocoll files
It crashes really often...

**Comment by JokerGermany** [comment]
Looks like deactivating message search stop the crashes...

**Comment by pipoprods** [comment]
I confirm this. When message search is active, Element crashes. No more crash when deactivated.

**Comment by andybalaam** [comment]
OK, so I the re-opened version of this is now a duplicate of #25114 and I'm closing it since that one is closed. Please re-open if I'm wrong.

**Comment by pipoprods** [comment]
The logic is hard to understand…
I opened #25114 that has been closed as duplicate of current bug. Now current bug is getting closed as duplicate of #25114. There's a snake eating its own tail problem here…

**Comment by lodex2** [comment]
Just stumbled upon this. I can confirm the problem and the temporary solution by disabling message search.

**Comment by andybalaam** [comment]
Argh, sorry my fault. I thought #25114 was closed because it was completed, but it was closed as a dup.

Re-opening.
