### ISSUE TITLE
Element-Desktopp can't save/download files (on Debian "Buster", ext4)

### ISSUE THREAD

**Issue by iohm5v8u94bz77b** [vector-im/element-web#25365]
### Steps to reproduce

It seems to be a bug, that my (actual) element-desktop (on debian "buster") is not capable to save files from others in chats and pms. It looks, as if it has write-permissions, because it is able to save its configuration and also to backup/export key-configuration locally. Also it makes a kind of "touch" on my filesystem, so the length of the "stored" files is 0 and thus they are empty. My filesystem-type is ext4...

Called on bash, it replies:
"
TypeError [ERR_INVALID_ARG_TYPE]: The "streams[stream.length - 1]" property must be of type function. Received an instance of WriteStream
    at popCallback (node:internal/streams/pipeline:68:3)
    at pipeline (node:internal/streams/pipeline:151:37)
    at /opt/Element/resources/app.asar/lib/webcontents-handler.js:148:51
    at Generator.next (<anonymous>)
    at fulfilled (/opt/Element/resources/app.asar/lib/webcontents-handler.js:20:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}
"

### Operating system

Debian "Buster"

### Application version

there is no command-line-option like "-v"

### How did you install the app?

per apt from https://packages.element.io/debian/

### Homeserver

According to "https://wiki.asra.gr/en:public_servers", a "Synapse 1.66.0" is running at digitale-gesellschaft.ch

### Will you send logs?

No

**Comment by t3chguy** [comment]
Is this relating to save/download or right-click `Save image as...`

**Comment by t3chguy** [comment]
Also Synapse 1.66.0 is very very out of date.
