### ISSUE TITLE
RoomListHeader/ContextMenuTooltipoButton: Unexpected concurrent DOM modification causing soft-crash

### ISSUE THREAD

**Issue by justjanne** [vector-im/element-web#25435]
```
2023-05-24T08:35:48.260Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (NotFoundError | 8)
2023-05-24T08:35:48.267Z E Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node. (NotFoundError | 8)
2023-05-24T08:35:48.268Z E The above error occurred while React was rendering the following components: 
    at div
    at h (webpack:///node_modules/matrix-react-sdk/src/components/views/elements/AccessibleButton.tsx:94:4)
    at m (webpack:///node_modules/matrix-react-sdk/src/components/views/elements/AccessibleTooltipButton.tsx:40:8)
    at d (webpack:///node_modules/matrix-react-sdk/src/accessibility/context_menu/ContextMenuTooltipButton.tsx:30:4)
    at div
    at qt (webpack:///node_modules/matrix-react-sdk/src/components/views/rooms/RoomListHeader.tsx:115:44)
    at div
    at div
    at _n (webpack:///node_modules/matrix-react-sdk/src/components/structures/LeftPanel.tsx:75:8)
    at div
    at nav
    at div
    at div
    at div
    at bu (webpack:///node_modules/matrix-react-sdk/src/components/structures/LoggedInView.tsx:140:8)
    at g (webpack:///node_modules/matrix-react-sdk/src/components/views/elements/ErrorBoundary.tsx:42:8)
    at $e (webpack:///node_modules/matrix-react-sdk/src/components/structures/MatrixChat.tsx:243:8)
```

**Comment by weeman1337** [comment]
@justjanne does this error cause anything visible to the user?

**Comment by justjanne** [comment]
@weeman1337 If you look at the rageshake, you'll see that it caused a soft-crash (that's the UI that days that part of the app has crashed with a button to reload that part).

IMO, that's user visible enough (though obviously still really uncommon)

**Comment by grinapo** [comment]
Well if that's my duplicate then it happens fairly often, got it about 5 times in the last few weeks. Pretty visible in my opinion, but that's only me.
