### ISSUE TITLE
Crash on "View Poll History"

### ISSUE THREAD

**Issue by padthaitofuhot** [vector-im/element-web#25573]
### Steps to reproduce

1. What can you see?
Central room view.  Left-hand room list sidebar open.  Right-hand sidebar looking at thread with deleted messages.

2. What did you click?
Room settings, "View Poll History"

3. No other steps.  However: **I recently deleted a poll from the room since users could not vote.**  Non-admin users of the room I was viewing reported permission denied errors when trying to send messages and vote in polls.  

#### What did you expect?
View poll history

#### What happened instead?
Something went wrong! window popped up.

### Operating system

Pop_OS! (Linux)

### Application version

Element version 1.11.33

### How did you install the app?

Flatpak

### Homeserver

localhost/matrixdotorg/synapse:v1.80.0-customized via matrix-docker-ansible-deploy

### Will you send logs?

Yes

**Comment by t3chguy** [comment]
```
2023-06-13T02:34:50.286Z E Cannot read properties of undefined (reading 'question')
TypeError: Cannot read properties of undefined (reading 'question')
    at new n (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:3182892)
    at t.parseMPoll (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:3178414)
    at e.value (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:4826512)
    at Function.value (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:4826134)
    at get unstableExtensibleEvent [as unstableExtensibleEvent] (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:277237)
    at _ (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:3411864)
    at aa (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:4911669)
    at Ys (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:4963794)
    at Ol (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:4951072)
    at Dl (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:4951000)
2023-06-13T02:34:50.291Z E Cannot read properties of undefined (reading 'question')
TypeError: Cannot read properties of undefined (reading 'question')
    at new n (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:3182892)
    at t.parseMPoll (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:3178414)
    at e.value (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:4826512)
    at Function.value (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:4826134)
    at get unstableExtensibleEvent [as unstableExtensibleEvent] (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:277237)
    at _ (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:3411864)
    at aa (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:4911669)
    at Ys (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:4963794)
    at Ol (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:4951072)
    at Dl (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:4951000)
2023-06-13T02:34:50.291Z E The above error occurred while React was rendering the following components: 
    at _ (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:3411839)
    at ol
    at div
    at O (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:3415433)
    at div
    at K (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:3419674)
    at div
    at Se (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:2590163)
    at div
    at m (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:1095915)
    at div
    at div
    at g (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:975146)
    at div
    at div
    at vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:3203129
    at _ (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:332442)
    at Ce (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:2590720)
    at g (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:3067385)
    at h (vector://vector/webapp/bundles/10d03808de0f3789e63e/bundle.js:2:3506328)
    at div
    at div
