### ISSUE TITLE
Element-R: stuck in a loop calling `/_matrix/client/v3/keys/signatures/upload`

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#25704]
Every time my client syncs, it makes a request to `/_matrix/client/v3/keys/signatures/upload` and then complains with:

```
Error processing outgoing-message requests from rust crypto-sdk Error: deserialization failed: missing field `error` at line 1 column 128
    at push.1685.module.exports.__wbindgen_error_new (matrix_sdk_crypto_js.js:6676:1)
    at <wasm_bindgen::JsError as core::convert::From<E>>::from::h66f6a8cb01617678 (01b16b46:0x313e37)
    at <matrix_sdk_crypto_js::responses::OwnedResponse as core::convert::TryFrom<(matrix_sdk_crypto_js::requests::RequestType,http::response::Response<alloc::vec::Vec<u8>>)>>::try_from::hde971358fe62519b (01b16b46:0x19b93b)
    at olmmachine_markRequestAsSent (01b16b46:0x2118e1)
    at OlmMachine.markRequestAsSent (matrix_sdk_crypto_js.js:3221:1)
    at OutgoingRequestProcessor.makeOutgoingRequest (OutgoingRequestProcessor.ts:99:35)
    at async RustCrypto.outgoingRequestLoop (rust-crypto.ts:876:21)
consoleObj.<computed> @ rageshake.ts:76
overrideMethod @ react_devtools_backend_compact.js:2367
(anonymous) @ logger.ts:48
outgoingRequestLoop @ rust-crypto.ts:880
await in outgoingRequestLoop (async)
onSyncCompleted @ rust-crypto.ts:770
doSync @ sync.ts:942
```

**Comment by richvdh** [comment]
The failure to parse the response is due to a bug in the rust-sdk; filed as https://github.com/matrix-org/matrix-rust-sdk/issues/2205#issuecomment-1619011812.

The question is why it is failing. The request payload is:

```json
{"@richvdh:sw1v.org":{"EOZDSWJVGZ":{"user_id":"@richvdh:sw1v.org","device_id":"EOZDSWJVGZ","algorithms":["m.megolm.v1.aes-sha2","m.olm.v1.curve25519-aes-sha2"],"keys":{"curve25519:EOZDSWJVGZ":"a1S+xfPfFBbrCteVaIDMtsIfU7bpzS7s/lLYFMIR3R4","ed25519:EOZDSWJVGZ":"ALUi8/AXqzob9EnRZQhY+o+dRIhyBTDsBvPcEAFocZY"},"signatures":{"@richvdh:sw1v.org":{"ed25519:MCiCKhj/vWl3f8M3ImlXP7G5qk4x9/bT+e6F28ZKlu8":"hpS/RcB7jX6/lpN/GwYj0JkbkWi+FuEWwbmi8BwDQq0MO+s28cpYiS0HvvD9wV+2MKpqfPiCit5ggJXkPqZMAg"}},"unsigned":{"device_display_name":"Element Android"}}}}
```

... ie, an attempt to sign `EOZDSWJVGZ` (the device I verified with) with `ed25519:MCiCKhj/vWl3f8M3ImlXP7G5qk4x9/bT+e6F28ZKlu8`.

However, my self-signing key is `ed25519:4CDFPgvgQryGrOAGLlscaauGQPLTLmlYKP/8VgLHzEo`. I don't really know where `ed25519:MCiCKhj/vWl3f8M3ImlXP7G5qk4x9/bT+e6F28ZKlu8` has come from.

**Comment by richvdh** [comment]
A reload broke the loop

**Comment by BillCarsonFr** [comment]
Check occurences of M_INVALID_SIGNATURE to know the severity? 
For now can't reproduce
