### ISSUE TITLE
Element-R: log spam when viewing Unable-to-decrypt event

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26272]
Whenever you open a room with a UISI event, this is spammed out to the logs:

```
Error getting encryption info on event Error: Can't find the room key to decrypt the event, withheld code: None
    __wbindgen_error_new matrix_sdk_crypto_wasm.js:6792
    __wbg_adapter_59 matrix_sdk_crypto_wasm.js:274
    real matrix_sdk_crypto_wasm.js:216
    promise callback*1796/</module.exports.__wbg_then_11f7a54d67b4bfad matrix_sdk_crypto_wasm.js:7573
    __wbg_adapter_56 matrix_sdk_crypto_wasm.js:270
    real matrix_sdk_crypto_wasm.js:252
    __wbg_setonsuccess_5f71593bc51653a3 matrix_sdk_crypto_wasm.js:7192
    __wbg_adapter_59 matrix_sdk_crypto_wasm.js:274
    real matrix_sdk_crypto_wasm.js:216
    promise callback*1796/</module.exports.__wbg_then_11f7a54d67b4bfad matrix_sdk_crypto_wasm.js:7573
    __wbg_adapter_56 matrix_sdk_crypto_wasm.js:270
    real matrix_sdk_crypto_wasm.js:252
    __wbg_setonsuccess_5f71593bc51653a3 matrix_sdk_crypto_wasm.js:7192
```

**Comment by richvdh** [comment]
There is a similar spam when viewing a message that is still being sent:

```
rageshake.ts:74 Error getting encryption info on event ~!UcgyhoigetVICUfvRw:matrix.org:m1698055312450.2 in room !UcgyhoigetVICUfvRw:matrix.org Error: leading sigil is incorrect or missing at line 1 column 62
    at push.1407.module.exports.__wbindgen_error_new (matrix_sdk_crypto_wasm.js:6834:1)
    at 011935b2:0x3c1df7
    at 011935b2:0x3d8214
    at 011935b2:0xb096c
    at 011935b2:0x24716f
    at 011935b2:0x294950
    at 011935b2:0x3f080a
    at __wbg_adapter_59 (matrix_sdk_crypto_wasm.js:274:1)
    at real (matrix_sdk_crypto_wasm.js:216:1)
```
