### ISSUE TITLE
[Disabled] Flaky cypress test: `Device verification` > `Verify device during login with QR code`

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26293]
https://github.com/matrix-org/matrix-js-sdk/pull/3770 / https://github.com/matrix-org/matrix-js-sdk/actions/runs/6395357104/job/17358911350#step:8:5058

```
     AssertionError: Timed out retrying after 10000ms: Unable to find an accessible element with the role "button" and name "Verify with another device"

 Here are the accessible roles:

 ...

  button:

  Name "Language Dropdown":
  <div
    aria-describedby="mx_LanguageDropdown_value"
    aria-disabled="true"
    aria-expanded="false"
    aria-haspopup="listbox"
    aria-label="Language Dropdown"
    aria-owns="mx_LanguageDropdown_input"
    class="mx_AccessibleButton mx_Dropdown_input mx_no_textinput mx_AccessibleButton_disabled"
    disabled=""
    role="button"
    tabindex="0"
  />

  Name "Help":
  <div
    aria-label="Help"
    class="mx_AccessibleButton mx_ServerPicker_help"
    role="button"
    tabindex="0"
  />

  Name "Edit":
  <div
    class="mx_AccessibleButton mx_ServerPicker_change mx_AccessibleButton_hasKind mx_AccessibleButton_kind_link"
    role="button"
    tabindex="0"
  />

  Name "Forgot password?":
  <div
    aria-disabled="true"
    class="mx_AccessibleButton mx_Login_forgot mx_AccessibleButton_hasKind mx_AccessibleButton_kind_link mx_AccessibleButton_disabled"
    disabled=""
    role="button"
    tabindex="0"
  />

  Name "Continue with OAuth test":
  <div
    class="mx_AccessibleButton mx_SSOButton"
    role="button"
    tabindex="0"
  />
```

Given the list of found roles, including "Continue with OAuth test", it might just have been slow to log in.

**Comment by richvdh** [comment]
This test is actually failing with multiple different problems:

 * https://github.com/matrix-org/matrix-js-sdk/actions/runs/6396609768/job/17362769571#step:8:1438: `findByRole	button, {name: Restore from Backup}`. I can also intermittently reproduce this locally. This check was added by #11686. 
 * https://github.com/matrix-org/matrix-js-sdk/actions/runs/6396609768/job/17362769571#step:8:6161: `     AssertionError: Timed out retrying after 10000ms: Expected container to be an Element, a Document or a DocumentFragment but got undefined.`

**Comment by richvdh** [comment]
Disabled the test for now for rust crypto in https://github.com/matrix-org/matrix-react-sdk/pull/11710

**Comment by richvdh** [comment]
Generally QR code verification seems a bit flaky. Trying it myself, after the "you've verified successfully!" banner, I saw this error in the logs:

```
rageshake.ts:74 WARN src/verification.rs:1277 Error calling changes callback: JsValue(Error: not implemented
Error: not implemented
    at get cancellationCode [as cancellationCode] (vector://vector/webapp/bundles/37a875d7a6ac3835fb69/34.js:2617:11)
    at Object.current (vector://vector/webapp/bundles/37a875d7a6ac3835fb69/bundle.js:201100:136)
    at RustVerificationRequest.eventListener (vector://vector/webapp/bundles/37a875d7a6ac3835fb69/bundle.js:20630:53)
    at RustVerificationRequest.emit (vector://vector/webapp/bundles/37a875d7a6ac3835fb69/bundle.js:59372:7)
    at RustVerificationRequest.emit (vector://vector/webapp/bundles/37a875d7a6ac3835fb69/bundle.js:48959:18)
    at onChange (vector://vector/webapp/bundles/37a875d7a6ac3835fb69/34.js:2312:12)
    at vector://vector/webapp/bundles/37a875d7a6ac3835fb69/37.js:7442:33
    at handleError (vector://vector/webapp/bundles/37a875d7a6ac3835fb69/37.js:346:18)
    at push.1377.module.exports.__wbg_call_97ae9d8645dc388b (vector://vector/webapp/bundles/37a875d7a6ac3835fb69/37.js:7441:66)
    at wasm://wasm/010897c6:wasm-function[9855]:0x38010e)
```

... and it seemed like the device was not, in fact, verified
