### ISSUE TITLE
[Disabled for Element-R] Flaky cypress test: `User verification > can receive a verification request when there is no existing DM`

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26420]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6612284097/job/17957827303#step:8:303

```
  1) User verification
       can receive a verification request when there is no existing DM:
     Error: The following error originated from your application code, not from Cypress. It was caused by an unhandled promise rejection.

  > Still no verifier after startSas() call

When Cypress detects uncaught errors originating from your application it will automatically fail the current test.

This behavior is configurable, and you can choose to turn this off by listening to the `uncaught:exception` event.

https://on.cypress.io/uncaught-exception-from-application
      at RustVerificationRequest.startVerification (http://localhost:8080/bundles/be6fdc548b71baaf015c/34.js:2629:13)
      at async (http://localhost:8080/bundles/be6fdc548b71baaf015c/bundle.js:202145:7)
```

**Comment by richvdh** [comment]
This is presumably an Element-R issue

**Comment by kerryarchibald** [comment]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6615782935/job/17968688123

**Comment by richvdh** [comment]
The problem here is that sometimes Alice's acceptance of the incoming verification request races with her `/keys/query` for Bob. Then we get:

```
WARN matrix_sdk_crypto::verification::requests: Can't create a QR code, the device that accepted the verification doesn't exist
    user_id="@bob_41:localhost" device_id="QTRATQPRBO"
    at /home/rav/work/matrix-rust-sdk/crates/matrix-sdk-crypto/src/verification/requests.rs:1217
```
