### ISSUE TITLE
Can not share full screen in Ubuntu (Wayland)

### ISSUE THREAD

**Issue by MatejKovacic** [vector-im/element-web#26458]
### Steps to reproduce

When I try to share entire screen, it is shared, but it is blank (black, actually). However, I can share application windows (but I am not sure if I can share all applications).

It seems it is a problem with Wayland screen sharing support. I have read that WebRTC should build with the enabled `rtc_use_pipewire` flag, maybe this is the issue here?

Also, this bug could be related: https://bugs.chromium.org/p/chromium/issues/detail?id=682122

#### What did you expect?
That screen sharing works

#### What happened instead?
Shared screen was blank.

### Operating system

Ubuntu 23.04

### Application version

Element version: 1.11.46 Olm version: 3.2.14

### How did you install the app?

Through Snap.

### Homeserver

matrix.org

### Will you send logs?

No

**Comment by t3chguy** [comment]
The snap package isn't maintained by us, please seek support from its maintainers.

**Comment by MatejKovacic** [comment]
No.

Snap maintainer is basically [ingesting the latest deb directly from upstream and bundling it in a snap](https://github.com/kenvandine/element-desktop/blob/3b91c25833950f3d3c49c46e0049d8f3bb263256/README.md#element-desktop). So it is no related to some Snap problem.

**Comment by t3chguy** [comment]
@MatejKovacic where instead they should probably be using the snap output of https://www.electron.build/ - Snaps are not the same as just running a binary.

> Without custom flags at installation, or subsequent [interface connections](https://snapcraft.io/docs/interface-management), snaps are confined to a restrictive security sandbox with no access to system resources outside of the snap.

**Comment by MatejKovacic** [comment]
OK, but why then sharing application windows is working (just full screen is not)?

Anyway, I will check with the snap packager also.

**Comment by t3chguy** [comment]
> OK, but why then sharing application windows is working

Electron/Chromium likely uses different APIs for those which are sandboxed differently - at the Web level they use the same API. https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getDisplayMedia / https://www.electronjs.org/docs/latest/api/desktop-capturer / https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia

**Comment by MatejKovacic** [comment]
Well, I installed officially supported version... and it is even weirder that the snap one.

I can not share anything, it just keeps me asking to share, and when I click Publish (Objavi), dialog window appears again.

![Zaslonska slika 2023-10-28 21-58-53](https://github.com/vector-im/element-web/assets/3339198/07f06fc4-b9c1-4538-819d-2d9f092e8575)

End even worse. When I cancel the call, I do not have a share screen button anymore...

**Comment by MatejKovacic** [comment]
Also, a terminal log:
```
/home/matej/.config/Element exists: yes
/home/matej/.config/Riot exists: no
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to sl,en
Fetching translation json for locale: sl
Could not fetch translation json for locale: 'sl' Error: Cannot find module './i18n/strings/sl.json'
Require stack:
- /opt/Element/resources/app.asar/lib/language-helper.js
- /opt/Element/resources/app.asar/lib/tray.js
- /opt/Element/resources/app.asar/lib/settings.js
- /opt/Element/resources/app.asar/lib/ipc.js
- /opt/Element/resources/app.asar/lib/electron-main.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/browser_init:2:117419)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at AppLocalization.fetchTranslationJson (/opt/Element/resources/app.asar/lib/language-helper.js:86:20)
    at /opt/Element/resources/app.asar/lib/language-helper.js:99:39
    at Array.filter (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element/resources/app.asar/lib/language-helper.js:98:39) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element/resources/app.asar/lib/language-helper.js',
    '/opt/Element/resources/app.asar/lib/tray.js',
    '/opt/Element/resources/app.asar/lib/settings.js',
    '/opt/Element/resources/app.asar/lib/ipc.js',
    '/opt/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Fetching translation json for locale: en
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to en
Fetching translation json for locale: en
Resetting the UI components after locale change
[9117:1028/215801.815775:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[9117:1028/215804.107619:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[9125:1028/215818.058285:ERROR:turn_port.cc(1836)] Received TURN CreatePermission error response, code=403; pruned connection.
[9125:1028/215818.060087:ERROR:turn_port.cc(1836)] Received TURN CreatePermission error response, code=403; pruned connection.
[9125:1028/215818.060260:ERROR:turn_port.cc(1836)] Received TURN CreatePermission error response, code=403; pruned connection.
[9125:1028/215818.060388:ERROR:turn_port.cc(1836)] Received TURN CreatePermission error response, code=403; pruned connection.
[9125:1028/215818.060551:ERROR:turn_port.cc(1836)] Received TURN CreatePermission error response, code=403; pruned connection.
[9125:1028/215818.060706:ERROR:turn_port.cc(1836)] Received TURN CreatePermission error response, code=403; pruned connection.
[9125:1028/215850.872039:ERROR:stun_port.cc(99)] Binding request timed out from 192.168.64.x:56845 (wlp3s0)
[9125:1028/215950.216924:ERROR:turn_port.cc(1836)] Received TURN CreatePermission error response, code=403; pruned connection.
[9125:1028/215950.217682:ERROR:turn_port.cc(1836)] Received TURN CreatePermission error response, code=403; pruned connection.
[9125:1028/215950.217802:ERROR:turn_port.cc(1836)] Received TURN CreatePermission error response, code=403; pruned connection.
[9125:1028/215950.217910:ERROR:turn_port.cc(1836)] Received TURN CreatePermission error response, code=403; pruned connection.
[9125:1028/215950.218837:ERROR:turn_port.cc(1836)] Received TURN CreatePermission error response, code=403; pruned connection.
[9125:1028/215950.218925:ERROR:turn_port.cc(1836)] Received TURN CreatePermission error response, code=403; pruned connection.
```

**Comment by MatejKovacic** [comment]
I have got reply from people preparing snap package. They also say this bug is not specific to the snap package. They have seen the same behaviour with the official deb package.

Can anyone look into this?
