### ISSUE TITLE
Flaky matrix-js-sdk jest test: `SAS verification › verification › should verify a cross-signing key`

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26499]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/6743827349/job/18332493604#step:6:2777

```
 FAIL  spec/unit/crypto/verification/sas.spec.ts (6.301 s)
  ● SAS verification › verification › should verify a cross-signing key

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      343 |         });
      344 |
    > 345 |         it("should verify a cross-signing key", async () => {
          |         ^
      346 |             alice.httpBackend.when("POST", "/keys/device_signing/upload").respond(200, {});
      347 |             alice.httpBackend.when("POST", "/keys/signatures/upload").respond(200, {});
      348 |             alice.httpBackend.flush(undefined, 2);

      at it (spec/unit/crypto/verification/sas.spec.ts:345:9)
      at describe (spec/unit/crypto/verification/sas.spec.ts:75:5)
      at Object.describe (spec/unit/crypto/verification/sas.spec.ts:37:1)
```

This is a unit test for *legacy* crypto, so unlikely to be worth fixing.

**Comment by richvdh** [comment]
Since this apparently hasn't happened since November, let's close it.
