### ISSUE TITLE
Element Desktop Nightly does not start

### ISSUE THREAD

**Issue by jaywink** [vector-im/element-web#26531]
### Steps to reproduce

After upgrading to this nightly version, app started. After reboot of computer it started, but only loaded a white screen. After closing that, clicking the icon does nothing. Executing from shell shows a core dump:

```
$ element-desktop-nightly 
/home/jaywink/.config/Element-Nightly exists: yes
/home/jaywink/.config/Riot-Nightly exists: no
Disabling hardware acceleration.
Enabling Sentry with dsn=https://029a0eb289f942508ae0fb17935bd8c5@sentry.matrix.org/6 environment=nightly
Starting auto update with base URL: https://packages.element.io/nightly/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to en-us
Fetching translation json for locale: en-us
Could not fetch translation json for locale: 'en-us' Error: Cannot find module './i18n/strings/en_US.json'
Require stack:
- /opt/Element-Nightly/resources/app.asar/lib/language-helper.js
- /opt/Element-Nightly/resources/app.asar/lib/tray.js
- /opt/Element-Nightly/resources/app.asar/lib/settings.js
- /opt/Element-Nightly/resources/app.asar/lib/ipc.js
- /opt/Element-Nightly/resources/app.asar/lib/electron-main.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/browser_init:2:116646)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at AppLocalization.fetchTranslationJson (/opt/Element-Nightly/resources/app.asar/lib/language-helper.js:86:20)
    at /opt/Element-Nightly/resources/app.asar/lib/language-helper.js:99:39
    at Array.filter (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element-Nightly/resources/app.asar/lib/language-helper.js:98:39) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element-Nightly/resources/app.asar/lib/language-helper.js',
    '/opt/Element-Nightly/resources/app.asar/lib/tray.js',
    '/opt/Element-Nightly/resources/app.asar/lib/settings.js',
    '/opt/Element-Nightly/resources/app.asar/lib/ipc.js',
    '/opt/Element-Nightly/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
Resetting the UI components after locale change
[10103:1108/162308.001197:ERROR:nss_util.cc(239)] Error initializing NSS with a persistent database (sql:/home/jaywink/.pki/nssdb): NSS error code: -8023
[10103:1108/162308.001260:ERROR:nss_util.cc(124)] Error initializing NSS without a persistent database: NSS error code: -8023
[10103:1108/162308.001264:FATAL:nss_util.cc(126)] nss_error=-8023, os_error=0
Trace/breakpoint trap (core dumped)

```

Any ideas how to clear?

#### What did you expect?

The application starts.

#### What happened instead?

Core dump.

### Operating system

Ubuntu 22.04.3 LTS

### Application version

2023110801

### How did you install the app?

Official deb repo

### Homeserver

element.io

### Will you send logs?

No

**Comment by t3chguy** [comment]
Cannot reproduce

![image](https://github.com/vector-im/element-web/assets/2403652/f6f5cd70-c37b-4bf6-b6a5-a266cd60240a)
