### ISSUE TITLE
Broken Jest test: EditWysiwygComposer › Should not render the component when not ready

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26603]
```
FAIL test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx (11.356 s)
  ● EditWysiwygComposer › Should not render the component when not ready

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      60 |     });
      61 |
    > 62 |     it("Should not render the component when not ready", async () => {
         |     ^
      63 |         // When
      64 |         const { rerender } = customRender(false);
      65 |         await waitFor(() => expect(screen.getByRole("textbox")).toHaveAttribute("contentEditable", "true"));

      at it (test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx:62:5)
      at Object.describe (test/components/views/rooms/wysiwyg_composer/EditWysiwygComposer-test.tsx:35:1)
```

https://github.com/matrix-org/matrix-react-sdk/actions/runs/6905611035/job/18788791126?pr=11899 and many others

**Comment by richvdh** [comment]
It passes locally, but does take 3 seconds. I can well believe that would be 5 seconds when running on a slower hosted CI worker.

**Comment by richvdh** [comment]
In the logs, I see:

```
  console.warn
    `WebAssembly.instantiateStreaming` failed because your server does not serve wasm with `application/wasm` MIME type. Falling back to `WebAssembly.instantiate` which is slower. Original error:
     TypeError [ERR_INVALID_ARG_TYPE]: The "source" argument must be an instance of Response or an Promise resolving to Response. Received an instance of Response
        at new NodeError (node:internal/errors:399:5)
        at node:internal/wasm_web_api:24:13 {
      code: 'ERR_INVALID_ARG_TYPE'
    }
```

... which seems relevant?
