### ISSUE TITLE
Unable to get session lock

### ISSUE THREAD

**Issue by adoeppner** [vector-im/element-web#26642]
### Steps to reproduce

1. I open the element-client on the system
2. I get a message `Element is open in another window. Click "Fortfahren" to use Element here and disconnect the other windows.` There are actually no other windows, the started process is the only running element process.

![image](https://github.com/vector-im/element-web/assets/95691011/cb87602b-fb55-4fe0-8731-ba83399062d2)

3. Then I click on continue and get an forever spinner. In the devtools I see a message like this:

```
getSessionLock[<<uuid>>] Last ping (from <<uuid>>) was -16014021ms ago, waiting
```

The negative milliseconds seem strange. I reinstalled the app to the newest version, restarted my system once or twice and killed all element-desktop processes by hand. Nothing seems to resolve the issue. In the webbrowser on the same machine it works without any problems. 

When starting the process over the console I get some stack traces regarding the language.

```
➜  ~ element-desktop
/home/aaron/.config/Element exists: yes
/home/aaron/.config/Riot exists: no
Starting auto update with base URL: https://packages.element.io/desktop/update/
Auto update not supported on this platform
Fetching translation json for locale: en_EN
Changing application language to de
Fetching translation json for locale: de
Could not fetch translation json for locale: 'de' Error: Cannot find module './i18n/strings/de.json'
Require stack:
- /opt/Element/resources/app.asar/lib/language-helper.js
- /opt/Element/resources/app.asar/lib/tray.js
- /opt/Element/resources/app.asar/lib/settings.js
- /opt/Element/resources/app.asar/lib/ipc.js
- /opt/Element/resources/app.asar/lib/electron-main.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/browser_init:2:116646)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at AppLocalization.fetchTranslationJson (/opt/Element/resources/app.asar/lib/language-helper.js:86:20)
    at /opt/Element/resources/app.asar/lib/language-helper.js:99:39
    at Array.filter (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element/resources/app.asar/lib/language-helper.js:98:39) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element/resources/app.asar/lib/language-helper.js',
    '/opt/Element/resources/app.asar/lib/tray.js',
    '/opt/Element/resources/app.asar/lib/settings.js',
    '/opt/Element/resources/app.asar/lib/ipc.js',
    '/opt/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change
Resetting the UI components after locale change
Changing application language to de
Fetching translation json for locale: de
Could not fetch translation json for locale: 'de' Error: Cannot find module './i18n/strings/de.json'
Require stack:
- /opt/Element/resources/app.asar/lib/language-helper.js
- /opt/Element/resources/app.asar/lib/tray.js
- /opt/Element/resources/app.asar/lib/settings.js
- /opt/Element/resources/app.asar/lib/ipc.js
- /opt/Element/resources/app.asar/lib/electron-main.js
- 
    at node:internal/modules/cjs/loader:1084:15
    at Function._resolveFilename (node:electron/js2c/browser_init:2:116646)
    at node:internal/modules/cjs/loader:929:27
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at Module.require (node:internal/modules/cjs/loader:1150:19)
    at require (node:internal/modules/cjs/helpers:121:18)
    at AppLocalization.fetchTranslationJson (/opt/Element/resources/app.asar/lib/language-helper.js:86:20)
    at /opt/Element/resources/app.asar/lib/language-helper.js:99:39
    at Array.filter (<anonymous>)
    at AppLocalization.setAppLocale (/opt/Element/resources/app.asar/lib/language-helper.js:98:39) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/Element/resources/app.asar/lib/language-helper.js',
    '/opt/Element/resources/app.asar/lib/tray.js',
    '/opt/Element/resources/app.asar/lib/settings.js',
    '/opt/Element/resources/app.asar/lib/ipc.js',
    '/opt/Element/resources/app.asar/lib/electron-main.js',
    undefined
  ]
}
Resetting the UI components after locale change

```

#### What did you expect?

A login into the element account.

#### What happened instead?

A forever spinner.

### Operating system

Ubuntu

### Application version

1.11.50 (from apt install)

### How did you install the app?

https://element.io/download

### Homeserver

non-public homeserver

### Will you send logs?

No

**Comment by adoeppner** [comment]
Resolved itself somehow.
