### ISSUE TITLE
Flaky Jest test `createMessageContent › Richtext composer input › Should create html message`

### ISSUE THREAD

**Issue by andybalaam** [vector-im/element-web#26650]
I saw this in one of my PRs, and then also here:

https://github.com/matrix-org/matrix-react-sdk/actions/runs/7003936866/job/19050658498?pr=11942
(for PR https://github.com/matrix-org/matrix-react-sdk/pull/11942 )

```
FAIL test/components/views/rooms/wysiwyg_composer/utils/createMessageContent-test.ts (8.642 s)
  ● createMessageContent › Richtext composer input › Should create html message

    thrown: "Exceeded timeout of 5000 ms for a test.
    Add a timeout value to this test to increase the timeout, if this is a long-running test. See https://jestjs.io/docs/api#testname-fn-timeout."

      43 |
      44 |     describe("Richtext composer input", () => {
    > 45 |         it("Should create html message", async () => {
         |         ^
      46 |             // When
      47 |             const content = await createMessageContent(message, true, { permalinkCreator });
      48 |

      at it (test/components/views/rooms/wysiwyg_composer/utils/createMessageContent-test.ts:45:9)
      at describe (test/components/views/rooms/wysiwyg_composer/utils/createMessageContent-test.ts:44:5)
      at Object.describe (test/components/views/rooms/wysiwyg_composer/utils/createMessageContent-test.ts:25:1)
```

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/7004851365

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/7004896043

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/7022979481/job/19108448409?pr=11963

**Comment by t3chguy** [comment]
https://github.com/matrix-org/matrix-react-sdk/actions/runs/7022999214/job/19108511388?pr=11967
