### ISSUE TITLE
Flaky Cypress test: Read receipts > new messages >      in threads >           Sending a new different-thread message after marking as read makes it unread

### ISSUE THREAD

**Issue by richvdh** [vector-im/element-web#26679]
https://github.com/matrix-org/matrix-js-sdk/actions/runs/7036590881/job/19149559649#step:8:194

```
 1) Read receipts
       new messages
         in threads
           Sending a new different-thread message after marking as read makes it unread:

      Timed out retrying after 10000ms
      + expected - actual

      -'2'
      +'1'
      
      at Context.eval (webpack://matrix-react-sdk/./cypress/e2e/read-receipts/read-receipts-utils.ts:442:0)
```

**Comment by richvdh** [comment]
For the record, this test was disabled until matrix-org/matrix-react-sdk#11903

**Comment by dbkr** [comment]
Sadly this doesn't look like it's fixed the flake: it's still failed twice with this fix in https://github.com/matrix-org/matrix-react-sdk/actions/runs/7087197140 and https://github.com/matrix-org/matrix-react-sdk/actions/runs/7086785624 both of which were on b02ff16a21bf7f064c228329ec182f36d6a593e5 which has the fix.

**Comment by richvdh** [comment]
links to the relevant failures:

https://github.com/matrix-org/matrix-react-sdk/actions/runs/7087197140/job/19286936806#step:8:189
https://github.com/matrix-org/matrix-react-sdk/actions/runs/7086785624/job/19285717668#step:8:188

both have failed with different errors to before:

```

  1) Read receipts
       new messages
         in threads
           Sending a new different-thread message after marking as read makes it unread:
     AssertionError: Timed out retrying after 10000ms: Expected <span.mx_NotificationBadge_count> not to exist in the DOM, but it was continuously found.
      at Context.eval (webpack://matrix-react-sdk/./cypress/e2e/read-receipts/read-receipts-utils.ts:418:0)
```
