### ISSUE TITLE
Cannot video call after laptop has been suspended

### ISSUE THREAD

**Issue by TheLastProject** [vector-im/element-web#5046]
### Description

After suspending the laptop and waking it again, it is impossible to video call. Any attempt will instantly show "<User> ended the call. (unknown failure: user_media_failed). The following is printed in the terminal:

```
Unhandled exception TypeError: powerSaveBlockerId.isStarted is not a function                                       
    at EventEmitter.<anonymous> (<hidden>/electron_app/src/electron-main.js:87:58)            
    at emitTwo (events.js:106:13)                         
    at EventEmitter.emit (events.js:194:7)                
    at WebContents.<anonymous> (<hidden>/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:247:13)
    at emitTwo (events.js:106:13)                         
    at WebContents.emit (events.js:194:7)                 
```

### Steps to reproduce

- Suspend laptop
- Unsuspend laptop
- Ask friend to call you (have not tried calling myself)

Log: not sent

### Version information

- **Platform**: desktop
- **OS**: Fedora 26 KDE
- **Version**: 0.12.3

**Comment by t3chguy** [comment]
that error is unrelated, but is a fun bug that you helped me spot
its riot being unable to removing the sleep-lock it has placed (which prevents your PC from automatically suspending)

The log we would need is out of chromium/electron itself, you can launch the console using <kbd>Ctrl</kbd> <kbd>Shift</kbd> <kbd>I</kbd>

**Comment by SimonBrandner** [comment]
@TheLastProject, have you ever seen this again?

**Comment by TheLastProject** [comment]
I haven't tried in forever. Given how this issue is almost 4 years old, it is probably no longer relevant.
