### ISSUE TITLE
Sync Error when switching to certain rooms crashes UI

### ISSUE THREAD

**Issue by BenBE** [vector-im/element-web#5778]
### Description

When using the Riot web client in Palemoon (27.6.2, fork of Firefox) the UI crashes when switching to certain rooms (couldn't make out a pattern yet, but rooms that crash keep crashing after reload). I can click on other rooms, but they wont get activated. Also hitting ENTER when sending a message just inserts a new line in the input field - if the UI is even complete (sometimes the list of users in the room is completely missing.

### Steps to reproduce

- Login (tested with both https://matrix.toppoint.de/ as well as https://riot.im/develop/)
- Navigate to some affected room
- Notice the following error in JS console:
```
"/sync error Error: CORS request rejected: https://matrix.toppoint.de/_matrix/client/r0/sync?filter=8&timeout=30000&set_presence=offline&since=s2001992_38936330_11288_1910727_42812_265_10851_111372_1" bundle.js:56412:21
monkeyPatch/</consoleObj[fnName]() bundle.js:56412
SyncApi.prototype._onSyncError() bundle.js:236429
_callee$() bundle.js:236315
tryCatch() bundle.js:238851
invoke() bundle.js:239085
defineIteratorMethods/</prototype[method]() bundle.js:238903
tryCatcher() bundle.js:1632
module.exports/PromiseSpawn.prototype._promiseRejected() bundle.js:60910
module.exports/Promise.prototype._settlePromise() bundle.js:62082
module.exports/Promise.prototype._rejectPromises() bundle.js:62184
module.exports/Promise.prototype._settlePromises() bundle.js:62196
Async.prototype._drainQueue() bundle.js:59173
Async.prototype._drainQueues() bundle.js:59183
Async/this.drainQueues() bundle.js:59057

Error: CORS request rejected: https://matrix.toppoint.de/_matrix/client/r0/sync?filter=8&timeout=30000&set_presence=offline&since=s2001992_38936330_11288_1910727_42812_265_10851_111372_1
Stack trace:
on_response@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:104710:23
on_state_change@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:104685:8
 bundle.js:56412:21
monkeyPatch/</consoleObj[fnName]() bundle.js:56412
SyncApi.prototype._onSyncError() bundle.js:236430
_callee$() bundle.js:236315
tryCatch() bundle.js:238851
invoke() bundle.js:239085
defineIteratorMethods/</prototype[method]() bundle.js:238903
tryCatcher()

"Caught /sync error" "e.exports<.componentDidUpdate@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:13:20122
a</e.prototype.notifyAll@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:69:22257
m.close@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:143:9198
i.closeAll@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:10150
i.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:9642
i.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:9562
.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:14:7820
x@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:14:7997
i.closeAll@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:10150
i.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:9642
d.batchedUpdates@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:143:2273
l@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:14:6947
r@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:47:29579
u<.enqueueSetState@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:47:30722
r.prototype.setState@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:70:5272
e.exports<._updateList<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:125:27076
e.exports/r@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:15:26919
e.exports<.onRoomStateMember@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:125:26637
n.prototype.emit@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:13:13264
c</<.value@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:63:26772
n.prototype.emit@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:13:13154
o.prototype.setStateEvents/<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:65:3622
e.exports.forEach@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:6:1298
o.prototype.setStateEvents@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:65:2979
r.prototype.addEvent@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:15:26117
r.prototype.addEventToTimeline@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:46:14209
r.prototype.addLiveEvent@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:46:14096
i.prototype._addLiveEvent@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:65:12439
i.prototype.addLiveEvents@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:65:15383
a.prototype._processRoomEvents@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:111:4676
e/<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:111:452
r@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:82:27709
u/<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:82:28756
s/</e[t]@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:82:27885
o@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:1:18655
e.exports/l.prototype._promiseFulfilled@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:37:12704
e.exports/e.coroutine/<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:37:14550
e/</</<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:111:924
o@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:1:18655
f@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:38:17673
c@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:38:17555
o@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:1:18655
e.exports/i.prototype._settlePromiseFromHandler@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:38:1020
e.exports/i.prototype._settlePromise@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:38:1823
e.exports/i.prototype._settlePromiseCtx@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:38:2331
r.prototype._drainQueue@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:36:19462
r.prototype._drainQueues@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:36:19537
r/this.drainQueues@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:36:17694
"

"Unhandled rejection e.exports<.componentDidUpdate@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:13:20122
a</e.prototype.notifyAll@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:69:22257
m.close@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:143:9198
i.closeAll@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:10150
i.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:9642
i.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:9562
.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:14:7820
x@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:14:7997
i.closeAll@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:10150
i.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:9642
d.batchedUpdates@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:143:2273
l@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:14:6947
r@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:47:29579
u<.enqueueSetState@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:47:30722
r.prototype.setState@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:70:5272
P<.onSync@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:117:2384
n.prototype.emit@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:13:13264
a.prototype._updateSyncState@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:111:5143
e/<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:110:28289
r@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:82:27709
u/<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:82:28756
s/</e[t]@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:82:27885
o@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:1:18655
e.exports/l.prototype._promiseFulfilled@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:37:12704
r.prototype._drainQueue@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:36:19462
r.prototype._drainQueues@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:36:19537
r/this.drainQueues@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:36:17694
"
```

```
"Unhandled rejection componentDidUpdate@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:12309:10
measureLifeCyclePerf@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:275280:13
ReactCompositeComponent._performComponentUpdate/<@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:275933:12
notifyAll@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:113808:10
ON_DOM_READY_QUEUEING.close@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:280308:6
TransactionImpl.closeAll@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:46849:12
TransactionImpl.perform@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:46796:12
TransactionImpl.perform@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:46783:14
.perform@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:15433:13
flushBatchedUpdates@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:15516:8
TransactionImpl.closeAll@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:46849:12
TransactionImpl.perform@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:46796:12
ReactDefaultBatchingStrategy.batchedUpdates@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:278683:15
enqueueUpdate@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:15544:6
enqueueUpdate@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:70223:4
ReactUpdateQueue.enqueueSetState@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:70417:6
ReactComponent.prototype.setState@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:116432:4
onSync@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:132066:10
EventEmitter.prototype.emit@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:14007:8
SyncApi.prototype._updateSyncState@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:237195:6
_callee$@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:236391:26
tryCatch@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:238851:38
invoke@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:239085:23
defineIteratorMethods/</prototype[method]@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:238903:17
tryCatcher@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:1632:17
module.exports/PromiseSpawn.prototype._promiseFulfilled@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:60901:19
Async.prototype._drainQueue@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:59178:10
Async.prototype._drainQueues@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:59183:6
Async/this.drainQueues@https://riot.im/develop/bundles/ecd0342dd782daec1dd8/bundle.js:59057:10
"
```

Describe how what happens differs from what you expected.

I'd expect the UI to indicate some problem instead of crashing and showing some weird behavior.

Log: not sent

### Version information

- **Platform**: web

For the web app:

- **Browser**: Palemoon 27.6.2
- **OS**: Windows 7, x64?
- **URL**: 
  - riot.im/develop
    - matrix-react-sdk version: <local>
    - riot-web version: cc4890f0b864-react-641add4964ba-js-4ad153c4251c
    - olm version: 2.2.1
  - matrix.toppoint.de
    - matrix-react-sdk version: 0.11.1
    - riot-web version: 0.13.1
    - olm version: 2.2.1

**Comment by MTRNord** [comment]
Might be intresting to know what the http error for the cors error is. (also I never had that Problem yet)

**Comment by BenBE** [comment]
A somewhat more complete log, shortened to remove outgoing key requests and HTTP GETs that did 200 OK:

```
GET 
https://matrix.toppoint.de/#/room/!hvHHdEYFIZGufBEVBR:toppoint.de [HTTP/1.1 200 OK 62ms]
An IndexedDB transaction that was not yet complete has been aborted due to page navigation. bundle.js:35:0
Successfully compiled asm.js code (total compilation time 67ms; unable to cache asm.js in synchronous scripts; try loading asm.js via <script async> or createElement('script')) olm.js
mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create bundle.js:82:30914
calling a builtin ArrayBuffer constructor without new is deprecated and will be forbidden in ES6 bundle.js:39:16850
calling a builtin typed array constructor without new is deprecated and will be forbidden in ES6 bundle.js:14:15130
GET 
XHR 
https://matrix.toppoint.de/i18n/languages.json [HTTP/1.1 200 OK 8ms]
"Initialised rageshake: See https://bugs.chromium.org/p/chromium/issues/detail?id=583193 to fix line numbers on Chrome." bundle.js:35:18920
GET 
XHR 
https://matrix.toppoint.de/i18n/en_US.json [HTTP/1.1 200 OK 70ms]
"set language to en-us" bundle.js:35:18920
"Removing logs: " Array [ "instance-0.214974565790763131507797…" ] bundle.js:35:18920
"Removed 1 old logs." bundle.js:35:18920
GET 
XHR 
https://matrix.toppoint.de/config.matrix.toppoint.de.json [HTTP/1.1 404 Not Found 27ms]
"Vector starting at https://matrix.toppoint.de/#/room/!hvHHdEYFIZGufBEVBR:toppoint.de" bundle.js:35:18920
"Restoring session for @BenBE:toppoint.de" bundle.js:35:18920
"setLoggedIn: mxid: @BenBE:toppoint.de deviceId: OKODBYTZJA guest: false hs: https://matrix.toppoint.de" bundle.js:35:18920
"Session persisted for @BenBE:toppoint.de" bundle.js:35:18920
"Lifecycle: Starting MatrixClient" bundle.js:35:18920
"IndexedDBStore.startup: connecting to backend" bundle.js:35:18920
"MatrixClientPeg: waiting for MatrixClient store to initialise" bundle.js:35:18920
GET 
XHR 
https://matrix.toppoint.de/version [HTTP/1.1 200 OK 6ms]
GET 
https://matrix.toppoint.de/img/spinner.gif [HTTP/1.1 200 OK 35ms]
PUT 
XHR 
https://matrix.toppoint.de/_matrix/client/r0/presence/%40BenBE%3Atoppoint.de/status [HTTP/1.1 200 OK 110ms]
"Switching to room id !hvHHdEYFIZGufBEVBR:toppoint.de at event undefined" bundle.js:35:18920
"Presence: online" bundle.js:35:18920
"IndexedDB worker is ready" bundle.js:35:18920
"LocalIndexedDBStoreBackend.connect: connecting" indexeddb-worker.js:4:25532
"LocalIndexedDBStoreBackend.connect: awaiting connection" indexeddb-worker.js:4:25900
"LocalIndexedDBStoreBackend.connect: connected" indexeddb-worker.js:4:26000
"LocalIndexedDBStoreBackend: loading account data" indexeddb-worker.js:4:28579
"LocalIndexedDBStoreBackend: loaded account data" indexeddb-worker.js:4:28668
"LocalIndexedDBStoreBackend: loaded sync data" indexeddb-worker.js:4:28906
"LocalIndexedDBStoreBackend: loaded sync data" indexeddb-worker.js:4:28991
"LocalIndexedDBStoreBackend: loaded initial data" indexeddb-worker.js:4:26294
"IndexedDBStore.startup: loading presence events" bundle.js:35:18920
"IndexedDBStore.startup: processing presence events" bundle.js:35:18920
"MatrixClientPeg: really starting MatrixClient" bundle.js:35:18920
"MatrixClientPeg: MatrixClient started" bundle.js:35:18920
POST 
XHR 
https://matrix.toppoint.de/_matrix/client/unstable/keys/upload/OKODBYTZJA [HTTP/1.1 200 OK 11ms]
GET 
XHR 
https://matrix.toppoint.de/_matrix/client/r0/pushrules/ [HTTP/1.1 200 OK 11ms]
"Got push rules" bundle.js:35:18920
GET 
XHR 
https://matrix.toppoint.de/_matrix/client/r0/user/%40BenBE%3Atoppoint.de/filter/8 [HTTP/1.1 200 OK 111ms]
"sync(): not doing HTTP hit, instead returning stored /sync data" bundle.js:35:18920
"Enabling encryption in !xaClpUlamjOwPfSSnh:toppoint.de; starting to track device lists for all users therein" bundle.js:35:18920
"Enabling encryption in !UWEfppQWvkdeNoWrmC:toppoint.de; starting to track device lists for all users therein" bundle.js:35:18920
"Enabling encryption in !zTIJsQlvShNKyFYfLk:toppoint.de; starting to track device lists for all users therein" bundle.js:35:18920
"Enabling encryption in !HtYTMvgxgGxhOwEsKR:toppoint.de; starting to track device lists for all users therein" bundle.js:35:18920
"EventTimelineSet.addLiveEvent: ignoring duplicate event $1505289628393mwXPE:toppoint.de" bundle.js:46:14018
"EventTimelineSet.addLiveEvent: ignoring duplicate event $15060040271374iUhJS:toppoint.de" bundle.js:46:14018
"connecting to indexeddb matrix-js-sdk:crypto" bundle.js:35:18920
"Enabling encryption in !hYbzPTsswrKArnBexw:toppoint.de; starting to track device lists for all users therein" bundle.js:35:18920
"EventTimelineSet.addLiveEvent: ignoring duplicate event $1506804810894oMXnX:toppoint.de" bundle.js:46:14018
"Enabling encryption in !RmqzsRJQhPcJYbaIqP:toppoint.de; starting to track device lists for all users therein" bundle.js:35:18920
"EventTimelineSet.addLiveEvent: ignoring duplicate event $15080988273613Ewtai:toppoint.de" bundle.js:46:14018
"MatrixClient sync state => PREPARED" bundle.js:35:18920
"newscreen room/!hvHHdEYFIZGufBEVBR:toppoint.de" bundle.js:35:18920
"RVS update:" "!hvHHdEYFIZGufBEVBR:toppoint.de" undefined "loading?" false "joining?" false "initial?" true "shouldPeek?" true bundle.js:35:18920
"can't initialise scroll state because messagePanel didn't load" bundle.js:35:18920
"Looking for queued outgoing room key requests" bundle.js:35:18920
Error: Unknown theme status bundle.js:114:24721
TypeError: d.default.findDOMNode(...).querySelectorAll(...).forEach is not a function bundle.js:123:31372
GET 
https://matrix.toppoint.de/_matrix/media/v1/thumbnail/matrix.eclabs.de/ykMEnGOYfvLvqdoZKUYgvfsO [HTTP/1.1 200 OK 239ms]
GET 
https://matrix.toppoint.de/undefined [HTTP/1.1 404 Not Found 1211ms]
POST 
XHR 
https://matrix.toppoint.de/_matrix/client/r0/publicised_groups [HTTP/1.1 200 OK 906ms]
"connected to indexeddb matrix-js-sdk:crypto" bundle.js:35:18920
GET 
XHR 
https://matrix.toppoint.de/_matrix/client/r0/sync [HTTP/1.1 200 OK 815ms]
"Caught /sync error" "e.exports<.componentDidUpdate@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:13:20122
a</e.prototype.notifyAll@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:69:22257
m.close@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:143:9198
i.closeAll@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:10150
i.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:9642
i.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:9562
.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:14:7820
x@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:14:7997
i.closeAll@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:10150
i.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:9642
d.batchedUpdates@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:143:2273
l@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:14:6947
r@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:47:29579
u<.enqueueSetState@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:47:30722
r.prototype.setState@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:70:5272
e.exports<._updateList<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:125:27076
e.exports/r@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:15:26919
e.exports<.onRoomStateMember@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:125:26637
n.prototype.emit@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:13:13264
c</<.value@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:63:26772
n.prototype.emit@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:13:13264
o.prototype.setStateEvents/<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:65:3622
e.exports.forEach@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:6:1298
o.prototype.setStateEvents@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:65:2979
r.prototype.addEvent@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:15:26117
r.prototype.addEventToTimeline@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:46:14209
r.prototype.addLiveEvent@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:46:14096
i.prototype._addLiveEvent@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:65:12439
i.prototype.addLiveEvents@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:65:15383
a.prototype._processRoomEvents@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:111:4676
e/<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:111:452
r@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:82:27709
u/<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:82:28756
s/</e[t]@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:82:27885
o@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:1:18655
e.exports/l.prototype._promiseFulfilled@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:37:12704
e.exports/e.coroutine/<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:37:14550
e/</</<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:111:924
o@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:1:18655
f@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:38:17673
c@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:38:17555
o@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:1:18655
e.exports/i.prototype._settlePromiseFromHandler@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:38:1020
e.exports/i.prototype._settlePromise@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:38:1823
e.exports/i.prototype._settlePromiseCtx@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:38:2331
r.prototype._drainQueue@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:36:19462
r.prototype._drainQueues@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:36:19537
r/this.drainQueues@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:36:17694
" bundle.js:35:18920

"MatrixClient sync state => SYNCING" bundle.js:35:18920
"Unhandled rejection e.exports<.componentDidUpdate@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:13:20122
a</e.prototype.notifyAll@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:69:22257
m.close@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:143:9198
i.closeAll@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:10150
i.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:9642
i.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:9562
.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:14:7820
x@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:14:7997
i.closeAll@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:10150
i.perform@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:35:9642
d.batchedUpdates@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:143:2273
l@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:14:6947
r@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:47:29579
u<.enqueueSetState@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:47:30722
r.prototype.setState@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:70:5272
P<.onSync@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:117:2384
n.prototype.emit@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:13:13264
a.prototype._updateSyncState@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:111:5143
e/<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:110:28289
r@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:82:27709
u/<@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:82:28756
s/</e[t]@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:82:27885
o@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:1:18655
e.exports/l.prototype._promiseFulfilled@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:37:12704
r.prototype._drainQueue@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:36:19462
r.prototype._drainQueues@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:36:19537
r/this.drainQueues@https://matrix.toppoint.de/bundles/dacc4b92117d0f1f8554/bundle.js:36:17694
" bundle.js:35:18920
POST 
XHR 
https://matrix.toppoint.de/_matrix/client/unstable/keys/upload/OKODBYTZJA [HTTP/1.1 200 OK 9ms]
"No more outgoing room key requests" bundle.js:35:18920
```

I noticed the following two requests fail:
```
GET 
XHR 
https://matrix.toppoint.de/config.matrix.toppoint.de.json [HTTP/1.1 404 Not Found 27ms]

GET 
https://matrix.toppoint.de/undefined [HTTP/1.1 404 Not Found 1211ms]
```

While the first looks like a server config error (will talk to the admins of that server), the latter seems like a client issue creating the wrong URL from a previous issue.

**Comment by MTRNord** [comment]
the first one is no problem and expected. the second is I think (atleast the last time is saw a undefined) is from communites.

**Comment by turt2live** [comment]
I suspect this is caused by your browser (Pale Moon) being based on an older version of Firefox that isn't used anymore. In particular, it seems to be failing to add the "code copy" button to a code block, which implies that your browser predates the API.

**Comment by BenBE** [comment]
NB: The used version (27.6.2) of Palemoon is the most recent one available, cf. [their release notes](http://www.palemoon.org/releasenotes.shtml).

But shouldn't the web UI work around crashing if some features aren't available/blocked in a browser? It's not that uncommon for some JS features not being available with some browsers.

**Comment by turt2live** [comment]
Riot does have that check, although I don't think it can detect this particular API being missing. It seems like Pale Moon supports some of the API, but not all of it.

**Comment by BenBE** [comment]
For the full picture: http://html5test.com/s/3985793a3b6ecaf2.html - HTH.

**Comment by wolfbeast** [comment]
The issue seems to be `TypeError: d.default.findDOMNode(...).querySelectorAll(...).forEach is not a function` -- The framework you have in use should not try to use `forEach()` on the output of `querySelectorAll()` directly because it's not an array. This kind of direct iteration is only supported in very recent versions of Chrome and Firefox, and not supported by MSIE, Edge or Pale Moon (other browsers unknown at this point).

Convert to an Array first with e.g. `Array.from()` before using `forEach()` on it, to be browser-agnostic.

**Comment by t3chguy** [comment]
`querySelectorAll` is not an array indeed, it is a NodeListOf which does nowadays have a forEach method.

This is fixed
