### ISSUE TITLE
e2e silently failed due to OTK bad mac

### ISSUE THREAD

**Issue by ara4n** [vector-im/element-web#6195]

**Comment by ara4n** [comment]
I tried to message @matthewtest7:matrix.org; it failed with an OTK bad MAC - but did so entirely silently, so the other side received UISIs with no explanation:

```
rageshake.js:65 Unable to verify signature on one-time key for device @matthewtest7:matrix.org:GCTYKIBXHN: Error: OLM.BAD_MESSAGE_MAC
    at https://riot.im/develop/bundles/a1e3049856cc4c0dc280/olm.js:113:190
    at oa.<anonymous> (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/olm.js:418:465)
    at oa.ed25519_verify (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/olm.js:111:460)
    at https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:245150:15
    at OlmDevice._getUtility (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:244130:17)
    at OlmDevice.verifySignature (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:245149:11)
    at https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:43609:20
    at tryCatcher (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:2069:24)
    at https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:64883:35
    at https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:43613:23
    at _callee3$ (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:43209:56)
    at tryCatch (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:255905:41)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:256139:23)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:255957:22)
    at Generator.tryCatcher (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:2069:24)
    at PromiseSpawn._promiseFulfilled (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:64388:50)
    at https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:64492:16
    at _verifyKeyAndStartSession (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:43255:23)
    at _loop2 (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:43539:48)
    at _loop (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:43545:46)
    at Object._callee2$ (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:43560:33)
    at tryCatch (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:255905:41)
    at Generator.invoke [as _invoke] (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:256139:23)
    at Generator.prototype.(anonymous function) [as next] (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:255957:22)
    at Generator.tryCatcher (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:2069:24)
    at PromiseSpawn._promiseFulfilled (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:64388:50)
    at Promise._settlePromise (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:65567:27)
    at Promise._fulfillPromises (https://riot.im/develop/bundles/a1e3049856cc4c0dc280/bundle.js:65661:15)
consoleObj.(anonymous function) @ rageshake.js:65
_callee3$ @ olmlib.js:222
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
tryCatcher @ util.js:16
PromiseSpawn._promiseRejected @ generators.js:107
Async._drainQueue @ async.js:138
Async._drainQueues @ async.js:143
Async.drainQueues @ async.js:17
Promise.then (async)
schedule @ schedule.js:18
Async._queueTick @ async.js:152
AsyncSettlePromises @ async.js:88
Async.settlePromises @ async.js:120
Promise._fulfill @ promise.js:640
Promise._resolveCallback @ promise.js:432
deferResolve @ promise.js:710
(anonymous) @ http-api.js:817
(anonymous) @ http-api.js:742
on_end @ index.js:294
on_state_change @ index.js:244
XMLHttpRequest.send (async)
run_xhr @ index.js:218
request @ index.js:179
_request @ http-api.js:718
requestOtherUrl @ http-api.js:594
request @ http-api.js:479
authedRequest @ http-api.js:428
authedRequestWithPrefix @ http-api.js:511
MatrixBaseApis.claimOneTimeKeys @ base-apis.js:1500
_callee2$ @ olmlib.js:164
tryCatch @ runtime.js:62
invoke @ runtime.js:296
prototype.(anonymous function) @ runtime.js:114
tryCatcher @ util.js:16
PromiseSpawn._promiseFulfilled @ generators.js:97
Promise._settlePromise @ promise.js:574
Promise._settlePromise0 @ promise.js:614
Promise._settlePromises @ promise.js:693
Async._drainQueue @ async.js:133
Async._drainQueues @ async.js:143
Async.drainQueues @ async.js:17
Promise.then (async)
schedule @ schedule.js:18
Async._queueTick @ async.js:152
AsyncSettlePromises @ async.js:88
Async.settlePromises @ async.js:120
Promise._fulfill @ promise.js:640
Promise._resolveCallback @ promise.js:432
(anonymous) @ promise.js:484
txn.oncomplete @ indexeddb-crypto-store-backend.js:529
23:15:17.544 rageshake.js:65 Started new sessionid RNyMPZbcpGihfS3bTZg1QIkZxV9XkFR09VYo2f2RnMg for device @matthewtest7:matrix.org:XLFJTFEDWE
```

**Comment by richvdh** [comment]
it was a bad mac because matthew had switched between /develop and /app (with crypto being stored in indexeddb and localstorage respectively).

I assume the point of this bug is not so much that the signature was invalid (which is #6196) but that the sender then silently swallows the errors.

**Comment by kittykat** [comment]
I'm going to close this issue for now as we haven't had any reports of similar issues and the code has been reworked since it was filed. Please re-open if you're still experiencing it.
