### ISSUE TITLE
E2E fails for all rooms

### ISSUE THREAD

**Issue by krombel** [vector-im/element-web#6714]
### Description

Describe here the problem that you are experiencing, or the feature you are requesting.

### Steps to reproduce
I don't know. I just see it on every load of the client...

Describe how what happens differs from what you expected.

Log:
```
Error configuring encryption in room !UCnwUWwIKhcpaPTHtR:sw1v.org: undefined
```
for each room I have encryption enabled and then for a lot of messages (with different id's):
```
Error decrypting event (id=$15259765253458176qdmku:matrix.org): TypeError: Cannot read property 'message' of undefined
    at MegolmDecryption._callee4$ (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:112514:43)
    at tryCatch (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:122320:41)
    at Generator.invoke [as _invoke] (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:122554:23)
    at Generator.prototype.(anonymous function) [as throw] (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:122372:22)
    at Generator.tryCatcher (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:1592:24)
    at PromiseSpawn._promiseRejected (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:48798:11)
    at Promise._settlePromise (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:49969:27)
    at Promise._settlePromise0 (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:50007:11)
    at Promise._settlePromises (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:50082:19)
    at Async._drainQueue (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:47060:17)
    at Async._drainQueues (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:47070:11)
    at Async.drainQueues (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:46944:15)
    at <anonymous>
```
When I try to send an event it looks like this:
```
setting pendingEvent status to sending in !UCnwUWwIKhcpaPTHtR:sw1v.org
rageshake.js:66 Error sending event Error: Room was previously configured to use encryption, but is no longer. Perhaps the homeserver is hiding the configuration event.
    at Crypto.encryptEvent (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:114208:16)
    at _encryptEventIfNeeded (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:68007:28)
    at https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:67913:34
    at tryCatcher (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:1592:24)
    at Promise._settlePromiseFromHandler (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:49905:32)
    at Promise._settlePromise (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:49962:19)
    at Promise._settlePromiseCtx (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:49999:11)
    at Async._drainQueue (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:47065:13)
    at Async._drainQueues (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:47070:11)
    at Async.drainQueues (https://riot.msg-net.de/dev-up/bundles/92bc8a4c7d6af28bc482/bundle.js:46944:15)
    at <anonymous>
consoleObj.(anonymous function) @ rageshake.js:66
(anonymous) @ client.js:1156
tryCatcher @ util.js:16
Promise._settlePromiseFromHandler @ promise.js:512
Promise._settlePromise @ promise.js:569
Promise._settlePromise0 @ promise.js:614
Promise._settlePromises @ promise.js:689
Async._drainQueue @ async.js:133
Async._drainQueues @ async.js:143
Async.drainQueues @ async.js:17
Promise resolved (async)
schedule @ schedule.js:18
Async._queueTick @ async.js:152
AsyncInvoke @ async.js:83
Async.invoke @ async.js:110
Promise._then @ promise.js:261
Promise.then @ promise.js:125
_sendEvent @ client.js:1115
MatrixClient.resendEvent @ client.js:911
resend @ Resend.js:38
(anonymous) @ Resend.js:26
resendUnsentEvents @ Resend.js:25
_onResendAllClick @ RoomStatusBar.js:159
boundFunc @ ReactErrorUtils.js:63
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:69
executeDispatch @ EventPluginUtils.js:83
executeDispatchesInOrder @ EventPluginUtils.js:106
executeDispatchesAndRelease @ EventPluginHub.js:41
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:52
forEachAccumulated @ forEachAccumulated.js:22
processEventQueue @ EventPluginHub.js:252
runEventQueueInBatch @ ReactEventEmitterMixin.js:15
handleTopLevel @ ReactEventEmitterMixin.js:25
handleTopLevelImpl @ ReactEventListener.js:70
perform @ Transaction.js:141
batchedUpdates @ ReactDefaultBatchingStrategy.js:60
batchedUpdates @ ReactUpdates.js:95
dispatchEvent @ ReactEventListener.js:145
rageshake.js:66 setting pendingEvent status to not_sent in !UCnwUWwIKhcpaPTHtR:sw1v.org
rageshake.js:66 Resend got send failure: Error(Error: Room was previously configured to use encryption, but is no longer. Perhaps the homeserver is hiding the configuration event.)
```

Every (encrypted) message only shows
`** Unable to decrypt: The sender's device has not sent us the keys for this message. **`
as message content

Btw: even a "Clear cache and reload" did not fix it...

### Version information

- **Platform**: web
- **Browser**: Chrome 63.0.3239.108
- **OS**: Ubuntu
- **URL**: riot.im/develop

**Comment by dbkr** [comment]
Is it possible your indexeddb has filled up (and is somehow throwing really, really unhelpful errors).

**Comment by krombel** [comment]
I (finally) logged out and in again in the hope that encryption now will work again.
But now it tells me, on client start
`Unable to initialise e2e: undefined`
Even (several) "Clear cache and reload"'s did not help.
Any further ideas I can check?

**Comment by kittykat** [comment]
Hi, I'm going to close this issue for now as it's old and there is not enough information here for us to be able to do any further investigation into it.
