### ISSUE TITLE
Sending messages stopped working

### ISSUE THREAD

**Issue by gavofyork** [vector-im/element-web#7238]
### Description

Impossible to send a message

### Steps to reproduce

Use Riot for long enough. Type message, press enter, nothing happens.

```
Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'mx_slate_composer_history_!SutRpTCZbdlEEEjOXq:matrix.parity.io[1]' exceeded the quota.
    at e.value (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:138:25920)
    at t.Be.handleReturn (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:160:2747)
    at Object.Be.onKeyDown (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:159:29883)
    at Object.onChange.t.schema.i.(anonymous function) [as onKeyDown] (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:175:4122)
    at t.value (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:15:18446)
    at https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:175:3779
    at e.value (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:16:15877)
    at t.Ge.change (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:175:3565)
    at t.Ge.onEvent (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:175:3752)
    at Object.n.(anonymous function) [as onKeyDown] (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:175:1592)
    at t.value (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:174:31150)
    at n.(anonymous function) (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:174:30111)
    at Object.r (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:53:6105)
    at a (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:53:2155)
    at Object.s [as executeDispatchesInOrder] (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:53:2370)
    at p (https://riot.im/app/bundles/cd8a5d8887db65aed165/bundle.js:28:17704)
```

### Version information

- **Platform**: In-browser

For the web app:

- **Browser**: Chrome 68.0.3440.106
- **OS**: macOS
- **URL**: riot.im/app

**Comment by gavofyork** [comment]
A year, perhaps? Probably with some very long messages in my chat history.

**Comment by gavofyork** [comment]
I cleared session storage and it's working again.

**Comment by ara4n** [comment]
oops, just answered this one by mail. you should just need to delete some disk space to stop the browser quotaing localstorage.

**Comment by ara4n** [comment]
(it’s a fundamental (mis)feature of localstorage and indexeddb that the browser can arbitrarily decide to stop storing data if it thinks you are running low on space)

**Comment by gavofyork** [comment]
![image](https://user-images.githubusercontent.com/138296/44806951-936cf380-abc8-11e8-84de-848527e32492.png)

I wouldn't really call that "running low". Isn't a hardcoded 5MB limit that Chrome imposes?

**Comment by turt2live** [comment]
Related: https://github.com/vector-im/riot-web/issues/6120

**Comment by yannicka** [comment]
I can't test this easily. Is the problem still there?

**Comment by t3chguy** [comment]
it looks like a browser quota issue, nothing the app can do anything about
